/* 模拟题库 · 高仿真考点模拟题（难度对齐真题） */
const MOCK_BANK = [
/* ===== 数据通信基础 ===== */
{ id:"m01", source:"mock", point:"数据通信基础", diff:3,
  stem:"设无噪声信道的带宽为 4kHz，采用 8 种不同的码元传输，则该信道能达到的最大数据速率为（　）。",
  options:["16kbps","24kbps","32kbps","48kbps"], answer:"B",
  analysis:"奈奎斯特定理：最大数据速率 = 2B·log2(N) = 2×4000×log2(8) = 24000bps = 24kbps。" },
{ id:"m02", source:"mock", point:"数据通信基础", diff:3,
  stem:"某信道带宽为 3kHz，信噪比为 30dB，则该信道容量约为（　）。",
  options:["9kbps","20kbps","30kbps","300kbps"], answer:"C",
  analysis:"香农公式：C = B·log2(1+S/N)。30dB 对应 S/N=1000，C = 3000×log2(1001) ≈ 30000bps ≈ 30kbps。" },
{ id:"m03", source:"mock", point:"数据通信基础", diff:2,
  stem:"模拟信号的最高频率为 4kHz，按采样定理进行 PCM 采样，采样频率至少应为（　）。",
  options:["4kHz","8kHz","12kHz","16kHz"], answer:"B",
  analysis:"采样定理：采样频率 ≥ 2×最高频率 = 2×4kHz = 8kHz。" },
{ id:"m04", source:"mock", point:"数据通信基础", diff:2,
  stem:"采用曼彻斯特编码传输，若数据速率为 10Mbps，则信号波特率为（　）。",
  options:["5M Baud","10M Baud","20M Baud","40M Baud"], answer:"C",
  analysis:"曼彻斯特编码每个数据位用两个码元表示（中间跳变），波特率 = 2×数据速率 = 20M Baud。" },
{ id:"m05", source:"mock", point:"数据通信基础", diff:2,
  stem:"关于差分曼彻斯特编码，下列说法正确的是（　）。",
  options:["每个比特中间跳变仅用于同步，用比特开始处电平是否变化表示 0 或 1","每个比特中间跳变既用于同步又表示数据","每位数据需要 3 个码元","编码效率为 100%"], answer:"A",
  analysis:"差分曼彻斯特编码：每位中间跳变只作时钟同步，数据由位开始边界处电平是否跳变表示，抗干扰性更强。" },
{ id:"m06", source:"mock", point:"数据通信基础", diff:2,
  stem:"4B/5B 编码的编码效率是（　）。",
  options:["50%","60%","80%","100%"], answer:"C",
  analysis:"4B/5B 每 4 位数据编码为 5 位码元，效率 4/5 = 80%，常用于 100BASE-FX/TX。" },
{ id:"m07", source:"mock", point:"数据通信基础", diff:1,
  stem:"异步传输与同步传输的区别在于（　）。",
  options:["异步传输以字符为单位同步，同步传输以帧为单位同步","异步传输不需要时钟","同步传输不需要时钟","异步传输效率更高"], answer:"A",
  analysis:"异步传输以字符为传输单位、每个字符前后加起始位/停止位同步；同步传输以数据块（帧）为单位，效率更高。" },
{ id:"m08", source:"mock", point:"数据通信基础", diff:1,
  stem:"波分复用（WDM）技术主要应用于（　）传输。",
  options:["双绞线","同轴电缆","光纤","无线信道"], answer:"C",
  analysis:"WDM 利用不同波长的光载波在同一根光纤中传输多路信号，是光纤通信的重要复用技术。" },
/* ===== 编码与差错 ===== */
{ id:"m09", source:"mock", point:"数据通信基础", diff:1,
  stem:"关于循环冗余校验（CRC），下列说法正确的是（　）。",
  options:["可以自动纠正多位错误","只能检错，不能纠错","可以纠正 1 位错误","不需要冗余位"], answer:"B",
  analysis:"CRC 检错能力强，但只能检测错误（发现后请求重传），不能自动纠错。" },
{ id:"m10", source:"mock", point:"数据通信基础", diff:3,
  stem:"若信息位为 8 位，要求能纠正 1 位错误，按海明编码规则至少需要（　）位校验位。",
  options:["3","4","5","6"], answer:"B",
  analysis:"海明不等式：2^r ≥ m+r+1，m=8 时 r=4（16≥13），需 4 位校验位。" },
{ id:"m11", source:"mock", point:"数据通信基础", diff:2,
  stem:"奇偶校验码的特点是（　）。",
  options:["只能检测奇数个错误","只能检测偶数个错误","能纠正 1 位错误","能检测任意多位错误"], answer:"A",
  analysis:"奇偶校验只能检测奇数个比特错误，无法定位错误，也无法检测偶数个错误。" },
{ id:"m12", source:"mock", point:"数据通信基础", diff:3,
  stem:"若生成多项式为 x³+x+1（即 1011），待发送数据为 1010，则计算得到的 CRC 校验码为（　）。",
  options:["010","011","110","101"], answer:"B",
  analysis:"数据 1010 后补 3 个 0 得 1010000，模 2 除以 1011，余数为 011，即 CRC 校验码。" },
{ id:"m13", source:"mock", point:"数据通信基础", diff:2,
  stem:"海明码中，校验位一般位于码字的（　）位置。",
  options:["序号为 2 的幂次的位置","码字末尾","码字开头","任意位置"], answer:"A",
  analysis:"海明码将校验位放在序号为 1、2、4、8…（2 的幂次）的位置上，其余为信息位。" },
/* ===== 网络体系结构 ===== */
{ id:"m14", source:"mock", point:"网络体系结构", diff:1,
  stem:"路由器工作在 OSI 参考模型的（　）。",
  options:["物理层","数据链路层","网络层","传输层"], answer:"C",
  analysis:"路由器根据 IP 地址进行分组转发，工作在网络层；交换机工作在数据链路层，集线器工作在物理层。" },
{ id:"m15", source:"mock", point:"网络体系结构", diff:2,
  stem:"数据从应用层到物理层依次经过的封装过程是（　）。",
  options:["报文→段→数据报→帧→比特流","帧→报文→段→数据报→比特流","数据报→报文→帧→段→比特流","比特流→帧→数据报→段→报文"], answer:"A",
  analysis:"应用层产生报文（Message），传输层封装为段（Segment），网络层封装为数据报（Datagram），数据链路层封装为帧（Frame），物理层转换为比特流。" },
{ id:"m16", source:"mock", point:"网络体系结构", diff:2,
  stem:"网关（Gateway）通常工作在 OSI 参考模型的（　）。",
  options:["物理层","数据链路层","网络层","传输层及以上"], answer:"D",
  analysis:"网关用于连接异构网络，进行协议转换，工作在传输层及以上（高层网关）。" },
{ id:"m17", source:"mock", point:"网络体系结构", diff:1,
  stem:"数据链路层的协议数据单元（PDU）称为（　）。",
  options:["报文","段","数据报","帧"], answer:"D",
  analysis:"数据链路层 PDU 是帧（Frame）；网络层是数据报/分组；传输层是段。" },
{ id:"m18", source:"mock", point:"网络体系结构", diff:1,
  stem:"TCP/IP 参考模型中，负责将数据报从源主机传送到目的主机（含路由选择）的是（　）。",
  options:["网络接口层","网际层","传输层","应用层"], answer:"B",
  analysis:"网际层（IP 层）负责寻址与路由选择，实现数据报端到端传输。" },
{ id:"m19", source:"mock", point:"网络体系结构", diff:2,
  stem:"OSI 参考模型分层的主要目的是（　）。",
  options:["降低实现复杂度，各层独立设计与演进","减少网络设备数量","统一物理介质","提高传输速率"], answer:"A",
  analysis:"分层使各层功能独立、接口清晰，便于设计、实现、调试与标准化，任何一层变化不影响其他层。" },
/* ===== 局域网与交换 ===== */
{ id:"m20", source:"mock", point:"局域网与交换", diff:2,
  stem:"划分 VLAN 的主要作用不包括（　）。",
  options:["隔离广播域","提高网络安全性","扩展二层广播域范围","简化网络管理"], answer:"C",
  analysis:"VLAN 将一个物理局域网划分为多个逻辑广播域，缩小而非扩大广播域，从而隔离广播、提升安全与可管理性。" },
{ id:"m21", source:"mock", point:"局域网与交换", diff:2,
  stem:"IEEE 802.1Q 标准在以太网帧中插入的 Tag 字段长度为（　）字节。",
  options:["2","4","6","8"], answer:"B",
  analysis:"802.1Q Tag 为 4 字节，位于源 MAC 地址之后，包含 TPID、Priority、CFI 和 12 位 VID。" },
{ id:"m22", source:"mock", point:"局域网与交换", diff:2,
  stem:"在 STP（生成树协议）中，根桥的选择依据是（　）。",
  options:["优先级最高（数值最小）且 MAC 地址最小的交换机","端口数量最多的交换机","带宽最大的交换机","最先启动的交换机"], answer:"A",
  analysis:"根桥选举：比较优先级（数值小优先），相同时比较 MAC 地址（小优先）。" },
{ id:"m23", source:"mock", point:"局域网与交换", diff:2,
  stem:"以太网链路聚合（如 LACP）的主要作用是（　）。",
  options:["将多条物理链路捆绑为一条逻辑链路，增加带宽并提供冗余","扩大广播域","实现 VLAN 间路由","提供数据加密"], answer:"A",
  analysis:"链路聚合将多条物理链路聚合为一条逻辑链路，提升带宽、实现负载分担与链路冗余。" },
{ id:"m24", source:"mock", point:"局域网与交换", diff:2,
  stem:"以太网规定最小帧长为（　）字节。",
  options:["46","64","128","1518"], answer:"B",
  analysis:"以太网最小帧长 64 字节（数据部分最少 46 字节），用于保证冲突检测的有效性。" },
{ id:"m25", source:"mock", point:"局域网与交换", diff:2,
  stem:"CSMA/CD 介质访问控制方法适用于（　）。",
  options:["全双工以太网","半双工共享式以太网","令牌环网","无线局域网"], answer:"B",
  analysis:"CSMA/CD 用于半双工共享式以太网；全双工链路无需冲突检测；WLAN 使用 CSMA/CA。" },
{ id:"m26", source:"mock", point:"局域网与交换", diff:2,
  stem:"下列关于交换机与集线器的说法正确的是（　）。",
  options:["交换机隔离冲突域，集线器不隔离冲突域","交换机不隔离广播域，集线器隔离广播域","交换机与集线器都隔离冲突域","交换机工作在网络层"], answer:"A",
  analysis:"交换机每个端口是一个冲突域，可隔离冲突域但不隔离广播域；集线器共享带宽，整个网络是一个冲突域。" },
{ id:"m27", source:"mock", point:"局域网与交换", diff:1,
  stem:"MAC 地址的长度是（　）位。",
  options:["32","48","64","128"], answer:"B",
  analysis:"MAC 地址为 48 位（6 字节），前 24 位为厂商 OUI，后 24 位为序列号。" },
/* ===== 广域网与接入 ===== */
{ id:"m28", source:"mock", point:"广域网与接入", diff:2,
  stem:"无源光网络（PON）中，负责将光信号分发给多个 ONU 的无源设备是（　）。",
  options:["OLT","ODN（光分配网络）","ONU","ONT"], answer:"B",
  analysis:"PON 由 OLT（光线路终端）、ODN（光分配网络，含分光器等无源器件）、ONU（光网络单元）组成，ODN 负责光信号分发。" },
{ id:"m29", source:"mock", point:"广域网与接入", diff:2,
  stem:"PPPoE 拨号认证常用的认证协议包括（　）。",
  options:["PAP 和 CHAP","RADIUS 和 TACACS","WPA 和 WPA2","SSL 和 TLS"], answer:"A",
  analysis:"PPPoE 支持 PAP（明文口令）与 CHAP（挑战握手）两种认证方式，CHAP 更安全。" },
{ id:"m30", source:"mock", point:"广域网与接入", diff:2,
  stem:"下列关于帧中继的说法正确的是（　）。",
  options:["帧中继是面向连接的可靠传输协议","帧中继在数据链路层实现复用与转发，简化差错控制","帧中继工作在网络层","帧中继提供端到端流量控制"], answer:"B",
  analysis:"帧中继是面向连接的二层分组交换技术，只做检错不做重传等复杂控制，由高层保证可靠传输。" },
{ id:"m31", source:"mock", point:"广域网与接入", diff:2,
  stem:"关于单模光纤与多模光纤，下列说法正确的是（　）。",
  options:["单模光纤纤芯细、传输距离远，多模光纤纤芯粗、传输距离短","多模光纤传输距离比单模更远","单模光纤使用 LED 光源，多模使用激光","两者传输距离相同"], answer:"A",
  analysis:"单模光纤纤芯细（约 9μm），模间色散小，用激光光源，适合长距离；多模光纤纤芯粗（50/62.5μm），用 LED 光源，适合短距离。" },
{ id:"m32", source:"mock", point:"广域网与接入", diff:1,
  stem:"FTTH 的含义是（　）。",
  options:["光纤到户","光纤到大楼","光纤到路边","光纤到交接箱"], answer:"A",
  analysis:"FTTH（Fiber To The Home）光纤到户；FTTB 光纤到大楼；FTTC 光纤到路边。" },
/* ===== 网络层与路由 ===== */
{ id:"m33", source:"mock", point:"网络层与路由", diff:2,
  stem:"默认路由（缺省路由）通常表示为（　）。",
  options:["0.0.0.0/0","127.0.0.0/8","255.255.255.255/32","10.0.0.0/8"], answer:"A",
  analysis:"默认路由目的网络为 0.0.0.0/0，匹配所有目标网络，用于没有更精确匹配时的兜底转发。" },
{ id:"m34", source:"mock", point:"网络层与路由", diff:2,
  stem:"OSPF 协议使用的度量（Metric）是（　）。",
  options:["跳数","带宽计算的接口开销","时延","MTU"], answer:"B",
  analysis:"OSPF 以接口开销（Cost，由带宽计算，默认 10^8/带宽）为度量，选择开销最小的路径。" },
{ id:"m35", source:"mock", point:"网络层与路由", diff:2,
  stem:"BGP 协议运行在（　）之上，默认使用端口（　）。",
  options:["TCP；179","UDP；179","TCP；520","UDP；520"], answer:"A",
  analysis:"BGP 基于 TCP 的 179 端口，通过 TCP 保证路由信息可靠传输。" },
{ id:"m36", source:"mock", point:"网络层与路由", diff:1,
  stem:"PING 命令利用 ICMP 的（　）报文实现连通性测试。",
  options:["Echo Request / Echo Reply","Destination Unreachable","Time Exceeded","Redirect"], answer:"A",
  analysis:"PING 发送 ICMP Echo Request，目的主机回复 Echo Reply，据此判断连通性与往返时延。" },
{ id:"m37", source:"mock", point:"网络层与路由", diff:1,
  stem:"ARP 协议的作用是（　）。",
  options:["根据 IP 地址解析 MAC 地址","根据 MAC 地址解析 IP 地址","实现域名到 IP 的解析","实现端口映射"], answer:"A",
  analysis:"ARP（地址解析协议）在同一广播域内根据目的 IP 地址查询对应的 MAC 地址；反向解析用 RARP。" },
{ id:"m38", source:"mock", point:"网络层与路由", diff:2,
  stem:"NAPT（网络地址端口转换）的特点是（　）。",
  options:["多个私有地址共享一个公网 IP，通过端口号区分不同会话","一个私有地址映射一个公网 IP","只转换源地址不转换端口","只适用于 IPv6"], answer:"A",
  analysis:"NAPT 将多个内部私有地址映射到同一公网 IP 的不同端口，实现多对一共享上网。" },
{ id:"m39", source:"mock", point:"网络层与路由", diff:2,
  stem:"路由器路由表中，优先级最高（最优先被选用）的路由来源通常是（　）。",
  options:["直连路由","静态路由","OSPF 路由","RIP 路由"], answer:"A",
  analysis:"华为设备路由协议优先级：直连 0、OSPF 10、静态 60、RIP 100，数值越小越优先，直连路由优先级最高。" },
{ id:"m40", source:"mock", point:"网络层与路由", diff:3,
  stem:"VRRP 虚拟路由冗余协议使用的组播地址是（　）。",
  options:["224.0.0.5","224.0.0.9","224.0.0.18","224.0.0.10"], answer:"C",
  analysis:"VRRP 报文发往组播地址 224.0.0.18；224.0.0.5/6 为 OSPF，224.0.0.9 为 RIPv2，224.0.0.10 为 EIGRP。" },
/* ===== IP 地址与子网 ===== */
{ id:"m41", source:"mock", point:"IP地址与子网", diff:1,
  stem:"下列地址中，属于私有 IP 地址的是（　）。",
  options:["10.1.2.3","114.114.114.114","8.8.8.8","202.96.128.86"], answer:"A",
  analysis:"私有地址块：10.0.0.0/8、172.16.0.0/12、192.168.0.0/16，10.1.2.3 属于 10.0.0.0/8。" },
{ id:"m42", source:"mock", point:"IP地址与子网", diff:3,
  stem:"将 192.168.1.0/24 划分为 4 个子网，每个子网可用的主机数为（　），子网掩码为（　）。",
  options:["62；255.255.255.192","30；255.255.255.224","62；255.255.255.224","126；255.255.255.128"], answer:"A",
  analysis:"划分 4 个子网需要借用 2 位主机位，掩码变为 /26（255.255.255.192），每子网主机位 6 位，可用主机 2^6-2=62。" },
{ id:"m43", source:"mock", point:"IP地址与子网", diff:2,
  stem:"子网 192.168.10.0/28 中可用的主机地址数为（　）。",
  options:["14","16","30","62"], answer:"A",
  analysis:"/28 主机位 4 位，可用主机数 = 2^4 - 2 = 14。" },
{ id:"m44", source:"mock", point:"IP地址与子网", diff:3,
  stem:"将 192.168.1.0/24 与 192.168.2.0/24 两个地址段聚合，得到的超网地址是（　）。",
  options:["192.168.0.0/22","192.168.0.0/23","192.168.1.0/23","192.168.3.0/22"], answer:"A",
  analysis:"192.168.1.0 与 192.168.2.0 二进制前 22 位相同，聚合为 192.168.0.0/22（覆盖 192.168.0.0~192.168.3.255）。" },
{ id:"m45", source:"mock", point:"IP地址与子网", diff:1,
  stem:"IP 地址 127.0.0.1 表示（　）。",
  options:["本机环回地址","受限广播地址","全网广播地址","默认路由地址"], answer:"A",
  analysis:"127.0.0.0/8 为环回地址，127.0.0.1 表示本机自身；255.255.255.255 为受限广播地址。" },
{ id:"m46", source:"mock", point:"IP地址与子网", diff:1,
  stem:"IPv6 地址的长度为（　）位。",
  options:["32","64","128","256"], answer:"C",
  analysis:"IPv6 地址为 128 位，用 8 组十六进制数表示，每组 16 位。" },
{ id:"m47", source:"mock", point:"IP地址与子网", diff:2,
  stem:"子网掩码 255.255.255.248 对应的 CIDR 前缀长度为（　），每个子网可用主机数为（　）。",
  options:["/29；6","/28；14","/29；8","/27；30"], answer:"A",
  analysis:"255.255.255.248 二进制最后一段为 11111000，网络位 29 位（/29），主机位 3 位，可用主机 2^3-2=6。" },
{ id:"m48", source:"mock", point:"IP地址与子网", diff:2,
  stem:"CIDR（无类域间路由）技术的特点是（　）。",
  options:["按可变长度前缀聚合地址，提高地址利用率","固定 A/B/C 类划分","每个地址块必须对应一个物理网络","只能用于 IPv6"], answer:"A",
  analysis:"CIDR 消除传统 A/B/C 类限制，用前缀长度标识网络，支持路由聚合，提高地址利用率。" },
/* ===== 传输层 ===== */
{ id:"m49", source:"mock", point:"传输层", diff:2,
  stem:"TCP 三次握手中，客户端发出 SYN 报文后进入的状态是（　）。",
  options:["SYN-SENT","SYN-RECEIVED","ESTABLISHED","CLOSE-WAIT"], answer:"A",
  analysis:"客户端发送 SYN 后进入 SYN-SENT（同步已发送）状态，收到 SYN+ACK 并回复 ACK 后进入 ESTABLISHED。" },
{ id:"m50", source:"mock", point:"传输层", diff:2,
  stem:"TCP 连接释放过程需要（　）次挥手，发起方在发送 FIN 后进入（　）状态。",
  options:["3 次；FIN-WAIT-1","4 次；FIN-WAIT-1","3 次；TIME-WAIT","4 次；CLOSE-WAIT"], answer:"B",
  analysis:"TCP 释放连接采用四次挥手（FIN→ACK→FIN→ACK），发起方发 FIN 后进入 FIN-WAIT-1。" },
{ id:"m51", source:"mock", point:"传输层", diff:1,
  stem:"下列关于 UDP 协议的说法正确的是（　）。",
  options:["面向连接，提供可靠传输","无连接，不保证可靠交付，开销小","有拥塞控制机制","按序可靠交付数据"], answer:"B",
  analysis:"UDP 无连接、不保证可靠交付、无拥塞控制，头部开销小，适合实时应用（DNS、视频、语音等）。" },
{ id:"m52", source:"mock", point:"传输层", diff:3,
  stem:"TCP 拥塞控制机制不包括（　）。",
  options:["慢启动","拥塞避免","快重传与快恢复","滑动窗口重排"], answer:"D",
  analysis:"TCP 拥塞控制包括慢启动、拥塞避免、快重传、快恢复；滑动窗口用于流量控制。" },
{ id:"m53", source:"mock", point:"传输层", diff:1,
  stem:"DNS 服务默认使用的端口号是（　）。",
  options:["53","67","69","161"], answer:"A",
  analysis:"DNS 使用 53 端口（TCP 和 UDP）；67/68 为 DHCP，69 为 TFTP，161 为 SNMP。" },
/* ===== 应用层 ===== */
{ id:"m54", source:"mock", point:"应用层协议", diff:2,
  stem:"DNS 域名解析过程中，当本地缓存没有记录时，查询请求首先发往（　）。",
  options:["根域名服务器","本地配置的 DNS 服务器","权威域名服务器","TLD 域名服务器"], answer:"B",
  analysis:"主机先查本地缓存与 hosts 文件，未命中则把查询发给本地 DNS 服务器（递归解析），由它逐级迭代查询。" },
{ id:"m55", source:"mock", point:"应用层协议", diff:1,
  stem:"HTTP 状态码 404 表示（　）。",
  options:["服务器内部错误","请求成功","资源未找到","永久重定向"], answer:"C",
  analysis:"404 Not Found 表示服务器找不到请求的资源；200 成功，301 永久重定向，500 服务器内部错误。" },
{ id:"m56", source:"mock", point:"应用层协议", diff:2,
  stem:"FTP 协议中，控制连接使用的端口是（　），数据连接使用的端口是（　）。",
  options:["21；20","20；21","23；25","25；110"], answer:"A",
  analysis:"FTP 控制连接 21 端口、数据连接 20 端口（主动模式），控制连接贯穿会话始终。" },
{ id:"m57", source:"mock", point:"应用层协议", diff:2,
  stem:"下列协议与端口对应正确的是（　）。",
  options:["SMTP-25、POP3-110、IMAP-143","SMTP-110、POP3-25、IMAP-143","SMTP-25、POP3-143、IMAP-110","SMTP-143、POP3-110、IMAP-25"], answer:"A",
  analysis:"SMTP 发送邮件用 25 端口；POP3 收信用 110；IMAP 同步用 143。" },
{ id:"m58", source:"mock", point:"应用层协议", diff:2,
  stem:"DHCP 客户端获取 IP 地址的过程中，四步交互的顺序是（　）。",
  options:["DISCOVER→OFFER→REQUEST→ACK","OFFER→DISCOVER→REQUEST→ACK","DISCOVER→REQUEST→OFFER→ACK","REQUEST→DISCOVER→ACK→OFFER"], answer:"A",
  analysis:"DHCP 流程：客户端广播 DHCP Discover → 服务器回应 DHCP Offer → 客户端广播 DHCP Request → 服务器确认 DHCP ACK。" },
{ id:"m59", source:"mock", point:"应用层协议", diff:1,
  stem:"URL 中 https://www.example.com:8080/index.html 的端口号是（　）。",
  options:["80","443","8080","21"], answer:"C",
  analysis:"URL 中冒号后的数字为端口号，此处为 8080；未显式指定时 HTTPS 默认 443、HTTP 默认 80。" },
/* ===== 无线网络 ===== */
{ id:"m60", source:"mock", point:"无线网络", diff:2,
  stem:"2.4GHz 频段 Wi-Fi 网络中，3 个互不干扰的信道是（　）。",
  options:["1、6、11","1、5、10","2、7、12","3、8、13"], answer:"A",
  analysis:"2.4GHz 相邻信道中心频率间隔 5MHz、每信道 22MHz，只有 1、6、11 三个信道互不重叠干扰。" },
{ id:"m61", source:"mock", point:"无线网络", diff:2,
  stem:"IEEE 802.11ax（Wi-Fi 6）相比 802.11ac 的主要改进是（　）。",
  options:["引入 OFDMA 与 MU-MIMO，提升高密度场景吞吐","改用 2.4GHz 单频段","取消加密","降低到 54Mbps"], answer:"A",
  analysis:"Wi-Fi 6（802.11ax）引入 OFDMA、上行 MU-MIMO、BSS Coloring 等，显著提升多用户高密度场景的性能与能效。" },
{ id:"m62", source:"mock", point:"无线网络", diff:2,
  stem:"WPA2 加密机制采用的核心算法是（　）。",
  options:["RC4 的 TKIP","基于 AES 的 CCMP","DES","MD5"], answer:"B",
  analysis:"WPA2 使用基于 AES 的 CCMP 加密算法；WPA/WEP 使用 RC4（TKIP）。" },
/* ===== 网络安全 ===== */
{ id:"m63", source:"mock", point:"网络安全", diff:1,
  stem:"下列属于对称加密算法的是（　）。",
  options:["AES","RSA","ECC","SM2"], answer:"A",
  analysis:"AES、DES、3DES、SM1/SM4 为对称加密；RSA、ECC、SM2 为非对称加密。" },
{ id:"m64", source:"mock", point:"网络安全", diff:2,
  stem:"在使用公钥密码体制传输机密数据时，发送方应使用（　）加密。",
  options:["接收方的公钥","接收方的私钥","发送方的公钥","发送方的私钥"], answer:"A",
  analysis:"机密性传输：用接收方公钥加密，只有接收方私钥能解密；用发送方私钥签名则用于身份认证与防抵赖。" },
{ id:"m65", source:"mock", point:"网络安全", diff:2,
  stem:"数字签名的主要作用是（　）。",
  options:["保证数据的机密性","提供身份认证、完整性与不可抵赖性","提高传输速度","压缩数据"], answer:"B",
  analysis:"数字签名用发送方私钥对消息摘要加密，接收方用发送方公钥验证，实现身份认证、完整性校验与不可否认。" },
{ id:"m66", source:"mock", point:"网络安全", diff:2,
  stem:"状态检测防火墙的特点是在（　）维护连接状态表进行过滤。",
  options:["网络层与传输层","物理层","应用层","会话层"], answer:"A",
  analysis:"状态检测防火墙在网路层和传输层维护连接状态（状态表），结合上下文动态决定是否放行，性能与安全性兼顾。" },
{ id:"m67", source:"mock", point:"网络安全", diff:2,
  stem:"下列属于 VPN 隧道协议的是（　）。",
  options:["IPSec","SNMP","HTTP","ARP"], answer:"A",
  analysis:"常见 VPN 隧道协议：IPSec、L2TP、PPTP、GRE；IPSec 提供加密、认证与完整性保护。" },
{ id:"m68", source:"mock", point:"网络安全", diff:2,
  stem:"SYN Flood 攻击属于（　）类型。",
  options:["拒绝服务攻击（DoS/DDoS）","SQL 注入","中间人攻击","暴力破解"], answer:"A",
  analysis:"SYN Flood 通过大量半开连接耗尽服务器资源，属于拒绝服务攻击。" },
{ id:"m69", source:"mock", point:"网络安全", diff:3,
  stem:"根据网络安全等级保护 2.0 要求，三级及以上系统应在（　）部署入侵防范措施。",
  options:["关键网络节点","客户端浏览器","所有终端","机房外部"], answer:"A",
  analysis:"等保 2.0 三级要求：在关键网络节点处检测、防止或限制从外部发起的网络攻击行为（入侵防范）。" },
/* ===== 存储与新技术 ===== */
{ id:"m70", source:"mock", point:"存储与新技术", diff:2,
  stem:"RAID 0 的特点是（　）。",
  options:["条带化读写，无冗余，利用率 100%，一块盘故障即数据损坏","镜像冗余，利用率 50%","分布式奇偶校验，允许一块盘故障","双校验，允许两块盘故障"], answer:"A",
  analysis:"RAID 0 将数据条带化分布到多块磁盘，性能高但无冗余；RAID 1 镜像；RAID 5 分布式奇偶校验允许单盘故障。" },
{ id:"m71", source:"mock", point:"存储与新技术", diff:2,
  stem:"SDN（软件定义网络）的核心思想是（　）。",
  options:["控制平面与数据平面分离，集中控制","所有设备分布式自治","通过专用硬件转发","取消网络虚拟化"], answer:"A",
  analysis:"SDN 将网络控制平面与转发平面分离，由控制器集中管理，通过 OpenFlow 等南向接口下发流表。" },
{ id:"m72", source:"mock", point:"存储与新技术", diff:1,
  stem:"云计算服务模型中，向用户提供虚拟机、存储等基础资源的模式是（　）。",
  options:["IaaS","PaaS","SaaS","DaaS"], answer:"A",
  analysis:"IaaS 提供基础设施（计算/存储/网络）；PaaS 提供开发运行平台；SaaS 提供软件应用服务。" },
{ id:"m73", source:"mock", point:"存储与新技术", diff:3,
  stem:"VXLAN 使用 24 位 VNID 标识虚拟网络，最多可支持（　）个隔离的二层网络。",
  options:["4094","约 1600 万","65536","256"], answer:"B",
  analysis:"VXLAN 的 VNID 占 24 位，2^24 ≈ 1677 万个，远超传统 VLAN 的 4094 个，满足多租户云数据中心需求。" },
/* ===== 网络规划与布线 ===== */
{ id:"m74", source:"mock", point:"网络规划与布线", diff:2,
  stem:"结构化布线系统中，连接工作区信息插座与楼层配线间的子系统是（　）。",
  options:["水平子系统","干线子系统","管理子系统","设备间子系统"], answer:"A",
  analysis:"水平子系统连接工作区信息插座与楼层配线间（管理间）；干线子系统（垂直）连接设备间与各楼层配线间。" },
{ id:"m75", source:"mock", point:"网络规划与布线", diff:2,
  stem:"六类（Cat 6）双绞线支持的最高传输频率为（　）。",
  options:["100MHz","250MHz","500MHz","16MHz"], answer:"B",
  analysis:"Cat 5e 支持 100MHz、Cat 6 支持 250MHz、Cat 6a 支持 500MHz；Cat 6 可支持千兆及以上以太网。" },
{ id:"m76", source:"mock", point:"系统开发与项目管理", diff:2,
  stem:"网络系统开发的一般流程顺序是（　）。",
  options:["需求分析→通信分析→逻辑网络设计→物理网络设计→安装维护","需求分析→物理设计→逻辑设计→通信分析→维护","通信分析→需求分析→逻辑设计→维护→物理设计","逻辑设计→需求分析→通信分析→物理设计→维护"], answer:"A",
  analysis:"网络工程五阶段：需求分析、通信分析、逻辑网络设计、物理网络设计、安装维护（运维）。" },
{ id:"m77", source:"mock", point:"网络规划与布线", diff:2,
  stem:"数据中心设计中，成行排列的机柜长度大于（　）米时，两端应设置通道。",
  options:["3","6","9","15"], answer:"B",
  analysis:"依据《数据中心设计规范》，成行机柜长度大于 6 米时两端应设通道；两通道间距大于 15 米时中间还应增加通道。" }
];
