/* 真题库 · 2018 上半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2018上-01", source:"real", year:2018, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"浮点数的表示分为阶和尾数两部分。两个浮点数相加时，需要先对阶，即（　）（n为阶差的绝对值）。",
  options:["将大阶向小阶对齐，同时将尾数左移n位","将大阶向小阶对齐，同时将尾数右移n位","将小阶向大阶对齐，同时将尾数左移n位","将小阶向大阶对齐，同时将尾数右移n位"], answer:"D",
  analysis:"对阶时小阶向大阶看齐，尾数相应右移n位以保持数值不变。" },
{ id:"r2018上-02", source:"real", year:2018, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"计算机运行过程中，遇到突发事件，要求CPU暂时停止正在运行的程序，转去为突发事件服务，服务完毕再自动返回原程序继续执行，这个过程称为（　）。",
  options:["阻塞","中断","动态绑定","静态绑定"], answer:"B",
  analysis:"CPU暂停现行程序转去处理紧急事件、处理完再返回的过程称为中断。" },
{ id:"r2018上-03", source:"real", year:2018, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"承上，中断处理过程中保存现场的目的是（　）。",
  options:["防止丢失数据","防止对其他部件造成影响","返回去继续执行原程序","为中断处理程序提供数据"], answer:"C",
  analysis:"保存断点与寄存器现场，使中断返回后能继续执行原程序。" },
{ id:"r2018上-04", source:"real", year:2018, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"著作权中，（　）的保护期不受限制。",
  options:["发表权","发行权","署名权","展览权"], answer:"C",
  analysis:"署名权、修改权、保护作品完整权的保护期不受限制；发表权及财产权有保护期。" },
{ id:"r2018上-05", source:"real", year:2018, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"王某是某公司的软件设计师，完成某项软件开发后按公司规定进行软件归档。以下有关该软件的著作权的叙述中，正确的是（　）。",
  options:["著作权应由公司和王某共同享有","著作权应由公司享有","著作权应由王某享有","除署名权以外，著作权的其他权利由王某享有"], answer:"B",
  analysis:"职务作品，针对本职工作开发并由公司承担责任，著作权由公司享有。" },
{ id:"r2018上-06", source:"real", year:2018, sem:"上", paper:"上午", point:"计算机硬件", diff:4,
  stem:"海明码是一种纠错码。对于32位的数据，至少需要增加（　）个校验位才能构成海明码。",
  options:["3","4","5","6"], answer:"D",
  analysis:"由2^k ≥ m+k+1，m=32，得k=6(2^6=64≥39)。" },
{ id:"r2018上-07", source:"real", year:2018, sem:"上", paper:"上午", point:"计算机硬件", diff:4,
  stem:"以10位数据为例，海明码位序从右至左排列，数据位D9(位序14=8+4+2)由P4、P3、P2校验，则数据位D5(位序10=8+2)由（　）进行校验。",
  options:["P4P1","P4P2","P4P3P1","P3P2P1"], answer:"B",
  analysis:"位序10=8+2，对应第8位的P4和第2位的P2。" },
{ id:"r2018上-08", source:"real", year:2018, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"流水线的吞吐率是指单位时间流水线处理的任务数，如果各段流水的操作时间不同，则流水线的吞吐率是（　）的倒数。",
  options:["最短流水段操作时间","各段流水的操作时间总和","最长流水段操作时间","流水段数乘以最长流水段操作时间"], answer:"C",
  analysis:"流水线吞吐率受最慢(最长)流水段制约，其值为最长流水段时间的倒数。" },
{ id:"r2018上-09", source:"real", year:2018, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"某软件项目活动图中，多条路径并行(如C-E-H、A-B-F-J-L、D-G-I-K等)，边上数字为活动持续天数。关键路径决定完成该项目的最少时间为（　）天。",
  options:["18","20","22","24"], answer:"C",
  analysis:"关键路径(最长路径)总时长为22天，即项目最短完成时间。" },
{ id:"r2018上-10", source:"real", year:2018, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"承上，活动图中活动EH和IJ的松弛时间分别为（　）天。",
  options:["3和3","3和6","5和3","5和6"], answer:"C",
  analysis:"松弛时间=关键路径时长减去该活动所在路径时长，计算得EH为5、IJ为3。" },
{ id:"r2018上-11", source:"real", year:2018, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"以下关于曼彻斯特编码的描述中，正确的是（　）。",
  options:["每个比特都由一个码元组成","检测比特前沿的跳变来区分0和1","用电平的高低来区分0和1","不需要额外传输同步信号"], answer:"D",
  analysis:"曼彻斯特编码在每位中间跳变，自带时钟信息，无需额外传输同步信号。" },
{ id:"r2018上-12", source:"real", year:2018, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"100BASE-TX交换机，一个端口通信的数据速率(全双工)最大可以达到（　）。",
  options:["25Mb/s","50Mb/s","100Mb/s","200Mb/s"], answer:"D",
  analysis:"全双工下收发各100Mb/s，合计200Mb/s。" },
{ id:"r2018上-13", source:"real", year:2018, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"快速以太网标准100BASE-FX采用的传输介质是（　）。",
  options:["同轴电缆","无屏蔽双绞线","CATV电缆","光纤"], answer:"D",
  analysis:"FX表示光纤(Fiber)。" },
{ id:"r2018上-14", source:"real", year:2018, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"按照同步光纤网传输标准(SONET)，OC-1的数据速率为（　）Mb/s。",
  options:["51.84","155.52","466.96","622.08"], answer:"A",
  analysis:"OC-1(STS-1)=51.84Mb/s；OC-3=155.52Mb/s。" },
{ id:"r2018上-15", source:"real", year:2018, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"关于单模光纤，下面的描述中错误的是（　）。",
  options:["芯线由玻璃或塑料制成","比多模光纤芯径小","光波在芯线中以多种反射路径传播","比多模光纤的传输距离远"], answer:"C",
  analysis:"单模光纤只允许一种模式传播，多模才以多种反射路径传播；C说反。" },
{ id:"r2018上-16", source:"real", year:2018, sem:"上", paper:"上午", point:"网络规划与布线", diff:1,
  stem:"路由器通常采用（　）连接以太网交换机。",
  options:["RJ-45端口","Console端口","异步串口","高速同步串口"], answer:"A",
  analysis:"路由器通过RJ-45(以太网电口)连接以太网交换机。" },
{ id:"r2018上-17", source:"real", year:2018, sem:"上", paper:"上午", point:"数据通信基础", diff:4,
  stem:"在相隔20km的两地间通过电缆以100Mb/s的速率传送1518字节长的以太帧，从开始发送到接收完数据需要的时间约是（　）μs（信号速率为200m/μs）。",
  options:["131","221","1310","2210"], answer:"B",
  analysis:"发送时间=1518×8/100Mb/s≈121μs，传播时间=20000m/200m/μs=100μs，合计约221μs。" },
{ id:"r2018上-18", source:"real", year:2018, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"VLAN之间的通信通过（　）实现。",
  options:["二层交换机","网桥","路由器","中继器"], answer:"C",
  analysis:"VLAN间属不同广播域，需路由器(或三层交换机)进行三层转发。" },
{ id:"r2018上-19", source:"real", year:2018, sem:"上", paper:"上午", point:"广域网与接入", diff:2,
  stem:"HFC接入网采用（　）传输介质接入住宅小区。",
  options:["同轴电缆","光纤","5类双绞线","无线介质"], answer:"B",
  analysis:"HFC从局端到小区采用光纤，小区入户用同轴电缆。" },
{ id:"r2018上-20", source:"real", year:2018, sem:"上", paper:"上午", point:"传输层", diff:3,
  stem:"TCP协议中，URG指针的作用是（　）。",
  options:["表明TCP段中有带外数据","表明数据需要紧急传送","表明带外数据在TCP段中的位置","表明TCP段的发送方式"], answer:"C",
  analysis:"URG指针指出紧急数据(带外数据)在TCP段中的结束位置。" },
{ id:"r2018上-21", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"RARP协议的作用是（　）。",
  options:["根据MAC地址查IP地址","根据IP地址查MAC地址","分配IP地址","查找域内授权域名服务器"], answer:"A",
  analysis:"RARP反向地址解析，根据已知MAC地址请求对应的IP地址。" },
{ id:"r2018上-22", source:"real", year:2018, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"E1载波的基本帧由32个子信道组成，其中子信道（　）用于传送控制信令。",
  options:["CH0和CH2","CH1和CH15","CH15和CH16","CH0和CH16"], answer:"D",
  analysis:"E1中CH0用于帧同步、CH16用于随路信令(控制信令)。" },
{ id:"r2018上-23", source:"real", year:2018, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"以太网的数据帧封装中，MAC头14字节、类型2字节、IP头、数据、CRC 4字节。包含在IP数据报中的数据部分最长应该是（　）字节。",
  options:["1434","1460","1480","1500"], answer:"C",
  analysis:"以太网MTU=1500字节为IP数据报总长，减去20字节IP头，数据部分最长1480字节。" },
{ id:"r2018上-24", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"主机hostA(MAC aa-aa-aa-aa-aa-aa)发出查询hostB(MAC bb-bb-bb-bb-bb-bb)的MAC地址的ARP请求帧，此帧中的目标MAC地址为（　）。",
  options:["aa-aa-aa-aa-aa-aa","bb-bb-bb-bb-bb-bb","00-00-00-00-00-00","ff-ff-ff-ff-ff-ff"], answer:"D",
  analysis:"ARP请求以二层广播帧发送，目标MAC为ff-ff-ff-ff-ff-ff。" },
{ id:"r2018上-25", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"承上，该ARP报文中的目标MAC地址字段为（　）。",
  options:["aa-aa-aa-aa-aa-aa","bb-bb-bb-bb-bb-bb","00-00-00-00-00-00","ff-ff-ff-ff-ff-ff"], answer:"C",
  analysis:"ARP请求中还不知道目标MAC，报文中目标MAC字段填全0。" },
{ id:"r2018上-26", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"在RIP协议中，默认（　）秒更新一次路由。",
  options:["30","60","90","100"], answer:"A",
  analysis:"RIP默认每30秒周期性广播路由更新。" },
{ id:"r2018上-27", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于OSPF的描述中，错误的是（　）。",
  options:["根据链路状态法计算最佳路由","用于自治系统内的内部网关协议","采用Dijkstra算法进行路由计算","OSPF网络中用区域1来表示主干网段"], answer:"D",
  analysis:"OSPF主干区域为区域0(Area 0)，不是区域1。" },
{ id:"r2018上-28", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于RIP与OSPF的说法中，错误的是（　）。",
  options:["RIP定时发布路由信息，而OSPF在网络拓扑发生变化时发布路由信息","RIP的路由信息发送给邻居，而OSPF路由信息发送给整个网络路由器","RIP采用组播方式发布路由信息，而OSPF以广播方式发布路由信息","RIP和OSPF均为内部路由协议"], answer:"C",
  analysis:"RIPv1用广播、RIPv2用组播更新；OSPF用组播(224.0.0.5/6)更新，C说反。" },
{ id:"r2018上-29", source:"real", year:2018, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"在路由器上采用（　）命令可得到 Cisco 风格路由表(如“R 192.168.1.0/24 [120/1] via ...”、“C ... is directly connected”)的输出。",
  options:["show routing table","show ip route","ip routing","route print"], answer:"B",
  analysis:"Cisco路由器查看IP路由表用 show ip route。" },
{ id:"r2018上-30", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"承上，上述Cisco风格路由表中标志“R”表明这条路由是（　）。",
  options:["重定向路由","RIP路由","接收路由","直接连接"], answer:"B",
  analysis:"Cisco路由表中R表示RIP learned路由；C表示直连。" },
{ id:"r2018上-31", source:"real", year:2018, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"在Linux中，使用Apache发布Web服务时默认Web站点的目录为（　）。",
  options:["/etc/httpd","/var/log/httpd","/var/home","/home/httpd"], answer:"D",
  analysis:"Apache默认Web文档根目录为/home/httpd(早期RPM布局)。" },
{ id:"r2018上-32", source:"real", year:2018, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，要更改一个文件的权限设置可使用（　）命令。",
  options:["attrib","modify","chmod","change"], answer:"C",
  analysis:"chmod用于修改文件权限模式。" },
{ id:"r2018上-33", source:"real", year:2018, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，负责配置DNS的文件是（　），它包含了主机的域名搜索顺序和DNS服务器的地址。",
  options:["/etc/hostname","/dev/host.conf","/etc/resolv.conf","/dev/name.conf"], answer:"C",
  analysis:"/etc/resolv.conf配置DNS服务器地址与搜索域。" },
{ id:"r2018上-34", source:"real", year:2018, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"主域名服务器在接收到域名请求后，首先查询的是（　）。",
  options:["本地hosts文件","转发域名服务器","本地缓存","授权域名服务器"], answer:"C",
  analysis:"DNS解析先查本地缓存，缓存未命中再迭代查询。" },
{ id:"r2018上-35", source:"real", year:2018, sem:"上", paper:"上午", point:"应用层协议", diff:3,
  stem:"主机host1对host2进行域名查询，经过本地域名服务器、中介域名服务器、根域名服务器、授权域名服务器等多级交互，下列说法中正确的是（　）。",
  options:["本地域名服务器采用迭代算法","中介域名服务器采用迭代算法","根域名服务器采用递归算法","授权域名服务器采用何种算法不确定"], answer:"D",
  analysis:"算法由各服务器配置决定，授权域名服务器本身可采用迭代或递归，不确定。" },
{ id:"r2018上-36", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"自动专用IP地址(APIPA)用于客户端无法获得动态地址时作为临时主机地址，以下地址中属于自动专用IP地址的是（　）。",
  options:["224.0.0.1","127.0.0.1","169.254.1.15","192.168.0.1"], answer:"C",
  analysis:"APIPA地址范围为169.254.0.0/16。" },
{ id:"r2018上-37", source:"real", year:2018, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"在DNS的资源记录中，A记录（　）。",
  options:["表示IP地址到主机名的映射","表示主机名到IP地址的映射","指定授权服务器","指定区域邮件服务器"], answer:"B",
  analysis:"A记录实现域名到IPv4地址的正向映射；PTR为反向映射。" },
{ id:"r2018上-38", source:"real", year:2018, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"DHCP客户端通过（　）方式发送DHCPDiscover消息。",
  options:["单播","广播","组播","任意播"], answer:"B",
  analysis:"客户端启动时还无IP，以广播(0.0.0.0→255.255.255.255)发送Discover。" },
{ id:"r2018上-39", source:"real", year:2018, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"FTP协议默认使用的数据端口是（　）。",
  options:["20","80","25","23"], answer:"A",
  analysis:"FTP控制端口21，数据端口20。" },
{ id:"r2018上-40", source:"real", year:2018, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"在安全通信中，A将所发送的信息使用（　）进行数字签名。",
  options:["A的公钥","A的私钥","B的公钥","B的私钥"], answer:"B",
  analysis:"发送方用自己的私钥对消息摘要签名。" },
{ id:"r2018上-41", source:"real", year:2018, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"承上，B收到该消息后可利用（　）验证该消息的真实性。",
  options:["A的公钥","A的私钥","B的公钥","B的私钥"], answer:"A",
  analysis:"用发送方A的公钥验证数字签名。" },
{ id:"r2018上-42", source:"real", year:2018, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"攻击者通过发送一个目的主机已经接收过的报文来达到攻击目的，这种攻击方式属于（　）攻击。",
  options:["重放","拒绝服务","数据截获","数据流分析"], answer:"A",
  analysis:"重放攻击(replay)重发已接收过的报文冒充合法通信。" },
{ id:"r2018上-43", source:"real", year:2018, sem:"上", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"网络管理员调试网络，使用（　）命令来持续查看网络连通性。",
  options:["ping 目标地址 -g","ping 目标地址 -t","ping 目标地址 -r","ping 目标地址 -a"], answer:"B",
  analysis:"Windows下 ping -t 持续ping直到手动停止。" },
{ id:"r2018上-44", source:"real", year:2018, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"DES是一种（　）加密算法，其密钥长度为56位。",
  options:["共享密钥","公开密钥","报文摘要","访问控制"], answer:"A",
  analysis:"DES是对称(共享密钥)加密算法。" },
{ id:"r2018上-45", source:"real", year:2018, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"3DES是基于DES的加密方式，对明文进行3次DES操作以提高加密强度，其密钥长度是（　）位。",
  options:["56","112","128","168"], answer:"B",
  analysis:"3DES(两密钥)有效密钥长度为112位。" },
{ id:"r2018上-46", source:"real", year:2018, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"SNMP协议实体发送请求和应答报文的默认端口号是（　）。",
  options:["160","161","162","163"], answer:"B",
  analysis:"SNMP请求/应答用UDP 161；Trap用162。" },
{ id:"r2018上-47", source:"real", year:2018, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，SNMP采用UDP提供数据报服务，原因不包括（　）。",
  options:["UDP数据传输效率高","UDP面向连接，没有数据丢失","UDP无需确认，不增加主机重传负担","UDP开销小，不增加网络负载"], answer:"B",
  analysis:"UDP是无连接的，不保证无丢失，B说法本身错误。" },
{ id:"r2018上-48", source:"real", year:2018, sem:"上", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"SNMP代理收到一个GetNext请求时，如果不能提供指定对象的值，代理以（　）响应。",
  options:["该实例的上个值","该实例的下个值","Trap报文","错误信息"], answer:"B",
  analysis:"GetNext请求返回字典序中的下一个对象实例的值。" },
{ id:"r2018上-49", source:"real", year:2018, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"某客户端可以ping通同一网段内的部分计算机，原因可能是（　）。",
  options:["本机TCP/IP协议不能正常工作","本机DNS服务器地址设置错误","本机网络接口故障","网络中存在访问过滤"], answer:"D",
  analysis:"能ping通部分说明本机协议/接口/DNS基本正常，只能访问部分多因访问控制列表/过滤所致。" },
{ id:"r2018上-50", source:"real", year:2018, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"在TCP协议中，用于进行流量控制的字段为（　）。",
  options:["端口号","序列号","应答编号","窗口"], answer:"D",
  analysis:"窗口(Window)字段用于接收方通告接收能力，实现流量控制。" },
{ id:"r2018上-51", source:"real", year:2018, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"HDLC协议中，若监控帧采用SREJ进行应答，表明采用的差错控制机制为（　）。",
  options:["后退N帧ARQ","选择性拒绝ARQ","停等ARQ","慢启动"], answer:"B",
  analysis:"SREJ为选择拒绝，采用选择性重传(Selective Repeat)ARQ。" },
{ id:"r2018上-52", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"以下地址中用于组播的是（　）。",
  options:["10.1.205.0","192.168.0.7","202.105.107.1","224.1.210.5"], answer:"D",
  analysis:"D类地址224.0.0.0~239.255.255.255用于IP组播。" },
{ id:"r2018上-53", source:"real", year:2018, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"下列IP地址中，不能作为源地址的是（　）。",
  options:["0.0.0.0","127.0.0.1","190.255.255.255/24","192.168.0.1/24"], answer:"C",
  analysis:"190.255.255.255为该网段广播地址，不能作为源地址。" },
{ id:"r2018上-54", source:"real", year:2018, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"某公司网络的地址是192.168.192.0/20，要把该网络分成32个子网，则对应的子网掩码应该是（　）。",
  options:["255.255.252.0","255.255.254.0","255.255.255.0","255.255.255.128"], answer:"D",
  analysis:"分32个子网需借5位，/20+5=/25，掩码255.255.255.128。" },
{ id:"r2018上-55", source:"real", year:2018, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"承上，每个子网可分配的主机地址数是（　）。",
  options:["62","126","254","510"], answer:"B",
  analysis:"/25每个子网128个地址，扣除网络地址与广播地址，可用主机126个。" },
{ id:"r2018上-56", source:"real", year:2018, sem:"上", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"使用CIDR技术把4个C类网络110.217.128.0/22、110.217.132.0/22、110.217.136.0/22和110.217.140.0/22汇聚成一个超网，得到的地址是（　）。",
  options:["110.217.128.0/18","110.217.128.0/19","110.217.128.0/20","110.217.128.0/21"], answer:"C",
  analysis:"4个/22块覆盖第三字节128~143共16个C类，聚合为/20(块16)，即110.217.128.0/20。" },
{ id:"r2018上-57", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"如果IPv6头部包含多个扩展头部，第一个扩展头部为（　）。",
  options:["逐跳头部","路由选择头部","分段头部","认证头部"], answer:"A",
  analysis:"逐跳选项头部(Hop-by-Hop)若存在必须为第一个扩展头部。" },
{ id:"r2018上-58", source:"real", year:2018, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"用于生成VLAN标记的协议是（　）。",
  options:["IEEE802.1q","IEEE802.3","IEEE802.5","IEEE802.1d"], answer:"A",
  analysis:"802.1q定义VLAN标签。" },
{ id:"r2018上-59", source:"real", year:2018, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"两个站点采用二进制指数后退算法进行避让，3次冲突之后再次冲突的概率是（　）。",
  options:["0.5","0.25","0.125","0.0625"], answer:"C",
  analysis:"第3次冲突后退窗口为2^3=8，随机选0~7，再次冲突概率1/8=0.125。" },
{ id:"r2018上-60", source:"real", year:2018, sem:"上", paper:"上午", point:"数据通信基础", diff:4,
  stem:"在CSMA/CD以太网中，数据速率为100Mb/s，网段长2km，信号速率为200m/μs，则此网络的最小帧长是（　）比特。",
  options:["1000","2000","10000","200000"], answer:"B",
  analysis:"往返传播延时=2×2000m/200m/μs=20μs，最小帧长=100Mb/s×20μs=2000bit。" },
{ id:"r2018上-61", source:"real", year:2018, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下列快速以太网物理层标准中，使用5类无屏蔽双绞线作为传输介质的是（　）。",
  options:["100BASE-FX","100BASE-T4","100BASE-TX","100BASE-T2"], answer:"C",
  analysis:"100BASE-TX使用2对5类UTP。" },
{ id:"r2018上-62", source:"real", year:2018, sem:"上", paper:"上午", point:"无线网络", diff:3,
  stem:"在802.11中采用优先级来进行不同业务的区分，优先级最低的是（　）。",
  options:["服务访问点轮询","服务访问点轮询的应答","分布式协调功能竞争访问","分布式协调功能竞争访问帧的应答"], answer:"C",
  analysis:"DCF竞争访问(异步帧)优先级最低；PCF轮询优先级较高。" },
{ id:"r2018上-63", source:"real", year:2018, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"以下关于网络布线子系统的说法中，错误的是（　）。",
  options:["工作区子系统指终端到信息插座的区域","水平子系统实现计算机设备与各管理子系统间的连接","干线子系统用于连接楼层之间的设备间","建筑群子系统连接建筑物"], answer:"B",
  analysis:"水平子系统连接楼层配线间到工作区信息插座；连接设备间与管理子系统的是干线(垂直)子系统。" },
{ id:"r2018上-64", source:"real", year:2018, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"在华为路由器上，执行（　）命令可以查看各接口IP地址/掩码、物理层与协议层UP/DOWN状态的简要信息。",
  options:["display current-configuration","display ip interface brief","display stp brief","display rip 1 route"], answer:"B",
  analysis:"display ip interface brief简要显示各接口状态与IP。" },
{ id:"r2018上-65", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:4,
  stem:"某网络拓扑配置了RIP协议且已更新完成，AR2路由表中172.16.0.0/16显示为RIP路由。从路由信息可以判断（　）。",
  options:["在AR2上ping 172.16.0.1丢包","在AR1上ping 3.3.3.3丢包","在AR1上ping 172.16.1.1丢包","在AR3上ping 1.1.1.1丢包"], answer:"C",
  analysis:"因路由聚合/分类问题，AR1无法正确到达AR3下的172.16.1.1。" },
{ id:"r2018上-66", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"承上，造成该故障的原因是（　）。",
  options:["在AR1上环回地址172.16.0.1配置错误","在AR3上环回地址172.16.1.1配置错误","RIPv1不支持无类网络","RIPv2不支持无类网络"], answer:"C",
  analysis:"RIPv1为有类路由，不发送子网掩码，导致不同子网聚合/路由错误。" },
{ id:"r2018上-67", source:"real", year:2018, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"下面关于路由器的描述中，正确的是（　）。",
  options:["路由器中串口与以太口必须是成对的","路由器中串口与以太口的IP地址必须在同一网段","路由器的串口之间通常是点对点连接","路由器的以太口之间必须是点对点连接"], answer:"C",
  analysis:"串口(Serial)通常用于广域网点对点连接。" },
{ id:"r2018上-68", source:"real", year:2018, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"PGP的功能中不包括（　）。",
  options:["邮件压缩","发送者身份认证","邮件加密","邮件完整性认证"], answer:"A",
  analysis:"PGP提供加密、认证、完整性，但不负责邮件压缩。" },
{ id:"r2018上-69", source:"real", year:2018, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"如果DHCP客户端发现分配的IP地址已经被使用，客户端向服务器发出（　）报文，拒绝该IP地址。",
  options:["DHCPRelease","DHCPDecline","DHCPNack","DHCPRenew"], answer:"B",
  analysis:"DHCPDecline表示客户端发现地址冲突，拒绝使用。" },
{ id:"r2018上-70", source:"real", year:2018, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"在层次化园区网络设计中，（　）是汇聚层的功能。",
  options:["高速数据传输","出口路由","广播域的定义","MAC地址过滤"], answer:"C",
  analysis:"汇聚层通过VLAN/路由划分定义广播域；核心层负责高速传输。" },
{ id:"r2018上-71", source:"real", year:2018, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"With circuit switching, a (　) path is established between two stations for communication.（选最贴切的词）",
  options:["unique","dedicated","nondedicated","independent"], answer:"B",
  analysis:"电路交换建立一条专用(dedicated)通路。" },
{ id:"r2018上-72", source:"real", year:2018, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"Switching and transmission resources within the network are (　) for the exclusive use of the circuit for the duration of the connection.（选最贴切的词）",
  options:["discarded","abandoned","reserved","broken"], answer:"C",
  analysis:"连接期间交换与传输资源被预留(reserved)专供该电路使用。" },
{ id:"r2018上-73", source:"real", year:2018, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"The connection is (　): Once it is established, it appears to attached devices as if there were a direct connection.（选最贴切的词）",
  options:["indistinct","direct","indirect","transparent"], answer:"D",
  analysis:"对终端设备而言该连接是透明(transparent)的，仿佛直连。" },
{ id:"r2018上-74", source:"real", year:2018, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"Packet switching was designed to provide a more efficient facility than circuit switching for (　) data traffic.（选最贴切的词）",
  options:["casual","bursty","limited","abundant"], answer:"B",
  analysis:"分组交换为突发(bursty)数据流量提供比电路交换更高效的传输。" },
{ id:"r2018上-75", source:"real", year:2018, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"With internal virtual circuits, a route is defined between two endpoints and all packets for that virtual circuit follow the (　) route.（选最贴切的词）",
  options:["same","different","single","multiple"], answer:"A",
  analysis:"虚电路中同一虚电路的所有分组沿相同(same)路由传输。" }
]);
