/* 真题库 · 2017 上半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2017上-01", source:"real", year:2017, sem:"上", paper:"上午", point:"计算机硬件", diff:1,
  stem:"CPU执行算术或逻辑运算时，常将源操作数和结果暂存在（　）中。",
  options:["程序计数器(PC)","累加器(AC)","指令寄存器(IR)","地址寄存器(AR)"], answer:"B",
  analysis:"累加器AC暂存运算的源操作数和中间结果。" },
{ id:"r2017上-02", source:"real", year:2017, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"系统由一组3个并联部件与一组2个并联部件串联构成，每个部件千小时可靠度为R，则系统千小时可靠度为（　）。",
  options:["(1-R³)(1-R²)","(1-(1-R)³)(1-(1-R)²)","(1-R³)+(1-R²)","(1-(1-R)³)+(1-(1-R)²)"], answer:"B",
  analysis:"每并联组可靠度1-(1-R)^k，两组再相乘。" },
{ id:"r2017上-03", source:"real", year:2017, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"已知数据信息为16位，最少应附加（　）位校验位，才能实现海明码纠错。",
  options:["3","4","5","6"], answer:"C",
  analysis:"2^k≥m+k+1，m=16时k=5。" },
{ id:"r2017上-04", source:"real", year:2017, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"活动图：A→B(3)→D(5)→I(2)→J(2)→L(8)；A→E(4)→G(3)→J(2)；A→C(5)→F(3)→H(1)→K(5)→L(3)；G→H(3)；J→K(2)。完成项目最少时间为（　）天。",
  options:["17","18","19","20"], answer:"D",
  analysis:"关键路径A-B-D-I-J-L=3+5+2+2+8=20天。" },
{ id:"r2017上-05", source:"real", year:2017, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"承上，活动BD和HK最早可以从第（　）天开始（AB/AE/AC最早从第1天开始）。",
  options:["3和10","4和11","3和9","4和10"], answer:"B",
  analysis:"B最早第3天完成故BD第4天开始；H最早第10天完成(经A-E-G-H)，HK第11天开始。" },
{ id:"r2017上-06", source:"real", year:2017, sem:"上", paper:"上午", point:"数据通信基础", diff:1,
  stem:"数字语音的采样频率定义为8kHz，这是因为（　）。",
  options:["语音信号定义的频率最高值为4kHz","语音信号定义的频率最高值为8kHz","数字语音传输线路带宽只有8kHz","一般声卡采样频率最高为每秒8k次"], answer:"A",
  analysis:"按奈奎斯特，采样率≥2倍最高频率，语音最高4kHz故采样8kHz。" },
{ id:"r2017上-07", source:"real", year:2017, sem:"上", paper:"上午", point:"计算机硬件", diff:1,
  stem:"用300DPI分辨率扫描一幅3×4英寸的图片，可得到（　）像素的数字图像。",
  options:["300×300","300×400","900×4","900×1200"], answer:"D",
  analysis:"300×3=900，300×4=1200。" },
{ id:"r2017上-08", source:"real", year:2017, sem:"上", paper:"上午", point:"操作系统", diff:3,
  stem:"页面大小4K，页表：页0→块1、页1→块3、页2→块4、页3→块6。逻辑地址2D16H变换后的物理地址为（　）。",
  options:["2048H","4096H","4D16H","6D16H"], answer:"C",
  analysis:"2D16H页号为2、偏移D16H，映射到块4：4×1000H+D16H=4D16H。" },
{ id:"r2017上-09", source:"real", year:2017, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:1,
  stem:"根据我国商标法，下列商品中必须使用注册商标的是（　）。",
  options:["医疗仪器","墙壁涂料","无糖食品","烟草制品"], answer:"D",
  analysis:"烟草制品必须使用注册商标。" },
{ id:"r2017上-10", source:"real", year:2017, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"甲、乙同日就同样发明创造提交专利申请，以下解决办法中不可能采用的是（　）。",
  options:["甲、乙作为共同申请人","一方放弃并从另一方获补偿","甲、乙都不授予专利权","甲、乙都授予专利权"], answer:"D",
  analysis:"同样发明创造只能授予一项专利，不能双方都授权。" },
{ id:"r2017上-11", source:"real", year:2017, sem:"上", paper:"上午", point:"广域网与接入", diff:2,
  stem:"以下关于光纤的说法中，错误的是（　）。",
  options:["单模光纤纤芯直径更细","单模光纤采用LED作为光源","多模光纤比单模传输距离近","多模光纤中光波以多种模式传播"], answer:"B",
  analysis:"单模光纤采用激光器(LD)作光源；LED用于多模。" },
{ id:"r2017上-12", source:"real", year:2017, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"电话信道频率0~4kHz，信噪比30dB，则信道容量为（　）kb/s。",
  options:["4","20","40","80"], answer:"C",
  analysis:"C=Wlog2(1+S/N)=4000×log2(1001)≈40000b/s=40kb/s。" },
{ id:"r2017上-13", source:"real", year:2017, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"承上，要达到此容量，至少需要（　）个信号状态。",
  options:["4","8","16","32"], answer:"D",
  analysis:"40000=2×4000×log2(L)，log2(L)=5，L=32。" },
{ id:"r2017上-14", source:"real", year:2017, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"4B/5B编码先将数据按4位分组映射到5单位代码，然后采用（　）进行编码。",
  options:["PCM","Manchester","QAM","NRZ-I"], answer:"D",
  analysis:"4B/5B后用NRZ-I不归零反相编码。" },
{ id:"r2017上-15", source:"real", year:2017, sem:"上", paper:"上午", point:"数据通信基础", diff:4,
  stem:"A以1Mb/s同步发200000字节文件给1km外的B，数据帧128比特(首部48比特)、应答帧22比特，收到应答后发下一帧，传播速率200m/us。传送文件花费时间为（　）s。",
  options:["1.6","2.4","3.2","3.6"], answer:"C",
  analysis:"按帧发送+应答+传播往返计算，总耗时约3.2s。" },
{ id:"r2017上-16", source:"real", year:2017, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"承上，有效的数据速率为（　）Mb/s。",
  options:["0.2","0.5","0.7","0.8"], answer:"B",
  analysis:"有效载荷96比特/帧，扣除首部与开销后约0.5Mb/s。" },
{ id:"r2017上-17", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"路由器与计算机串行接口连接、利用虚拟终端对路由器本地配置的接口是（　）。",
  options:["Console口","同步串行口","SFP端口","AUX端口"], answer:"A",
  analysis:"Console口用于本地(虚拟终端)初始配置。" },
{ id:"r2017上-18", source:"real", year:2017, sem:"上", paper:"上午", point:"广域网与接入", diff:1,
  stem:"承上，路由器通过光纤连接广域网的接口是（　）。",
  options:["Console口","同步串行口","SFP端口","AUX端口"], answer:"C",
  analysis:"SFP光模块端口用于光纤广域网连接。" },
{ id:"r2017上-19", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"IEEE 802.3z为1000Mb/s标准，下列千兆以太网中不属于该标准的是（　）。",
  options:["1000Base-SX","1000Base-LX","1000Base-T","1000Base-CX"], answer:"C",
  analysis:"1000Base-T属802.3ab(双绞线)，非802.3z。" },
{ id:"r2017上-20", source:"real", year:2017, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"IPv4首部中首部长度字段(IHL)的值最小为（　）。",
  options:["2","5","10","15"], answer:"B",
  analysis:"IHL以4字节为单位，最小5即20字节。" },
{ id:"r2017上-21", source:"real", year:2017, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"为防止IP数据报在网络中无限制转发，IPv4首部通过（　）字段加以控制。",
  options:["URG","Offset","More","TTL"], answer:"D",
  analysis:"TTL每经一跳减1，到0丢弃，防止环路无限转发。" },
{ id:"r2017上-22", source:"real", year:2017, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"主机甲发SYN=1、序列号2000，若主机乙同意建立连接，则发给甲的报文段为（　）。",
  options:["(SYN=1,ACK=1,seq=2001,ack=2001)","(SYN=1,ACK=0,seq=2000,ack=2000)","(SYN=1,ACK=0,seq=2001,ack=2001)","(SYN=0,ACK=1,seq=2000,ack=2000)"], answer:"A",
  analysis:"乙回SYN+ACK，确认号=2000+1=2001。" },
{ id:"r2017上-23", source:"real", year:2017, sem:"上", paper:"上午", point:"传输层", diff:1,
  stem:"承上，若主机乙不同意建立连接，则（　）字段置“1”。",
  options:["URG","RST","PSH","FIN"], answer:"B",
  analysis:"拒绝连接时发RST复位报文。" },
{ id:"r2017上-24", source:"real", year:2017, sem:"上", paper:"上午", point:"传输层", diff:4,
  stem:"TCP慢启动，MSS=1000字节，甲发第1段并收到确认、接收窗口3000字节，则此时甲最多可发（　）字节。",
  options:["1000","2000","3000","4000"], answer:"B",
  analysis:"慢启动收到1个ACK后拥塞窗口=2MSS=2000，受min(cwnd,rwnd)=2000限制。" },
{ id:"r2017上-25", source:"real", year:2017, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"RIPv2有选择地把路由信息发给邻居、一条路由不发回其来源，这种方案称为（　）。",
  options:["反向毒化","乒乓反弹","水平分割法","垂直划分法"], answer:"C",
  analysis:"水平分割不把路由从收到它的接口发回去。" },
{ id:"r2017上-26", source:"real", year:2017, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"承上，该方案的作用是（　）。",
  options:["支持CIDR","解决路由环路","扩大最大跳步数","不使用广播更新"], answer:"B",
  analysis:"水平分割用于避免距离矢量路由环路。" },
{ id:"r2017上-27", source:"real", year:2017, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"OSPF中（　）不接受本AS以外的路由信息，对外部目标采用默认路由0.0.0.0。",
  options:["分支区域","标准区域","主干区域","存根区域"], answer:"D",
  analysis:"Stub存根区域用默认路由替代外部ASE路由。" },
{ id:"r2017上-28", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"客户机请求Web的以太网帧前16字节为：00-23-89-1a-06-7c | 00-1d-7d-39-62-3e | 08-00。客户机默认网关的物理地址为（　）。",
  options:["00-23-89-1a-06-7c","00-1d-7d-39-62-3e","00-00-00-00-00-00","ff-ff-ff-ff-ff-ff"], answer:"A",
  analysis:"帧第1个6字节为目的MAC，即下一跳网关MAC 00-23-89-1a-06-7c。" },
{ id:"r2017上-29", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"承上，客户机查找默认网关物理地址时使用的协议是（　）。",
  options:["FTP","ARP","BGP","ICMP"], answer:"B",
  analysis:"ARP把网关IP解析为MAC地址。" },
{ id:"r2017上-30", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"承上，客户机查找网关MAC时发出的数据帧中目的MAC地址为（　）。",
  options:["00-23-89-1a-06-7c","00-1d-7d-39-62-3e","00-00-00-00-00-00","ff-ff-ff-ff-ff-ff"], answer:"D",
  analysis:"ARP请求为二层广播，目的MAC为全f广播地址。" },
{ id:"r2017上-31", source:"real", year:2017, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"下面关于Linux目录的描述中，正确的是（　）。",
  options:["只有一个根目录，用/root表示","有多个根目录，用/加目录名表示","只有一个根目录，用/表示","有多个根目录，用目录名表示"], answer:"C",
  analysis:"Linux目录树只有一个根，用/表示。" },
{ id:"r2017上-32", source:"real", year:2017, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，可以使用（　）命令为计算机配置IP地址。",
  options:["ifconfig","config","ip-address","ipconfig"], answer:"A",
  analysis:"ifconfig用于查看/配置网络接口IP。" },
{ id:"r2017上-33", source:"real", year:2017, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，通常使用（　）命令删除一个文件或目录。",
  options:["rm -i","mv -i","mk -i","cat -i"], answer:"A",
  analysis:"rm删除文件/目录，-i删除前确认。" },
{ id:"r2017上-34", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"在以太网中发生冲突时采用退避机制，（　）优先传输数据。",
  options:["冲突次数最少的设备","冲突中IP地址最小的设备","冲突域中重传计时器首先过期的设备","同时开始传输的设备"], answer:"C",
  analysis:"退避后重传计时器先到期的设备优先发送。" },
{ id:"r2017上-35", source:"real", year:2017, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"在Windows中，远程桌面使用的默认端口是（　）。",
  options:["80","3389","8080","1024"], answer:"B",
  analysis:"RDP远程桌面默认TCP 3389。" },
{ id:"r2017上-36", source:"real", year:2017, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"Linux中创建权限rw-rw-r--的普通文件，下面说法正确的是（　）。",
  options:["文件所有者对该文件可读可写","同组用户对该文件只可读","其他用户对该文件可读可写","其他用户对该文件可读可查询"], answer:"A",
  analysis:"rw-rw-r--：所有者与同组可读写，其他只读。" },
{ id:"r2017上-37", source:"real", year:2017, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"PGP使用（　）进行数据加密。",
  options:["RSA","IDEA","MD5","SHA-1"], answer:"B",
  analysis:"PGP用对称算法IDEA加密邮件正文。" },
{ id:"r2017上-38", source:"real", year:2017, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"承上，PGP使用（　）进行数据完整性验证。",
  options:["RSA","IDEA","MD5","SHA-1"], answer:"C",
  analysis:"PGP用MD5消息摘要做完整性校验。" },
{ id:"r2017上-39", source:"real", year:2017, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"IPSec用于增强IP网络安全，下面说法中不正确的是（　）。",
  options:["可对数据进行完整性保护","提供用户身份认证服务","认证头添加在TCP封装内部","对数据加密传输"], answer:"C",
  analysis:"IPSec在IP层加AH/ESP，并非封装在TCP内部。" },
{ id:"r2017上-40", source:"real", year:2017, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"浏览器输入正确网址后，本地主机将首先在（　）中查询该网址对应的IP地址。",
  options:["本地DNS缓存","本机hosts文件","本地DNS服务器","根域名服务器"], answer:"B",
  analysis:"域名解析先查本机hosts文件(及本地缓存)。" },
{ id:"r2017上-41", source:"real", year:2017, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"三重DES加密使用（　）个密钥对明文进行3次加密。",
  options:["1","2","3","4"], answer:"B",
  analysis:"常用3DES两密钥版本(K1-K2-K1)。" },
{ id:"r2017上-42", source:"real", year:2017, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"承上，三重DES的密钥长度为（　）位。",
  options:["56","112","128","168"], answer:"B",
  analysis:"两个56位密钥共112位。" },
{ id:"r2017上-43", source:"real", year:2017, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"以下加密算法中，适合对大量原文消息进行加密传输的是（　）。",
  options:["RSA","SHA-1","MD5","RC5"], answer:"D",
  analysis:"RC5为对称分组密码，适合大量数据加密。" },
{ id:"r2017上-44", source:"real", year:2017, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"用户A、B分别在CA I1和I2取得证书，（　）是A、B互信的必要条件。",
  options:["A、B互换私钥","A、B互换公钥","I1、I2互换私钥","I1、I2互换公钥"], answer:"D",
  analysis:"两个CA互信需互换各自公钥，建立交叉认证。" },
{ id:"r2017上-45", source:"real", year:2017, sem:"上", paper:"上午", point:"网络安全", diff:1,
  stem:"SHA-1是将不同长度输入信息转换成（　）位固定长度摘要的算法。",
  options:["128","160","256","512"], answer:"B",
  analysis:"SHA-1产生160位摘要。" },
{ id:"r2017上-46", source:"real", year:2017, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"网络管理员执行undo mac-address blackhole命令，其作用是（　）。",
  options:["禁止用户接口透传VLAN","关闭接口MAC学习功能","为用户接口配置端口安全","删除配置的黑洞MAC"], answer:"D",
  analysis:"undo取消黑洞MAC配置。" },
{ id:"r2017上-47", source:"real", year:2017, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"介质老化/破损/规格不匹配致物理接口DOWN，常用（　）命令检查光纤模块状态参数。",
  options:["virtual-cable-test","display transceiver interface","display device","display interface"], answer:"B",
  analysis:"display transceiver interface查看光模块参数状态。" },
{ id:"r2017上-48", source:"real", year:2017, sem:"上", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"设备CPU长时间过高，display stp topology-change中“Number of topology changes”频繁变化，可初步判断故障由（　）导致。",
  options:["硬件故障","网络攻击","网络震荡","网络环路"], answer:"C",
  analysis:"拓扑变化频繁表明STP网络震荡。" },
{ id:"r2017上-49", source:"real", year:2017, sem:"上", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"承上，可能的原因是（　）。",
  options:["网络上某个端口链路属性频繁变化","广播风暴造成大量协议报文","设备受到DHCP协议报文攻击","硬件故障上报大量中断"], answer:"A",
  analysis:"端口up/down频繁触发拓扑变更，导致网络震荡。" },
{ id:"r2017上-50", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"SwitchA ping SwitchB(192.168.1.100)不通，查接口配置后用port link-type trunk修改SwitchB排除故障，原因是（　）。",
  options:["SwitchB接口VLAN不正确","SwitchB接口状态为DOWN","SwitchB链路类型配置错误","SwitchB丢弃ICMP报文"], answer:"C",
  analysis:"修改链路类型为trunk即链路类型配置错误。" },
{ id:"r2017上-51", source:"real", year:2017, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"DHCP给PC1分配的默认网关是202.117.110.65/27，则PC1的地址可能是（　）。",
  options:["202.117.110.94","202.117.110.95","202.117.110.96","202.117.110.97"], answer:"A",
  analysis:"/27块64-95，可用主机66-94，仅.94可用(.95广播)。" },
{ id:"r2017上-52", source:"real", year:2017, sem:"上", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"给定192.168.1.0/24，部门1需100、部门2需50、部门3需30、部门4/5各需10，按VLSM，部门3的子网掩码为（　）。",
  options:["255.255.255.128","255.255.255.192","255.255.255.224","255.255.255.240"], answer:"C",
  analysis:"部门3需30台，/27提供30主机，掩码255.255.255.224。" },
{ id:"r2017上-53", source:"real", year:2017, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"某单位有1000台主机，至少需分配（　）个C类网络。",
  options:["4","8","12","16"], answer:"A",
  analysis:"4×254=1016≥1000。" },
{ id:"r2017上-54", source:"real", year:2017, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"承上，超网号202.25.64.0，则地址掩码是（　）。",
  options:["255.255.224.0","255.255.240.0","255.255.248.0","255.255.252.0"], answer:"D",
  analysis:"4个C类聚合前缀/22，掩码255.255.252.0。" },
{ id:"r2017上-55", source:"real", year:2017, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"在网络101.113.10.0/29中，能接收到目的地址是101.113.10.7的报文的主机数最多有（　）个。",
  options:["1","3","5","6"], answer:"D",
  analysis:".7是该/29块广播地址，广播帧被块内6个可用主机收到。" },
{ id:"r2017上-56", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"查看VLAN配置信息的命令是（　）。",
  options:["display current-configuration","display vlan brief","system-view","vlan vlan-id"], answer:"B",
  analysis:"display vlan brief查看VLAN简要配置。" },
{ id:"r2017上-57", source:"real", year:2017, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"R1-R2-R3三台RIPv2路由器串联连接，路由表项最少需经过（　）可达到收敛状态。",
  options:["30s","60s","90s","120s"], answer:"B",
  analysis:"RIP每30s更新，3台串联需经2个更新周期=60s收敛。" },
{ id:"r2017上-58", source:"real", year:2017, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"运行OSPF的路由器在选举DR/BDR之前，DR是（　）。",
  options:["路由器自身","直连路由器","IP地址最大的路由器","MAC地址最大的路由器"], answer:"A",
  analysis:"选举前DR尚未确定，各路由器以自身为DR参与(Hello中DR=0或自身)。" },
{ id:"r2017上-59", source:"real", year:2017, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"关于OSPF路由协议，正确的是（　）。",
  options:["OSPF是距离矢量协议","进程号全局有效","不同进程之间可以进行路由重分布","主区域为区域1"], answer:"C",
  analysis:"OSPF进程号本地有效，不同进程间可重分布；主区域为Area0。" },
{ id:"r2017上-60", source:"real", year:2017, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"IPv6链路本地单播地址的前缀为（　）。",
  options:["001","1111 1110 10","1111 1110 11","1111 1111"], answer:"B",
  analysis:"链路本地地址前缀FE80::/10即1111111010。" },
{ id:"r2017上-61", source:"real", year:2017, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"IPv6可聚集全球单播地址的前缀为（　）。",
  options:["001","1111 1110 10","1111 1110 11","1111 1111"], answer:"A",
  analysis:"全球单播地址以001(2000::/3)开头。" },
{ id:"r2017上-62", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"在缺省配置时交换机所有端口（　）。",
  options:["属于直通状态","属于不同VLAN","属于同一VLAN","地址都相同"], answer:"C",
  analysis:"缺省所有端口都在默认VLAN1。" },
{ id:"r2017上-63", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"承上，不同VLAN的数据帧必须通过（　）传输。",
  options:["DNS服务器","路由器","二层交换机","DHCP服务器"], answer:"B",
  analysis:"VLAN间需经路由器(三层设备)路由。" },
{ id:"r2017上-64", source:"real", year:2017, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"在以太网中出于对（　）的考虑，需设置数据帧的最小帧。",
  options:["重传策略","故障检测","冲突检测","提高速率"], answer:"C",
  analysis:"最小帧长保证冲突在发送完毕前可被检测到。" },
{ id:"r2017上-65", source:"real", year:2017, sem:"上", paper:"上午", point:"无线网络", diff:1,
  stem:"在中国区域内，2.4GHz无线频段分为（　）个信道。",
  options:["11","12","13","14"], answer:"C",
  analysis:"中国/欧洲2.4G共13个非重叠信道(1~13)。" },
{ id:"r2017上-66", source:"real", year:2017, sem:"上", paper:"上午", point:"无线网络", diff:1,
  stem:"802.11g的最高数据传输速率为（　）Mbps。",
  options:["11","28","54","108"], answer:"C",
  analysis:"802.11g最高54Mbps。" },
{ id:"r2017上-67", source:"real", year:2017, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"结构化布线中，水平子系统的作用是（　）。",
  options:["实现各楼层设备间子系统之间互连","实现中央主配线架和各种设备连接","连接干线子系统和用户工作区","连接各建筑物中的通信系统"], answer:"C",
  analysis:"水平子系统连接设备间(管理)子系统到工作区信息插座。" },
{ id:"r2017上-68", source:"real", year:2017, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"承上，干线子系统的作用是（　）。",
  options:["实现各楼层设备间子系统之间互连","实现中央主配线架和各种设备连接","连接干线子系统和用户工作区","连接各建筑物中的通信系统"], answer:"A",
  analysis:"干线(垂直)子系统互连各楼层设备间。" },
{ id:"r2017上-69", source:"real", year:2017, sem:"上", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"新办公楼双核心+接入交换机拓扑规划，以下说法不合理的是（　）。",
  options:["核心交换机间可采用VRRP、虚拟化等技术","各VLAN间访问需经过两台核心之一","接入交换机多采用三层交换机","网络拓扑结构可靠"], answer:"C",
  analysis:"接入层一般用二层交换机，三层路由由核心承担。" },
{ id:"r2017上-70", source:"real", year:2017, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"巡检发现交换机端口CRC错包不断上涨，下面原因中不可能的是（　）。",
  options:["端口状态异常","物理链路故障","电磁干扰","病毒攻击"], answer:"D",
  analysis:"CRC错包源于物理层/链路层问题，病毒攻击不会直接造成CRC错误。" },
{ id:"r2017上-71", source:"real", year:2017, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"...PDUs may traverse (　) paths through the network.（选最贴切的词）",
  options:["same","different","single","unique"], answer:"B",
  analysis:"PDU可能沿不同(different)路径到达。" },
{ id:"r2017上-72", source:"real", year:2017, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"...each PDU is given a unique number, numbers are assigned (　).（选最贴切的词）",
  options:["randomly","equally","uniformly","sequentially"], answer:"D",
  analysis:"序号按顺序(sequentially)分配。" },
{ id:"r2017上-73", source:"real", year:2017, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"...reorder (　) PDUs on the basis of sequence number.（选最贴切的词）",
  options:["received","sent","transmitting","forwarding"], answer:"A",
  analysis:"接收端对已收到(received)的PDU重新排序。" },
{ id:"r2017上-74", source:"real", year:2017, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"...with a (　) sequence number field, sequence number will repeat.（选最贴切的词）",
  options:["various","diverse","finite","infinite"], answer:"C",
  analysis:"序号字段有限(finite)，使用后会循环复用。" },
{ id:"r2017上-75", source:"real", year:2017, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"...the maximum sequence number must be (　) than the maximum number of outstanding PDUs.（选最贴切的词）",
  options:["smaller","greater","less","more"], answer:"B",
  analysis:"最大序号必须大于(greater)在途PDU最大数，才能唯一标识。" }
]);
