/* 真题库 · 2018 下半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2018下-01", source:"real", year:2018, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"采用n位补码（包含一个符号位）表示数据，可以直接表示数值（　）。",
  options:["2^n","-2^n","2^(n-1)","-2^(n-1)"], answer:"D",
  analysis:"n位补码表示范围为 -2^(n-1) ~ 2^(n-1)-1，可直接表示 -2^(n-1)。" },
{ id:"r2018下-02", source:"real", year:2018, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"以下关于采用一位奇校验方法的叙述中，正确的是（　）。",
  options:["若所有奇数位出错，则可以检测出该错误但无法纠正错误","若所有偶数位出错，则可以检测出该错误并加以纠正","若有奇数个数据位出错，则可以检测出该错误但无法纠正错误","若有偶数个数据位出错，则可以检测出该错误并加以纠正"], answer:"C",
  analysis:"奇校验只能检错不能纠错；奇数位出错会改变奇偶性可被检出，但无法定位出错位。" },
{ id:"r2018下-03", source:"real", year:2018, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"下列关于流水线方式执行指令的叙述中，不正确的是（　）。",
  options:["流水线方式可提高单条指令的执行速度","流水线方式下可同时执行多条指令","流水线方式提高了各部件的利用率","流水线方式提高了系统的吞吐率"], answer:"A",
  analysis:"流水线提高的是吞吐率（多条指令并行），单条指令执行时间并未缩短。" },
{ id:"r2018下-04", source:"real", year:2018, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"在存储体系中位于主存与CPU之间的高速缓存(Cache)用于存放主存中部分信息的副本，主存地址与Cache地址之间的转换工作（　）。",
  options:["由系统软件实现","由硬件自动完成","由应用软件实现","由用户发出指令完成"], answer:"B",
  analysis:"Cache地址映射与替换由硬件自动完成，对程序员透明。" },
{ id:"r2018下-05", source:"real", year:2018, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"在指令系统的各种寻址方式中，获取操作数最快的方式是（　）。",
  options:["直接寻址","间接寻址","立即寻址","寄存器寻址"], answer:"C",
  analysis:"立即寻址的操作数直接在指令中，无需访存，获取最快。" },
{ id:"r2018下-06", source:"real", year:2018, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"有可能无限期拥有的知识产权是（　）。",
  options:["著作权","专利权","商标权","集成电路布图设计权"], answer:"C",
  analysis:"商标权可无限次续展注册，理论上可无限期拥有；著作权、专利权有法定保护期。" },
{ id:"r2018下-07", source:"real", year:2018, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"某软件项目活动图中多条路径并行(如A-B-E-G、A-B-H等，边上数字为活动持续天数)，完成该项目的最少时间为（　）天。",
  options:["20","37","38","46"], answer:"D",
  analysis:"关键路径(最长路径)总时长为46天。" },
{ id:"r2018下-08", source:"real", year:2018, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"承上，活动图中活动FG的松弛时间为（　）天。",
  options:["9","10","18","26"], answer:"C",
  analysis:"松弛时间=关键路径时长减去该活动所在路径时长，计算得18天。" },
{ id:"r2018下-09", source:"real", year:2018, sem:"下", paper:"上午", point:"操作系统", diff:4,
  stem:"某计算机系统中互斥资源R的可用数为8，系统中有3个进程P1、P2和P3竞争R，且每个进程都需要i个R，该系统可能会发生死锁的最小i值为（　）。",
  options:["1","2","3","4"], answer:"D",
  analysis:"最坏情况3进程各占i-1个共3(i-1)，若3(i-1)≥8即i≥4时可能死锁，最小i=4。" },
{ id:"r2018下-10", source:"real", year:2018, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"以下关于信息和数据的描述中，错误的是（　）。",
  options:["通常从数据中可以提取信息","信息和数据都由数字组成","信息是抽象的、数据是具体的","客观事物中都蕴涵着信息"], answer:"B",
  analysis:"数据不仅由数字组成，还包括文字、图像、声音等；B说法错误。" },
{ id:"r2018下-11", source:"real", year:2018, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"设信号的波特率为800Baud，采用幅度-相位复合调制技术，由4种幅度和8种相位组成16种码元，则信道的数据速率为（　）。",
  options:["1600b/s","2400b/s","3200b/s","4800b/s"], answer:"C",
  analysis:"16种码元即每码元log2(16)=4bit，数据速率=800×4=3200b/s。" },
{ id:"r2018下-12", source:"real", year:2018, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"采用双极型AMI编码进行数据传输，接收波形按位0~10排列，已知AMI编码中1极性应交替翻转，波形中违反极性交替规则、出错的是第（　）位。",
  options:["2","5","7","9"], answer:"C",
  analysis:"AMI编码中“1”的极性须交替翻转，第7位极性与规则矛盾，为出错位。" },
{ id:"r2018下-13", source:"real", year:2018, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"以下关于DPSK调制技术的描述中，正确的是（　）。",
  options:["采用2种相位，一种固定表示数据0，一种固定表示数据1","采用2种相位，通过前沿有无相位的改变来表示数据0和1","采用4种振幅，每个码元表示2比特","采用4种频率，每个码元表示2比特"], answer:"B",
  analysis:"DPSK为差分相移键控，利用相邻码元前沿有无相位跳变来表示0/1。" },
{ id:"r2018下-14", source:"real", year:2018, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"下面关于Manchester编码的叙述中，错误的是（　）。",
  options:["Manchester编码是一种双相码","Manchester编码是一种归零码","Manchester编码提供了比特同步信息","Manchester编码应用在以太网中"], answer:"B",
  analysis:"曼彻斯特编码是双相码、非归零码(每位中间均有电平)，不是归零码。" },
{ id:"r2018下-15", source:"real", year:2018, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"假设模拟信号的频率范围为2~8MHz，采样频率必须大于（　）时，才能使得到的样本信号不失真。",
  options:["4MHz","6MHz","12MHz","16MHz"], answer:"D",
  analysis:"奈奎斯特定理：采样频率大于最高频率2倍，即2×8MHz=16MHz。" },
{ id:"r2018下-16", source:"real", year:2018, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"设信道带宽为1000Hz，信噪比为30dB，则信道的最大数据速率约为（　）b/s。",
  options:["10000","20000","30000","40000"], answer:"A",
  analysis:"香农公式C=Wlog2(1+S/N)，30dB即S/N=1000，C≈1000×log2(1001)≈10000b/s。" },
{ id:"r2018下-17", source:"real", year:2018, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"设信道带宽为5000Hz，采用PCM编码，采样周期为125μs，每个样本量化为256个等级，则信道的数据速率为（　）。",
  options:["10Kb/s","40Kb/s","56Kb/s","64Kb/s"], answer:"D",
  analysis:"采样率=1/125μs=8000次/秒，256级=8bit，速率=8000×8=64Kb/s。" },
{ id:"r2018下-18", source:"real", year:2018, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"使用ADSL接入Internet，用户端需要安装（　）协议。",
  options:["PPP","SLIP","PPTP","PPPoE"], answer:"D",
  analysis:"ADSL拨号上网采用PPPoE在以太网上承载PPP。" },
{ id:"r2018下-19", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"下列关于OSPF协议的说法中，错误的是（　）。",
  options:["OSPF的每个区域(Area)运行路由选择算法的一个实例","OSPF采用Dijkstra算法计算最佳路由","OSPF路由器向各个活动端口组播Hello分组来发现邻居路由器","OSPF协议默认的路由更新周期为30秒"], answer:"D",
  analysis:"OSPF为触发更新，无30秒周期；RIP才是30秒周期更新。" },
{ id:"r2018下-20", source:"real", year:2018, sem:"下", paper:"上午", point:"传输层", diff:3,
  stem:"TCP使用3次握手协议建立连接，以防止（　）。",
  options:["出现半连接","无法连接","产生错误的连接","连接失效"], answer:"C",
  analysis:"三次握手防止已失效的旧连接请求突然到达而产生错误连接。" },
{ id:"r2018下-21", source:"real", year:2018, sem:"下", paper:"上午", point:"传输层", diff:2,
  stem:"承上，当请求方发出SYN连接请求后，等待对方回答（　）以建立正确的连接。",
  options:["SYN,ACK","FIN,ACK","PSH,ACK","RST,ACK"], answer:"A",
  analysis:"服务器收到SYN后回复SYN+ACK。" },
{ id:"r2018下-22", source:"real", year:2018, sem:"下", paper:"上午", point:"传输层", diff:2,
  stem:"承上，当出现错误连接时，响应（　）。",
  options:["SYN,ACK","FIN,ACK","PSH,ACK","RST,ACK"], answer:"D",
  analysis:"出现错误连接时用RST复位。" },
{ id:"r2018下-23", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"ARP协议数据单元封装在（　）中传送。",
  options:["IP分组","以太帧","TCP段","ICMP报文"], answer:"B",
  analysis:"ARP报文直接封装在以太网帧中(类型0x0806)。" },
{ id:"r2018下-24", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"在BGP4协议中，路由器通过发送（　）报文将正常工作信息告知邻居。",
  options:["hello","update","keepalive","notification"], answer:"C",
  analysis:"BGP用Keepalive报文维持对等体连接、告知正常工作。" },
{ id:"r2018下-25", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"承上，当出现路由信息的新增或删除时，采用（　）报文告知对方。",
  options:["hello","update","keepalive","notification"], answer:"B",
  analysis:"BGP用Update报文发布路由增删信息。" },
{ id:"r2018下-26", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"RIP协议默认的路由更新周期是（　）秒。",
  options:["30","60","90","100"], answer:"A",
  analysis:"RIP默认30秒周期更新。" },
{ id:"r2018下-27", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于OSPF协议的叙述中，正确的是（　）。",
  options:["OSPF是一种路径矢量协议","OSPF使用链路状态公告(LSA)扩散路由信息","OSPF网络中用区域1来表示主干网段","OSPF路由器向邻居发送路由更新信息"], answer:"B",
  analysis:"OSPF用LSA在区域内泛洪链路状态信息；它是链路状态协议，主干为区域0。" },
{ id:"r2018下-28", source:"real", year:2018, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"Windows下nslookup结果显示：Name: nsl.softwaretest.com，Address: 10.10.20.1，Aliases: ftp.softwaretest.com。则ftp.softwaretest.com的IP地址是（　）。",
  options:["192.168.21.252","192.168.21.1","10.10.20.1","10.10.20.254"], answer:"C",
  analysis:"ftp为别名(CNAME)，其解析到的真实主机地址即10.10.20.1。" },
{ id:"r2018下-29", source:"real", year:2018, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"承上，该别名关系可通过在DNS服务器中新建（　）实现。",
  options:["邮件交换器","别名","域","主机"], answer:"B",
  analysis:"CNAME别名记录用于将一个域名指向另一个主机名。" },
{ id:"r2018下-30", source:"real", year:2018, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在Linux中，（　）命令可将文件按修改时间顺序显示。",
  options:["ls -a","ls -b","ls -c","ls -d"], answer:"C",
  analysis:"ls -c按修改时间排序显示。" },
{ id:"r2018下-31", source:"real", year:2018, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在Linux中，强制复制目录的命令是（　）。",
  options:["cp -f","cp -i","cp -a","cp -l"], answer:"A",
  analysis:"cp -f强制复制(覆盖不提示)。" },
{ id:"r2018下-32", source:"real", year:2018, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"可以利用（　）实现Linux平台和Windows平台之间的数据共享。",
  options:["NetBIOS","NFS","Appletalk","Samba"], answer:"D",
  analysis:"Samba实现Linux与Windows之间通过SMB/CIFS共享文件与打印机。" },
{ id:"r2018下-33", source:"real", year:2018, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"关于Windows操作系统中DHCP服务器的租约，下列说法中错误的是（　）。",
  options:["租约期固定是8天","当租约期过去50%时，客户机将与服务器联系更新租约","当租约期过去87.5%时，客户机与服务器联系失败，重新启动IP租用过程","客户机可采用ipconfig/renew重新申请地址"], answer:"A",
  analysis:"DHCP租约可由服务器自定义，默认8天并非固定不变。" },
{ id:"r2018下-34", source:"real", year:2018, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在配置IIS时，IIS的发布目录（　）。",
  options:["只能够配置在c:\\inetpub\\wwwroot上","只能够配置在本地磁盘C上","只能够配置在本地磁盘D上","既能够配置在本地磁盘上，也能配置在联网的其它计算机上"], answer:"D",
  analysis:"IIS主目录可指向本地任意磁盘路径或网络共享(联网的其他计算机)。" },
{ id:"r2018下-35", source:"real", year:2018, sem:"下", paper:"上午", point:"应用层协议", diff:3,
  stem:"主机A主域名服务器202.112.115.3，辅助202.112.115.5，www.aaaa.com授权域名服务器102.117.112.254。若主机A访问时由102.117.112.254返回解析结果，则（　）。",
  options:["若202.112.115.3工作正常，其必定采用了迭代算法","若202.112.115.3工作正常，其必定采用了递归算法","102.117.112.254必定采用了迭代算法","102.117.112.254必定采用了递归算法"], answer:"A",
  analysis:"本地域名服务器若采用迭代(逐级查询)，才会最终由授权服务器直接返回结果。" },
{ id:"r2018下-36", source:"real", year:2018, sem:"下", paper:"上午", point:"应用层协议", diff:3,
  stem:"关于DHCPOffer报文的说法中，（　）是错误的。",
  options:["接收到该报文后，客户端即采用报文中所提供的地址","报文源MAC地址是DHCP服务器的MAC地址","报文目的IP地址是255.255.255.255","报文默认目标端口是68"], answer:"A",
  analysis:"客户端收到Offer后并不立即采用，还需发送Request请求并收到ACK后才使用该地址。" },
{ id:"r2018下-37", source:"real", year:2018, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"在DNS服务器中的（　）资源记录定义了区域的邮件服务器及其优先级。",
  options:["SOA","NS","PTR","MX"], answer:"D",
  analysis:"MX(邮件交换)记录指定邮件服务器及其优先级。" },
{ id:"r2018下-38", source:"real", year:2018, sem:"下", paper:"上午", point:"广域网与接入", diff:3,
  stem:"用于配置DDR(Dial-on-Demand Routing)链路重新建立连接等待时间的命令是（　）。",
  options:["dialer timer idle","dialer timer compete","dialer timer enable","dialer timer wait-carrier"], answer:"D",
  analysis:"dialer timer wait-carrier配置DDR重新建立连接(等待载波)的时间。" },
{ id:"r2018下-39", source:"real", year:2018, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"使用（　）命令释放当前主机自动获取的IP地址。",
  options:["ipconfig /all","ipconfig /reload","ipconfig /release","ipconfig /reset"], answer:"C",
  analysis:"ipconfig /release释放DHCP获取的IP地址。" },
{ id:"r2018下-40", source:"real", year:2018, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"通过代理服务器(Proxy Server)访问Internet的主要功能不包括（　）。",
  options:["突破对某些网站的访问限制","提高访问某些网站的速度","避免来自Internet上病毒的入侵","隐藏本地主机的IP地址"], answer:"C",
  analysis:"代理服务器可共享地址、缓存加速、隐藏内部IP，但不能防病毒入侵。" },
{ id:"r2018下-41", source:"real", year:2018, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"以下关于三重DES加密的叙述中，正确的是（　）。",
  options:["三重DES加密使用一个密钥进行三次加密","三重DES加密使用两个密钥进行三次加密","三重DES加密使用三个密钥进行三次加密","三重DES加密的密钥长度是DES密钥长度的3倍"], answer:"B",
  analysis:"3DES常用两个密钥(K1、K2)做E-D-E三次运算，有效密钥长度112位。" },
{ id:"r2018下-42", source:"real", year:2018, sem:"下", paper:"上午", point:"无线网络", diff:3,
  stem:"IEEE802.11i标准制定的无线网络加密协议（　）是一个基于AES算法的加密方案。",
  options:["RC4","CCMP","WEP","WPA"], answer:"B",
  analysis:"802.11i采用CCMP，基于AES算法。" },
{ id:"r2018下-43", source:"real", year:2018, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"承上，该加密方案基于（　）算法。",
  options:["RSA","DES","TKIP","AES"], answer:"D",
  analysis:"CCMP基于AES(计数器模式CBC-MAC)。" },
{ id:"r2018下-44", source:"real", year:2018, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"MD5是（　）算法。",
  options:["路由选择","摘要","共享密钥","公开密钥"], answer:"B",
  analysis:"MD5是报文摘要(哈希)算法。" },
{ id:"r2018下-45", source:"real", year:2018, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"承上，对任意长度的输入计算得到的结果长度为（　）位。",
  options:["56","128","140","160"], answer:"B",
  analysis:"MD5输出固定128位摘要。" },
{ id:"r2018下-46", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"在SNMP协议中，管理站要设置被管对象属性信息，需要采用（　）命令进行操作。",
  options:["get","getnext","set","trap"], answer:"C",
  analysis:"SetRequest用于管理站设置被管对象属性。" },
{ id:"r2018下-47", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，被管对象有差错报告，需要采用（　）命令进行操作。",
  options:["get","getnext","set","trap"], answer:"D",
  analysis:"代理用Trap向管理站主动报告异常/差错事件。" },
{ id:"r2018下-48", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"SNMP协议实体发送请求和应答报文的默认端口号是（　）。",
  options:["160","161","162","163"], answer:"B",
  analysis:"SNMP请求/应答用UDP 161。" },
{ id:"r2018下-49", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"在Windows中运行route print后，路由表中接口(Interface)列为102.217.115.132的本机记录，该主机的IP地址为（　）。",
  options:["102.217.115.132","102.217.115.254","127.0.0.1","224.0.0.1"], answer:"A",
  analysis:"本机IP地址即路由表中自身接口地址102.217.115.132。" },
{ id:"r2018下-50", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，该主机所在网络(102.217.115.128)的子网掩码为（　）。",
  options:["255.0.0.0","255.255.255.0","255.255.255.128","255.255.255.255"], answer:"C",
  analysis:"路由表中网络102.217.115.128对应掩码255.255.255.128。" },
{ id:"r2018下-51", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，该主机的默认网关为（　）。",
  options:["102.217.115.132","102.217.115.254","127.0.0.1","224.0.0.1"], answer:"B",
  analysis:"缺省路由0.0.0.0的下一跳即默认网关102.217.115.254。" },
{ id:"r2018下-52", source:"real", year:2018, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"下列关于私有地址个数和地址的描述中，都正确的是（　）。",
  options:["A类有10个：10.0.0.0~10.10.0.0","B类有16个：172.0.0.0~172.15.0.0","B类有16个：169.0.0.0~169.15.0.0","C类有256个：192.168.0.0~192.168.255.0"], answer:"D",
  analysis:"C类私有地址为192.168.0.0/16，即192.168.0.0~192.168.255.0共256个C类。" },
{ id:"r2018下-53", source:"real", year:2018, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"以下IP地址中，既能作为目标地址又能作为源地址，且以该地址为目的地址的报文在Internet上通过路由器进行转发的是（　）。",
  options:["0.0.0.0","127.0.0.1","100.10.255.255/16","202.117.112.5/24"], answer:"D",
  analysis:"202.117.112.5为合法公网单播地址，可作源/目的且可在Internet转发；其余为本机/回环/保留地址。" },
{ id:"r2018下-54", source:"real", year:2018, sem:"下", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"网络192.21.136.0/24和192.21.143.0/24汇聚后的地址是（　）。",
  options:["192.21.136.0/21","192.21.136.0/20","192.21.136.0/22","192.21.128.0/21"], answer:"A",
  analysis:"136~143共8个C类块，第三字节块大小8，聚合为/21，即192.21.136.0/21。" },
{ id:"r2018下-55", source:"real", year:2018, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"把IP网络划分成子网的好处是（　）。",
  options:["减小冲突域的大小","减小广播域的大小","增加可用主机的数量","减轻路由器的负担"], answer:"B",
  analysis:"划分子网可隔离广播域，减小广播域范围(二层仍需VLAN隔离冲突域)。" },
{ id:"r2018下-56", source:"real", year:2018, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"某主机接口的IP地址为192.168.7.131/26，则该IP地址所在网络的广播地址是（　）。",
  options:["192.168.7.255","192.168.7.129","192.168.7.191","192.168.7.252"], answer:"C",
  analysis:"/26块大小64，131落在128~191段，网络192.168.7.128，广播192.168.7.191。" },
{ id:"r2018下-57", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"IPv6链路本地单播地址的前缀为（　）。",
  options:["001","1111 1110 10","1111 1110 11","1111 1111"], answer:"B",
  analysis:"IPv6链路本地地址前缀为FE80::/10，即1111 1110 10。" },
{ id:"r2018下-58", source:"real", year:2018, sem:"下", paper:"上午", point:"网络规划与布线", diff:1,
  stem:"路由器的（　）接口通过光纤连接广域网。",
  options:["SFP端口","同步串行口","Console接口","AUX端口"], answer:"A",
  analysis:"SFP(光模块)端口通过光纤连接广域网链路。" },
{ id:"r2018下-59", source:"real", year:2018, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"CSMA/CD协议是（　）协议。",
  options:["物理层","介质访问子层","逻辑链路子层","网络层"], answer:"B",
  analysis:"CSMA/CD工作在数据链路层的介质访问控制(MAC)子层。" },
{ id:"r2018下-60", source:"real", year:2018, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"以太网的最大帧长为1518字节，每个数据帧前面有8个字节的前导字段，帧间隔为9.6μs，快速以太网100BASE-T发送两帧之间的最大间隔时间约为（　）μs。",
  options:["12.1","13.2","121","132"], answer:"D",
  analysis:"发送一帧=(1518+8)×8/100Mb/s≈122μs，加帧间隔9.6μs约132μs。" },
{ id:"r2018下-61", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"下列命令中，不能用于诊断DNS故障的是（　）。",
  options:["netstat","nslookup","ping","tracert"], answer:"A",
  analysis:"netstat查看连接/端口，不涉及DNS解析；nslookup、ping、tracert均可诊断DNS。" },
{ id:"r2018下-62", source:"real", year:2018, sem:"下", paper:"上午", point:"存储与新技术", diff:1,
  stem:"在冗余磁盘阵列中，以下不具有容错技术的是（　）。",
  options:["RAID0","RAID1","RAID5","RAID10"], answer:"A",
  analysis:"RAID0仅条带化无校验无镜像，不提供容错，任一盘故障数据全失。" },
{ id:"r2018下-63", source:"real", year:2018, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"下面的描述中属于工作区子系统区域范围的是（　）。",
  options:["实现楼层设备间之间的连接","接线间配线架到工作区信息插座","终端设备到信息插座的整个区域","接线间内各种交连设备之间的连接"], answer:"C",
  analysis:"工作区子系统指从终端设备到信息插座的整个区域。" },
{ id:"r2018下-64", source:"real", year:2018, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以下关于三层交换机的叙述中，正确的是（　）。",
  options:["三层交换机包括二层交换和三层转发，二层交换由硬件实现，三层转发采用软件实现","三层交换机仅实现三层转发功能","通常路由器用在单位内部，三层交换机放置在出口","三层交换机除了存储转发外，还可以采用直通交换技术"], answer:"D",
  analysis:"三层交换机既支持存储转发也支持直通(cut-through)交换以降低延迟。" },
{ id:"r2018下-65", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"IP数据报首部中IHL(Internet首部长度)字段的最小值为（　）。",
  options:["5","20","32","128"], answer:"A",
  analysis:"IHL以4字节为单位，最小首部20字节即IHL=5。" },
{ id:"r2018下-66", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"查看OSPF接口的开销、状态、类型、优先级等的命令是（　）。",
  options:["display ospf","display ospf error","display ospf interface","display ospf neighbor"], answer:"C",
  analysis:"display ospf interface查看OSPF接口细节。" },
{ id:"r2018下-67", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，查看OSPF在接收报文时出错记录的命令是（　）。",
  options:["display ospf","display ospf error","display ospf interface","display ospf neighbor"], answer:"B",
  analysis:"display ospf error查看OSPF报文接收出错统计。" },
{ id:"r2018下-68", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:4,
  stem:"Switch A与Switch B跨网段通过BFD(Bidirectional Forwarding Detection)会话绑定静态路由，配置中创建bfd会话并 ip route-static ... track bfd-session。该配置实现的是（　）。",
  options:["实现毫秒级链路故障感知并刷新路由表","能够感知链路故障并进行链路切换","将感知到的链路故障通知NMS","自动关闭故障链路接口并刷新路由表"], answer:"A",
  analysis:"BFD毫秒级检测链路故障，联动静态路由快速刷新/撤销，实现快速故障感知。" },
{ id:"r2018下-69", source:"real", year:2018, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，验证该BFD配置结果的命令是（　）。",
  options:["display nqa results","display bfd session all","display efm session all","display current-configuration | include nqa"], answer:"B",
  analysis:"display bfd session all查看BFD会话状态。" },
{ id:"r2018下-70", source:"real", year:2018, sem:"下", paper:"上午", point:"网络安全", diff:4,
  stem:"Switch上用基本ACL限制FTP访问：rule 5允许172.16.105.0段、rule 10允许172.16.107.0段(限时段ftp-access)、rule 15拒绝其他。由配置可判断：①PC1(172.16.105.111)任何时间可访问FTP；②PC2(172.16.107.111)在2018年周一不能访问；③PC2在2018年周六下午3点可访问；④PC3(10.10.10.1)任何时间不能访问。",
  options:["①②③④","①②④","②③","①③④"], answer:"A",
  analysis:"PC1规则无时间限制故任意时间可访问；PC2仅在时间段(周六14:00-18:00等off-day)内放行，周一不在时段被拒；PC3不在放行范围被deny拒绝。①②③④均成立。" },
{ id:"r2018下-71", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"The TTL field... The datagram was (　) when the value became zero.（选最贴切的词）",
  options:["received","discarded","rejected","transferred"], answer:"B",
  analysis:"TTL减到0时数据报被丢弃(discarded)。" },
{ id:"r2018下-72", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"Today, this field is used mostly to control the (　) number of hops (routers) visited by the datagram.（选最贴切的词）",
  options:["maximum","minimum","exact","certain"], answer:"A",
  analysis:"现用TTL控制报文经过的最大(maximum)跳数。" },
{ id:"r2018下-73", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"When a source host sends the datagram, it (　) a number in this field.（选最贴切的词）",
  options:["controls","transmits","stores","receives"], answer:"C",
  analysis:"源主机在该字段存入(stores)一个初始数值。" },
{ id:"r2018下-74", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"A datagram may travel between two or more routers for a long time without ever getting delivered to the (　).（选最贴切的词）",
  options:["switch","router","source host","destination host"], answer:"D",
  analysis:"报文可能在环路中徘徊而永远到达不了目的主机(destination host)。" },
{ id:"r2018下-75", source:"real", year:2018, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"This field limits the (　) of a datagram.（选最贴切的词）",
  options:["lifetime","moving time","receiving time","transmitting time"], answer:"A",
  analysis:"TTL限制了数据报的生存时间(lifetime)。" }
]);
