/* 真题库 · 2014 下半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2014下-01", source:"real", year:2014, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"属于CPU中算术逻辑单元(ALU)的部件是（　）。",
  options:["程序计数器","加法器","指令寄存器","指令译码器"], answer:"B",
  analysis:"ALU由加法器等运算部件组成；PC、IR、译码器属于控制部件。" },
{ id:"r2014下-02", source:"real", year:2014, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"内存按字节编址从A5000H到DCFFFH的区域，其存储容量为（　）。",
  options:["123KB","180KB","223KB","224KB"], answer:"D",
  analysis:"DCFFF-A5000+1=38000H=229376B=224KB。" },
{ id:"r2014下-03", source:"real", year:2014, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"计算机采用分级存储体系的主要目的是为了解决（　）的问题。",
  options:["主存容量不足","存储器读写可靠性","外设访问效率","存储容量、成本和速度之间的矛盾"], answer:"D",
  analysis:"Cache-主存-辅存分级，兼顾速度、容量与成本。" },
{ id:"r2014下-04", source:"real", year:2014, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"Flynn分类法基于信息流特征将计算机分成4类，其中（　）只有理论意义而无实例。",
  options:["SISD","MISD","SIMD","MIMD"], answer:"B",
  analysis:"MISD(多指令流单数据流)无实际商用实例。" },
{ id:"r2014下-05", source:"real", year:2014, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"以下关于结构化开发方法的叙述中，不正确的是（　）。",
  options:["总的指导思想是自顶向下、逐层分解","基本原则是功能的分解与抽象","与面向对象相比更适合大规模、特别复杂的项目","特别适合于数据处理领域的项目"], answer:"C",
  analysis:"结构化方法适合规模适中、需求明确的项目，超大规模复杂项目并非其优势。" },
{ id:"r2014下-06", source:"real", year:2014, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:3,
  stem:"模块A、B、C都包含相同的5个语句，这些语句之间没有联系。为避免重复抽出组成模块D，则模块D的内聚类型为（　）内聚。",
  options:["功能","通信","逻辑","巧合"], answer:"D",
  analysis:"抽出的语句间无任何联系，属偶然(巧合)内聚，是最弱的内聚。" },
{ id:"r2014下-07", source:"real", year:2014, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"软件项目活动图中，起点A：A-B=3,B-D=5,D-I=2,B-I=6,A-E=4,E-G=3,G-J=2,J-L=8,A-C=5,C-F=3,F-H=1,G-H=3,H-K=4,J-K=2,K-L=3。则里程碑（　）在关键路径上。",
  options:["B","E","C","K"], answer:"A",
  analysis:"关键路径A-B-D-I-J-L=3+5+2+2+8=20，B在其上。" },
{ id:"r2014下-08", source:"real", year:2014, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"承上活动图，活动GH(G→H，历时3)的松弛时间是（　）。",
  options:["0","1","2","3"], answer:"D",
  analysis:"G最早开始7，H最晚开始13(由K倒推)，GH松弛=13-3-7=3。" },
{ id:"r2014下-09", source:"real", year:2014, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:3,
  stem:"将高级语言源程序翻译成机器语言时常引入中间代码。以下关于中间代码的叙述中，不正确的是（　）。",
  options:["中间代码不依赖于具体机器","使用中间代码可提高编译程序的可移植性","中间代码可以用树或图表示","中间代码可以用栈和队列表示"], answer:"D",
  analysis:"中间代码常用三地址码、树、DAG表示，不用栈和队列。" },
{ id:"r2014下-10", source:"real", year:2014, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"甲公司接受乙公司委托开发一项应用软件，双方未订立任何书面合同。此情形下（　）享有该软件的著作权。",
  options:["甲公司","甲、乙公司共同","乙公司","甲、乙公司均不"], answer:"A",
  analysis:"委托开发无书面合同时，著作权归受托方(实际开发者甲公司)。" },
{ id:"r2014下-11", source:"real", year:2014, sem:"下", paper:"上午", point:"操作系统", diff:3,
  stem:"思科路由器内存体系中，用来存放IOS引导(boot)程序的是（　）。",
  options:["FLASH","ROM","NVRAM","DRAM"], answer:"B",
  analysis:"引导程序(bootstrap)固化在ROM；IOS在FLASH，启动配置在NVRAM。" },
{ id:"r2014下-12", source:"real", year:2014, sem:"下", paper:"上午", point:"操作系统", diff:3,
  stem:"承上，路由器运行时活动配置文件存放在（　）中。",
  options:["FLASH","ROM","NVRAM","DRAM"], answer:"D",
  analysis:"运行配置(running-config)存于DRAM(RAM)，断电丢失。" },
{ id:"r2014下-13", source:"real", year:2014, sem:"下", paper:"上午", point:"广域网与接入", diff:3,
  stem:"下面的广域网络中属于电路交换网络的是（　）。",
  options:["ADSL","X.25","FRN(帧中继)","ATM"], answer:"A",
  analysis:"X.25、帧中继为分组交换，ATM为信元交换；ADSL经电话线电路接入。" },
{ id:"r2014下-14", source:"real", year:2014, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"PCM把模拟信号数字化，通常模拟话音信道带宽4000Hz，则数字化采样频率至少为（　）次/秒。",
  options:["2000","4000","8000","16000"], answer:"C",
  analysis:"奈奎斯特准则：采样频率≥2倍带宽=8000Hz。" },
{ id:"r2014下-15", source:"real", year:2014, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"设信道带宽4000Hz，信噪比30dB，按香农定理，信道容量为（　）。",
  options:["4Kb/s","1.6Kb/s","40Kb/s","120Kb/s"], answer:"C",
  analysis:"30dB→S/N=1000；C=4000·log2(1001)≈4000×9.97≈40Kb/s。" },
{ id:"r2014下-16", source:"real", year:2014, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"所谓正交幅度调制(QAM)，是把两个（　）的模拟信号合成为一个载波信号。",
  options:["幅度相同、相位相差90度","幅度相同、相位相差180度","频率相同、相位相差90度","频率相同、相位相差180度"], answer:"A",
  analysis:"QAM用两个相位相差90°(正交)的载波分别携带I/Q分量叠加而成。" },
{ id:"r2014下-17", source:"real", year:2014, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"ISDN基本速率接口(BRI)供小型企业和家庭使用，可提供的最大数据速率为（　）。",
  options:["128Kb/s","144Kb/s","1024Kb/s","2048Kb/s"], answer:"B",
  analysis:"BRI=2B+D(64+64+16)=144Kb/s。" },
{ id:"r2014下-18", source:"real", year:2014, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"ISDN主速率接口(PRI)供大型企业使用，可提供的最大数据速率为（　）。",
  options:["128Kb/s","144Kb/s","1024Kb/s","2048Kb/s"], answer:"D",
  analysis:"PRI(E1)=30B+D=2048Kb/s。" },
{ id:"r2014下-19", source:"real", year:2014, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"PPP是连接广域网的封装协议，下面关于PPP的描述中错误的是（　）。",
  options:["能够控制数据链路的建立","能够分配和管理广域网的IP地址","只能采用IP作为网络层协议","能够有效地进行错误检测"], answer:"C",
  analysis:"PPP支持多网络层协议(IP、IPX等)，并非只能用IP。" },
{ id:"r2014下-20", source:"real", year:2014, sem:"下", paper:"上午", point:"广域网与接入", diff:3,
  stem:"下面关于帧中继的描述中错误的是（　）。",
  options:["在第三层建立虚电路","提供面向连接的服务","是一种高效率的数据链路技术","充分利用了光纤通信和数字网络技术优势"], answer:"A",
  analysis:"帧中继工作在数据链路层(第二层)，并非网络层(第三层)。" },
{ id:"r2014下-21", source:"real", year:2014, sem:"下", paper:"上午", point:"广域网与接入", diff:3,
  stem:"思科路由器支持的帧中继本地管理接口类型(Lmi-type)不包括（　）。",
  options:["Cisco","DCE","ANSI","Q933A"], answer:"B",
  analysis:"LMI类型有Cisco、ANSI、Q933a，不含DCE。" },
{ id:"r2014下-22", source:"real", year:2014, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"边界网关协议BGP4被称为路径矢量协议，它传送的路由信息是由一个地址前缀后跟（　）组成。",
  options:["一串IP地址","一串自治系统编号","一串路由器编号","一串子网地址"], answer:"B",
  analysis:"BGP的AS-Path属性记录途经的自治系统编号序列。" },
{ id:"r2014下-23", source:"real", year:2014, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"承上，BGP这种协议的优点是（　）。",
  options:["防止域间路由循环","可以及时更新路由","便于发现最短通路","考虑了多种路由度量因素"], answer:"A",
  analysis:"AS-Path携带途经AS序列，收到含自身AS的路由即丢弃，防环。" },
{ id:"r2014下-24", source:"real", year:2014, sem:"下", paper:"上午", point:"网络层与路由", diff:4,
  stem:"与RIPv2相比，IGRP增加了一些新特性，下面描述中错误的是（　）。",
  options:["路由度量不再把跳数作为唯一因素，还包含带宽、延迟等参数","增加触发更新加快收敛，不必等更新周期结束","既支持等代价负载均衡，也支持不等代价负载均衡","最大跳数由15跳扩大到255跳，可支持更大网络"], answer:"B",
  analysis:"触发更新并非IGRP相对RIPv2新增特性(RIP已有)，故该项描述错误。" },
{ id:"r2014下-25", source:"real", year:2014, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"为解决RIP路由环路可采用多种方法，下面效果最好的是（　）。",
  options:["不要把从一个邻居学到的路由再发给那个邻居","经常检查邻居路由器状态及时发现断链","把从邻居学到的路由置为无限大再发回给该邻居","缩短更新周期以便链路失效后尽快达到无限大"], answer:"C",
  analysis:"路由毒化(毒化逆转)将坏路由置为16跳不可达再发回，防环效果最好。" },
{ id:"r2014下-26", source:"real", year:2014, sem:"下", paper:"上午", point:"广域网与接入", diff:3,
  stem:"城域以太网中，IEEE802.1ah定义的运营商主干网桥协议，基本技术是在用户以太帧中再封装一层（　）。",
  options:["运营商的MAC帧头","运营商的VLAN标记","用户VLAN标记","用户帧类型标记"], answer:"A",
  analysis:"802.1ah(运营商网桥)在用户帧外再封装一层运营商MAC帧头。" },
{ id:"r2014下-27", source:"real", year:2014, sem:"下", paper:"上午", point:"广域网与接入", diff:3,
  stem:"承上，这种技术被称为（　）技术。",
  options:["Q-in-Q","IP-in-IP","NAT-in-NAT","MAC-in-MAC"], answer:"D",
  analysis:"802.1ah双层MAC封装称为MAC-in-MAC(运营商骨干网桥)。" },
{ id:"r2014下-28", source:"real", year:2014, sem:"下", paper:"上午", point:"传输层", diff:3,
  stem:"抓包工具截获的结果如图，图中第1行记录显示的是（　）。",
  options:["TCP错误连接响应报文","TCP连接建立请求报文","TCP连接建立响应报文","Urgent紧急报文"], answer:"A",
  analysis:"第1行是携带RST标志的TCP错误连接响应(复位)报文。" },
{ id:"r2014下-29", source:"real", year:2014, sem:"下", paper:"上午", point:"传输层", diff:2,
  stem:"承上抓包结果，该报文由（　）发出。",
  options:["Web客户端","Web服务器","DNS服务器","DNS客户端"], answer:"B",
  analysis:"该复位报文由Web服务器端发出。" },
{ id:"r2014下-30", source:"real", year:2014, sem:"下", paper:"上午", point:"操作系统", diff:3,
  stem:"管理员为Linux的/etc/hosts添加记录：192.168.1.100 linumu100.com web80；192.168.1.120 emailserver。下列说法正确的是（　）。",
  options:["linumu100.com是主机192.168.1.100的主机名","web80是主机192.168.1.100的主机名","emailserver是主机192.168.1.120的别名","192.168.1.120行记录的格式是错误的"], answer:"A",
  analysis:"hosts中IP后第一个名字为规范主机名，其余为别名；故linumu100.com是.100主机名。" },
{ id:"r2014下-31", source:"real", year:2014, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"下列关于Linux文件组织方式的说法中，（　）是错误的。",
  options:["Linux文件系统使用索引节点记录文件信息","文件索引节点号由管理员手工分配","每个文件与唯一的索引节点号对应","一个索引节点号可对应多个文件(硬链接)"], answer:"B",
  analysis:"inode号由文件系统自动分配，不能手工指定。" },
{ id:"r2014下-32", source:"real", year:2014, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"netstat -r 命令的功能是（　）。",
  options:["显示路由记录","查看连通性","追踪DNS服务器","捕获网络配置信息"], answer:"A",
  analysis:"-r显示路由表(route)；查看连通性用ping。" },
{ id:"r2014下-33", source:"real", year:2014, sem:"下", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"搭建试验平台、进行网络仿真是网络生命周期中（　）阶段的任务。",
  options:["需求规范","逻辑网络设计","物理网络设计","实施"], answer:"B",
  analysis:"逻辑网络设计阶段用试验网/原型验证设计方案。" },
{ id:"r2014下-34", source:"real", year:2014, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在Windows系统中可通过停止（　）服务来阻止对域名解析Cache的访问。",
  options:["DNS Server","Remote Procedure Call(RPC)","Nslookup","DNS Client"], answer:"D",
  analysis:"DNS Client服务负责本机解析缓存，停止它即停用缓存。" },
{ id:"r2014下-35", source:"real", year:2014, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"公司域名pq.com，POP服务器pop.pq.com、SMTP服务器smtp.pq.com。配置Foxmail时发送邮件服务器栏应填（　）。",
  options:["pop.pq.com","smtp.pq.com","pq.com","pop3.pq.com"], answer:"B",
  analysis:"发送邮件用SMTP服务器smtp.pq.com。" },
{ id:"r2014下-36", source:"real", year:2014, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"承上，Foxmail接收邮件服务器栏应填（　）。",
  options:["pop.pq.com","smtp.pq.com","pq.com","pop3.pq.com"], answer:"A",
  analysis:"接收邮件用POP3服务器pop.pq.com。" },
{ id:"r2014下-37", source:"real", year:2014, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"在Linux操作系统中，采用（　）来搭建DNS服务器。",
  options:["Samba","Tomcat","Bind","Apache"], answer:"C",
  analysis:"BIND是主流DNS服务器软件。" },
{ id:"r2014下-38", source:"real", year:2014, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"DNS服务器的默认端口号是（　）端口。",
  options:["50","51","52","53"], answer:"D",
  analysis:"DNS使用UDP/TCP 53端口。" },
{ id:"r2014下-39", source:"real", year:2014, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"使用（　）命令可以向FTP服务器上传文件。",
  options:["get","dir","put","push"], answer:"C",
  analysis:"put上传，get下载，dir列目录。" },
{ id:"r2014下-40", source:"real", year:2014, sem:"下", paper:"上午", point:"网络安全", diff:4,
  stem:"有CA：I1、I2，A在I1获证、B在I2获证，I1与I2已交换公钥。用I1《A》表示I1颁给A的证书，A可通过（　）证书链获取B的公钥。",
  options:["I1《I2》I2《B》","I2《B》I1《I2》","I1《B》I2《I2》","I2《I1》I2《B》"], answer:"A",
  analysis:"A信任I1，先取I1颁发的I2证书I1《I2》，再取I2颁发的B证书I2《B》。" },
{ id:"r2014下-41", source:"real", year:2014, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"PGP提供数据加密和数字签名服务，采用（　）进行身份认证。",
  options:["RSA公钥证书","RSA私钥证书","Kerberos证书","DES私钥证书"], answer:"A",
  analysis:"PGP用RSA公钥(数字签名)进行身份认证。" },
{ id:"r2014下-42", source:"real", year:2014, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"承上，PGP使用（　）(128位密钥)进行数据加密。",
  options:["IDEA","RSA","DES","Diffie-Hellman"], answer:"A",
  analysis:"PGP用IDEA(128位对称密钥)加密邮件正文。" },
{ id:"r2014下-43", source:"real", year:2014, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"承上，PGP使用（　）进行数据完整性验证。",
  options:["HASH","MD5","三重DES","SHA-1"], answer:"B",
  analysis:"经典PGP采用MD5摘要做数据完整性验证。" },
{ id:"r2014下-44", source:"real", year:2014, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"以下关于S-HTTP的描述中，正确的是（　）。",
  options:["S-HTTP是面向报文的安全通信协议，使用TCP 443端口","S-HTTP所用语法和报文格式与HTTP相同","S-HTTP也可写为HTTPS","S-HTTP的安全基础并非SSL"], answer:"D",
  analysis:"S-HTTP独立于SSL，面向单个报文加密；443端口属于HTTPS(SSL)。" },
{ id:"r2014下-45", source:"real", year:2014, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"把交换机由特权模式转换到全局配置模式使用的命令是（　）。",
  options:["interface f0/1","config terminal","enable","no shutdown"], answer:"B",
  analysis:"configure terminal(conf t)从特权模式进入全局配置模式。" },
{ id:"r2014下-46", source:"real", year:2014, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"在无线局域网中，AP(无线接入点)工作在OSI模型的（　）。",
  options:["物理层","数据链路层","网络层","应用层"], answer:"B",
  analysis:"AP是二层设备，工作在数据链路层。" },
{ id:"r2014下-47", source:"real", year:2014, sem:"下", paper:"上午", point:"网络安全", diff:4,
  stem:"利用扩展ACL禁止用户通过telnet访问子网202.112.111.0/24的命令是（　）。",
  options:["access-list 110 deny telnet any 202.112.111.0 0.0.0.255 eq 23","access-list 110 deny udp any 202.112.111.0 eq telnet","access-list 110 deny tcp any 202.112.111.0 0.0.0.255 eq 23","access-list 10 deny tcp any 202.112.111.0 255.255.255.0 eq 23"], answer:"C",
  analysis:"扩展ACL编号100-199，指定tcp、目的网络+通配符掩码、eq 23。" },
{ id:"r2014下-48", source:"real", year:2014, sem:"下", paper:"上午", point:"操作系统", diff:3,
  stem:"以下关于Windows Server 2003域管理模式的描述中，正确的是（　）。",
  options:["域间信任关系只能是单向信任","单域模型中只有一个主域控制器，其他都为备份","如果域控制器改变目录信息，应把变化复制到其他域控制器","只有一个域控制器可以改变目录信息"], answer:"C",
  analysis:"活动目录多主复制，某DC更改后须同步复制到其他DC。" },
{ id:"r2014下-49", source:"real", year:2014, sem:"下", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"SNMPv2的（　）操作为管理站提供了从被管设备中一次取回一大批数据的能力。",
  options:["GetNextRequest","InformRequest","SetRequest","GetBulkRequest"], answer:"D",
  analysis:"GetBulkRequest是SNMPv2新增的批量取数操作。" },
{ id:"r2014下-50", source:"real", year:2014, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"DNS资源记录中，指明区域主服务器和管理员邮件地址的是（　）记录。",
  options:["SOA","PTR","MX","NS"], answer:"A",
  analysis:"SOA记录标识区域主名字服务器及管理员邮箱等。" },
{ id:"r2014下-51", source:"real", year:2014, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"承上，指明区域邮件服务器地址的是（　）记录。",
  options:["SOA","PTR","MX","NS"], answer:"C",
  analysis:"MX记录指定邮件交换(邮件)服务器。" },
{ id:"r2014下-52", source:"real", year:2014, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"以下地址中属于自动专用IP地址(APIPA)的是（　）。",
  options:["224.0.0.1","127.0.0.1","192.168.0.1","169.254.1.15"], answer:"D",
  analysis:"APIPA为169.254.0.0/16，DHCP失败时自动分配。" },
{ id:"r2014下-53", source:"real", year:2014, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"公司得到一个B类网络地址块，需划分成若干个含1000台主机的子网，则可划分成（　）个子网。",
  options:["100","64","128","500"], answer:"B",
  analysis:"1000台需主机位10位(2^10-2=1022)；B类主机位16，借6位作子网，2^6=64。" },
{ id:"r2014下-54", source:"real", year:2014, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"IP地址202.117.17.254/22是什么地址（　）。",
  options:["网络地址","全局广播地址","主机地址","定向广播地址"], answer:"C",
  analysis:"/22网络号202.117.16.0，范围16.0~19.255，.17.254为可用主机地址。" },
{ id:"r2014下-55", source:"real", year:2014, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"把8个地址块20.15.0.0~20.15.7.0聚合成一个超级地址块，得到的网络地址是（　）。",
  options:["20.15.0.0/20","20.15.0.0/21","20.15.0.0/16","20.15.0.0/24"], answer:"B",
  analysis:"8=2^3，前缀24-3=21，即20.15.0.0/21。" },
{ id:"r2014下-56", source:"real", year:2014, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"每一个访问控制列表(ACL)最后都隐含着一条（　）语句。",
  options:["deny any","deny all","permit any","permit all"], answer:"A",
  analysis:"ACL末尾隐式 deny any any(拒绝所有)。" },
{ id:"r2014下-57", source:"real", year:2014, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"以下关于访问控制列表的论述中，错误的是（　）。",
  options:["访问控制列表要在路由器全局模式下配置","具有严格限制条件的语句应放在ACL的最后","每个有效的ACL至少应包含一条允许语句","ACL不能过滤由路由器自己产生的数据"], answer:"B",
  analysis:"严格(具体)的语句应放在前面，先匹配精确条件。" },
{ id:"r2014下-58", source:"real", year:2014, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"IPv6的可聚合全球单播地址前缀为（　）。",
  options:["010","011","001","100"], answer:"C",
  analysis:"可聚合全球单播地址前缀为2000::/3，即最高3位001。" },
{ id:"r2014下-59", source:"real", year:2014, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"承上，IPv6任意播(anycast)地址的组成是（　）。",
  options:["子网前缀+全0","子网前缀+全1","链路本地地址前缀+全0","链路本地地址前缀+全1"], answer:"A",
  analysis:"任播地址=子网前缀+全0接口标识。" },
{ id:"r2014下-60", source:"real", year:2014, sem:"下", paper:"上午", point:"传输层", diff:2,
  stem:"如果一个TCP连接处于ESTABLISHED状态，这表示（　）。",
  options:["已经发出了连接请求","连接已经建立","处于连接监听状态","等待对方释放连接的响应"], answer:"B",
  analysis:"ESTABLISHED表示三次握手完成、连接已建立。" },
{ id:"r2014下-61", source:"real", year:2014, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"以太网CSMA/CD冲突时用二进制指数后退算法计算后退时延，以下论述中错误的是（　）。",
  options:["冲突次数越多，后退的时间越短","平均后退次数与负载大小有关","后退时延平均值与负载大小有关","重发次数达一定极限后放弃发送"], answer:"A",
  analysis:"冲突次数越多，退避窗口越大，后退时间越长而非越短。" },
{ id:"r2014下-62", source:"real", year:2014, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"在局域网中静态划分VLAN是根据（　）划分。",
  options:["MAC地址","IP地址","端口号","管理区域"], answer:"C",
  analysis:"静态VLAN按交换机端口划分。" },
{ id:"r2014下-63", source:"real", year:2014, sem:"下", paper:"上午", point:"无线网络", diff:3,
  stem:"以下通信技术中，未在IEEE802.11无线局域网中使用的是（　）。",
  options:["FHSS","DSSS","CDMA","IR"], answer:"C",
  analysis:"802.11使用FHSS、DSSS、红外(IR)，不使用CDMA。" },
{ id:"r2014下-64", source:"real", year:2014, sem:"下", paper:"上午", point:"无线网络", diff:3,
  stem:"ZigBee(802.15.4)含全功能设备(FFD)和简化功能设备(RFD)，以下描述错误的是（　）。",
  options:["协调器是全功能设备，只能作为PAN控制器使用","被动式红外传感器是简化功能设备，受协调器控制","协调器也可运行某些应用，发起和接受通信请求","简化功能设备之间不能互相通信，只能与协调器通信"], answer:"A",
  analysis:"协调器(FFD)并非只能作PAN控制器，也可作普通FFD通信。" },
{ id:"r2014下-65", source:"real", year:2014, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"在IPv4和IPv6混合网络中，协议翻译技术(NAT-PT)用于（　）。",
  options:["两个IPv6主机通过IPv4网络通信","两个IPv4主机通过IPv6网络通信","纯IPv4主机和纯IPv6主机之间的通信","两个双协议栈主机之间的通信"], answer:"C",
  analysis:"协议翻译实现纯IPv4与纯IPv6主机互通；隧道用于同协议栈跨网。" },
{ id:"r2014下-66", source:"real", year:2014, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"结构化布线系统中，水平子系统的作用是（　）。",
  options:["连接各个建筑物中的通信系统","连接干线子系统和用户工作区","实现中央主配线架与各种设备之间的连接","实现各楼层设备间子系统之间的互连"], answer:"B",
  analysis:"水平子系统连接楼层配线间与工作区信息插座。" },
{ id:"r2014下-67", source:"real", year:2014, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"承上，园区(建筑群)子系统的作用是（　）。",
  options:["连接各个建筑物中的通信系统","连接干线子系统和用户工作区","实现中央主配线架与各种不同设备之间的连接","实现各楼层设备间子系统之间的互连"], answer:"A",
  analysis:"建筑群(园区)子系统连接不同建筑物之间的通信线缆。" },
{ id:"r2014下-68", source:"real", year:2014, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"网络系统设计过程中，逻辑网络设计阶段的任务是（　）。",
  options:["对现有网络资源进行分析，确定网络逻辑结构","根据需求说明书确定网络的安全系统架构","根据需求规范和通信规范分析各网段通信流量","根据用户需求选择特定网络技术、互连设备和拓扑结构"], answer:"D",
  analysis:"逻辑设计确定技术、设备与拓扑；物理设计才落实具体分布。" },
{ id:"r2014下-69", source:"real", year:2014, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"下列关于网络汇聚层的描述中，正确的是（　）。",
  options:["负责收集用户信息如IP地址、访问日志","实现资源访问控制和流量控制等功能","将分组从一个区域高速转发到另一个区域","提供认证和计费等管理功能"], answer:"B",
  analysis:"汇聚层实施路由聚合、访问策略与流量控制；高速转发是核心层。" },
{ id:"r2014下-70", source:"real", year:2014, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"CDMA for cellular systems: each cell is allocated a frequency (　), split into reverse and forward parts.（选最贴切的词）",
  options:["wave","signal","bandwidth","domain"], answer:"C",
  analysis:"分配一个频率带宽(bandwidth)，分反向/正向两部分。" },
{ id:"r2014下-71", source:"real", year:2014, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"...half for reverse (mobile to base) and half for (　) (base to mobile unit).（选最贴切的词）",
  options:["forward","reverse","backward","ahead"], answer:"A",
  analysis:"正向(forward)信道=基站到移动台，与反向(reverse)对应。" },
{ id:"r2014下-72", source:"real", year:2014, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"For full-duplex (　), a mobile unit uses both reverse and forward channels.（选最贴切的词）",
  options:["connection","transmission","compromise","communication"], answer:"D",
  analysis:"full-duplex communication(全双工通信)同时收发。" },
{ id:"r2014下-73", source:"real", year:2014, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"Transmission is in the form of direct-sequence spread (　), which uses a chipping code...（选最贴切的词）",
  options:["structure","spectrum","stream","strategy"], answer:"B",
  analysis:"direct-sequence spread spectrum(直扩频谱/DSSS)。" },
{ id:"r2014下-74", source:"real", year:2014, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"Multiple access is provided by assigning (　) chipping codes to multiple users...（选最贴切的词）",
  options:["concurrent","orthogonal","higher","lower"], answer:"B",
  analysis:"分配相互正交(orthogonal)的扩频码，使接收端分离各用户信号。" }
]);
