/* 真题库 · 2015 上半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2015上-01", source:"real", year:2015, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"机器字长为n位的二进制数，可以用补码表示（　）个不同的有符号定点小数。",
  options:["2^n","2^(n-1)","2^n-1","2^(n-1)-1"], answer:"A",
  analysis:"n位补码(含符号位)共可表示2^n个不同的有符号数。" },
{ id:"r2015上-02", source:"real", year:2015, sem:"上", paper:"上午", point:"计算机硬件", diff:1,
  stem:"计算机中CPU对其访问速度最快的是（　）。",
  options:["内存","Cache","通用寄存器","硬盘"], answer:"C",
  analysis:"寄存器在CPU内部，速度最快。" },
{ id:"r2015上-03", source:"real", year:2015, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"计算机中CPU的中断响应时间指的是（　）的时间。",
  options:["从发出中断请求到中断处理结束","从中断处理开始到中断处理结束","CPU分析判断中断请求","从发出中断请求到开始进入中断处理程序"], answer:"D",
  analysis:"中断响应时间=从发出中断请求到CPU开始执行中断处理程序之间的时间。" },
{ id:"r2015上-04", source:"real", year:2015, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"总线宽度32bit，时钟频率200MHz，若每5个时钟周期传送一个32bit的字，则该总线的带宽为（　）MB/s。",
  options:["40","80","160","200"], answer:"C",
  analysis:"每字4字节，200M/5=40M字/秒，40M×4=160MB/s。" },
{ id:"r2015上-05", source:"real", year:2015, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"以下关于指令流水线性能度量的叙述中，错误的是（　）。",
  options:["最大吞吐率取决于流水线中最慢一段所需时间","流水线出现断流，加速比会明显下降","要使加速比和效率最大化应对各级采用相同运行时间","流水线采用异步控制会明显提高其性能"], answer:"D",
  analysis:"流水线多用同步(锁存)控制，异步控制不会明显提高性能。" },
{ id:"r2015上-06", source:"real", year:2015, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"对高级语言源程序进行编译或解释可分多个阶段，解释方式不包含（　）阶段。",
  options:["词法分析","语法分析","语义分析","目标代码生成"], answer:"D",
  analysis:"解释程序不生成目标代码，边解释边执行。" },
{ id:"r2015上-07", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"C程序中全局变量的存储空间在（　）分配。",
  options:["代码区","静态数据区","栈区","堆区"], answer:"B",
  analysis:"全局变量与静态变量存于静态数据区(数据段)。" },
{ id:"r2015上-08", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:3,
  stem:"某进程4个页面，分配3个存储块。页0/2/3在内存(访问位均为1，修改位均为0)，页1不在内存。采用第二次机会(CLOCK)页面替换，访问页1时应淘汰的页号为（　）。",
  options:["0","1","2","3"], answer:"D",
  analysis:"按时钟算法扫描，访问位均为1，清位后依次跳过，最终淘汰页3。" },
{ id:"r2015上-09", source:"real", year:2015, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"王某是某公司软件设计师，软件开发完成后按公司规定编写文档并提交存档，该软件文档的著作权（　）享有。",
  options:["应由公司","应由公司和王某共同","应由王某","除署名权外其他权利由王某"], answer:"A",
  analysis:"按公司规定完成的职务文档，著作权归公司。" },
{ id:"r2015上-10", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"当登录交换机时，符号（　）是特权模式提示符。",
  options:["@","#",">","&"], answer:"B",
  analysis:"特权(EXEC)模式提示符为#；用户模式为>。" },
{ id:"r2015上-11", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"下面的选项中，显示系统硬件和软件版本信息的命令是（　）。",
  options:["show configuration","show environment","show version","show platform"], answer:"C",
  analysis:"show version显示IOS版本、硬件等版本信息。" },
{ id:"r2015上-12", source:"real", year:2015, sem:"上", paper:"上午", point:"广域网与接入", diff:2,
  stem:"Cisco路由器高速同步串口默认的封装协议是（　）。",
  options:["PPP","LAPB","HDLC","ATM-DXI"], answer:"C",
  analysis:"Cisco同步串口默认封装HDLC。" },
{ id:"r2015上-13", source:"real", year:2015, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以下关于网桥和交换机区别的叙述中，正确的是（　）。",
  options:["交换机基于软件实现，网桥基于硬件实现","交换机定义广播域，网桥定义冲突域","交换机根据IP地址转发，网桥根据MAC地址转发","交换机比网桥端口多，转发速度更快"], answer:"D",
  analysis:"交换机是多端口高速网桥，端口多、硬件转发更快。" },
{ id:"r2015上-14", source:"real", year:2015, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"正交幅度调制16-QAM的数据速率是码元速率的（　）倍。",
  options:["2","4","8","16"], answer:"B",
  analysis:"16-QAM每个码元携带log2(16)=4比特。" },
{ id:"r2015上-15", source:"real", year:2015, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"电话线路带通滤波器带宽3kHz(300~3300Hz)，按奈奎斯特采样定理，最小采样频率应为（　）。",
  options:["300Hz","3390Hz","6000Hz","6600Hz"], answer:"D",
  analysis:"按最高频率3300Hz计，采样≥2×3300=6600Hz。" },
{ id:"r2015上-16", source:"real", year:2015, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"当一个帧离开路由器接口时，其第二层封装信息中（　）。",
  options:["数据速率由10BASE-TX变为100BASE-TX","源和目标IP地址改变","源和目标MAC地址改变","模拟线路变为数字线路"], answer:"C",
  analysis:"每经过一跳，帧的源/目的MAC都改为出接口MAC和下一跳MAC。" },
{ id:"r2015上-17", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于OSPF区域(Area)的叙述中，正确的是（　）。",
  options:["各个OSPF区域都要连接到主干区域","分层的OSPF网络不需要多个区域","单个OSPF网络只有区域1","区域ID取值范围是1~32768"], answer:"A",
  analysis:"所有非骨干区域必须直连骨干区域(Area 0)。" },
{ id:"r2015上-18", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"运行OSPF的路由器用（　）报文来建立和更新它的拓扑数据库。",
  options:["由其他路由器发送的链路状态公告(LSA)","从点对点链路收到的信标","由指定路由器收到的TTL分组","从邻居路由器收到的路由表"], answer:"A",
  analysis:"OSPF交换LSA构建链路状态(拓扑)数据库。" },
{ id:"r2015上-19", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"链路状态路由协议的主要特点是（　）。",
  options:["邻居之间交换路由表","通过事件触发及时更新路由","周期性更新全部路由表","无法显示整个网络拓扑结构"], answer:"B",
  analysis:"链路状态协议事件触发更新，收敛快；距离矢量才周期性发整张路由表。" },
{ id:"r2015上-20", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"从RIP路由信息“R 10.10.10.7 [120/2] via 10.10.10.8, 00:00:24, Serial 0/1”可得到的结论是（　）。",
  options:["下一个路由更新将在36秒后到达","到达目标10.10.10.7的距离是两跳","串口S0/1的IP地址是10.10.10.8","串口S0/1的IP地址是10.10.10.7"], answer:"B",
  analysis:"[120/2]中管理距离120、度量2跳；via后是下一跳地址而非本接口地址。" },
{ id:"r2015上-21", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"运行距离矢量路由协议的路由器（　）。",
  options:["把路由表发送到整个路由域所有路由器","使用最短通路算法确定最佳路由","根据邻居发来的信息更新自己的路由表","维护整个网络的拓扑数据库"], answer:"C",
  analysis:"距离矢量把自己的路由表发给邻居，据邻居通告更新。" },
{ id:"r2015上-22", source:"real", year:2015, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以下关于VLAN的叙述中，正确的是（　）。",
  options:["VLAN对分组进行过滤，增强了网络安全性","VLAN提供了在大型网络中保护IP地址的方法","VLAN在可路由网络中提供了低延迟的互联手段","VLAN简化了在网络中增加、移除和移动主机的操作"], answer:"A",
  analysis:"VLAN隔离广播、限制通信，提供二层安全过滤。" },
{ id:"r2015上-23", source:"real", year:2015, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"当局域网中更换交换机时，怎样保证新交换机成为网络中的根交换机（　）。",
  options:["降低网桥优先级","改变交换机的MAC地址","降低交换机端口的根路径费用","为交换机指定特定的IP地址"], answer:"A",
  analysis:"网桥ID(优先级+MAC)最小者为根，降低优先级即可成为根桥。" },
{ id:"r2015上-24", source:"real", year:2015, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"双绞线1/3、2/6交叉(一端白绿-橙)的配置支持（　）之间的连接。",
  options:["PC到路由器","PC到交换机","服务器到交换机","交换机到路由器"], answer:"A",
  analysis:"该交叉线用于PC与路由器(同型设备)直连。" },
{ id:"r2015上-25", source:"real", year:2015, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"Server A:131.1.123.24/27、GW:131.1.123.33；Workstation B:131.1.123.43/27、GW:131.1.123.33。工作站B无法与服务器A通信，故障是（　）。",
  options:["服务器A的IP是广播地址","工作站B的IP是网络地址","工作站B与网关不在同一子网","服务器A与网关不在同一子网"], answer:"D",
  analysis:"/27块32-63，A=24在0-31块，与网关33(32-63块)不在同一子网。" },
{ id:"r2015上-26", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"网络中Router2直连网络1(192.168.0.0)及两个202.117.112.0/30、202.117.113.0/30网段，采用RIP，Router2上需声明的网络是（　）。",
  options:["仅网络1","网络1、202.117.112.0/30和202.117.113.0/30","网络1、网络2和网络3","仅两个/30网段"], answer:"B",
  analysis:"RIP network命令需声明本路由器所有直连主类/子网。" },
{ id:"r2015上-27", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"IIS服务身份验证方式中，安全级别最低的是（　）。",
  options:["NET Passport身份验证","集成Windows身份验证","基本身份验证","摘要式身份验证"], answer:"C",
  analysis:"基本身份验证以Base64明文传输，安全性最低。" },
{ id:"r2015上-28", source:"real", year:2015, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"有较高实时性要求的应用是（　）。",
  options:["电子邮件","网页浏览","VoIP","网络管理"], answer:"C",
  analysis:"VoIP话音对时延敏感，实时性要求高。" },
{ id:"r2015上-29", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，文件（　）用于解析主机域名。",
  options:["/etc/hosts","/etc/host.conf","/etc/hostname","/etc/bind"], answer:"A",
  analysis:"/etc/hosts提供静态主机名到IP映射。" },
{ id:"r2015上-30", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，要删除用户组group1应使用（　）命令。",
  options:["delete group1","gdelete group1","groupdel group1","gd group1"], answer:"C",
  analysis:"groupdel group1删除用户组。" },
{ id:"r2015上-31", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"Windows Server 2003用IPSec保密，密钥交换采用主密钥完全向前保密(PFS)，则“身份验证和生成密钥间隔”默认值为480分钟和（　）个会话。",
  options:["1","2","161","530"], answer:"A",
  analysis:"PFS默认在1个会话后生成新主密钥。" },
{ id:"r2015上-32", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"在Windows用户管理中使用组策略A-G-DL-P，其中P表示（　）。",
  options:["用户账号","资源访问权限","域本地组","通用组"], answer:"B",
  analysis:"A用户、G全局组、DL域本地组、P权限(资源权限)。" },
{ id:"r2015上-33", source:"real", year:2015, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"以下叙述中，不属于无源光网络(PON)优势的是（　）。",
  options:["设备简单、安装维护费用低、投资小","组网灵活，支持多种拓扑结构","安装方便，不需另租或建造机房","无源光网络适用于点对点通信"], answer:"D",
  analysis:"PON为点对多点(树型)结构，并非适用于点对点。" },
{ id:"r2015上-34", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"查看DNS缓存记录的命令是（　）。",
  options:["ipconfig /flushdns","nslookup","ipconfig /release","ipconfig /displaydns"], answer:"D",
  analysis:"ipconfig /displaydns显示本机DNS解析缓存。" },
{ id:"r2015上-35", source:"real", year:2015, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Windows操作系统中，（　）文件可以帮助域名解析。",
  options:["cookie","index","Hosts","default"], answer:"C",
  analysis:"%SystemRoot%\system32\drivers\etc\hosts提供本地域名解析。" },
{ id:"r2015上-36", source:"real", year:2015, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"DHCP（　）报文的目的IP地址为255.255.255.255。",
  options:["DhcpDiscover","DhcpOffer","DhcpNack","DhcpAck"], answer:"A",
  analysis:"客户端无IP时以广播255.255.255.255发送Discover。" },
{ id:"r2015上-37", source:"real", year:2015, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"客户端采用（　）报文来拒绝DHCP服务器提供的IP地址。",
  options:["DhcpOffer","DhcpDecline","DhcpAck","DhcpNack"], answer:"B",
  analysis:"客户端发现地址冲突时发DHCPDECLINE拒绝。" },
{ id:"r2015上-38", source:"real", year:2015, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"若一直得不到回应，DHCP客户端总共会广播（　）次请求。",
  options:["3","4","5","6"], answer:"B",
  analysis:"DHCPDISCOVER重试共4次(1,2,4,8秒)。" },
{ id:"r2015上-39", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"提供电子邮件安全服务的协议是（　）。",
  options:["PGP","SET","S-HTTP","Kerberos"], answer:"A",
  analysis:"PGP为电子邮件提供加密与签名。" },
{ id:"r2015上-40", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:1,
  stem:"IDS设备的主要作用是（　）。",
  options:["用户认证","报文认证","入侵检测","数据加密"], answer:"C",
  analysis:"入侵检测系统监测并报告入侵行为。" },
{ id:"r2015上-41", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"宏病毒可以感染后缀为（　）的文件。",
  options:["exe","txt","pdf","xls"], answer:"D",
  analysis:"宏病毒感染Office文档(如.xls/.doc)。" },
{ id:"r2015上-42", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"Kerberos是一种（　）。",
  options:["加密算法","签名算法","认证服务","病毒"], answer:"C",
  analysis:"Kerberos是基于票据的网络身份认证服务。" },
{ id:"r2015上-43", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"以下关于三重DES(3DES)加密的叙述中，正确的是（　）。",
  options:["使用一个密钥进行三次加密","使用两个密钥进行三次加密","使用三个密钥进行三次加密","密钥长度是DES的3倍"], answer:"B",
  analysis:"常用3DES两密钥版本(K1-K2-K1)，对数据加密-解密-加密。" },
{ id:"r2015上-44", source:"real", year:2015, sem:"上", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"SNMP协议属于（　）层协议。",
  options:["物理","网络","传输","应用"], answer:"D",
  analysis:"SNMP是应用层协议，基于UDP。" },
{ id:"r2015上-45", source:"real", year:2015, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"SNMPv3新增了（　）功能。",
  options:["管理站之间通信","代理","认证和加密","数据块检索"], answer:"C",
  analysis:"SNMPv3主要增强安全性：认证与加密。" },
{ id:"r2015上-46", source:"real", year:2015, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"网络管理系统中故障管理的目标是（　）。",
  options:["自动排除故障","优化网络性能","提升网络安全","自动监测故障"], answer:"D",
  analysis:"故障管理负责检测、定位和告警故障。" },
{ id:"r2015上-47", source:"real", year:2015, sem:"上", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"主机无法访问www.sohu.com，tracert显示第1跳59.67.148.1可达，第2跳返回“Destination net unreachable”。原因可能是（　）。",
  options:["该计算机IP地址设置有误","相关路由器上进行了访问控制","本地网关不可达","本地DNS服务器工作不正常"], answer:"B",
  analysis:"能解析到IP且首跳可达，后续路由器返回网络不可达，疑似中间路由器ACL拒绝。" },
{ id:"r2015上-48", source:"real", year:2015, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"使用 netstat -o 命令可显示网络（　）。",
  options:["IP、ICMP、TCP、UDP协议统计信息","以太网统计信息","以数字格式显示所有连接、地址及端口","每个连接的进程ID"], answer:"D",
  analysis:"-o显示每个连接关联的进程ID(PID)。" },
{ id:"r2015上-49", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"IEEE 802.1x是一种基于（　）的认证协议。",
  options:["用户ID","报文","MAC地址","SSID"], answer:"A",
  analysis:"802.1x基于端口、对用户身份(ID/账户)进行认证。" },
{ id:"r2015上-50", source:"real", year:2015, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"为弥补WEP协议安全缺陷，WPA安全认证方案增加的机制是（　）。",
  options:["共享密钥认证","临时密钥完整性协议(TKIP)","较短的初始化向量","采用更强的加密算法"], answer:"B",
  analysis:"WPA用TKIP动态变化密钥，弥补WEP静态密钥缺陷。" },
{ id:"r2015上-51", source:"real", year:2015, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"DHCP分配的默认网关是192.168.5.33/28，（　）是本地主机的有效地址。",
  options:["192.168.5.32","192.168.5.55","192.168.5.47","192.168.5.40"], answer:"D",
  analysis:"/28块32-47，可用主机33-46，只有.40可用(.32网络、.47广播、.55别块)。" },
{ id:"r2015上-52", source:"real", year:2015, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"如果指定地址掩码是255.255.254.0，则有效的主机地址是（　）。",
  options:["126.17.3.0","174.15.3.255","20.15.36.0","115.12.4.0"], answer:"A",
  analysis:"/23中第三字节偶数段为首尾边界；.3.0为奇数段中的可用主机地址，余者均为网络/广播地址。" },
{ id:"r2015上-53", source:"real", year:2015, sem:"上", paper:"上午", point:"IP地址与子网", diff:1,
  stem:"要检查本机的IP协议是否工作正常，应ping的地址是（　）。",
  options:["192.168.0.1","10.1.1.1","127.0.0.1","128.0.1.1"], answer:"C",
  analysis:"ping环回地址127.0.0.1验证本机TCP/IP协议栈。" },
{ id:"r2015上-54", source:"real", year:2015, sem:"上", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"工作站A:202.117.17.24/28，工作站B:202.117.17.100/28，直连不能通信，怎样修改才能互通（　）。",
  options:["把A改为202.117.17.15","把B改为202.117.17.112","把子网掩码改为25","把子网掩码改为26"], answer:"C",
  analysis:"改掩码为/25(25)后.24与.100同处0-127块，可直连同子网。" },
{ id:"r2015上-55", source:"real", year:2015, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"路由器接口地址200.15.10.6/29，默认网关200.15.10.7，配置后路由器ping不通远程设备，原因是（　）。",
  options:["默认网关地址不属于该子网","默认网关地址是子网广播地址","路由器接口地址是子网广播地址","路由器接口地址是组播地址"], answer:"B",
  analysis:"/29块0-7，广播地址为.7，网关不能设为广播地址。" },
{ id:"r2015上-56", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:4,
  stem:"扩展ACL 110: 10 deny tcp 162.15.0.0 0.0.255.255 any eq telnet; 20 deny ... eq smtp; 30 deny ... eq http; 40 permit tcp 162.15.0.0 0.0.255.255 any。来自互联网、目标162.15.10.10的HTTP报文经ACL后（　）。",
  options:["由于行30拒绝，报文被丢弃","由于行40允许，报文被接受","由于ACL末尾隐含拒绝，报文被丢弃","由于源地址不在列表中，报文被接受"], answer:"C",
  analysis:"ACL匹配源地址162.15.x.x，该报文源为互联网地址不匹配任一行，末尾隐式deny any丢弃。" },
{ id:"r2015上-57", source:"real", year:2015, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"下面4个IPv6地址中，无效地址是（　）。",
  options:["::192:168:0:1",":2001:3452:4955:2367::","2002:c0a8:101::43","2003:dead:beef:4dad:23:34:bb:101"], answer:"B",
  analysis:"以单个冒号开头(:::2001…)格式非法，应为2001:…或::开头。" },
{ id:"r2015上-58", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"IPv6站点通过IPv4网络通信需隧道技术，常用的3种自动隧道技术是（　）。",
  options:["VPN、PPTP和IPsec隧道","6to4、6over4和ISATAP隧道","VPN、PPP和ISATAP隧道","IPsec、6over4和PPTP隧道"], answer:"B",
  analysis:"IPv6自动隧道有6to4、6over4、ISATAP。" },
{ id:"r2015上-59", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"网络入口处ACL封锁TCP和UDP的21、23、25端口，则仍能访问该网络的应用是（　）。",
  options:["FTP","DNS","SMTP","Telnet"], answer:"B",
  analysis:"21=FTP、23=Telnet、25=SMTP被封；DNS用53端口不受影响。" },
{ id:"r2015上-60", source:"real", year:2015, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"以太网采用物理地址(MAC)的目的是（　）。",
  options:["唯一地标识第二层设备","使不同网络中的设备可互相通信","用于区分第二层帧和第三层分组","物理地址比网络地址优先级高"], answer:"A",
  analysis:"MAC地址在局域网内唯一标识二层网卡/设备。" },
{ id:"r2015上-61", source:"real", year:2015, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"HostA(192.168.6.27/24,网关192.168.6.1) ping HostB(192.168.4.7/24)，封装帧时ARP表应选用（　）。",
  options:["192.168.4.7→000f.2480.8916","192.168.4.7→0010.5a0c.feae","192.168.6.2→0010.5a0c.feae","192.168.6.1→000f.2480.8916"], answer:"D",
  analysis:"跨网段时HostA把帧发给默认网关192.168.6.1(Router2 Fa0/0,MAC 000f.2480.8916)。" },
{ id:"r2015上-62", source:"real", year:2015, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"4G移动通信标准TD-LTE与FDD-LTE的区别是（　）。",
  options:["频率的利用方式不同","划分上下行信道的方式不同","采用的调制方式有区别","拥有专利技术的厂家不同"], answer:"B",
  analysis:"FDD用成对频段频分双工，TD-LTE用同一频段时分双工，上下行信道划分方式不同。" },
{ id:"r2015上-63", source:"real", year:2015, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"关于移动Ad Hoc网络MANET，（　）不是MANET的特点。",
  options:["网络拓扑结构动态变化","电源能量限制终端须节能工作","可直接应用传统路由协议支持最佳路由","每个结点既是主机又是路由器"], answer:"C",
  analysis:"MANET拓扑动态变化，传统有线路由协议不适用，需专用路由。" },
{ id:"r2015上-64", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"（　）针对TCP连接进行攻击。",
  options:["拒绝服务","暴力攻击","网络侦察","特洛伊木马"], answer:"A",
  analysis:"SYN Flood等拒绝服务攻击针对TCP三次握手/连接耗尽资源。" },
{ id:"r2015上-65", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:4,
  stem:"公司3台不同品牌路由器运行RIPv1，分配201.113.210.0/24，希望用VLSM划分3个子网、每子网40台主机，最优方案是（　）。",
  options:["改EIGRP，3个/27子网","改RIPv2，3个/26子网(64/128/192)","改OSPF，3个/28子网","保持RIPv1，3个/26子网"], answer:"B",
  analysis:"RIPv1不支持VLSM，需改RIPv2；/26每子网62台≥40，3个/26可行。" },
{ id:"r2015上-66", source:"real", year:2015, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"发现网络数据传输很慢、服务质量达不到要求，应首先检查哪一个协议层的工作情况（　）。",
  options:["物理层","会话层","网络层","传输层"], answer:"A",
  analysis:"传输慢先排查物理层(线路、接口速率、误码)等基础问题。" },
{ id:"r2015上-67", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"（　）时使用默认路由。",
  options:["访问本地Web服务器","在路由表中找不到目标网络","没有动态路由","访问ISP网关"], answer:"B",
  analysis:"默认路由在路由表无精确匹配条目时兜底转发。" },
{ id:"r2015上-68", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"安全需求分为物理、网络、系统和应用安全，下列属于系统安全的是（　）。",
  options:["机房安全","入侵检测","漏洞补丁管理","数据库安全"], answer:"C",
  analysis:"漏洞补丁管理属系统(主机操作系统)安全。" },
{ id:"r2015上-69", source:"real", year:2015, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"承上，下列属于应用安全的是（　）。",
  options:["机房安全","入侵检测","漏洞补丁管理","数据库安全"], answer:"D",
  analysis:"数据库安全属应用(业务数据)安全。" },
{ id:"r2015上-70", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"Traditional packet forwarding relies on network layer (　) protocols, or static routing.（选最贴切的词）",
  options:["switching","signaling","routing","session"], answer:"C",
  analysis:"依赖网络层路由(routing)协议或静态路由。" },
{ id:"r2015上-71", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"...make an independent forwarding decision at each (　) within the network.（选最贴切的词）",
  options:["switch","hop","host","customer"], answer:"B",
  analysis:"在网络中每个跳(hop)独立作出转发决策。" },
{ id:"r2015上-72", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"The forwarding decision is based solely on the destination (　) IP address.（选最贴切的词）",
  options:["connection","transmission","broadcast","customer"], answer:"D",
  analysis:"仅依据目的客户(customer)IP地址转发。" },
{ id:"r2015上-73", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"...follow the same path if no other equal-cost (　) exist.（选最贴切的词）",
  options:["paths","distance","broadcast","session"], answer:"A",
  analysis:"若无其他等开销路径(paths)，同目的报文走同一路径。" },
{ id:"r2015上-74", source:"real", year:2015, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"EIGRP also supports non-equal-cost (　) sharing...configure variance.（选最贴切的词）",
  options:["loan","load","content","constant"], answer:"B",
  analysis:"EIGRP支持非等开销负载(load)分担，需配置variance。" }
]);
