/* 真题库 · 2023 上半年 */
/* 来源：jiubanyipeng.com《2023年上半年网工综合知识真题与答案》、信管网考友版交叉核对 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2023上-01", source:"real", year:2023, sem:"上", paper:"上午", point:"计算机硬件", diff:1,
  stem:"固态硬盘的存储介质是（　）。",
  options:["光盘","闪存","软盘","磁盘"], answer:"B",
  analysis:"SSD固态硬盘以NAND闪存为存储介质，区别于机械硬盘的磁盘。" },
{ id:"r2023上-02", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"虚拟存储技术把（　）有机地结合起来使用，从而得到一个更大容量的'内存'。",
  options:["内存与外存","Cache与内存","寄存器与Cache","Cache与外存"], answer:"A",
  analysis:"虚拟存储由内存与外存(磁盘)结合，通过换页/段提供比实际内存更大的逻辑地址空间。" },
{ id:"r2023上-03", source:"real", year:2023, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"下列接口协议中，不属于硬盘接口协议的是（　）。",
  options:["IDE","SATA","SPI","SCSI"], answer:"C",
  analysis:"IDE、SATA、SCSI均为磁盘接口；SPI是串行外设总线(芯片间)，不是硬盘接口。" },
{ id:"r2023上-04", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"进程所请求的资源得到满足后，可以使进程的状态从（　）。",
  options:["运行态变为就绪态","运行态变为等待态","就绪态变为运行态","等待态变为就绪态"], answer:"D",
  analysis:"等待(阻塞)事件完成、资源满足后，进程由等待态进入就绪态，等待调度。" },
{ id:"r2023上-05", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"下列操作系统中，不属于国产操作系统的是（　）。",
  options:["CentOS","Deepin(深度)","NeoKylin(中标麒麟)","HarmonyOS(鸿蒙)"], answer:"A",
  analysis:"CentOS是RedHat系开源Linux发行版，非国产；Deepin、麒麟、鸿蒙均为国产。" },
{ id:"r2023上-06", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"采用多道程序设计可以有效地提高CPU、内存和I/O设备的（　）。",
  options:["灵活性","可靠性","兼容性","利用率"], answer:"D",
  analysis:"多道程序让CPU与I/O并行忙碌，提高系统资源利用率。" },
{ id:"r2023上-07", source:"real", year:2023, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"在网络工程的生命周期中，对用户需求进行了解和分析是在（　）阶段。",
  options:["需求分析","设计","实施","运维"], answer:"A",
  analysis:"需求分析阶段负责了解、记录并分析用户需求。" },
{ id:"r2023上-08", source:"real", year:2023, sem:"上", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"下列工具软件中，不是网络运维常用工具的是（　）。",
  options:["SecureCRT","Wireshark","Putty","Eclipse"], answer:"D",
  analysis:"SecureCRT/Putty是远程终端工具，Wireshark是抓包工具，均为网络运维常用；Eclipse是IDE。" },
{ id:"r2023上-09", source:"real", year:2023, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"下列描述中，不符合《中华人民共和国网络安全法》的是（　）。",
  options:["网络产品应符合相关国家标准强制性要求","网络运营者可根据业务需要自行决定网络日志留存时间","应制定网络安全事件应急预案","收集个人信息应遵循正当、必要原则"], answer:"B",
  analysis:"《网络安全法》规定网络日志留存不少于六个月，不能由运营者随意决定。" },
{ id:"r2023上-10", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"受到破坏后会对国家安全造成特别严重损害的信息系统，应按等级保护第（　）级要求进行安全规划。",
  options:["二","三","四","五"], answer:"D",
  analysis:"等级保护五级对应'受到破坏后对国家安全造成特别严重损害'。" },
{ id:"r2023上-11", source:"real", year:2023, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"下列不属于双绞线测试参数的是（　）。",
  options:["近端串扰","衰减","丢包率","等效远端串扰"], answer:"C",
  analysis:"双绞线认证测试测近端串扰、衰减、等效远端串扰等；丢包率是网络性能指标，非线缆测试参数。" },
{ id:"r2023上-12", source:"real", year:2023, sem:"上", paper:"上午", point:"网络规划与布线", diff:1,
  stem:"下列不属于光纤跳线接头类型的是（　）。",
  options:["FC","LC","SC","SEP"], answer:"D",
  analysis:"常见光纤接头有FC、SC、LC、ST、MU等；SEP不是光纤接头类型。" },
{ id:"r2023上-13", source:"real", year:2023, sem:"上", paper:"上午", point:"数据通信基础", diff:1,
  stem:"Modem的主要作用是（　）。",
  options:["数模转换","路由转发","认证","地址转换"], answer:"A",
  analysis:"调制解调器实现数字信号与模拟信号(数/模)相互转换，以便在电话线上传输。" },
{ id:"r2023上-14", source:"real", year:2023, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"百兆以太网(100BASE-TX)采用的数据编码方法是（　）。",
  options:["曼彻斯特","64B/66B","8B/10B","4B/5B"], answer:"D",
  analysis:"100BASE-TX采用4B/5B编码；曼彻斯特用于经典10M以太网，8B/10B用于千兆。" },
{ id:"r2023上-15", source:"real", year:2023, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"若采用QAM调制的无噪声理想信道带宽为2MHz，最大数据传输速率为28Mbps，则该信道采用的调制方式是（　）。",
  options:["QAM-128","QAM-64","QAM-32","QAM-16"], answer:"A",
  analysis:"奈奎斯特：R=2W·log2M，28=2×2×log2M→log2M=7→M=128，即QAM-128。" },
{ id:"r2023上-16", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:1,
  stem:"在我国商用密码算法体系中，（　）属于摘要算法。",
  options:["SM2","SM3","SM4","SM9"], answer:"B",
  analysis:"SM3是密码杂凑(摘要)算法；SM2公钥、SM4分组、SM9标识密码。" },
{ id:"r2023上-17", source:"real", year:2023, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"使用Traceroute命令时，由中间路由器返回的ICMP超时报文，其Type和Code分别是（　）。",
  options:["Type=3,Code=0","Type=8,Code=0","Type=11,Code=0","Type=12,Code=0"], answer:"C",
  analysis:"ICMP超时(Time Exceeded)Type=11，Code=0；Traceroute利用TTL逐次加一收到超时报文。" },
{ id:"r2023上-18", source:"real", year:2023, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"在EPON中，若用户端家庭网关/交换机由运营商统一进行VLAN管理，则UNI端口的VLAN操作模式优先配置为（　）。",
  options:["标记模式","透传模式","Trunk模式","Translation模式"], answer:"B",
  analysis:"运营商统一管理VLAN时，ONU/家庭网关UNI口应设为透传(tag transparent)，不做VLAN处理。" },
{ id:"r2023上-19", source:"real", year:2023, sem:"上", paper:"上午", point:"无线网络", diff:1,
  stem:"在IEEE标准体系中，WiFi 6对应的标准是（　）。",
  options:["802.11ac","802.11n","802.11b","802.11ax"], answer:"D",
  analysis:"WiFi 6 = 802.11ax；WiFi 5为802.11ac，WiFi 4为802.11n。" },
{ id:"r2023上-20", source:"real", year:2023, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"TCP三次握手时，若客户端SYN段序号为a，则服务端回复的SYN+ACK段中的确认号为（　）。",
  options:["a","a+1","a+20","随机值"], answer:"B",
  analysis:"对SYN(及ISN)确认时确认号=ISN+1，故为a+1(SYN占用一个序号)。" },
{ id:"r2023上-21", source:"real", year:2023, sem:"上", paper:"上午", point:"网络体系结构", diff:1,
  stem:"在OSI参考模型中，负责对应用层消息进行压缩、加密功能的层次是（　）。",
  options:["传输层","会话层","表示层","应用层"], answer:"C",
  analysis:"表示层负责数据语法转换，包括压缩、加密/解密、格式编码。" },
{ id:"r2023上-22", source:"real", year:2023, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"TCP拥塞控制中，快速重传使主机在计时器超时前快速恢复，其触发条件是（　）。",
  options:["计时器超时","拥塞窗口超过阈值","收到该报文的ACK","收到3个冗余ACK"], answer:"D",
  analysis:"快速重传在收到3个重复(冗余)ACK时立即重传，不必等待超时。" },
{ id:"r2023上-23", source:"real", year:2023, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"在RIP协议中，默认的最大度量值(不可达)是（　）跳。",
  options:["15","16","32","64"], answer:"B",
  analysis:"RIP以跳数为度量，15为最大有效跳数，16表示网络不可达(用于防环)。" },
{ id:"r2023上-24", source:"real", year:2023, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"除设置最大度量值外，RIP还可采用（　）防止路由环路。",
  options:["水平分割和垂直翻转","水平分割和路由毒化","垂直翻转和路由毒化","垂直翻转和毒化逆转"], answer:"B",
  analysis:"RIP常用水平分割(不把路由从入接口发回)和路由毒化(将坏路由度量置16)防环。" },
{ id:"r2023上-25", source:"real", year:2023, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"运行OSPF的路由器在广播网络中每（　）秒向各接口发送一次Hello报文。",
  options:["10","20","30","40"], answer:"A",
  analysis:"广播/NBMA网络OSPF Hello间隔默认10秒，Dead间隔为40秒。" },
{ id:"r2023上-26", source:"real", year:2023, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"(接上题)OSPF Hello报文的作用不包括（　）。",
  options:["发现并建立邻居关系","选举DR/BDR","建立双向通讯关系","同步链路状态数据库"], answer:"D",
  analysis:"Hello用于发现/维护邻居、选举DR/BDR；同步数据库靠DD/LSR/LSU，非Hello。" },
{ id:"r2023上-27", source:"real", year:2023, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"下列用于自治系统(AS)之间的路由协议是（　）。",
  options:["RIP","OSPF","BGP","IS-IS"], answer:"C",
  analysis:"BGP是外部网关协议(EGP)，用于AS间；RIP/OSPF/IS-IS均为AS内(IGP)。" },
{ id:"r2023上-28", source:"real", year:2023, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"以下关于Telnet的叙述中，不正确的是（　）。",
  options:["Telnet支持命令模式和会话模式","Telnet采用明文传输","Telnet默认端口是23","Telnet采用UDP协议"], answer:"D",
  analysis:"Telnet基于TCP(端口23)而非UDP，且明文传输不安全。" },
{ id:"r2023上-29", source:"real", year:2023, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"以下关于DHCP服务的说法中，正确的是（　）。",
  options:["DHCP服务器可远程操作客户端开启/关闭服务","同一子网有且只能有一台DHCP服务器","在DHCP服务域内可通过预留确保工作站使用固定IP","DHCP客户端须先配置正确服务器地址才能使用DHCP"], answer:"C",
  analysis:"DHCP通过地址预留/绑定可让指定主机固定获得某IP；客户端以广播发现服务器无需预配地址，且同一子网可有多台服务器。" },
{ id:"r2023上-30", source:"real", year:2023, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"WWW的控制协议是（　）。",
  options:["FTP","HTTP","SSL","DNS"], answer:"B",
  analysis:"万维网WWW基于HTTP进行页面请求与传输。" },
{ id:"r2023上-31", source:"real", year:2023, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"下面用于收取电子邮件的协议是（　）。",
  options:["SMTP","SNMP","ICMP","POP3"], answer:"D",
  analysis:"POP3/IMAP用于接收邮件；SMTP用于发送。" },
{ id:"r2023上-32", source:"real", year:2023, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"要查询DNS域内的权威域名服务器信息，可查看（　）资源记录。",
  options:["SOA","NS","PTR","A"], answer:"B",
  analysis:"NS(Name Server)记录指定域的权威域名服务器。" },
{ id:"r2023上-33", source:"real", year:2023, sem:"上", paper:"上午", point:"IP地址与子网", diff:1,
  stem:"IPv6组播地址的前缀是（　）。",
  options:["FF","FE","FD","FC"], answer:"A",
  analysis:"IPv6组播地址以FF00::/8开头(前缀FF)。" },
{ id:"r2023上-34", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中通常使用（　）作为Web服务器。",
  options:["IIS","Apache","NFS","MySQL"], answer:"B",
  analysis:"Linux平台常用Apache(httpd)作为Web服务器；IIS是Windows的。" },
{ id:"r2023上-35", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"(接上题)Apache默认的Web站点目录为（　）。",
  options:["/etc/httpd","/var/log/httpd","/etc/home","/home/httpd"], answer:"D",
  analysis:"早期Apache默认文档根目录为/home/httpd(对应其站点主目录)。" },
{ id:"r2023上-36", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"为方便远程维护Windows Server 2008 R2服务器，需在服务器上启用（　）服务。",
  options:["DHCP","FTP","DNS","远程桌面"], answer:"D",
  analysis:"远程桌面(RDP)用于图形化远程维护Windows服务器。" },
{ id:"r2023上-37", source:"real", year:2023, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"FTP开启匿名登录时，其用户名是（　）。",
  options:["root","user","guest","anonymous"], answer:"D",
  analysis:"FTP匿名登录用户名为anonymous，口令通常为任意邮箱格式。" },
{ id:"r2023上-38", source:"real", year:2023, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"(接上题)若要在FTP上传文件，应使用（　）命令。",
  options:["copy","paste","put","get"], answer:"C",
  analysis:"FTP中put上传本地文件到服务器，get从服务器下载。" },
{ id:"r2023上-39", source:"real", year:2023, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"邮件客户端使用（　）协议在服务器和客户端之间同步邮件列表(含已读状态)。",
  options:["POP3","SMTP","IMAP","SSL"], answer:"C",
  analysis:"IMAP在服务器上管理邮件、同步状态；POP3下载后通常从服务器删除，不同步状态。" },
{ id:"r2023上-40", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Windows平台上，命令 arp -d * 的作用是（　）。",
  options:["开启ARP学习","添加一条ARP记录","显示当前ARP记录","删除所有ARP记录"], answer:"D",
  analysis:"arp -d删除指定(此处*为所有)ARP缓存项。" },
{ id:"r2023上-41", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"为禁止外部用户访问位于非DMZ区的财务服务器，管理员应在边界防火墙上配置（　）策略。",
  options:["地址转换","访问控制","入侵防御","VPN"], answer:"B",
  analysis:"禁止外部访问指定服务器，应配置访问控制列表(ACL)进行包过滤。" },
{ id:"r2023上-42", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"(接上题)该访问控制策略配置的源地址应为（　）。",
  options:["0.0.0.0(任意)","10.0.122.1","10.0.123.2","10.0.123.2"], answer:"A",
  analysis:"要禁止所有外部用户访问财务服务器，源地址应为任意(any/0.0.0.0)，目的为财务服务器。" },
{ id:"r2023上-43", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"在PKI体系中浏览器与服务器通过SSL/TLS实现HTTPS，二者用于加密HTTP消息的方式是（　）。",
  options:["对方公钥+公钥加密","本方公钥+公钥加密","会话密钥+公钥加密","会话密钥+对称加密"], answer:"D",
  analysis:"HTTPS实际数据用随机会话密钥做对称加密(高效)，会话密钥再经对方公钥加密安全交换。" },
{ id:"r2023上-44", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(接上题)若服务器证书被撤销，产生的后果是（　）。",
  options:["服务器不能执行加解密","服务器不能执行签名","客户端无法再信任该服务器","客户端无法发送加密消息给服务器"], answer:"C",
  analysis:"证书被撤销(CRL/OCSP)后，客户端校验不通过，不再信任该服务器身份。" },
{ id:"r2023上-45", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"(接上题)若浏览器仍继续与该已撤销证书服务器通信，存在的安全隐患是（　）。",
  options:["浏览器发送的消息可能丢失","加密消息可能被第三方解密","加密消息可能被篡改","客户端身份可能泄露"], answer:"B",
  analysis:"证书被撤销意味着该公钥不可信(可能为伪造/中间人持有)，继续通信则加密内容可能被中间人解密。" },
{ id:"r2023上-46", source:"real", year:2023, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"在SNMP各项功能中，属于网络控制功能的是（　）。",
  options:["性能管理","计费管理","配置管理","故障管理"], answer:"A",
  analysis:"SNMP可对设备性能进行监测/控制，题源答案为性能管理(网络控制类)。" },
{ id:"r2023上-47", source:"real", year:2023, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于ICMP的叙述中，错误的是（　）。",
  options:["ICMP封装在IP数据报的数据部分","ICMP消息的传输是可靠的","ICMP是IP协议必需的部分","ICMP可用于差错控制"], answer:"B",
  analysis:"ICMP基于IP传输，本身不可靠(无确认、无重传)；它封装在IP数据报中，用于差错/控制。" },
{ id:"r2023上-48", source:"real", year:2023, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"某主机无法上网，查看本地连接发现只有发送包没有接收包，故障原因可能是（　）。",
  options:["网线没插好","DNS配置错误","IP地址配置错误","TCP/IP协议故障"], answer:"C",
  analysis:"能发不收常为本机IP/掩码配置错误(如IP与本网段不匹配)导致回包无法返回。" },
{ id:"r2023上-49", source:"real", year:2023, sem:"上", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"SNMP的传输层协议是（　）。",
  options:["UDP","TCP","IP","ICMP"], answer:"A",
  analysis:"SNMP基于UDP(161/162端口)传输。" },
{ id:"r2023上-50", source:"real", year:2023, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"SNMP的消息类型不包含（　）。",
  options:["Get-Request","Get-Next-Request","Get-Response","Get-Next-Response"], answer:"D",
  analysis:"SNMP PDU类型有GetRequest、GetNextRequest、GetResponse、SetRequest、Trap等，无'Get-Next-Response'。" },
{ id:"r2023上-51", source:"real", year:2023, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"下列IP地址中不能够被路由器转发的是（　）。",
  options:["192.169.102.78","101.10.10.251","127.16.23.1","172.33.22.16"], answer:"C",
  analysis:"127.0.0.0/8是环回地址段，127.16.23.1属环回，不会被路由器转发到外网。" },
{ id:"r2023上-52", source:"real", year:2023, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"IPv4地址192.168.10.201/26的子网掩码是（　）。",
  options:["255.255.255.0","255.255.255.128","255.255.192.0","255.255.255.192"], answer:"D",
  analysis:"/26即26位网络位，掩码为255.255.255.192。" },
{ id:"r2023上-53", source:"real", year:2023, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"(接上题)192.168.10.201/26所在的网络号是（　）。",
  options:["192.168.10.0","192.168.10.64","192.168.10.192","192.168.10.128"], answer:"C",
  analysis:"/26块大小64：192.168.10.192~255，201落在该段，网络号192.168.10.192。" },
{ id:"r2023上-54", source:"real", year:2023, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"路由器收到目的地址为201.46.17.4的数据包，按最长匹配应发往（　）子网。",
  options:["201.46.0.0/21","201.46.16.0/20","201.46.8.0/22","201.46.20.0/22"], answer:"B",
  analysis:"201.46.17.4落在201.46.16.0/20(16.0~31.255)内，且其掩码最长，故匹配该路由。" },
{ id:"r2023上-55", source:"real", year:2023, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"将连续的2个C类地址聚合后，子网掩码最长是（　）位。",
  options:["24","23","22","21"], answer:"B",
  analysis:"两个连续C类(/24)聚合成一个块，掩码减少1位，即/23。" },
{ id:"r2023上-56", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"以下关于命令 user-interface vty 0 的说法正确的是（　）。",
  options:["配置用户等级为配置级","不允许连接虚拟终端","进入交换机的远程登录(VTY0)用户界面","连接交换机不需要输入密码"], answer:"C",
  analysis:"user-interface vty 0用于进入第0条虚拟终端线路视图，配置Telnet/SSH远程登录参数。" },
{ id:"r2023上-57", source:"real", year:2023, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"交换机启动自检信息显示 'Check startup software...ok / Check configuration file...ok / Check PAF...ok'，其中 Check PAF(资源文件) 步骤的作用是（　）。",
  options:["检查资源文件是否正确","对资源文件进行CRC校验","激活设备存储器中的License文件","系统回滚到上一个正常启动版本"], answer:"A",
  analysis:"启动过程Check PAF即检查资源文件(PAF)是否正确可用。" },
{ id:"r2023上-58", source:"real", year:2023, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"在 display ip routing-table 输出中，描述路由标记(标志)的字段是（　）。",
  options:["Proto","Pre","Cost","Flags"], answer:"D",
  analysis:"路由表中Flags(标志位，如D-download to FIB、R-relay)描述路由标记；Proto为协议、Pre为优先级、Cost为开销。" },
{ id:"r2023上-59", source:"real", year:2023, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"以下关于VLAN标识的叙述中，错误的是（　）。",
  options:["VLAN ID用12bit表示","VLAN ID扩展范围是1025-4096","标准范围内可用于Ethernet的VLAN ID为1-1005","VLAN name用32个字符表示，可为字母和数字"], answer:"C",
  analysis:"802.1Q中VLAN ID共12位(0-4095)，其中1-4094可用；Cisco标准范围1-1005、扩展1006-4094，'1-1005可用于Ethernet'表述错误。" },
{ id:"r2023上-60", source:"real", year:2023, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"IEEE 802.1Q规定VLAN Tag字段中，用于定义帧优先级的是（　）。",
  options:["PRI","CFI","TPID","VID"], answer:"A",
  analysis:"802.1Q Tag中3位PRI(Priority)定义帧优先级；CFI为规范格式指示，TPID为标签协议标识，VID为VLAN号。" },
{ id:"r2023上-61", source:"real", year:2023, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"（　）命令可通过VLAN对二层流量进行隔离，实现对网络资源的控制。",
  options:["management-vlan","voice-vlan","mux-vlan","aggregate-vlan"], answer:"C",
  analysis:"MUX VLAN通过主从VLAN(互通型/隔离型)实现VLAN内端口间二层隔离与资源控制。" },
{ id:"r2023上-62", source:"real", year:2023, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"交换机display stp输出显示 [Mode MSTP]，CIST Bridge=32768.000f-e23e-f9b0。可判断（　）。",
  options:["SWA的桥ID是32768","SWA是根桥","SWA工作在RSTP模式","SWA工作在MSTP模式"], answer:"D",
  analysis:"输出明确标注 Mode MSTP，故SWA工作在MSTP模式；桥ID=32768.000f-e23e-f9b0。" },
{ id:"r2023上-63", source:"real", year:2023, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"在5G技术中，用于提升接入用户数(多用户多流)的技术是（　）。",
  options:["MIMO","NGV","SOMA","SDN"], answer:"A",
  analysis:"大规模MIMO通过多天线多流，显著提升单小区并发接入用户数和容量。" },
{ id:"r2023上-64", source:"real", year:2023, sem:"上", paper:"上午", point:"数据通信基础", diff:4,
  stem:"100BaseT以太网争用时间片为25.6μs，某站已连续3次冲突，按二进制指数退避算法，该站需等待的最短和最长时间分别是（　）。",
  options:["0μs和179.2μs","0μs和819.2μs","25.6μs和179.2μs","25.6μs和819.2μs"], answer:"C",
  analysis:"第3次重传后r=3，退避间隔∈[0,2^3-1]=[0,7]个争用期；最短0×25.6=0μs，最长7×25.6=179.2μs。" },
{ id:"r2023上-65", source:"real", year:2023, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"以下关于2.4G和5G无线网络区别的说法中，错误的是（　）。",
  options:["2.4G相邻信道间有干扰，5G相邻信道几乎无干扰","5G比2.4G传输速度快","穿过障碍物时5G比2.4G衰减小","5G比2.4G工作频段范围大"], answer:"C",
  analysis:"5G频率高、绕射和穿透能力弱，穿障碍物衰减比2.4G更大，故C错误。" },
{ id:"r2023上-66", source:"real", year:2023, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"同楼层20个办公室组建WLAN，要求连网一次后各办公室无缝漫游，最合理的方案是（　）。",
  options:["各办公室部署独立无线路由器","各办公室部署胖AP经交换机接互联网路由器","各办公室部署胖AP接互联网","各办公室部署瘦AP，经交换机连接到AC和互联网路由器"], answer:"D",
  analysis:"跨AP无缝漫游需瘦AP(FIT AP)+无线控制器(AC)统一管理、统一SSID和漫游。" },
{ id:"r2023上-67", source:"real", year:2023, sem:"上", paper:"上午", point:"存储与新技术", diff:2,
  stem:"FC-SAN存储通常通过光纤与服务器的（　）连接。",
  options:["光口网卡","USB接口","光纤通道卡(HBA)","RAID控制器"], answer:"C",
  analysis:"FC-SAN通过光纤通道HBA卡将服务器连接到FC交换机/存储。" },
{ id:"r2023上-68", source:"real", year:2023, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"以下关于结构化布线系统的说法中，错误的是（　）。",
  options:["工作区子系统是网络管理人员值班场所，需配备UPS","干线子系统实现各楼层配线间与建筑物设备间互联","设备间子系统由建筑物进户线、交换设备等组成","建筑群子系统实现各建筑物设备间互联"], answer:"A",
  analysis:"工作区子系统是从墙面信息插座到终端的区域，并非'值班场所'；A错误。" },
{ id:"r2023上-69", source:"real", year:2023, sem:"上", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"以下关于三层模型核心层设计的说法中，错误的是（　）。",
  options:["核心层是网络高速骨干，应有冗余设计","核心层应做包过滤和策略路由以提升安全防护","核心层连接的设备不应过多","需访问互联网时核心层应含外部网络连接"], answer:"B",
  analysis:"核心层追求高速转发，不应在此做包过滤/策略路由等耗时操作(这些应在汇聚/接入层)。" },
{ id:"r2023上-70", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"等保第三级对用户身份鉴别的要求是：在第二级基础上，（　）。",
  options:["设置密码复杂度要求并定期更换","具有登录失败处理功能","防止鉴别信息传输过程中被窃听","采用双因子登录认证，且其中一种鉴别技术至少使用密码技术"], answer:"D",
  analysis:"三级要求身份鉴别采用两种以上组合鉴别技术(双因子)，且至少一种使用密码技术。" },
{ id:"r2023上-71", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) An Intrusion Detection System (IDS) monitors network traffic for suspicious activity. While (1) detection and reporting are primary functions, some IDSs can take actions... (1)应填（　）。",
  options:["Detection","Defending","Definition","Description"], answer:"A",
  analysis:"IDS核心即'检测(Detection)'可疑活动并告警。" },
{ id:"r2023上-72", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) While (2) detection and reporting are the primary functions of an IDS... (2)应填（　）。",
  options:["connection","anomaly","action","error"], answer:"B",
  analysis:"异常检测(anomaly detection)是IDS主要检测方式之一。" },
{ id:"r2023上-73", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) ...taking actions when (3) malicious activity or anomalous traffic is detected... (3)应填（　）。",
  options:["normal","frequent","malicious","known"], answer:"C",
  analysis:"当检测到恶意(malicious)活动或异常流量时IDS可采取行动。" },
{ id:"r2023上-74", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) ...including (4) traffic sent from suspicious IP addresses. (4)应填（　）。",
  options:["receiving","blocking","replying","storing"], answer:"D",
  analysis:"IDS可记录/存储(storing)来自可疑IP的流量用于分析溯源。" },
{ id:"r2023上-75", source:"real", year:2023, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) ...collected centrally using a (5) Security Information and Event Management (SIEM) system. (5)应填（　）。",
  options:["status","service","security","section"], answer:"C",
  analysis:"SIEM即Security(安全)信息与事件管理系统。" }
]);
