/* 真题库 · 2016 下半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2016下-01", source:"real", year:2016, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"CPU需将指令从内存取出分析执行。CPU依据（　）来区分内存中以二进制编码存放的指令和数据。",
  options:["指令周期的不同阶段","指令和数据的寻址方式","指令操作码的译码结果","指令和数据所在的存储单元"], answer:"A",
  analysis:"CPU在取指周期取指令、在执行周期取数据，靠指令周期阶段区分。" },
{ id:"r2016下-02", source:"real", year:2016, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"在一个指令周期中，为从内存读取指令操作码，首先要将（　）的内容送到地址总线上。",
  options:["指令寄存器(IR)","通用寄存器(GR)","程序计数器(PC)","状态寄存器(PSW)"], answer:"C",
  analysis:"取指前PC指向指令地址，PC内容送地址总线。" },
{ id:"r2016下-03", source:"real", year:2016, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"16位浮点数：阶符1位、阶码值6位、数符1位、尾数8位。阶码用移码、尾数用补码，则该浮点数表示的数值范围是（　）。",
  options:["-2^64~(1-2^-8)2^64","-2^63~(1-2^-8)2^63","-(1-2^-8)2^64~(1-2^-8)2^64","-(1-2^-8)2^63~(1-2^-8)2^63"], answer:"B",
  analysis:"阶码6位移码范围-64~63，最大阶2^63，故范围约-2^63~(1-2^-8)2^63。" },
{ id:"r2016下-04", source:"real", year:2016, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"已知数据信息为16位，最少应附加（　）位校验位，以实现海明码纠错。",
  options:["3","4","5","6"], answer:"C",
  analysis:"2^k≥m+k+1，m=16时k=5(32≥22)。" },
{ id:"r2016下-05", source:"real", year:2016, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"取指4△t、分析2△t、执行3△t，流水方式执行完100条指令需要（　）△t。",
  options:["200","300","400","405"], answer:"D",
  analysis:"首条9△t，周期=4△t，9+99×4=405。" },
{ id:"r2016下-06", source:"real", year:2016, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"敏捷方法中，每30天一次迭代称为“冲刺”，按需求优先级、多个自组织小组并行递增实现产品的是（　）。",
  options:["极限编程XP","水晶法","并列争球法(Scrum)","自适应软件开发"], answer:"C",
  analysis:"Scrum(并列争球法)以Sprint冲刺迭代、自组织团队为特征。" },
{ id:"r2016下-07", source:"real", year:2016, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"活动图：START-B(2)；B→C(3)→E(5)→H(2)→J(4)；B→F(4)→J(5)；E→F(3)；B→D(2)→G(3)→F(6)；G→I(6)→J(2)。完成项目最少时间为（　）天。",
  options:["11","15","16","18"], answer:"D",
  analysis:"关键路径START-B-C-E-F-J或START-B-D-G-F-J均为18天。" },
{ id:"r2016下-08", source:"real", year:2016, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"承上活动图，活动BC和BF最多可以晚开始（　）天而不影响进度。",
  options:["0和7","0和11","2和7","2和11"], answer:"A",
  analysis:"BC在关键路径上松弛0天；BF(4天)关键路径上F最早第13天到，BF第6天完成，可晚7天。" },
{ id:"r2016下-09", source:"real", year:2016, sem:"下", paper:"上午", point:"操作系统", diff:3,
  stem:"系统有n个进程共享资源R，R可用数为3(n≥3)，采用PV操作，则信号量S的取值范围为（　）。",
  options:["-1~n-1","-3~3","-(n-3)~3","-(n-1)~1"], answer:"C",
  analysis:"初值3，最多n个进程申请，最坏阻塞n-3个，范围-(n-3)~3。" },
{ id:"r2016下-10", source:"real", year:2016, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"甲、乙两厂同日向商标局申请“B”商标，申请前均未使用，此情形下（　）能核准注册。",
  options:["甲厂","由甲、乙厂抽签确定的厂","乙厂","甲、乙两厂"], answer:"B",
  analysis:"同日申请且均未使用，协商不成由抽签(或商标局裁定)确定。" },
{ id:"r2016下-11", source:"real", year:2016, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"能隔离局域网中广播风暴、提高带宽利用率的设备是（　）。",
  options:["网桥","集线器","路由器","交换机"], answer:"C",
  analysis:"路由器三层隔离广播域，阻隔广播风暴。" },
{ id:"r2016下-12", source:"real", year:2016, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"点对点协议PPP中LCP的作用是（　）。",
  options:["包装各种上层协议","封装承载的网络层协议","把分组转变成信元","建立和配置数据链路"], answer:"D",
  analysis:"LCP负责建立、配置和测试数据链路连接。" },
{ id:"r2016下-13", source:"real", year:2016, sem:"下", paper:"上午", point:"传输层", diff:1,
  stem:"TCP/IP网络中的（　）实现应答、排序和流控功能。",
  options:["数据链路层","网络层","传输层","应用层"], answer:"C",
  analysis:"TCP传输层提供可靠应答、排序与流量控制。" },
{ id:"r2016下-14", source:"real", year:2016, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"异步通信每字符含1起始位、7数据位、1奇偶位、1终止位，每秒传100字符，采用DPSK，则码元速率为（　）。",
  options:["200波特","500波特","1000波特","2000波特"], answer:"C",
  analysis:"每字符10位×100字符/秒=1000波特。" },
{ id:"r2016下-15", source:"real", year:2016, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"承上，有效数据速率为（　）。",
  options:["200b/s","500b/s","700b/s","1000b/s"], answer:"C",
  analysis:"仅7位数据有效：7×100=700b/s。" },
{ id:"r2016下-16", source:"real", year:2016, sem:"下", paper:"上午", point:"广域网与接入", diff:1,
  stem:"E1载波的数据速率是（　）Mb/s。",
  options:["1.544","2.048","8.448","34.368"], answer:"B",
  analysis:"E1=2.048Mb/s。" },
{ id:"r2016下-17", source:"real", year:2016, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"E3载波的数据速率是（　）Mb/s。",
  options:["1.544","2.048","8.448","34.368"], answer:"D",
  analysis:"E3=34.368Mb/s。" },
{ id:"r2016下-18", source:"real", year:2016, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"IPv6链路本地地址是在地址前缀1111 1110 10之后附加（　）形成的。",
  options:["IPv4地址","MAC地址","主机名","随机产生的字符串"], answer:"B",
  analysis:"链路本地地址由FE80::/10 + 接口ID(常由MAC生成)构成。" },
{ id:"r2016下-19", source:"real", year:2016, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"连接终端和数字专线的设备CSU/DSU被集成在路由器的（　）端口中。",
  options:["RJ-45端口","同步串口","AUI端口","异步串口"], answer:"B",
  analysis:"CSU/DSU集成在路由器同步串口连接数字专线。" },
{ id:"r2016下-20", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"下面哪个协议可通过主机的逻辑地址查找对应的物理地址（　）。",
  options:["DHCP","SMTP","SNMP","ARP"], answer:"D",
  analysis:"ARP把IP(逻辑)地址解析为MAC(物理)地址。" },
{ id:"r2016下-21", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"下面应用层协议中通过UDP传送的是（　）。",
  options:["SMTP","TFTP","POP3","HTTP"], answer:"B",
  analysis:"TFTP基于UDP 69端口。" },
{ id:"r2016下-22", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"代理ARP是指（　）。",
  options:["由邻居交换机把ARP请求传给远端目标","由一个路由器代替远端目标回答ARP请求","由DNS服务器代替远端目标回答ARP请求","由DHCP服务器分配一个回答ARP请求的路由器"], answer:"B",
  analysis:"代理ARP由路由器代替远端目标应答本网段主机的ARP请求。" },
{ id:"r2016下-23", source:"real", year:2016, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"路由器收到多个路由协议转发的关于某目标的多条路由，它如何决定采用哪条（　）。",
  options:["选择与自己路由协议相同的","选择路由费用最小的","比较各个路由的管理距离","比较各个路由协议的版本"], answer:"C",
  analysis:"不同协议来源按管理距离(AD)择优，最小者优先。" },
{ id:"r2016下-24", source:"real", year:2016, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"下面选项中属于链路状态路由选择协议的是（　）。",
  options:["OSPF","IGRP","BGP","RIPv2"], answer:"A",
  analysis:"OSPF是链路状态协议；RIP/IGRP为距离矢量，BGP为路径矢量。" },
{ id:"r2016下-25", source:"real", year:2016, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"OSPF多区域网络：区域1含R1/R2/R3，主干区域含R4/R5/R6，R6接外部AS。属于主干路由器的是（　）。",
  options:["R1","R2","R3","R4"], answer:"D",
  analysis:"连接主干区域(Area0)的路由器为主干路由器，R4在主干区域。" },
{ id:"r2016下-26", source:"real", year:2016, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"承上，属于自治系统边界路由器(ASBR)的是（　）。",
  options:["R3","R4","R5","R6"], answer:"D",
  analysis:"连接外部AS、引入外部路由的R6为ASBR。" },
{ id:"r2016下-27", source:"real", year:2016, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"RIPv2与RIPv1相比，它改进了什么（　）。",
  options:["最大跳数扩大了，可适应更大网络","变成无类别协议，必须配置子网掩码","用跳数和带宽作为度量值","可周期性发送更新，收敛更快"], answer:"B",
  analysis:"RIPv2支持CIDR/无类别、报文中携带子网掩码。" },
{ id:"r2016下-28", source:"real", year:2016, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"CRC校验，生成多项式G(X)=X5+X2+X+1，传输数据1011110010101，生成的帧检验序列为（　）。",
  options:["10101","01101","00000","11100"], answer:"C",
  analysis:"按模2除法计算，余数为00000。" },
{ id:"r2016下-29", source:"real", year:2016, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"结构化布线六子系统中，干线子系统的作用是（　）。",
  options:["连接各建筑物中的通信系统","连接干线子系统和用户工作区","实现中央主配线架与各种设备连接","实现各楼层设备间子系统之间的互连"], answer:"D",
  analysis:"干线(垂直)子系统连接各楼层设备间子系统。" },
{ id:"r2016下-30", source:"real", year:2016, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"tracert www.163.com.cn首跳为100.100.17.254，则本地默认网关IP地址是（　）。",
  options:["128.168.20.254","100.100.17.254","219.137.167.157","61.144.3.17"], answer:"B",
  analysis:"tracert第一跳即本地默认网关100.100.17.254。" },
{ id:"r2016下-31", source:"real", year:2016, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，tracert最终目标(Tracing route to ...[219.137.167.157])，网站www.163.com.cn的IP地址是（　）。",
  options:["128.168.20.254","100.100.17.254","219.137.167.157","61.144.3.17"], answer:"C",
  analysis:"首行括号中的地址即为目标www.163.com.cn的IP。" },
{ id:"r2016下-32", source:"real", year:2016, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中要查看eth0的Link/inet/Bcast/Mask及RX/TX packets信息，可使用命令（　）。",
  options:["ifconfig","ipconfig eth0","ipconfig","ifconfig eth0"], answer:"D",
  analysis:"ifconfig eth0显示指定网卡eth0的详细配置与统计。" },
{ id:"r2016下-33", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"当DHCP服务器拒绝客户端的IP地址请求时，发送（　）报文。",
  options:["DhcpOffer","DhcpDecline","DhcpAck","DhcpNack"], answer:"D",
  analysis:"服务器拒绝时回DHCPNAK。" },
{ id:"r2016下-34", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:3,
  stem:"进行域名解析时，当主域名服务器查找不到IP地址时，由（　）负责域名解析。",
  options:["本地缓存","辅域名服务器","根域名服务器","转发域名服务器"], answer:"D",
  analysis:"主服务器无法解析时交由转发域名服务器继续解析。" },
{ id:"r2016下-35", source:"real", year:2016, sem:"下", paper:"上午", point:"传输层", diff:1,
  stem:"在建立TCP连接过程中出现错误连接时，（　）标志字段置“1”。",
  options:["SYN","RST","FIN","ACK"], answer:"B",
  analysis:"RST位复位异常连接。" },
{ id:"r2016下-36", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"POP3服务器默认使用（　）协议。",
  options:["UDP","TCP","SMTP","HTTP"], answer:"B",
  analysis:"POP3基于TCP。" },
{ id:"r2016下-37", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"承上，POP3默认端口是（　）。",
  options:["21","25","53","110"], answer:"D",
  analysis:"POP3端口110。" },
{ id:"r2016下-38", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"当客户端收到多个DHCP服务器的响应时，客户端会选择（　）地址作为自己的IP。",
  options:["最先到达的","最大的","最小的","租期最长的"], answer:"A",
  analysis:"客户端选取最先到达的OFFER。" },
{ id:"r2016下-39", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"在DOS窗口执行 nslookup > set type=a > xyz.com.cn，该命令序列的作用是（　）。",
  options:["查询xyz.com.cn的邮件服务器信息","查询xyz.com.cn到IP地址的映射","查询xyz.com.cn的资源记录类型","显示xyz.com.cn中各种可用的信息资源记录"], answer:"B",
  analysis:"set type=a查询A记录，即域名到IP的映射。" },
{ id:"r2016下-40", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"DHCP工作4种消息：①Discover②Offer③Request④Ack，正确顺序是（　）。",
  options:["①③②④","①②③④","②①③④","②③①④"], answer:"B",
  analysis:"DORA：Discover-Offer-Request-Ack。" },
{ id:"r2016下-41", source:"real", year:2016, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在Linux中，（　）命令可将文件以修改时间顺序显示。",
  options:["ls -a","ls -b","ls -c","ls -d"], answer:"C",
  analysis:"ls -c按修改/状态时间排序显示。" },
{ id:"r2016下-42", source:"real", year:2016, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在一台主机上建立多个独立域名站点，下面方法中（　）是错误的。",
  options:["为计算机安装多块网卡","使用不同的主机头名","使用虚拟目录","使用不同的端口号"], answer:"C",
  analysis:"虚拟目录只是站点下的路径映射，不能区分独立域名站点。" },
{ id:"r2016下-43", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"下面不属于数字签名作用的是（　）。",
  options:["接收者可验证消息来源真实性","发送者无法否认发送过该消息","接收者无法伪造或篡改消息","可验证接收者的合法性"], answer:"D",
  analysis:"数字签名验证发送者身份与完整性，不验证接收者。" },
{ id:"r2016下-44", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"下面可用于消息认证的算法是（　）。",
  options:["DES","PGP","MD5","KMI"], answer:"C",
  analysis:"MD5摘要用于消息认证。" },
{ id:"r2016下-45", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"DES密钥长度56位，三重DES的密钥长度为（　）位。",
  options:["168","128","112","56"], answer:"C",
  analysis:"3DES两密钥各56位共112位。" },
{ id:"r2016下-46", source:"real", year:2016, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在Windows Server 2003中，（　）组成员用户具有完全控制权限。",
  options:["Users","Power Users","Administrators","Guests"], answer:"C",
  analysis:"Administrators管理员组拥有完全控制权限。" },
{ id:"r2016下-47", source:"real", year:2016, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"SNMP协议中，网管代理使用（　）操作向管理站发送异步事件报告。",
  options:["trap","set","get","get-next"], answer:"A",
  analysis:"代理用trap向管理站主动报告异步事件。" },
{ id:"r2016下-48", source:"real", year:2016, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"发现主机受ARP攻击需清除ARP缓存，使用的命令是（　）。",
  options:["arp -a","arp -s","arp -d","arp -g"], answer:"C",
  analysis:"arp -d删除(清空)ARP缓存。" },
{ id:"r2016下-49", source:"real", year:2016, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"从FTP服务器下载文件的命令是（　）。",
  options:["get","dir","put","push"], answer:"A",
  analysis:"FTP的get下载、put上传。" },
{ id:"r2016下-50", source:"real", year:2016, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"内网P2P/视频/游戏流量过大影响性能，可采用（　）保障正常Web及邮件流量。",
  options:["使用网闸","升级核心交换机","部署流量控制设备","部署网络安全审计设备"], answer:"C",
  analysis:"流量控制(QoS)设备对P2P限速、保障关键业务。" },
{ id:"r2016下-51", source:"real", year:2016, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"ISP分配某公司地址块199.34.76.64/28，该公司得到的IP地址数是（　）。",
  options:["8","16","32","64"], answer:"B",
  analysis:"/28块共16个地址。" },
{ id:"r2016下-52", source:"real", year:2016, sem:"下", paper:"上午", point:"网络层与路由", diff:4,
  stem:"路由表4个表项中，与地址220.112.179.92匹配的是（　）。",
  options:["220.112.145.32/22","220.112.145.64/22","220.112.147.64/22","220.112.177.64/22"], answer:"D",
  analysis:"按最长前缀匹配，179.92落在177.64/22对应块。" },
{ id:"r2016下-53", source:"real", year:2016, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"下面4个主机地址中，属于网络110.17.200.0/21的是（　）。",
  options:["110.17.198.0","110.17.206.0","110.17.217.0","110.17.224.0"], answer:"B",
  analysis:"/21块第三字节200~207，206在此块内。" },
{ id:"r2016下-54", source:"real", year:2016, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"用户得到地址范围110.15.0.0~110.15.7.0，这个地址块可以用（　）表示。",
  options:["110.15.0.0/20","110.15.0.0/21","110.15.0.0/16","110.15.0.0/24"], answer:"B",
  analysis:"第三字节0~7共8个=CIDR前缀/21。" },
{ id:"r2016下-55", source:"real", year:2016, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"承上，其中可以分配（　）个可用主机地址。",
  options:["2048","2046","2000","2056"], answer:"B",
  analysis:"/21共2048个地址，去掉网络与广播=2046。" },
{ id:"r2016下-56", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"下面提示符（　）表示特权模式。",
  options:[">","#","(config)#","!"], answer:"B",
  analysis:"特权EXEC模式提示符为#。" },
{ id:"r2016下-57", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"把路由器当前配置文件存储到NVRAM中的命令是（　）。",
  options:["Router(config)#copy current to starting","Router#copy starting to running","Router(config)#copy running-config starting-config","Router#copy run startup"], answer:"D",
  analysis:"copy running-config startup-config(简写copy run startup)保存到NVRAM。" },
{ id:"r2016下-58", source:"real", year:2016, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"路由器显示“Serial 1 is down, line protocol is down”，问题出在OSI参考模型的（　）。",
  options:["物理层","数据链路层","网络层","会话层"], answer:"A",
  analysis:"接口和线路协议均down表示物理层(线路/线缆/信号)故障。" },
{ id:"r2016下-59", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下面交换机命令中，（　）为端口指定VLAN。",
  options:["S1(config-if)# vlan-membership static","S1(config-if)# vlan database","S1(config-if)# switchport mode access","S1(config-if)# switchport access vlan 1"], answer:"D",
  analysis:"switchport access vlan <id>把接入端口划入指定VLAN。" },
{ id:"r2016下-60", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"STP协议的作用是（　）。",
  options:["防止二层环路","以太网流量控制","划分逻辑网络","基于端口的认证"], answer:"A",
  analysis:"生成树协议逻辑阻塞冗余链路，防止二层环路。" },
{ id:"r2016下-61", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"VLAN之间通信需要（　）的支持。",
  options:["网桥","路由器","VLAN服务器","交换机"], answer:"B",
  analysis:"VLAN间为不同广播域，需路由器(或三层交换机)路由。" },
{ id:"r2016下-62", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以太网中出现冲突后，发送方什么时候可以再次尝试发送（　）。",
  options:["再次收到目标站的发送请求后","在JAM信号停止并等待一段固定时间后","在JAM信号停止并等待一段随机时间后","当JAM信号指示冲突已清除后"], answer:"C",
  analysis:"冲突后发送方执行二进制指数退避，等待随机时间再重发。" },
{ id:"r2016下-63", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"网桥怎样知道网络端口连接了哪些站点（　）。",
  options:["从端口收到数据帧，将其目标地址记入该端口数据库","从端口收到数据帧，将其源地址记入该端口数据库","向端口各站点发送请求获取其MAC地址","由管理员预先配置各端口地址数据库"], answer:"B",
  analysis:"网桥学习入帧的源MAC，记入端口地址表。" },
{ id:"r2016下-64", source:"real", year:2016, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"当网桥连接的局域网出现环路时（　）。",
  options:["运行生成树协议阻塞一部分端口","运行DHCP重新分配端口地址","通过站点协商产生备用端口","各网桥选举产生多个无环路生成树"], answer:"A",
  analysis:"STP阻塞部分冗余端口，逻辑上破除环路。" },
{ id:"r2016下-65", source:"real", year:2016, sem:"下", paper:"上午", point:"无线网络", diff:1,
  stem:"IEEE 802.11标准采用的工作频段是（　）。",
  options:["900MHz和800MHz","900MHz和2.4GHz","5GHz和800MHz","2.4GHz和5GHz"], answer:"D",
  analysis:"802.11使用2.4GHz和5GHz ISM频段。" },
{ id:"r2016下-66", source:"real", year:2016, sem:"下", paper:"上午", point:"无线网络", diff:1,
  stem:"IEEE 802.11 MAC子层定义的竞争性访问控制协议是（　）。",
  options:["CSMA/CA","CSMA/CB","CSMA/CD","CSMA/CG"], answer:"A",
  analysis:"无线采用CSMA/CA(冲突避免)。" },
{ id:"r2016下-67", source:"real", year:2016, sem:"下", paper:"上午", point:"无线网络", diff:1,
  stem:"无线局域网新标准IEEE 802.11n提供的最高数据速率可达到（　）Mb/s。",
  options:["54","100","200","300"], answer:"D",
  analysis:"802.11n理论最高可达300Mb/s(甚至600)。" },
{ id:"r2016下-68", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"网络设计实施中，属于系统安全需求措施的是（　）。",
  options:["设备防雷击","入侵检测","漏洞发现与补丁管理","流量控制"], answer:"C",
  analysis:"漏洞发现与补丁管理属系统(主机)安全。" },
{ id:"r2016下-69", source:"real", year:2016, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"在网络分层设计模型中，对核心层工作规程的建议是（　）。",
  options:["要进行数据压缩以提高链路利用率","尽量避免使用访问控制列表以减少转发延迟","可允许最终用户直接访问","尽量避免冗余连接"], answer:"B",
  analysis:"核心层追求高速转发，应避免ACL过滤等增加延迟的处理。" },
{ id:"r2016下-70", source:"real", year:2016, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"网络规划设计中选择网络技术时，下面考虑不正确的是（　）。",
  options:["网络带宽要保证用户能快速访问资源","要选择具有前瞻性的网络新技术","选择时要考虑未来网络扩充需要","通过投入产出分析确定使用何种技术"], answer:"B",
  analysis:"应选用成熟稳定技术而非一味追新，前瞻性不等于盲目选新技术。" },
{ id:"r2016下-71", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"...the symmetric key (　) approach is typically used for encryption of data.（选最贴切的词）",
  options:["cryptography","decode","privacy","security"], answer:"A",
  analysis:"对称密钥密码(cryptography)用于数据加密。" },
{ id:"r2016下-72", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"...used for the encryption of data providing (　).（选最贴切的词）",
  options:["conduction","confidence","confidentiality","connection"], answer:"C",
  analysis:"加密提供机密性(confidentiality)。" },
{ id:"r2016下-73", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"...asymmetric key cryptography is mainly used in key (　) and nonrepudiation.（选最贴切的词）",
  options:["authentication","structure","encryption","exchange"], answer:"D",
  analysis:"非对称密钥主要用于密钥交换(key exchange)和不可否认。" },
{ id:"r2016下-74", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"The hash (　) (noncryptic) ... does not provide confidentiality but provides message integrity.（选最贴切的词）",
  options:["algorithm","secure","structure","encryption"], answer:"A",
  analysis:"哈希算法(algorithm)本身不加密。" },
{ id:"r2016下-75", source:"real", year:2016, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"...cryptographic hash algorithms provide message (　) and identity of peers.（选最贴切的词）",
  options:["confidentiality","integrity","service","robustness"], answer:"B",
  analysis:"密码哈希提供报文完整性(integrity)。" }
]);
