/* 真题库 · 2025 上半年 */
/* 来源：尚大教育/B站考友回忆版(opus 1075210002758631429) 为主，环球网校分段答案交叉核对 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2025上-01", source:"real", year:2025, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"C类网络为50台主机的局域网规划子网掩码为（　）。",
  options:["/29","/27","/26","/28"], answer:"C",
  analysis:"需满足 2^n-2≥50，n=6 时 62>50，故主机位6位，掩码长度 32-6=26，即 /26。" },
{ id:"r2025上-02", source:"real", year:2025, sem:"上", paper:"上午", point:"数据通信基础", diff:1,
  stem:"将信号分配到不同时隙的复用技术是（　）。",
  options:["波分复用(WDM)","码分复用(CDM)","频分复用(FDM)","时分复用(TDM)"], answer:"D",
  analysis:"时分复用(TDM)按时间划分信道，不同时隙传输不同信号，符合'不同时隙'题意；FDM按频率、WDM是光域频分、CDM按码型区分。" },
{ id:"r2025上-03", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"要求：(1)禁止用户访问服务器172.16.1.2的TCP 80和443端口以外的所有端口；(2)允许内部地址10.0.10.0/24通过SSH(22)登录该服务器。下列规则序列可满足要求的是（　）。",
  options:["①允许任意源访问172.16.1.2的80/443；②禁止10.0.10.0/24访问其22；③允许任意访问其任意端口","①允许任意源访问80/443；②禁止任意访问任意端口；③允许10.0.10.0/24访问22","①允许任意源访问80/443；②允许10.0.10.0/24访问22；③禁止任意访问任意端口","①禁止任意访问任意端口；②允许任意源访问172.16.1.2的80/443；③允许10.0.10.0/24访问22"], answer:"C",
  analysis:"防火墙规则按序匹配即停。C：先放行80/443，再放行内网SSH，最后兜底禁止其他，完全满足；A第②条误禁SSH且第③条过宽，B第②条已全禁使第③条永不命中。" },
{ id:"r2025上-04", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"主机感染蠕虫病毒，下列处置措施不合理的是（　）。",
  options:["移除移动硬盘、U盘等外设","更新病毒库并在线扫描查杀病毒","断开网络连接","立即重启进入安全模式"], answer:"B",
  analysis:"蠕虫靠网络自我复制传播，应先断网再本地查杀；'更新病毒库+在线扫描'仍需联网，正是蠕虫传播途径，不合理。" },
{ id:"r2025上-05", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"BGP邻居始终无法进入Established状态，其故障原因可能是（　）。",
  options:["as-number与邻居IP不匹配","未配置路由宣告","Router ID冲突","邻居IP地址不可达"], answer:"A",
  analysis:"BGP建邻须经过Idle/Connect/OpenSent/OpenConfirm到Established；AS号(as-number)配置不匹配会导致OPEN报文协商失败、无法建立邻居。路由宣告只影响路由交换，不影响建邻。" },
{ id:"r2025上-06", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"在交换机上配置基本ACL(acl number 2000 rule 10 permit ...)，则下列网络中会被阻止的是（　）。",
  options:["123.1.4.0","123.1.3.0","123.1.2.0","123.1.5.0"], answer:"B",
  analysis:"基本ACL按源IP过滤，规则放行123.1.4.0网段后，其余网段(含123.1.3.0)被隐式拒绝。" },
{ id:"r2025上-07", source:"real", year:2025, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下列关于交换机Trunk端口处理数据帧的说法正确的是（　）。",
  options:["Trunk端口发送时，携带VLAN标签与PVID不同则直接丢弃","Trunk端口接收时，携带VLAN标签与PVID相同则保留标签转发","Trunk端口收到未带标签帧时直接丢弃","Trunk端口收到带VLAN标签帧时，若该VLAN在允许列表则保留标签转发"], answer:"D",
  analysis:"Trunk口收到带标签帧，若VLAN在允许列表(允许通过)则保留标签转发；收到无标签帧打PVID标签，不会因标签与PVID不同而丢弃。" },
{ id:"r2025上-08", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"堡垒机的主要功能和作用不包括（　）。",
  options:["可提升设备的运维效率","通过多因素身份认证提高安全性","可有效防范远程命令执行漏洞等高危隐患","对运维会话和行为监控便于审计溯源"], answer:"A",
  analysis:"堡垒机提供多因素认证、安全访问通道、操作审计溯源，目的是安全管控；'提升运维效率'不是其作用，反而增加访问层。" },
{ id:"r2025上-09", source:"real", year:2025, sem:"上", paper:"上午", point:"存储与新技术", diff:2,
  stem:"下列关于RAID的说法正确的是（　）。",
  options:["RAID降低了数据存储成本","RAID0通过条带化提高读写效率但无冗余","RAID1采用镜像冗余保障数据安全","RAID5通过多副本机制保障数据安全"], answer:"A",
  analysis:"RAID在提升安全性/性能的同时相比同等冗余单机方案降低总体成本；RAID0无冗余，RAID1才是镜像，RAID5是分布式奇偶校验而非多副本。" },
{ id:"r2025上-10", source:"real", year:2025, sem:"上", paper:"上午", point:"存储与新技术", diff:2,
  stem:"下列关于分布式存储的说法正确的是（　）。",
  options:["通过RAID技术保障数据安全","中心节点存在性能瓶颈和单点故障隐患","数据副本主要作用是离线数据分析","具有较强的横向扩展能力"], answer:"D",
  analysis:"分布式存储以数据分片/复制实现可靠性，去中心化、无中心节点瓶颈，核心优势是横向扩展(scale-out)；副本用于高可用而非离线分析，RAID是本地存储技术。" },
{ id:"r2025上-11", source:"real", year:2025, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"在系统视图下执行命令 [SW] observe-port xxx，其作用是将指定端口配置为（　）。",
  options:["边缘端口","观察端口","镜像端口","目的端口"], answer:"B",
  analysis:"observe-port用于配置观察端口(接收镜像流量的目的端口，接监控设备)；被镜像的源端口为镜像端口。" },
{ id:"r2025上-12", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"OSPF使用（　）来维护邻居关系。",
  options:["Hello报文","LSR报文","LSU报文","LSAck报文"], answer:"A",
  analysis:"OSPF通过Hello报文发现并维护邻居关系、选举DR/BDR；LSR请求LSA、LSU发送LSA、LSAck确认，均不用于维护邻居。" },
{ id:"r2025上-13", source:"real", year:2025, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"下列关于IPv6地址FE80::1说法正确的是（　）。",
  options:["组播地址，用于向多设备发送数据","全球单播地址","保留的环回地址，等同IPv4的127.0.0.1","链路本地地址，只在同一物理网段有效"], answer:"D",
  analysis:"FE80::/10是链路本地地址前缀，仅在本地链路有效、不被路由器转发；IPv6环回为::1，全球单播以2000::/3开头，组播以FF00::/8开头。" },
{ id:"r2025上-14", source:"real", year:2025, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"在Linux中要排除tmpfs、devtmpfs挂载点，并以KB/MB/GB易读单位显示空间使用情况，应使用（　）命令。",
  options:["df -t tmpfs -x devtmpfs","df -x tmpfs -x devtmpfs","df -h -t tmpfs -t devtmpfs","df -h -x tmpfs -x devtmpfs"], answer:"D",
  analysis:"-h以易读单位显示，-x排除指定文件系统类型；需同时排除tmpfs和devtmpfs，故 df -h -x tmpfs -x devtmpfs。" },
{ id:"r2025上-15", source:"real", year:2025, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"下列CPU属于ARM架构的是（　）。",
  options:["龙芯","飞腾","兆芯","海光"], answer:"B",
  analysis:"飞腾部分系列基于ARM架构；龙芯基于LoongArch/MIPS，兆芯、海光基于x86。" },
{ id:"r2025上-16", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"与ECDSA算法等效的国产数字签名算法包含在（　）中。",
  options:["SM2","SM3","SM4","SM9"], answer:"A",
  analysis:"SM2是国产椭圆曲线公钥密码，提供数字签名，与ECDSA等效；SM3是杂凑、SM4是分组加密、SM9是标识密码。" },
{ id:"r2025上-17", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"OSPF路由协议中Type-3类型LSA的发布者是（　）。",
  options:["ABR路由器","任意路由器","ASBR路由器","IR路由器"], answer:"A",
  analysis:"Type-3 LSA(网络汇总LSA)由ABR(区域边界路由器)发布，用于向其他区域通告本区域路由。" },
{ id:"r2025上-18", source:"real", year:2025, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"企业网络采用分层模型的主要优点是（　）。",
  options:["易于隔离故障，网络稳定性高","IP地址统一分配方便管理","降低网络复杂性便于实现","支持标准化提高互操作性"], answer:"A",
  analysis:"分层模型核心优点是故障隔离、便于定位、单层问题不波及全网、易扩展。" },
{ id:"r2025上-19", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"IP首部中TTL字段的作用是（　）。",
  options:["限制数据报在网络中的生存时间","标识数据报类型","控制数据报分片","指定数据报服务类型"], answer:"A",
  analysis:"TTL每经一路由器减1，减为0即丢弃，防止报文在网络中无限循环。" },
{ id:"r2025上-20", source:"real", year:2025, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"下列关于交换机的说法正确的是（　）。",
  options:["交换机每个端口形成一个独立的冲突域","交换机所有端口合并形成一个冲突域","交换机不能隔离冲突域","交换机与集线器功能相同"], answer:"A",
  analysis:"交换机每端口即一个独立冲突域；集线器所有端口同属一个冲突域，这是二者主要区别。" },
{ id:"r2025上-21", source:"real", year:2025, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"以下关于数据的说法错误的是（　）。",
  options:["应定期对数据备份以保障安全","政务数据不得对外开放","履行职责中收集的敏感数据应保密不得非法泄露","数据备份应采用加密存储方式"], answer:"B",
  analysis:"在保障安全和隐私前提下，政务数据去标识化后可依法开放共享，'不得对外开放'过于绝对。" },
{ id:"r2025上-22", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"在路由器上执行 [R1-ospf-1] preference ase 80，其作用是（　）。",
  options:["配置OSPF路由优先级增大80","配置OSPF外部路由优先级为80","配置OSPF内部路由优先级为80","配置OSPF路由优先级减少80"], answer:"B",
  analysis:"preference命令设置路由优先级(数值越小越优)，ase特指OSPF外部路由(AS-External)，即把外部路由优先级设为80。" },
{ id:"r2025上-23", source:"real", year:2025, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"使用甘特图进行（　）。",
  options:["进度管理","管理团队沟通","成本控制","风险管理"], answer:"A",
  analysis:"甘特图以条形图直观展示活动计划与实际进度，主要用于进度规划与控制。" },
{ id:"r2025上-24", source:"real", year:2025, sem:"上", paper:"上午", point:"网络体系结构", diff:1,
  stem:"网络层的数据单元称为（　）。",
  options:["比特(Bit)","段(Segment)","数据包(Packet)","帧(Frame)"], answer:"C",
  analysis:"物理层比特、数据链路层帧、网络层数据包(Packet)、传输层段(Segment)/数据报。" },
{ id:"r2025上-25", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:1,
  stem:"在国产商用密码标准中，SM3算法主要用于（　）。",
  options:["生成密钥对","生成随机数","数据加密","生成消息摘要"], answer:"D",
  analysis:"SM3是密码杂凑(哈希)算法，用于生成消息摘要，类似SHA-256。" },
{ id:"r2025上-26", source:"real", year:2025, sem:"上", paper:"上午", point:"传输层", diff:3,
  stem:"在TCP拥塞控制中，若重传计时器超时，通常会（　）。",
  options:["重传数据并重新进入慢启动阶段","只重传最后一个数据段","增大拥塞窗口","等待更长时间后重传"], answer:"A",
  analysis:"重传超时判为网络拥塞，重传未确认数据，将拥塞窗口置为1 MSS、重新进入慢启动，ssthresh置为当前cwnd一半。" },
{ id:"r2025上-27", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"可防止BGP路由环路的措施是（　）。",
  options:["最大跳数限制","安全认证","AS路径(AS_PATH)检查","路由过滤"], answer:"C",
  analysis:"BGP用AS_PATH属性防环：收到的路由AS_PATH中若包含本AS号则拒绝，避免AS间环路。最大跳数是RIP机制，BGP不靠跳数防环。" },
{ id:"r2025上-28", source:"real", year:2025, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"以下说法错误的是（　）。",
  options:["RFID通信距离通常可达十多米","RFID和NFC均可以进行双向通信","NFC通信距离通常不超过10厘米","NFC设备可同时作为RFID阅读器和卡片使用"], answer:"B",
  analysis:"RFID多为阅读器主动查询、标签被动响应(单向为主)，并非'均双向通信'；NFC才支持双向近场交互。" },
{ id:"r2025上-29", source:"real", year:2025, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"某集群中服务器性能差异较大，配置（　）负载均衡方式较为合理。",
  options:["轮询","加权轮询","最少连接","IP哈希"], answer:"B",
  analysis:"性能不均时用加权轮询(WRR)按处理能力分配权重，强机多分担，避免弱机过载。" },
{ id:"r2025上-30", source:"real", year:2025, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"在科研项目中因研究需要，须（　）才能收集个人生物识别信息(如指纹)。",
  options:["经学校信息化部门批准","向公安部门备案","取得本人的书面同意","经伦理委员会审批"], answer:"C",
  analysis:"依《个人信息保护法》，收集生物识别等敏感个人信息须取得本人单独(书面)同意，行政备案不能替代。" },
{ id:"r2025上-31", source:"real", year:2025, sem:"上", paper:"上午", point:"传输层", diff:3,
  stem:"若TCP连接接收窗口为20KB，往返时间RTT为100ms，则最大吞吐量约为（　）。",
  options:["20KB/s","2MB/s","200KB/s","2GB/s"], answer:"C",
  analysis:"吞吐≈窗口/RTT = 20KB / 0.1s = 200KB/s。" },
{ id:"r2025上-32", source:"real", year:2025, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"海明码由k位信息位和r位监督位构成。若信息位k=4，要纠正1位错误，监督位r最少应为（　）。",
  options:["5","4","2","3"], answer:"D",
  analysis:"须满足 2^r ≥ k+r+1。k=4时：r=2→4<7不满足；r=3→8≥8满足，故最少3位。" },
{ id:"r2025上-33", source:"real", year:2025, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"在Linux中将文件从a目录复制到b目录，并保留创建者、创建时间、修改时间等属性，应使用（　）命令。",
  options:["cp -l","cp -a","cp -d","cp -r"], answer:"B",
  analysis:"cp -a归档模式递归复制并保留所有属性(所有者、时间戳、权限)；-l建硬链接、-d保留链接、-r仅递归。" },
{ id:"r2025上-34", source:"real", year:2025, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"某存储器芯片有12根地址线、8根数据线，其存储容量为（　）。",
  options:["16KB","4KB","8KB","2KB"], answer:"B",
  analysis:"容量=2^地址线数 × 数据线字节数 = 2^12 × 1B = 4096B = 4KB。" },
{ id:"r2025上-35", source:"real", year:2025, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"命令 [SW1-GigabitEthernet0/0/1] description vlan20 的作用是（　）。",
  options:["配置端口GE0/0/1的描述信息","将端口GE0/0/1从vlan20移除","将端口GE0/0/1加入vlan20","删除端口GE0/0/1配置"], answer:"A",
  analysis:"description仅为接口设置描述文本便于管理，不改变VLAN成员。" },
{ id:"r2025上-36", source:"real", year:2025, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"操作系统中的Shell属于（　）。",
  options:["内核","设备驱动程序","用户接口","应用程序"], answer:"C",
  analysis:"Shell是命令解释器，提供用户与操作系统交互的接口，属用户接口层。" },
{ id:"r2025上-37", source:"real", year:2025, sem:"上", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"某邮件系统每天相同时间故障、约10分钟后自动恢复。造成该故障的原因可能是（　）。",
  options:["数据库用户名密码过期","邮件服务器网卡故障","防火墙访问控制策略配置错误","出现IP地址冲突"], answer:"C",
  analysis:"定时发作又自动恢复，符合基于时间段的防火墙策略(定时放通/阻断)；密码过期、网卡故障、IP冲突不会精确定时自愈。" },
{ id:"r2025上-38", source:"real", year:2025, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"黑盒测试的主要作用是测试（　）。",
  options:["功能是否符合需求","程序并发处理能力","程序内部结构设计","代码覆盖率"], answer:"A",
  analysis:"黑盒测试不关心内部结构，只验证输入输出是否符合需求规格，即功能正确性。" },
{ id:"r2025上-39", source:"real", year:2025, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"数据报文从交换机端口G0/0/2(VLAN20)进入、从G0/0/10送出，则该报文送出时的Tag情况是（　）。",
  options:["untagged, tag=10","tagged, tag=10","tagged, tag=20","untagged, tag=20"], answer:"D",
  analysis:"帧属VLAN20，从access口G0/0/10出时剥离标签，故为untagged且对应VLAN20。" },
{ id:"r2025上-40", source:"real", year:2025, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"用户A向用户C发邮件，并希望该邮件的回复发给用户B，应将B的地址写在（　）字段。",
  options:["Reply-To:","Received:","From:","To:"], answer:"A",
  analysis:"Reply-To指定回复时应发往的地址，而非原始发件人地址。" },
{ id:"r2025上-41", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"某OA系统登录页POST请求中存在大量包含'or 1=1--'的恶意请求，应采取（　）措施。",
  options:["部署防火墙","安装防病毒软件","部署Web应用防火墙(WAF)","更新应用补丁"], answer:"C",
  analysis:"'or 1=1'是典型SQL注入，针对Web应用层漏洞，应由WAF专门检测阻断；普通防火墙防网络层，杀毒防终端。" },
{ id:"r2025上-42", source:"real", year:2025, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"SDN中控制器和交换机之间常用的通信协议是（　）。",
  options:["SNMP","BGP","OpenFlow","NETCONF"], answer:"C",
  analysis:"OpenFlow是SDN控制器与数据平面交换机之间的南向标准协议。" },
{ id:"r2025上-43", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"RA收到RB的Hello报文但收不到RC的Hello报文，可能原因是（　）。",
  options:["RC与RA相连接口被配置为OSPF静默接口","RC与RA相连接口被配置为OSPF区域1","RC设备故障无法发送Hello","RC与RA之间链路故障"], answer:"A",
  analysis:"OSPF静默接口(silent-interface)不收发OSPF报文、不建邻居；不同区域接口仍可收发Hello。" },
{ id:"r2025上-44", source:"real", year:2025, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"光纤万兆以太网(10GBASE-R)发送信息流使用的编码方式是（　）。",
  options:["差分曼彻斯特","4B/5B","64B/66B","8B/10B"], answer:"C",
  analysis:"万兆以太网10GBASE-R采用64B/66B编码；8B/10B用于千兆，4B/5B用于百兆/FDDI。" },
{ id:"r2025上-45", source:"real", year:2025, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Windows中可用于查看主机IP地址配置信息的命令是（　）。",
  options:["ipconfig","dir","netstat","ping"], answer:"A",
  analysis:"ipconfig显示本机TCP/IP配置(IP/掩码/网关)。" },
{ id:"r2025上-46", source:"real", year:2025, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"用172.16.0.0/16划分子网，每子网至少500个可用IP，最多可划分（　）个子网。",
  options:["256","128","64","32"], answer:"B",
  analysis:"500主机需2^9-2=510，即9位主机位；可借16-9=7位子网位，故2^7=128个子网。" },
{ id:"r2025上-47", source:"real", year:2025, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"以下具有自同步能力的编码方式是（　）。",
  options:["哈夫曼编码","RZ(归零编码)","曼彻斯特编码","NRZ(非归零编码)"], answer:"C",
  analysis:"曼彻斯特编码每位中间有跳变，接收方可从中提取时钟，自同步能力强。" },
{ id:"r2025上-48", source:"real", year:2025, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"在光网络中，OADM(光分插复用器)设备的主要功能是（　）。",
  options:["提供电力支持","进行频率分析","实现光信号加密","进行光信号的选择分插"], answer:"D",
  analysis:"OADM在WDM系统中选择性上下(Add/Drop)特定波长，不影响其他波长传输。" },
{ id:"r2025上-49", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"下列关于RIP路由协议的描述错误的是（　）。",
  options:["RIP使用触发更新可加速收敛","RIP使用SPF算法计算最短路由","RIP是距离矢量路由协议","RIP是动态路由协议"], answer:"B",
  analysis:"RIP是距离矢量协议，用Bellman-Ford按跳数选路(最大15跳)；SPF是链路状态协议(OSPF)用的算法。" },
{ id:"r2025上-50", source:"real", year:2025, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"下列地址段中可以聚合为172.16.40.0/21的是（　）。",
  options:["172.16.41.0和172.16.43.0","172.16.42.0和172.16.43.0","172.16.41.0和172.16.42.0","172.16.40.0和172.16.44.0"], answer:"D",
  analysis:"172.16.40.0/21覆盖40.0~47.255；其中172.16.40.0/22(40~43)与172.16.44.0/22(44~47)合并恰为/21。" },
{ id:"r2025上-51", source:"real", year:2025, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"下面关于电子邮件服务的说法中正确的是（　）。",
  options:["SMTP基于TCP协议进行可靠的邮件传输","允许用户不经邮件服务器直接把邮件发给接收方","发送服务器和接收服务器不能共用一台服务器","客户端到服务器用SMTP，服务器之间用POP3"], answer:"A",
  analysis:"SMTP基于TCP可靠传输；邮件必须经服务器中转，收发服务器可同机，服务器之间也用SMTP，POP3/IMAP用于收信。" },
{ id:"r2025上-52", source:"real", year:2025, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"交换机收到目的MAC地址不在转发表中的单播帧时，会（　）。",
  options:["泛洪该帧到除入端口外其他端口","按IP查表转发","丢弃该帧","按默认路由转发"], answer:"A",
  analysis:"未知单播帧向除接收端口外所有端口泛洪(flooding)，以便到达目的并学习MAC。" },
{ id:"r2025上-53", source:"real", year:2025, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"要使Hybrid端口对转发的数据帧添加VLAN Tag，应在（　）下执行配置。",
  options:["系统视图下 port hybrid pvid vlan 30","系统视图下 port hybrid tagged vlan 30","接口视图下 port hybrid pvid vlan 30","接口视图下 port hybrid tagged vlan 30"], answer:"D",
  analysis:"port hybrid tagged vlan配置该VLAN带标签转发，且此类端口配置须在接口视图下执行。" },
{ id:"r2025上-54", source:"real", year:2025, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"下列关于网络安全设备的说法错误的是（　）。",
  options:["开发者不得设置后门或恶意程序","运行和检测日志至少保留三个月","应定期进行安全审计","须通过国家认证"], answer:"B",
  analysis:"依《网络安全法》，网络日志应保存不少于六个月，而非三个月。" },
{ id:"r2025上-55", source:"real", year:2025, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"在5G网络架构中，网络切片(Network Slicing)的主要优势是（　）。",
  options:["扩大信号范围","降低设备成本","为不同应用提供定制化服务","提高网络传输速率"], answer:"C",
  analysis:"网络切片在同一物理网上切出多个虚拟网络，分别优化时延、大连接等场景，实现对不同应用的定制化服务。" },
{ id:"r2025上-56", source:"real", year:2025, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"在全网状拓扑中，若节点数为N，所需物理链路数量是（　）。",
  options:["N","N²","N(N-1)/2","N²-N"], answer:"C",
  analysis:"每节点连N-1条，每链路算两次，故为 N(N-1)/2。" },
{ id:"r2025上-57", source:"real", year:2025, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"在DNS中，要把域名映射到IPv6地址，应添加（　）记录。",
  options:["MX","NS","A","AAAA"], answer:"D",
  analysis:"AAAA记录用于域名→IPv6地址；A记录用于IPv4。" },
{ id:"r2025上-58", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"（　）级信息系统应至少每年进行一次等级保护测评。",
  options:["一","二","三","四"], answer:"C",
  analysis:"三级及以上信息系统每年至少开展一次等保测评。" },
{ id:"r2025上-59", source:"real", year:2025, sem:"上", paper:"上午", point:"网络规划与布线", diff:1,
  stem:"具有低衰减、高带宽优势的传输介质是（　）。",
  options:["光纤","电磁波","同轴电缆","双绞线"], answer:"A",
  analysis:"光纤以光信号传输，衰减极低、带宽极高，适合远距离。" },
{ id:"r2025上-60", source:"real", year:2025, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"下列（　）为WLAN用户提供基于Web的身份认证。",
  options:["802.1x","Kerberos","MAC","Portal"], answer:"D",
  analysis:"Portal认证是基于Web页面的认证，用户被重定向到认证页输入账号密码；802.1x是端口接入、Kerberos基于票据、MAC基于物理地址。" },
{ id:"r2025上-61", source:"real", year:2025, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"下列选项中，不属于上网行为审计系统功能的是（　）。",
  options:["阻止内部用户访问恶意URL","对外部用户访问服务器的流量进行加密和解密","实时监控网络流量","及时发现内部失陷主机"], answer:"B",
  analysis:"加解密流量是SSL代理/VPN等功能；审计系统只记录分析流量，不改变流量内容。" },
{ id:"r2025上-62", source:"real", year:2025, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"ARP请求包的目的MAC地址是（　）。",
  options:["单播地址","本机MAC地址","任播地址","广播地址"], answer:"D",
  analysis:"ARP请求以广播(FF-FF-FF-FF-FF-FF)发送，拥有目标IP者单播回应。" },
{ id:"r2025上-63", source:"real", year:2025, sem:"上", paper:"上午", point:"网络体系结构", diff:1,
  stem:"在数据链路层，以太网帧头通常包括（　）。",
  options:["源MAC地址、目的MAC地址与类型字段","发送端口和接收端口","序号与确认号","源IP与目的IP"], answer:"A",
  analysis:"以太网帧头含目的MAC、源MAC、类型/长度字段；IP地址属网络层，序号确认号属传输层。" },
{ id:"r2025上-64", source:"real", year:2025, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"虚拟内存的主要作用是（　）。",
  options:["扩大逻辑内存容量","提高内存访问速度","减少内存碎片","提高系统安全性"], answer:"A",
  analysis:"虚拟内存把部分数据换出到磁盘，使进程可用比物理内存更大的地址空间，即扩大逻辑内存容量。" },
{ id:"r2025上-65", source:"real", year:2025, sem:"上", paper:"上午", point:"传输层", diff:1,
  stem:"UDP首部不包括（　）字段。",
  options:["目标端口","序列号","源端口","校验和"], answer:"B",
  analysis:"UDP首部仅源端口、目标端口、长度、校验和；无连接不可靠，不含序列号(序列号是TCP字段)。" },
{ id:"r2025上-66", source:"real", year:2025, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"若某设备收到目的IP为本地、但MAC地址不匹配的数据帧，则数据链路层会（　）该帧。",
  options:["丢弃","广播","缓存","转发到上层"], answer:"A",
  analysis:"MAC层过滤先于IP层，目的MAC非本机的帧直接丢弃，不上交网络层。" },
{ id:"r2025上-67", source:"real", year:2025, sem:"上", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"下列工具中用于端口扫描的是（　）。",
  options:["Traceroute","Nmap","Wireshark","Ping"], answer:"B",
  analysis:"Nmap专用于主机发现和端口扫描；Traceroute测路径，Wireshark抓包分析，Ping测连通性。" },
{ id:"r2025上-68", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形填空) Organizations need advanced (1) solutions such as end-to-end encryption and MFA.  (1)应填（　）。",
  options:["network","hardware","software","cryptographic"], answer:"D",
  analysis:"后文列举端到端加密、多因子认证，均属密码学/cryptographic解决方案。" },
{ id:"r2025上-69", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形填空) (2) technology ensures that data remains confidential during transmission. (2)应填（　）。",
  options:["blockchain","digital signature","encryption","hashing"], answer:"C",
  analysis:"保证传输中数据机密性(confidentiality)是加密(encryption)的核心功能。" },
{ id:"r2025上-70", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形填空) (3) systems are essential for secure communications and prevent unauthorized access to networks. (3)应填（　）。",
  options:["blockchain","cloud","peer-to-peer","authentication"], answer:"D",
  analysis:"'防止未授权访问网络资源'对应身份认证(authentication)系统。" },
{ id:"r2025上-71", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形填空) Organizations must develop comprehensive (4) policies to protect digital assets. (4)应填（　）。",
  options:["design","storage","performance","security"], answer:"D",
  analysis:"全文围绕网络安全，'安全(security)策略与规程'最贴切。" },
{ id:"r2025上-72", source:"real", year:2025, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形填空) Emerging technologies such as (5) help analysts detect anomalies and respond to threats. (5)应填（　）。",
  options:["6G","virtual reality (VR)","artificial intelligence (AI)","3D printing"], answer:"C",
  analysis:"'分析海量数据、发现异常模式并自动响应威胁'描述的是人工智能(AI)在安全运营中的应用。" },
{ id:"r2025上-73", source:"real", year:2025, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"下列关于SNMP协议功能的描述，正确的是（　）。",
  options:["通过数据校验，保障数据存储安全","监控网络设备的运行状态与性能","用于发送电子邮件","实现网络用户身份认证"], answer:"B",
  analysis:"SNMP主要用于对被管网络设备的状态、性能进行监控管理，不用于存储安全、邮件传输或用户认证。" }
]);
