/* 真题库 · 2025 下半年 */
/* 来源：openEuler社区《2025下半年网工综合知识真题(回忆版)参考答案+解析》为主，环球网校分段(m.hqwx.com/mjineng)交叉核对 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2025下-01", source:"real", year:2025, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"对一个非实时操作系统而言，采用（　）的进程调度方式，可以兼顾效率和公平。",
  options:["优先级调度","最短作业优先","时间片轮转","先来先服务"], answer:"C",
  analysis:"时间片轮转让每个进程分得均等时间片轮流执行，兼顾公平与效率；优先级调度会导致低优先级饥饿，SJF偏向短作业，FCFS无公平保障。" },
{ id:"r2025下-02", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"路由协议的主要作用是（　）。",
  options:["实现物理地址和IP地址的互相转换","交换网络拓扑信息，确定数据传输的最佳路径","保障数据的高可靠传输","将多个可网管二层交换机连接组成一个局域网"], answer:"B",
  analysis:"路由协议交换拓扑/路由信息，计算最佳转发路径；A是ARP，C是TCP，D是二层交换。" },
{ id:"r2025下-03", source:"real", year:2025, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"某公司WEB服务器经常被利用未修复的Struts2漏洞发起远程攻击，可部署（　）设备有效阻断该类攻击。",
  options:["WEB防火墙(WAF)","普通防火墙","漏洞扫描系统","入侵防御系统(IPS)"], answer:"A",
  analysis:"WAF专门防护Web应用层漏洞(Struts2、SQL注入、XSS)；普通防火墙做五元组访问控制，IPS非Web层最佳选型。" },
{ id:"r2025下-04", source:"real", year:2025, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"下列关于物联卡的描述中正确的是（　）。",
  options:["为智能终端设备提供定位、联网等功能","仅可以进行单向通信","任何个人、企业均可不受限制购买使用","可以作为手机SIM卡进行语音通话"], answer:"A",
  analysis:"物联卡为智能终端提供联网(部分含定位)，双向通信，管控严格个人不能随意购买，一般不支持语音通话。" },
{ id:"r2025下-05", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"交换机配置：port link-type access / port default vlan 100 / port-security enable。下列说法正确的是（　）。",
  options:["该access端口仅可以接入交换机或路由器","该端口配置了学习MAC地址最大保存时间为1小时","该端口收到无VLAN标签的数据帧会打上VLAN100标签在交换机内部转发","该端口收到带VLAN100标签的数据帧会剥离标签在内部转发"], answer:"C",
  analysis:"Access口收到untag帧打PVID(VLAN100)标签内部转发，发出时才剥离；access口接终端PC，未配老化时间。" },
{ id:"r2025下-06", source:"real", year:2025, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"《网络安全法》对网络运营者处置网络安全事件的要求是（　）。",
  options:["按预案采取补救措施并查明原因，再视情况决定是否上报","制定应急预案并定期演练，发生事件立即启动预案处置并按规定上报","详细记录处置过程，在年度安全报告中向主管部门汇报","按预案采取补救措施，并在行业内部进行安全风险预警"], answer:"B",
  analysis:"《网络安全法》要求制定应急预案、定期演练，发生事件立即启动处置并按规定上报主管部门。" },
{ id:"r2025下-07", source:"real", year:2025, sem:"下", paper:"上午", point:"网络体系结构", diff:1,
  stem:"SDN的灵活性可以帮助实现（　）。",
  options:["彻底消除网络延迟","限制用户的网络访问","减少基础设施投资","快速配置和动态调整网络资源"], answer:"D",
  analysis:"SDN控制转发分离、集中管控，可快速下发策略、动态调整资源；不能消除延迟，也不一定减少硬件投资。" },
{ id:"r2025下-08", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"OSPF路由协议中Hello报文的主要作用是（　）。",
  options:["邻居之间交换链路状态信息","向邻居传递路由更新路由表","发现邻居并维护邻居关系","用于ABR和ASBR的选举"], answer:"C",
  analysis:"Hello用于发现、保活邻居；交换LSA摘要靠DD报文，传LSU更新路由。" },
{ id:"r2025下-09", source:"real", year:2025, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"下列存储介质中，属于磁介质存储器的是（　）。",
  options:["机械硬盘","固态硬盘","DRAM","NAND闪存"], answer:"A",
  analysis:"机械硬盘HDD靠磁碟磁头磁介质存储；SSD/NAND是闪存，DRAM是半导体内存。" },
{ id:"r2025下-10", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"IPv6邻居发现协议(NDP)替代了IPv4的（　）功能。",
  options:["DNS解析","NAT转换","DHCP分配","ARP协议"], answer:"D",
  analysis:"IPv6 NDP完成地址解析(NS/NA)，替代IPv4的ARP。" },
{ id:"r2025下-11", source:"real", year:2025, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在Windows操作系统中，使用（　）命令启动远程桌面连接。",
  options:["config","telnet","mstsc","wscript"], answer:"C",
  analysis:"mstsc打开远程桌面连接；telnet是远程命令行登录。" },
{ id:"r2025下-12", source:"real", year:2025, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"无线通信中数据包引入冗余位的主要作用是（　）。",
  options:["降低数据传输的复杂性","提高信号的带宽利用率","增强数据的压缩效率","实现错误检测和纠正"], answer:"D",
  analysis:"校验位/FEC前向纠错冗余比特用于检错和纠错。" },
{ id:"r2025下-13", source:"real", year:2025, sem:"下", paper:"上午", point:"网络规划与布线", diff:1,
  stem:"某企业办公区最长布线不超过50米，要求千兆带宽且成本低，最符合的传输介质是（　）。",
  options:["多模光纤","双绞线","单模光纤","同轴电缆"], answer:"B",
  analysis:"50米内、千兆、成本优先，选双绞线(超五类/六类)。" },
{ id:"r2025下-14", source:"real", year:2025, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"下列关于SNMP的描述正确的是（　）。",
  options:["SNMPv3通过TLS实现端到端加密","SNMP系统由NMS和MIB两部分组成","SNMPv2c引入GetBulk操作实现高效块检索","SNMPv1基于团体名认证安全性较高"], answer:"C",
  analysis:"SNMPv2c新增GetBulk批量获取；v3用USM而非TLS，SNMP由NMS/Agent/MIB三部分组成，v1团体名明文安全性差。" },
{ id:"r2025下-15", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"交换机配置 interface Vlanif10 / ip address 172.16.10.1 255.255.255.0，下列说法正确的是（　）。",
  options:["将所有access接口默认设为vlan10","创建逻辑接口并配置IP地址","将交换机下所有终端默认网关设为此地址","所有数据帧默认转发至该逻辑接口"], answer:"B",
  analysis:"Vlanif是三层逻辑虚接口，该命令只创建接口并配IP；终端网关需手动或DHCP下发。" },
{ id:"r2025下-16", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"在交换机上划分VLAN是为了（　）。",
  options:["为用户自动分配IP地址","减少数据帧冲突","缩小网络的广播域","简化交换机的管理"], answer:"C",
  analysis:"VLAN把一个大广播域切小，隔离二层广播。" },
{ id:"r2025下-17", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"华为路由器接口已配IP并欲将其加入OSPF区域0，正确的命令是（　）。",
  options:["network 10.1.1.1 24 area 0","接口视图下 ospf enable area 0","ospf 1 area 0 ip address ...","import-route interface"], answer:"B",
  analysis:"华为接口视图下 ospf enable area 0 使能OSPF；network命令后跟反掩码而非掩码长度。" },
{ id:"r2025下-18", source:"real", year:2025, sem:"下", paper:"上午", point:"网络体系结构", diff:2,
  stem:"IPv6报文首部中Next Header字段的作用是（　）。",
  options:["描述服务类型","描述扩展首部类型","描述载荷(上层)协议类型","描述报文首部的下一个字段"], answer:"C",
  analysis:"Next Header指明紧随IPv6头之后的上层协议(TCP/UDP)或后续扩展头类型。" },
{ id:"r2025下-19", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"交换机两条物理链路配置为一个聚合组，流量如何负载均衡？（　）。",
  options:["配置负载均衡策略按哈希将流量分发到不同物理链路","配置链路优先级，流量优先走高优先级链路","配置MSTP设一主一备实现冗余","聚合协议自动协商使每条链路均分流量"], answer:"A",
  analysis:"链路聚合需配置负载分担策略(源/目MAC、IP哈希)，不会自动均分流量。" },
{ id:"r2025下-20", source:"real", year:2025, sem:"下", paper:"上午", point:"无线网络", diff:1,
  stem:"在5G网络中采用毫米波频段的优势是（　）。",
  options:["降低基站间干扰","提供超大带宽实现高速传输","支撑广覆盖、低频段通信","穿透能力强"], answer:"B",
  analysis:"毫米波频率高、带宽大、速率极高；缺点是穿透差、覆盖距离短。" },
{ id:"r2025下-21", source:"real", year:2025, sem:"下", paper:"上午", point:"传输层", diff:1,
  stem:"TCP三次握手中，客户端第一个SYN报文的序列号字段是（　）。",
  options:["固定为0","由服务器指定","根据客户端IP计算得出","由客户端随机生成"], answer:"D",
  analysis:"ISN初始序列号随机生成，防止序列号预测攻击。" },
{ id:"r2025下-22", source:"real", year:2025, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"某公司需将国内收集的大量重要数据传输到国外，该公司（　）。",
  options:["与境外公司签订合同即可","需要通过国家网信部门组织的安全评估","告知数据所有者并征得同意即可","自行进行安全评估即可"], answer:"B",
  analysis:"重要数据出境须经网信部门组织的安全评估(依据《数据安全法》《个人信息保护法》)。" },
{ id:"r2025下-23", source:"real", year:2025, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"某终端DHCP获取到IP为169.254.58.22/16，其他终端正常上网，故障原因可能是（　）。",
  options:["与DHCP服务器通信异常，未能获取到IP","子网掩码配置错误应为255.255.255.0","出口网关配置ACL阻断该终端","出口网关设备故障"], answer:"A",
  analysis:"169.254.x.x是Windows APIPA自动私有地址，说明DHCP获取失败；其他终端正常故网关无问题。" },
{ id:"r2025下-24", source:"real", year:2025, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"下列关于分布式存储系统的表述中，属于其核心特征的是（　）。",
  options:["将数据临时存于内存实现快速访问","将数据分片存储在多个节点上，提高吞吐量和性能","通过条带化增强扩展能力","通过RAID技术保障数据安全"], answer:"B",
  analysis:"分布式存储把数据分片分散到多节点并行读写提升吞吐；RAID是传统磁盘阵列技术。" },
{ id:"r2025下-25", source:"real", year:2025, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"APP隐私政策写'继续使用即表示同意处理个人信息'，这种获取同意的方式（　）。",
  options:["不合法，同意应在充分知情下自愿、明确做出","合法，已告知并取得同意","合法有效，用户有不使用的自由","不合法，必须获得用户书面签字同意"], answer:"A",
  analysis:"《个人信息保护法》要求个人信息处理须取得个人明确同意，默示同意不生效，且无需纸质签字。" },
{ id:"r2025下-26", source:"real", year:2025, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"下列选项属于上网行为管理系统主要功能的是（　）。",
  options:["对内部用户互联网访问行为进行管控和审计","优化动态路由实现高速转发路由选择","检测阻断XSS、SQL注入等外部攻击","配置访问控制策略实现边界隔离"], answer:"A",
  analysis:"上网行为管理(AC)管控审计内网用户上网行为；C是WAF，D是防火墙。" },
{ id:"r2025下-27", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"二层交换机主要按照（　）进行数据帧转发。",
  options:["目标MAC地址","目标IP地址","源IP地址","源MAC地址"], answer:"A",
  analysis:"二层交换机基于目的MAC转发帧；源MAC用于学习MAC地址表。" },
{ id:"r2025下-28", source:"real", year:2025, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"从数据传输方向分析，下列输入输出设备中与其他三种不同的是（　）。",
  options:["鼠标","键盘","麦克风","显示器"], answer:"D",
  analysis:"鼠标、键盘、麦克风是输入设备；显示器是输出设备。" },
{ id:"r2025下-29", source:"real", year:2025, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，pwd命令的作用是（　）。",
  options:["设置用户口令","删除文件目录","显示当前目录路径","修改权限"], answer:"C",
  analysis:"pwd打印当前工作目录；passwd改密码，rm删除，chmod改权限。" },
{ id:"r2025下-30", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"新接入PC与同网段PC通信时，ARP缓存无目标IP-MAC映射，主机将（　）。",
  options:["将数据包发送至网关","发送ARP广播包","丢弃报文","发送ICMP请求获取目标MAC"], answer:"B",
  analysis:"ARP缓存无条目时发ARP广播请求获取目标MAC。" },
{ id:"r2025下-31", source:"real", year:2025, sem:"下", paper:"上午", point:"传输层", diff:1,
  stem:"UDP协议的特点是（　）。",
  options:["确保数据按顺序到达且不丢失","无连接协议，不保证可靠性和顺序","可发送任意大小数据包不受限","传输前需握手确保连接可靠"], answer:"B",
  analysis:"UDP无连接、不可靠、无握手；报文仍受链路MTU限制。" },
{ id:"r2025下-32", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"VRRP中SW1优先级150(delay 0)、SW2默认优先级100，SW1故障后修复上线，下列说法正确的是（　）。",
  options:["SW1立即抢占成为Master","SW1和SW2通过心跳线协商切换","SW1等待150秒后抢占","SW1不会抢占除非SW2故障"], answer:"A",
  analysis:"SW1优先级150>100且抢占模式delay 0，恢复上线立即抢占Master；VRRP靠组播报文而非独立心跳线。" },
{ id:"r2025下-33", source:"real", year:2025, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"计算机系统中执行加减乘除等运算指令的核心部件是（　）。",
  options:["运算器","控制器","I/O设备","存储器"], answer:"A",
  analysis:"运算器(ALU)负责算术逻辑运算；控制器负责取指译码。" },
{ id:"r2025下-34", source:"real", year:2025, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"DNS查询中服务器名能查到IP、但反向查询失败，原因是DNS服务器（　）。",
  options:["A记录为空","宕机","PTR记录为空","MX记录为空"], answer:"C",
  analysis:"PTR指针记录用于反向解析(IP查域名)；A记录用于正向域名查IP。" },
{ id:"r2025下-35", source:"real", year:2025, sem:"下", paper:"上午", point:"网络体系结构", diff:1,
  stem:"数据链路层的主要功能包括（　）。",
  options:["物理地址寻址","数据包分段","拥塞控制","路由选择"], answer:"A",
  analysis:"数据链路层做MAC寻址；分段、拥塞控制属传输层，路由选择属网络层。" },
{ id:"r2025下-36", source:"real", year:2025, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"多终端实时同步一致邮件状态(已读/未读/归档)，应配置（　）协议接收邮件。",
  options:["POP3","HTTP","IMAP","SMTP"], answer:"C",
  analysis:"IMAP邮件状态保存在服务器，多终端同步；POP3下载到本地不同步状态；SMTP发信。" },
{ id:"r2025下-37", source:"real", year:2025, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"在CDMA技术中，确保信号同时传输互不干扰的关键是（　）。",
  options:["为每个用户分配不同码片序列","为每个用户分配不同时隙","为每个用户分配不同频带","为每个用户分配不同波长"], answer:"A",
  analysis:"CDMA码分多址靠不同正交码片区分用户；TDMA按时隙、FDMA按频带。" },
{ id:"r2025下-38", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"OSPF采用多区域(Area)设计的主要目的是（　）。",
  options:["每个区域采用不同路由协议提升灵活性","限制LSA泛洪范围、降低SPF计算开销、提升可扩展性","多骨干区域提高冗余","实现不同AS间路由控制和隔离"], answer:"B",
  analysis:"OSPF划区域使LSA只在本区域泛洪，减少LSA数量和SPF计算，适合大型网络；骨干只有Area0。" },
{ id:"r2025下-39", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"(英语完形 NAT) When a packet sent by an (1) user reaches a NAT gateway... (1)应填（　）。",
  options:["internal","Internet","ethernet","intranet"], answer:"D",
  analysis:"NAT处理的是内网(intranet)用户访问互联网的报文。" },
{ id:"r2025下-40", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"(英语完形 NAT) ...the gateway translates the IP address in the (2) header... (2)应填（　）。",
  options:["UDP segment","Ethernet frame","TCP segment","IP datagram"], answer:"D",
  analysis:"NAT修改的是IP数据报(IP datagram)首部中的IP地址。" },
{ id:"r2025下-41", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"(英语完形 NAT) ...forwards the packet to the (3). (3)应填（　）。",
  options:["Internet","server","LAN","client"], answer:"A",
  analysis:"NAT网关把转换后报文转发到互联网(Internet)。" },
{ id:"r2025下-42", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"(英语完形 NAT) ...differentiate intranet users based on (4). (4)应填（　）。",
  options:["IP address","IDs","MACs","port numbers"], answer:"D",
  analysis:"多内网用户复用同一公网IP靠端口号(port numbers)区分，即PAT。" },
{ id:"r2025下-43", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"(英语完形 NAT) In this way, the (5) IP address can be reused. (5)应填（　）。",
  options:["private","public","internal","reserved"], answer:"B",
  analysis:"NAT让公网(public)地址可被大量内网主机复用，缓解IPv4地址枯竭。" },
{ id:"r2025下-44", source:"real", year:2025, sem:"下", paper:"上午", point:"网络体系结构", diff:1,
  stem:"下列网络拓扑中，所有节点均需连接至中心设备的是（　）。",
  options:["星型","环型","总线型","网状"], answer:"A",
  analysis:"星型拓扑所有节点连接到中心交换机/集线器。" },
{ id:"r2025下-45", source:"real", year:2025, sem:"下", paper:"上午", point:"无线网络", diff:1,
  stem:"无线局域网的介质访问控制方法是（　）。",
  options:["CSMA/CA","Token Ring","CSMA/CD","Token Bus"], answer:"A",
  analysis:"WLAN用CSMA/CA避免冲突；有线以太网用CSMA/CD。" },
{ id:"r2025下-46", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"接入交换机启用STP后新终端接入要等约30秒才正常，如何配置解决且不影响稳定？（　）。",
  options:["配置该端口STP优先级为0","配置该端口为边缘端口","配置该端口类型为trunk","禁用STP"], answer:"B",
  analysis:"边缘端口(Edge Port)跳过监听/学习状态直接进入转发，用于接终端，不参与生成树计算。" },
{ id:"r2025下-47", source:"real", year:2025, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"SSH替代Telnet的安全远程登录协议，其默认端口号是（　）。",
  options:["24","25","22","23"], answer:"C",
  analysis:"SSH默认22；Telnet 23；SMTP 25。" },
{ id:"r2025下-48", source:"real", year:2025, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"企业要求运维人员不能直接访问服务器、所有运维行为留痕、可阻断高危命令。较合理的方案是（　）。",
  options:["配强密码并部署第三方监控软件","主机部署安全防护系统阻断高危行为","配VPN账号并开启审计日志","部署堡垒机并配置命令拦截和会话监控"], answer:"D",
  analysis:"堡垒机代理访问(不能直连服务器)、会话录像审计、命令拦截，完全满足三要求。" },
{ id:"r2025下-49", source:"real", year:2025, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"计算机信息系统确定保护等级的依据是（　）。",
  options:["公安与行业主管部门协商结果","等保测评机构的测评报告","系统重要性及遭破坏后对国家安全/社会秩序/公共利益/合法权益的危害程度","所属单位自行申报"], answer:"C",
  analysis:"等保定级依据系统重要性和遭破坏后的危害程度。" },
{ id:"r2025下-50", source:"real", year:2025, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"万兆以太网的工作模式是（　）。",
  options:["单工","半双工","共享","全双工"], answer:"D",
  analysis:"万兆以太网(10G)只支持全双工，无半双工模式。" },
{ id:"r2025下-51", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"BGP配置路由聚合，将192.168.0.0/24~192.168.31.0/24聚合为/19并检测环路，正确命令是（　）。",
  options:["summary 192.168.0.0 19","aggregate 192.168.0.0 19","network 192.168.0.0 255.255.224.0","aggregate 192.168.0.0 255.255.224.0 as-set"], answer:"D",
  analysis:"BGP聚合用aggregate；/19掩码为255.255.224.0；as-set携带AS路径可防环路。" },
{ id:"r2025下-52", source:"real", year:2025, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"震网病毒(Stuxnet)专门针对工业控制系统，其主要突破途径是（　）。",
  options:["移动介质","office文档","开源软件","局域网"], answer:"A",
  analysis:"震网最初通过U盘等移动介质传播，攻击伊朗核设施工控系统。" },
{ id:"r2025下-53", source:"real", year:2025, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"小区光纤到户方案中，光分配网络不含任何有源电子器件，该方案属于（　）架构。",
  options:["FTTB","PON","xDSL","FTTC"], answer:"B",
  analysis:"PON无源光网络，ODN全部为无源器件无需电源；FTTH是PON的应用场景。" },
{ id:"r2025下-54", source:"real", year:2025, sem:"下", paper:"上午", point:"网络体系结构", diff:1,
  stem:"在TCP/IP参考模型中，网络诊断命令ping工作在（　）。",
  options:["网络接口层","应用层","传输层","网际互连层(网络层)"], answer:"D",
  analysis:"ping用ICMP，ICMP属TCP/IP网际互连层(网络层)。" },
{ id:"r2025下-55", source:"real", year:2025, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"下列选项中无法提升计算机系统性能的是（　）。",
  options:["流水线","网络存储","高速缓存","超线程"], answer:"B",
  analysis:"流水线、Cache、超线程提升CPU性能；网络存储是存储方案，不提升本机运算性能。" },
{ id:"r2025下-56", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下列关于交换机VLAN配置的说法正确的是（　）。",
  options:["Trunk口收到无Tag帧直接丢弃","可基于端口也可基于MAC地址划分VLAN","跨交换机同VLAN必须借助路由互通","交换机默认无VLAN须先配置方可使用"], answer:"B",
  analysis:"VLAN可按端口、MAC、IP等方式划分；Trunk收到untag帧打PVID；同VLAN跨交换机Trunk二层互通；交换机默认存在VLAN1。" },
{ id:"r2025下-57", source:"real", year:2025, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"将172.16.0.0/16划分子网，每子网至少容纳10000个主机，子网掩码最长可以是（　）。",
  options:["255.255.128.0","255.255.192.0","255.255.240.0","255.255.224.0"], answer:"A",
  analysis:"需2^n-2≥10000→n≥14位主机位；网络位=32-14=18位，掩码255.255.128.0(/18)。" },
{ id:"r2025下-58", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"下列关于交换机堆叠的说法错误的是（　）。",
  options:["Master故障后Standby立即接管，但MAC和路由表需重新学习","不同厂家堆叠用私有协议，成员一般同厂家同型号","堆叠可实现跨设备链路聚合","堆叠将多台设备逻辑虚拟为一台，配置自动同步下发"], answer:"A",
  analysis:"堆叠集群中表项(MAC、路由)主备实时同步，主设备故障备机接管无需重新学习，故A错误。" },
{ id:"r2025下-59", source:"real", year:2025, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"下列Linux命令中，适合查看较大文件的是（　）。",
  options:["tail","cat","head","less"], answer:"D",
  analysis:"less分页浏览大文件；cat一次性全部输出，tail看末尾，head看开头。" },
{ id:"r2025下-60", source:"real", year:2025, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"核心数据库要求读写性能高、有冗余、磁盘利用率≥50%，最符合的RAID级别是（　）。",
  options:["RAID 6","RAID 5","RAID 0","RAID 10"], answer:"B",
  analysis:"RAID5允许坏一块盘、利用率(n-1)/n≥50%、读写性能好；RAID10利用率仅50%，RAID6利用率更低，RAID0无冗余。" },
{ id:"r2025下-61", source:"real", year:2025, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"以下属于国产商用密码算法的是（　）。",
  options:["RSA","DES","SM4","AES"], answer:"C",
  analysis:"SM4是国密对称加密算法；RSA、DES、AES均为国外算法。" },
{ id:"r2025下-62", source:"real", year:2025, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"iptables规则：默认DROP→放行10.10.10.10访问22→无条件DROP→放行80→放行443。结果SSH通但其他主机无法访问HTTP，原因是（　）。",
  options:["规则0阻断所有流量后续规则失效","HTTP/HTTPS需同时配INPUT和OUTPUT链","规则2先匹配到流量执行DROP，后续3、4永不执行","规则3、4未明确源IP 0.0.0/0仅匹配回环"], answer:"C",
  analysis:"iptables按顺序匹配即停，规则2是无条件DROP，所有非SSH流量命中即丢弃，后面的80/443规则永不执行。" },
{ id:"r2025下-63", source:"real", year:2025, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"IPv4地址192.168.10.215/27的网络号是（　）。",
  options:["192.168.10.0","192.168.10.192","192.168.10.64","192.168.10.128"], answer:"B",
  analysis:"/27块大小32，子网为0/32/64/96/128/160/192/224，215落在192段，网络号192.168.10.192。" },
{ id:"r2025下-64", source:"real", year:2025, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"SM2数字签名生成过程中，用于生成消息摘要的辅助函数来自于（　）。",
  options:["SM3","SM9","SM4","ZUC"], answer:"A",
  analysis:"SM2签名摘要算法使用国密SM3；SM4对称加密、SM9标识密码、ZUC序列密码。" },
{ id:"r2025下-65", source:"real", year:2025, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"在默认情况下，Windows的Tracert命令（　）。",
  options:["发送UDP包到目标端口，分析ICMP端口不可达","发送递增TTL的ICMP回显请求，分析ICMP超时","定期向目标发ARP请求记录响应时间","发送TCP SYN到目标80端口分析路由器响应"], answer:"B",
  analysis:"Windows tracert发送递增TTL的ICMP Echo Request，依据沿途返回的超时报文画路径；Linux traceroute默认UDP。" },
{ id:"r2025下-66", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"BGP到达同一目的地有多条优先级相同的路由时，应如何选路？（　）。",
  options:["比较ORIGIN类型优先级","AS-PATH最短的优先","从EBGP邻居学来的路由优先","MED值最小的优先"], answer:"C",
  analysis:"BGP选路优先EBGP路由优于IBGP路由(在其他属性相同情况下)。" },
{ id:"r2025下-67", source:"real", year:2025, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"黑盒测试的主要特点是（　）。",
  options:["验证程序输入输出是否符合预期","需要掌握编程和代码实现细节","使用逻辑覆盖、路径测试等方法","从开发者角度关注代码质量"], answer:"A",
  analysis:"黑盒不关心内部代码，只验证输入输出；B/C/D属白盒测试。" },
{ id:"r2025下-68", source:"real", year:2025, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"销售部终端突然全部无法上网，接入交换机电源灯正常但各接口灯均不亮，故障原因可能是（　）。",
  options:["出现路由环路STP阻塞所有端口","交换机硬件故障","电源适配器工作不稳定","交换机配置丢失"], answer:"B",
  analysis:"电源灯正常说明供电正常，所有接口灯熄灭指向交换机硬件故障；环路不会让所有接口灯熄灭。" },
{ id:"r2025下-69", source:"real", year:2025, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"敏捷开发模型中，'每日站会'(Daily Scrum)的主要目的是（　）。",
  options:["快速同步团队的任务状态","详细讨论系统实现方案","及时评审需求迭代变更","详细汇报个人工作进展"], answer:"A",
  analysis:"每日站会简短同步状态、暴露阻碍，不做深度方案讨论。" },
{ id:"r2025下-70", source:"real", year:2025, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"运行STP的网络中，如何选举根桥？（　）。",
  options:["背板带宽最高的交换机被选为根桥","Bridge ID最小的交换机被选为根桥","最先发出BPDU的交换机被选为根桥","接口速率最高的交换机被选为根桥"], answer:"B",
  analysis:"根桥依据Bridge ID(优先级+MAC)数值最小者当选。" },
{ id:"r2025下-71", source:"real", year:2025, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"IPv4数据报大于链路MTU时IP协议分片。关于IP分片，描述正确的是（　）。",
  options:["每个分片有相同标识符和不同片偏移值，用于组装原始包","分片后的重组由下一跳路由器完成","分片过程数据包顺序可打乱由路由器重排","分片只能由源主机完成"], answer:"A",
  analysis:"同一报文各分片ID相同、片偏移不同以便重组；重组只在目的主机完成，中间路由器也可分片。" },
{ id:"r2025下-72", source:"real", year:2025, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"在数字通信中，使用差分编码的主要目的是（　）。",
  options:["降低对带宽的要求","提高传输效率","减少信号间的干扰","增加数据的安全性"], answer:"C",
  analysis:"差分编码依靠信号跳变表示比特，可抑制相位偏移和码间干扰。" },
{ id:"r2025下-73", source:"real", year:2025, sem:"下", paper:"上午", point:"无线网络", diff:1,
  stem:"移动终端连接到WLAN中进行的第一步操作是（　）。",
  options:["识别","扫描","认证","关联"], answer:"B",
  analysis:"无线接入流程：扫描(Probe)→认证→关联，第一步是扫描AP信号。" },
{ id:"r2025下-74", source:"real", year:2025, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"校园网需全覆盖、学生与教师网络逻辑隔离、运维简单，最符合的方案是（　）。",
  options:["大二层结构，接入层各接口配ACL，出口配NAT","为教师学生各建一套网络物理隔离","层次化结构，教师学生划分不同VLAN，配ACL控制互访，出口配NAT","出口为师生分配不同公网IP，配路由策略隔离"], answer:"C",
  analysis:"层次化架构+VLAN逻辑隔离+ACL控制互访+出口NAT，运维简单且满足需求。" },
{ id:"r2025下-75", source:"real", year:2025, sem:"下", paper:"上午", point:"传输层", diff:3,
  stem:"某TCP连接初始阈值16KB，慢启动阶段每RTT窗口翻倍，经过3个RTT后拥塞窗口大小为（　）。",
  options:["32KB","128KB","16KB","64KB"], answer:"D",
  analysis:"依回忆版解析：初始窗口16KB，慢启动每RTT翻倍，1RTT=32KB、2RTT=64KB，到达阈值后按拥塞避免收敛，经3个RTT后为64KB(此题题干表述特殊，以官方回忆答案为准)。" }
]);
