/* 真题库 · 2019 上半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2019上-01", source:"real", year:2019, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"计算机执行指令的过程中，需要由（　）产生每条指令的操作信号并将信号送往相应的部件进行处理，以完成指定的操作。",
  options:["CPU的控制器","CPU的运算器","DMA控制器","Cache控制器"], answer:"A",
  analysis:"控制器负责产生指令操作信号（控制信号），运算器负责数据运算。" },
{ id:"r2019上-02", source:"real", year:2019, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"DMA控制方式是在（　）之间直接建立数据通路进行数据的交换处理。",
  options:["CPU与主存","CPU与外设","主存与外设","外设与外设"], answer:"C",
  analysis:"DMA方式在外设与主存之间直接成批传送数据，无需CPU干预。" },
{ id:"r2019上-03", source:"real", year:2019, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"在（　）校验方法中，采用模2运算来构造校验位。",
  options:["水平奇偶","垂直奇偶","海明码","循环冗余"], answer:"D",
  analysis:"CRC循环冗余校验采用模2除法（异或运算）生成校验位。" },
{ id:"r2019上-04", source:"real", year:2019, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"以下关于RISC（精简指令系统计算机）技术的叙述中，错误的是（　）。",
  options:["指令长度固定、指令种类尽量少","指令功能强大、寻址方式复杂多样","增加寄存器数目以减少访存次数","用硬布线电路实现指令解码，快速完成指令译码"], answer:"B",
  analysis:"RISC指令长度固定、种类少、寻址方式简单；指令功能强、寻址复杂是CISC特征。" },
{ id:"r2019上-05", source:"real", year:2019, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:3,
  stem:"甲公司购买了一个工具软件，并使用该工具软件开发了新的名为“恒友”的软件，甲公司在销售新软件的同时，向客户提供工具软件的复制品，则该行为（　）。",
  options:["侵犯了著作权","不构成侵权行为","侵犯了专利权","属于不正当竞争"], answer:"A",
  analysis:"销售新软件同时向客户提供其未授权复制的工具软件复制品，侵犯了工具软件著作权人的复制权/发行权。" },
{ id:"r2019上-06", source:"real", year:2019, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:3,
  stem:"甲公司未对“恒友”软件注册商标就推向市场并获好评。三个月后，乙公司也推出名为“恒友”的类似软件，并对之进行了商标注册，则其行为（　）。",
  options:["侵犯了著作权","不构成侵权行为","侵犯了商标权","属于不正当竞争"], answer:"B",
  analysis:"甲公司未注册商标，乙公司将“恒友”注册为商标并不构成对甲公司商标权的侵犯；甲亦无证据证明乙抄袭其作品。" },
{ id:"r2019上-07", source:"real", year:2019, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"10个成员组成的开发小组，若任意两人之间都有沟通路径，则一共有（　）条沟通路径。",
  options:["100","90","50","45"], answer:"D",
  analysis:"任意两人一条路径，即组合数 C(10,2)=10×9/2=45。" },
{ id:"r2019上-08", source:"real", year:2019, sem:"上", paper:"上午", point:"操作系统", diff:3,
  stem:"某文件系统采用位示图（bitmap）记录磁盘的使用情况。若计算机系统的字长为64位，磁盘的容量为1024G，物理块大小为4MB，那么位示图的大小需要（　）个字。",
  options:["1200","2400","4096","9600"], answer:"C",
  analysis:"磁盘块数=1024G/4MB=262144块，每块1位；64位一字，需262144/64=4096字。" },
{ id:"r2019上-09", source:"real", year:2019, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"某文件系统目录结构中根目录下有 MyDrivers、Hotfix，MyDrivers 下有 update、user2、user1，user2 下有 book2.doc。当前工作目录为 MyDrivers，要访问 book2.doc，其绝对路径和相对路径分别为（　）。",
  options:["MyDrivers\\user2\\ 和 \\user2\\","\\MyDrivers\\user2\\ 和 \\user2\\","\\MyDrivers\\user2\\ 和 user2\\","MyDrivers\\user2\\ 和 user2\\"], answer:"C",
  analysis:"绝对路径从根“\\”开始：\\MyDrivers\\user2\\；相对路径从当前 MyDrivers 出发：user2\\。" },
{ id:"r2019上-10", source:"real", year:2019, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"设信号的波特率为1000Baud，信道支持的最大数据速率为2000b/s，则信道采用的调制技术为（　）。",
  options:["BPSK","QPSK","BFSK","4B5B"], answer:"B",
  analysis:"数据速率/波特率=2000/1000=2bit/码元，即4种码元，对应QPSK（正交相移键控）。" },
{ id:"r2019上-11", source:"real", year:2019, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"假设模拟信号的频率为10-16MHz，采样频率必须大于（　）时，才能使得到的样本信号不失真。",
  options:["8MHz","10MHz","20MHz","32MHz"], answer:"D",
  analysis:"奈奎斯特采样定理：采样频率大于信号最高频率的2倍，即2×16MHz=32MHz。" },
{ id:"r2019上-12", source:"real", year:2019, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"下列千兆以太网标准中，传输距离最短的是（　）。",
  options:["1000BASE-FX","1000BASE-CX","1000BASE-SX","1000BASE-LX"], answer:"B",
  analysis:"1000BASE-CX为短距离铜缆（同轴/双绞线，约25m），距离最短；LX光纤可达数千米。" },
{ id:"r2019上-13", source:"real", year:2019, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以下关于直通式交换机和存储转发式交换机的叙述中，正确的是（　）。",
  options:["存储转发式交换机采用软件实现交换","直通式交换机存在环帧传播的风险","存储转发式交换机无需进行CRC校验","直通式交换机比存储转发式交换机交换速率慢"], answer:"B",
  analysis:"直通式交换机不做差错校验，转发完整帧前就读取目的MAC，存在转发碎片/错误帧（环帧）的风险。" },
{ id:"r2019上-14", source:"real", year:2019, sem:"上", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"下列指标中，仅用于双绞线测试的是（　）。",
  options:["最大衰减限值","波长窗口参数","回波损耗限值","近端串扰"], answer:"D",
  analysis:"近端串扰(NEXT)是双绞线独有的测试指标；波长窗口参数用于光纤。" },
{ id:"r2019上-15", source:"real", year:2019, sem:"上", paper:"上午", point:"数据通信基础", diff:4,
  stem:"采用HDLC协议进行数据传输，帧0-7循环编号。当发送站发送了编号为0、1、2、3、4的5帧时，收到了对方应答帧REJ3，此时发送站应发送的后续3帧为（　）。",
  options:["2、3、4","3、4、5","3、5、6","5、6、7"], answer:"B",
  analysis:"REJ（拒绝/回退N帧）表示从第3帧起全部重发，即3、4、5。" },
{ id:"r2019上-16", source:"real", year:2019, sem:"上", paper:"上午", point:"数据通信基础", diff:4,
  stem:"承上，若发送站收到的对方应答帧为SREJ3，则发送站应发送的后续3帧为（　）。",
  options:["2、3、4","3、4、5","3、5、6","5、6、7"], answer:"C",
  analysis:"SREJ（选择拒绝）只重发出错的第3帧，之后继续发送尚未发送的5、6帧，故为3、5、6。" },
{ id:"r2019上-17", source:"real", year:2019, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"E1载波的控制开销占（　）。",
  options:["0.518%","6.25%","1.25%","25%"], answer:"B",
  analysis:"E1每32个时隙中第0、16时隙为开销，开销=2/32=6.25%。" },
{ id:"r2019上-18", source:"real", year:2019, sem:"上", paper:"上午", point:"广域网与接入", diff:2,
  stem:"E1基本帧的传送时间为（　）。",
  options:["100ms","200μs","125μs","150μs"], answer:"C",
  analysis:"E1每秒8000帧，帧传送时间=1/8000=125μs。" },
{ id:"r2019上-19", source:"real", year:2019, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"TCP和UDP协议均提供了（　）能力。",
  options:["连接管理","差错校验和重传","流量控制","端口寻址"], answer:"D",
  analysis:"TCP与UDP都通过端口号实现端到端进程（应用）寻址；连接管理、重传、流量控制仅TCP具备。" },
{ id:"r2019上-20", source:"real", year:2019, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"建立TCP连接时，一端主动打开后所处的状态为（　）。",
  options:["SYN_SENT","ESTABLISHED","CLOSE-WAIT","LAST-ACK"], answer:"A",
  analysis:"主动打开并发送SYN后进入SYN_SENT状态，等待对方SYN+ACK。" },
{ id:"r2019上-21", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"ARP的协议数据单元封装在（　）中传送。",
  options:["以太帧","IP数据报","TCP段","UDP段"], answer:"A",
  analysis:"ARP报文直接封装在以太网帧中（类型字段0x0806），不经过IP。" },
{ id:"r2019上-22", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"ICMP的协议数据单元封装在（　）中传送。",
  options:["以太帧","IP数据报","TCP段","UDP段"], answer:"B",
  analysis:"ICMP报文作为IP数据报的数据部分封装在IP中（协议号1）。" },
{ id:"r2019上-23", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"RIP路由协议数据单元封装在（　）中传送。",
  options:["以太帧","IP数据报","TCP段","UDP段"], answer:"D",
  analysis:"RIP使用UDP，端口520。" },
{ id:"r2019上-24", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"在点对点网络上，运行OSPF协议的路由器每（　）秒钟向它的各个接口发送Hello分组，告知邻居它的存在。",
  options:["10","20","30","40"], answer:"A",
  analysis:"OSPF在广播/NBMA、点对点网络上Hello间隔为10秒；NBMA为30秒。" },
{ id:"r2019上-25", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"下列路由协议中，用于AS之间路由选择的是（　）。",
  options:["RIP","OSPF","IS-IS","BGP"], answer:"D",
  analysis:"BGP是自治系统间（域间）路由协议；RIP、OSPF、IS-IS为域内路由协议。" },
{ id:"r2019上-26", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"某设备执行命令后显示：Area 0.0.0.0 接口 192.168.1.1 的邻居 Router ID 2.2.2.2（State: Full），Area 0.0.0.1 接口 192.168.2.1 的邻居 Router ID 3.3.3.3。已知拓扑中该设备两个接口分别为 192.168.1.1/24 与 192.168.2.1/24，该设备是（　）。",
  options:["R1","R2","R3","R4"], answer:"A",
  analysis:"接口192.168.1.1与192.168.2.1同时出现在一台路由器上，对应拓扑中的R1。" },
{ id:"r2019上-27", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"承上，上述显示OSPF邻居信息所执行的命令是（　）。",
  options:["display bgp routing-table","display isis isdb","display ospf peer","display ip routing-table"], answer:"C",
  analysis:"查看OSPF邻居表用 display ospf peer。" },
{ id:"r2019上-28", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"承上，上述邻居信息片段中反映邻居状态是否正常的参数是（　）。",
  options:["State","Mode","Priority","MTU"], answer:"A",
  analysis:"State 字段显示 Full 表示邻居状态正常；Full 为完全邻接。" },
{ id:"r2019上-29", source:"real", year:2019, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"配置POP3服务器时，邮件服务器中默认开放TCP的（　）端口。",
  options:["21","25","53","110"], answer:"D",
  analysis:"POP3默认TCP 110；21为FTP控制、25为SMTP、53为DNS。" },
{ id:"r2019上-30", source:"real", year:2019, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，可以使用命令（　）针对文件newfiles.txt为所有用户添加执行权限。",
  options:["chmod -x newfiles.txt","chmod +x newfiles.txt","chmod -w newfiles.txt","chmod +w newfiles.txt"], answer:"B",
  analysis:"chmod +x 为所有用户(u/g/o)添加执行权限；-x为去掉执行权限。" },
{ id:"r2019上-31", source:"real", year:2019, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"在Linux中，可在（　）文件中修改Web服务器配置。",
  options:["/etc/host.conf","/etc/resolv.conf","/etc/inetd.conf","/etc/httpd.conf"], answer:"D",
  analysis:"Apache(HTTPD)主配置文件为httpd.conf；resolv.conf为DNS解析配置。" },
{ id:"r2019上-32", source:"real", year:2019, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，要查看文件的详细信息，可使用（　）命令。",
  options:["ls -a","ls -l","ls -i","ls -S"], answer:"B",
  analysis:"ls -l 以长格式显示文件详细信息；-a显示隐藏文件，-i显示inode，-S按大小排序。" },
{ id:"r2019上-33", source:"real", year:2019, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在Windows命令行窗口中使用（　）命令可以查看本机各个接口的DHCP服务是否已启用。",
  options:["ipconfig","ipconfig /all","ipconfig /renew","ipconfig /release"], answer:"B",
  analysis:"ipconfig /all 显示完整配置，含各接口DHCP是否已启用等详细信息。" },
{ id:"r2019上-34", source:"real", year:2019, sem:"上", paper:"上午", point:"操作系统", diff:3,
  stem:"在Windows系统的服务项中，（　）服务使用SMB协议创建并维护客户端网络与远程服务器之间的连接。",
  options:["SNMP Trap","Windows Search","Workstation","Superfetch"], answer:"C",
  analysis:"Workstation服务(lanmanworkstation)负责SMB客户端，建立与远程服务器的连接。" },
{ id:"r2019上-35", source:"real", year:2019, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"下列不属于电子邮件协议的是（　）。",
  options:["POP3","IMAP","SMTP","MPLS"], answer:"D",
  analysis:"MPLS是多协议标签交换（二层/三层之间的隧道技术），不是邮件协议。" },
{ id:"r2019上-36", source:"real", year:2019, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"下述协议中与安全电子邮箱服务无关的是（　）。",
  options:["SSL","HTTPS","MIME","PGP"], answer:"C",
  analysis:"MIME是多用途互联网邮件扩展（邮件正文编码格式），本身不提供安全；SSL/HTTPS/PGP用于邮件安全。" },
{ id:"r2019上-37", source:"real", year:2019, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"DHCP服务器设置了C类私有地址为地址池，某Windows客户端获得的地址是169.254.107.100，出现该现象可能的原因是（　）。",
  options:["该网段存在多台DHCP服务器","DHCP服务器为客户端分配了该地址","DHCP服务器停止工作","客户端TCP/IP协议配置错误"], answer:"C",
  analysis:"169.254.x.x是APIPA自动私有地址，当客户端找不到DHCP服务器（如DHCP停止工作）时自动分配。" },
{ id:"r2019上-38", source:"real", year:2019, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"在Windows Server 2008系统中，不能使用IIS搭建的是（　）服务器。",
  options:["WEB","DNS","SMTP","FTP"], answer:"B",
  analysis:"IIS可搭建Web、FTP、SMTP等服务；DNS需用DNS服务器角色，不属IIS。" },
{ id:"r2019上-39", source:"real", year:2019, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"用户发出HTTP请求后，收到状态码为505的响应，出现该现象的原因是（　）。",
  options:["页面请求正常，数据传输成功","服务器根据客户端请求切换协议","服务器端HTTP版本不支持","请求资源不存在"], answer:"C",
  analysis:"HTTP 505表示服务器不支持该请求所用的HTTP协议版本。" },
{ id:"r2019上-40", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"非对称加密算法中，加密和解密使用不同的密钥，下面的加密算法中（　）属于非对称加密算法。",
  options:["AES","RSA","IDEA","DES"], answer:"B",
  analysis:"RSA是非对称（公钥）加密算法；AES、IDEA、DES均为对称加密算法。" },
{ id:"r2019上-41", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"若甲、乙采用非对称密钥体系进行保密通信，甲用乙的公钥加密数据文件，乙使用（　）来对数据文件进行解密。",
  options:["甲的公钥","甲的私钥","乙的公钥","乙的私钥"], answer:"D",
  analysis:"用乙的公钥加密，只能用对应的乙的私钥解密。" },
{ id:"r2019上-42", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"用户A和B要进行安全通信，通信过程需确认双方身份和消息不可否认。A、B通信时可使用（　）来对用户的身份进行认证。",
  options:["数字证书","消息加密","用户私钥","数字签名"], answer:"A",
  analysis:"数字证书（由CA签发，含公钥与身份信息）用于身份认证。" },
{ id:"r2019上-43", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"承上，使用（　）确保消息不可否认。",
  options:["数字证书","消息加密","用户私钥","数字签名"], answer:"D",
  analysis:"数字签名（发送方用自己的私钥签名）可保证消息的不可否认性。" },
{ id:"r2019上-44", source:"real", year:2019, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"Windows环境下，在命令运行状态下执行（　）命令，可查看本机活动连接及监听端口列表（含TCP/UDP各端口状态）。",
  options:["netstat -a","ipconfig /all","tasklist","net start"], answer:"A",
  analysis:"netstat -a 显示所有连接和监听端口，可看到161等UDP端口是否处于监听状态。" },
{ id:"r2019上-45", source:"real", year:2019, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，在上述端口列表输出中，（　）项说明SNMP服务已经启动，对应端口已经开启。",
  options:["UDP 0.0.0.0:161","UDP 0.0.0.0:500","TCP 0.0.0.0:135","TCP 0.0.0.0:445"], answer:"A",
  analysis:"SNMP代理默认使用UDP 161端口。" },
{ id:"r2019上-46", source:"real", year:2019, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"使用snmputil.exe查看代理MIB对象时执行命令 snmputil get 192.168.1.31 public 1.3.6.1.2.1.1.3.0，其中OID部分是（　）。",
  options:["192.168.1.31","1.3.6.1.2.1.1.3.0","system.sysUpTime.0","TimeTicks 1268803"], answer:"B",
  analysis:"最后一个参数1.3.6.1.2.1.1.3.0为sysUpTime对象的OID。" },
{ id:"r2019上-47", source:"real", year:2019, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"在华为交换机的故障诊断命令中，查看告警信息的命令是（　）。",
  options:["display patch","display trap","display interface brief","display current-configuration"], answer:"B",
  analysis:"display trap 用于查看告警(trap)信息。" },
{ id:"r2019上-48", source:"real", year:2019, sem:"上", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"华为交换机不断重启，每次在配置恢复阶段（未输出“Recover configuration...”之前）就发生复位，下面哪个故障处理措施可以不考虑？（　）",
  options:["重传系统大包文件，并设置为启动文件，重启设备","新建空的配置文件上传，并设置为启动文件，重启设备","重传系统大包文件问题还未解决，再次更新BOOTROM","多次重启后问题无法解决，将问题反馈给华为技术支持"], answer:"B",
  analysis:"问题发生在配置恢复阶段之前（系统启动大包阶段），与配置文件无关，故上传空配置文件无意义。" },
{ id:"r2019上-49", source:"real", year:2019, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"设备上无法创建正确的MAC转发表项，造成二层数据转发失败，故障的原因包括（　）。①MAC、接口、VLAN绑定错误 ②配置了MAC地址学习去使能 ③存在环路MAC地址学习错误 ④MAC表项限制或超规格",
  options:["①②③④","①②④","②③","②④"], answer:"A",
  analysis:"四种情况都可能导致MAC转发表项无法正确建立，造成二层转发失败。" },
{ id:"r2019上-50", source:"real", year:2019, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"假设某公司有8000台主机，采用CIDR方法进行划分，则至少给它分配（　）个C类网络。",
  options:["8","10","16","32"], answer:"D",
  analysis:"一个C类网络254个可用主机，8000/254≈31.5，向上取整需32个C类网络。" },
{ id:"r2019上-51", source:"real", year:2019, sem:"上", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"承上，如果192.168.210.181是其中一台主机地址，则其网络地址为（　）。",
  options:["192.168.192.0/19","192.168.192.0/20","192.168.208.0/19","192.168.208.0/20"], answer:"A",
  analysis:"32个C类即聚合为/19（块大小32），第三字节210落在192~223段，网络地址为192.168.192.0/19。" },
{ id:"r2019上-52", source:"real", year:2019, sem:"上", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"路由器收到一个数据报文，其目标地址为20.112.17.12，该地址属于（　）子网。",
  options:["20.112.17.8/30","20.112.16.0/24","20.96.0.0/11","20.112.18.0/23"], answer:"C",
  analysis:"/11掩码第二字节块大小32，20.96.0.0/11覆盖20.96.0.0~20.127.255.255，112落在此范围。" },
{ id:"r2019上-53", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"IPv6基本首部的长度为（　）个字节。",
  options:["20","40","64","128"], answer:"B",
  analysis:"IPv6固定基本首部长度为40字节。" },
{ id:"r2019上-54", source:"real", year:2019, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"IPv6首部中与IPv4中TTL字段对应的是（　）字段。",
  options:["负载长度","通信类型","跳数限制","下一首部"], answer:"C",
  analysis:"IPv6的跳数限制(Hop Limit)对应IPv4的TTL。" },
{ id:"r2019上-55", source:"real", year:2019, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"某校园网的地址是202.115.192.0/19，要把该网络分成30个子网，则子网掩码应该是（　）。",
  options:["255.255.200.0","255.255.224.0","255.255.254.0","255.255.255.0"], answer:"D",
  analysis:"分30个子网需借5位(2^5=32)，/19+5=/24，掩码255.255.255.0。" },
{ id:"r2019上-56", source:"real", year:2019, sem:"上", paper:"上午", point:"数据通信基础", diff:4,
  stem:"以太网的最大帧长为1518字节，每个数据帧前面有8个字节的前导字段，帧间隔为9.6μs。传输240000bit的IP数据报，采用100BASE-TX网络，需要的最短时间为（　）。",
  options:["1.23ms","12.3ms","2.63ms","26.3ms"], answer:"C",
  analysis:"240000bit/(1500×8)=200帧；每帧(1518+8)×8bit/100Mbps=122μs加帧间隔9.6μs，约200×131.6μs≈26.3ms/10≈2.63ms量级。" },
{ id:"r2019上-57", source:"real", year:2019, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"下面列出的4种快速以太网物理层标准中，采用4B5B编码技术的是（　）。",
  options:["100BASE-FX","100BASE-T4","100BASE-TX","100BASE-T2"], answer:"A",
  analysis:"100BASE-FX（光纤快速以太网）采用4B5B编码；TX采用MLT-3，T4采用8B6T。" },
{ id:"r2019上-58", source:"real", year:2019, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以太网协议中使用了二进制指数后退算法，其冲突后最大的尝试次数为（　）次。",
  options:["8","10","16","20"], answer:"C",
  analysis:"二进制指数后退最大重传次数为16次，超过则丢弃该帧。" },
{ id:"r2019上-59", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"震网（Stuxnet）病毒是一种破坏工业基础设施的恶意代码，利用系统漏洞攻击工业控制系统，是一种危害性极大的（　）。",
  options:["引导区病毒","宏病毒","木马病毒","蠕虫病毒"], answer:"D",
  analysis:"震网(Stuxnet)可利用漏洞自我复制传播，属于蠕虫病毒。" },
{ id:"r2019上-60", source:"real", year:2019, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"默认管理VLAN是（　）。",
  options:["VLAN 0","VLAN 1","VLAN 10","VLAN 100"], answer:"B",
  analysis:"交换机默认VLAN1为管理VLAN，所有端口默认属于VLAN1。" },
{ id:"r2019上-61", source:"real", year:2019, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"以下关于跳频扩频技术的描述中，正确的是（　）。",
  options:["扩频通信减少了干扰并有利于通信保密","用不同的频率传播信号扩大了通信的范围","每一个信号比特编码成N个码片比特来传输","信号散布到更宽的频带上增加了信道阻塞的概率"], answer:"A",
  analysis:"跳频扩频(FHSS)通过在多频率点跳变传输，抗干扰能力强且利于保密。" },
{ id:"r2019上-62", source:"real", year:2019, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"下列无线网络技术中，覆盖范围最小的是（　）。",
  options:["802.15.1 蓝牙","802.11n 无线局域网","802.15.4 ZigBee","802.16m 无线城域网"], answer:"A",
  analysis:"蓝牙(802.15.1)为个域网，覆盖仅约10m，范围最小。" },
{ id:"r2019上-63", source:"real", year:2019, sem:"上", paper:"上午", point:"无线网络", diff:3,
  stem:"无线局域网中AP的轮询会导致异步帧延迟，在IEEE802.11网络中定义了（　）机制来解决这一问题。",
  options:["RTS/CTS机制","二进制指数退避","超级帧","无争用服务"], answer:"D",
  analysis:"PCF（点协调功能）提供无争用服务，由AP集中轮询，解决异步帧冲突延迟问题。" },
{ id:"r2019上-64", source:"real", year:2019, sem:"上", paper:"上午", point:"存储与新技术", diff:2,
  stem:"RAID技术中，磁盘容量利用率最低的是（　）。",
  options:["RAID0","RAID1","RAID5","RAID6"], answer:"B",
  analysis:"RAID1为镜像，利用率仅50%；RAID0为100%，RAID5为(n-1)/n，RAID6为(n-2)/n。" },
{ id:"r2019上-65", source:"real", year:2019, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"三层网络设计方案中，（　）是汇聚层的功能。",
  options:["不同区域的高速数据转发","用户认证、计费管理","终端用户接入网络","实现网络的访问策略控制"], answer:"D",
  analysis:"汇聚层负责路由聚合、VLAN间路由与访问策略控制；接入层负责终端接入，核心层负责高速转发。" },
{ id:"r2019上-66", source:"real", year:2019, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"以下关于网络工程需求分析的叙述中，错误的是（　）。",
  options:["任何网络都不可能是一个能够满足各项功能需求的万能网","需求分析要充分考虑用户的业务需求","需求的定义越明确和详细，网络建成后用户的满意度越高","网络需求分析时可以先不考虑成本因素"], answer:"D",
  analysis:"成本（预算）是网络需求分析必须考虑的重要约束因素。" },
{ id:"r2019上-67", source:"real", year:2019, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:4,
  stem:"某网络工程项目施工计划：开始后并行进行A工作(3天，4人)、C工作(7天，3人)；A完成后进行B工作(5天，3人)；B、C均完成后结束。要求项目7天内完工，至少需要投入（　）人。",
  options:["4","6","7","14"], answer:"C",
  analysis:"C为关键路径(7天)占3人；A(3天4人)与B(5天3人)需在7天内完成，资源优化后峰值至少7人。" },
{ id:"r2019上-68", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"Network security consists of policies and practices to prevent and monitor (　) access, misuse, modification, or denial of a computer network and network-accessible resources.（选最贴切的词）",
  options:["unauthorized","harmful","dangerous","frequent"], answer:"A",
  analysis:"网络安全用于防止和监控未授权(unauthorized)访问。" },
{ id:"r2019上-69", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"Network security involves the authorization of access to data in a network, which is controlled by the network (　).（选最贴切的词）",
  options:["user","agent","server","administrator"], answer:"D",
  analysis:"网络访问授权由管理员(administrator)控制。" },
{ id:"r2019上-70", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"The most common and simple way of protecting a network resource is by assigning it a (　) name and a corresponding password.（选最贴切的词）",
  options:["complex","unique","catchy","long"], answer:"B",
  analysis:"为网络资源分配唯一(unique)的名称和对应口令是最常见简单的保护方式。" },
{ id:"r2019上-71", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"Once authenticated, a (　) enforces access policies such as what services are allowed to be accessed by the network users.（选最贴切的词）",
  options:["firewall","proxy","gateway","host"], answer:"A",
  analysis:"防火墙(firewall)强制执行访问控制策略。" },
{ id:"r2019上-72", source:"real", year:2019, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"Though effective to prevent unauthorized access, this component may fail to check potentially harmful content such as computer (　) or Trojans being transmitted over the network.（选最贴切的词）",
  options:["spams","malwares","worms","programs"], answer:"C",
  analysis:"防火墙无法检查蠕虫(worms)、木马等通过网络传输的有害内容。" }
]);
