/* 真题库 · 2022 上半年（原定5月28日，因疫情推迟至11月与下半年同期但不同卷） */
REAL_BANK = REAL_BANK.concat([
{ id:"r2022上-01", source:"real", year:2022, sem:"上", paper:"上午", point:"计算机硬件", diff:1,
  stem:"计算机操作的最小时间单位是（　）。",
  options:["指令周期","时钟周期","总线周期","CPU周期"], answer:"B",
  analysis:"时钟周期（振荡周期）为时钟频率的倒数，是CPU最基本、最小的时间单位，一个时钟周期仅完成一个最基本动作；总线周期、CPU周期、指令周期均由若干时钟周期构成。" },
{ id:"r2022上-02", source:"real", year:2022, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"以下关于冯·诺依曼计算机的叙述中，不正确的是（　）。",
  options:["程序指令和数据都采用二进制表示","程序指令总是存储在主存中，而数据则存储在高速缓存中","程序的功能都由中央处理器（CPU）执行指令来实现","程序的执行过程由指令进行自动控制"], answer:"B",
  analysis:"冯·诺依曼机中程序指令和数据都存储在主存中，并非数据单独存于高速缓存；二者均以二进制表示，由CPU执行指令自动控制。" },
{ id:"r2022上-03", source:"real", year:2022, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"在风险管理中，降低风险危害的策略不包括（　）。",
  options:["回避风险","转移风险","消除风险","接受风险并控制损失"], answer:"C",
  analysis:"风险控制四种基本方法为风险回避、损失控制、风险转移、风险保留；风险本质无法被现实“消除”。" },
{ id:"r2022上-04", source:"real", year:2022, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"为了减少在线观看网络视频卡顿，经常采用流媒体技术。以下关于流媒体说法不正确的是（　）。",
  options:["流媒体需要缓存","流媒体视频资源不能下载到本地","流媒体技术可以用于观看视频、网络直播","流媒体资源文件格式可以是 asf、rm 等"], answer:"B",
  analysis:"流媒体边下边播，其视频资源文件本身是可以下载到本地的；需缓存、可用于直播、格式可为 asf/rm。" },
{ id:"r2022上-05", source:"real", year:2022, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"以下选项中，不属于计算机操作系统主要功能的是（　）。",
  options:["管理计算机系统的软硬件资源","充分发挥计算机资源的效率","为其他软件提供良好的运行环境","存储数据"], answer:"D",
  analysis:"操作系统主要功能包括处理机/内存/设备/文件管理等，存储数据是存储设备本身的职责，并非操作系统功能。" },
{ id:"r2022上-06", source:"real", year:2022, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"智能手机包含运行内存和机身内存，以下关于运行内存的说法中，不正确的是（　）。",
  options:["也称手机RAM","用于暂时存放处理器所需的运算数据","能够永久保存数据","手机运行内存越大，性能越好"], answer:"C",
  analysis:"运行内存即RAM，只能临时存储数据供CPU交换，掉电即失，不能永久保存数据。" },
{ id:"r2022上-07", source:"real", year:2022, sem:"上", paper:"上午", point:"存储与新技术", diff:1,
  stem:"某电商平台根据用户消费记录分析用户消费偏好，预测未来消费倾向，这是（　）技术的典型应用。",
  options:["物联网","区块链","云计算","大数据"], answer:"D",
  analysis:"从海量历史消费记录中挖掘偏好、预测趋势，是大数据分析的典型应用。" },
{ id:"r2022上-08", source:"real", year:2022, sem:"上", paper:"上午", point:"存储与新技术", diff:2,
  stem:"以下关于云计算的叙述中，不正确的是（　）。",
  options:["云计算将所有客户的计算都集中在一台大型计算机上进行","云计算是基于互联网的相关服务的增加、使用和交付模式","云计算支持用户在任意位置使用各种终端获取相应服务","云计算的基础是面向服务的架构和虚拟化的系统部署"], answer:"A",
  analysis:"云计算是分布式计算，将任务分解后由多台服务器组成的集群并行处理，并非集中在一台大型机上。" },
{ id:"r2022上-09", source:"real", year:2022, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:3,
  stem:"SOA（面向服务的架构）是一种（　）服务架构。",
  options:["细粒度、紧耦合","粗粒度、松耦合","粗粒度、紧耦合","细粒度、松耦合"], answer:"B",
  analysis:"SOA 将应用分解为粗粒度、松耦合的服务，通过精确定义的接口通信，服务层可被直接调用。" },
{ id:"r2022上-10", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:1,
  stem:"在需要保护的信息资产中，（　）是最重要的。",
  options:["软件","硬件","数据","环境"], answer:"C",
  analysis:"信息安全的核心是数据/信息本身，软件、硬件、环境都是为数据安全服务的载体。" },
{ id:"r2022上-11", source:"real", year:2022, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"以下频率中，属于微波波段的是（　）。",
  options:["30Hz","30KHz","30MHz","30GHz"], answer:"D",
  analysis:"微波指频率在 300MHz～300GHz 之间的电磁波，选项中仅 30GHz 落在微波波段。" },
{ id:"r2022上-12", source:"real", year:2022, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以下关于以太网交换机的说法中，错误的是（　）。",
  options:["以太网交换机工作在数据链路层","以太网交换机可以隔离冲突域","以太网交换机中存储转发交换方式相比直接交换方式其延迟更短","以太网交换机通过MAC地址表转发数据"], answer:"C",
  analysis:"存储转发需完整接收并校验整个帧后再转发，延迟比直接（直通）交换更长。" },
{ id:"r2022上-13", source:"real", year:2022, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"一台16口的全双工千兆交换机，至少需要（　）的背板带宽才能实现线速转发。",
  options:["1.488Gbps","3.2Gbps","32Gbps","320Gbps"], answer:"C",
  analysis:"全双工总带宽=端口数×端口速率×2=16×1G×2=32Gbps。" },
{ id:"r2022上-14", source:"real", year:2022, sem:"上", paper:"上午", point:"数据通信基础", diff:1,
  stem:"模拟信号数字化的正确步骤是（　）。",
  options:["采样、量化、编码","编码、量化、采样","采样、编码、量化","编码、采样、量化"], answer:"A",
  analysis:"PCM 模拟信号数字化依次经过采样、量化、编码三步。" },
{ id:"r2022上-15", source:"real", year:2022, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"5G 采用的正交振幅调制（QAM）技术中，256QAM 的一个载波上可以调制（　）比特信息。",
  options:["2","4","6","8"], answer:"D",
  analysis:"256=2^8，每个码元表示 log2(256)=8 位二进制。" },
{ id:"r2022上-16", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:4,
  stem:"下面关于 Kerberos 认证协议的叙述中，正确的是（　）。",
  options:["密钥分发中心包括认证服务器、票据授权服务器和客户机三个部分","协议的交互采用公钥加密算法加密消息","用户和服务器之间不需要共享长期密钥","协议的目的是让用户获得访问应用服务器的服务许可票据"], answer:"D",
  analysis:"KDC 仅含 AS 与 TGS（不含客户机）；交互用对称（私钥）加密；用户与认证服务器需共享长期密钥；其目的是获取访问应用服务器的服务许可票据。" },
{ id:"r2022上-17", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:4,
  stem:"如果 PC 通过 tracert 命令获取路由器 R3 的 IP 地址（R3 为第三跳），PC 发出封装 ICMP 消息的 IP 报文应满足的特征是（　）。",
  options:["ICMP 消息的 Type=11, Code=0；IP 报文的 TTL 字段为3","ICMP 消息的 Type=8, Code=0；IP 报文的 TTL 字段为3","ICMP 消息的 Type=11, Code=0；IP 报文的 TTL 字段为128","ICMP 消息的 Type=8, Code=0；IP 报文的 TTL 字段为128"], answer:"B",
  analysis:"tracert 逐跳发送 ICMP Echo Request（Type=8）并递增 TTL；探测第三跳 R3 时 TTL=3，R3 返回超时报文使 PC 获知其地址。" },
{ id:"r2022上-18", source:"real", year:2022, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"在光纤接入技术中，EPON 系统中的 ONU 向 OLT 发送数据采用（　）技术。",
  options:["TDM","FDM","TDMA","广播"], answer:"C",
  analysis:"EPON 下行 OLT 到 ONU 采用广播；上行 ONU 到 OLT 采用时分多址 TDMA，按时间片分配上行带宽。" },
{ id:"r2022上-19", source:"real", year:2022, sem:"上", paper:"上午", point:"无线网络", diff:4,
  stem:"在双链路热备无线接入网中，STA 通过 Portal 认证上线，AP 当前连接的主 AC 为 AC1，STA 通过 AP 在 AC1 上线。关于 AC2 的描述中，正确的是（　）。",
  options:["AC2 上有 AP 的信息，且 AP 在 AC2 的状态为 standby","AC2 上有 AP 的信息，且 AP 在 AC2 的状态为 normal","AC2 上有 STA 的信息，且 STA 的状态为未认证","AC2 上有 STA 的信息，且 STA 的状态为已认证"], answer:"D",
  analysis:"华为 AC 双机热备会在主备间同步数据，保证主备设备信息一致，故备用 AC2 上也有该 STA 信息且状态为已认证，故障时可无缝切换。" },
{ id:"r2022上-20", source:"real", year:2022, sem:"上", paper:"上午", point:"传输层", diff:2,
  stem:"在 TCP 协议连接释放过程中，请求释放连接的一方（客户端）发送连接释放报文段，该报文段应该将（　）。",
  options:["FIN 置1","FIN 置0","ACK 置1","ACK 置0"], answer:"A",
  analysis:"主动关闭方发送 FIN=1 的报文发起四次挥手，用于释放连接。" },
{ id:"r2022上-21", source:"real", year:2022, sem:"上", paper:"上午", point:"传输层", diff:3,
  stem:"以下关于 TCP 拥塞控制机制的说法中，错误的是（　）。",
  options:["慢启动阶段，将拥塞窗口值设置为1","慢启动算法执行时拥塞窗口指数增长，直到拥塞窗口值达到慢启动门限值","在拥塞避免阶段，拥塞窗口线性增长","当网络出现拥塞时，慢启动门限值恢复为初始值"], answer:"D",
  analysis:"发生拥塞时慢启动门限值 ssthresh 更新为当前 cwnd 的一半（cwnd/2），拥塞窗口降为1重新慢启动，并非门限恢复初始值。" },
{ id:"r2022上-22", source:"real", year:2022, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"在 OSI 参考模型中，（　）在物理线路上提供可靠的数据传输服务。",
  options:["物理层","数据链路层","网络层","传输层"], answer:"B",
  analysis:"数据链路层在相邻节点间分帧传送，并通过校验、应答保证物理线路上的无差错传输。" },
{ id:"r2022上-23", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下路由协议中，（　）属于有类路由协议。",
  options:["RIPv1","OSPF","IS-IS","BGP"], answer:"A",
  analysis:"RIPv1 不发送子网掩码，是有类路由协议；RIPv2、OSPF、IS-IS、BGP 均为无类。" },
{ id:"r2022上-24", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"以下关于 RIPv1 和 RIPv2 路由选择协议说法中，错误的是（　）。",
  options:["都是基于 Bellman 算法的","都是基于跳数作为度量值的","都包含有 Request 和 Response 两种分组，且分组完全一致的","都是采用传输层的 UDP 协议承载"], answer:"C",
  analysis:"RIPv2 分组额外携带子网掩码、认证等字段，与 RIPv1 分组并不完全一致。" },
{ id:"r2022上-25", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"一台运行 OSPF 路由协议的路由器，转发接口为 100Mbps，其 cost 值应该是（　）。",
  options:["1","10","100","1000"], answer:"A",
  analysis:"OSPF 接口 cost 默认=10^8/带宽，100Mbps 时为 10^8/10^8=1。" },
{ id:"r2022上-26", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"在 BGP 路由选择协议中，（　）属性可以避免在 AS 之间产生环路。",
  options:["Origin","AS_PATH","Next Hop","Community"], answer:"B",
  analysis:"AS_PATH 记录路由经过的 AS 序列，若收到的路由中已含本地 AS 号则丢弃，从而避免 AS 间环路。" },
{ id:"r2022上-27", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"以下关于 IS-IS 路由选择协议的说法中，错误的是（　）。",
  options:["IS-IS 路由协议是一种基于链路状态的 IGP 路由协议","IS-IS 路由协议可将自治系统划分为骨干区域和非骨干区域","IS-IS 路由协议中的路由器的不同接口可以属于不同的区域","IS-IS 路由协议的地址结构由 IDP 和 DSP 两部分组成"], answer:"C",
  analysis:"IS-IS 路由器的所有接口必须属于同一区域（与 OSPF 不同，OSPF 不同接口可属不同区域）。" },
{ id:"r2022上-28", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:1,
  stem:"以下协议中，不属于安全的数据/文件传输协议的是（　）。",
  options:["HTTPS","SSH","SFTP","Telnet"], answer:"D",
  analysis:"Telnet 明文传输，不提供加密；HTTPS、SSH、SFTP 均为安全传输协议。" },
{ id:"r2022上-29", source:"real", year:2022, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"在浏览器地址栏输入 ftp://ftp.tsinghua.edu.cn/ 进行访问时，下列操作中浏览器不会执行的是（　）。",
  options:["域名解析","建立 TCP 连接","发送 HTTP 请求报文","发送 FTP 命令"], answer:"C",
  analysis:"访问 FTP 时浏览器先做域名解析，再与服务器建立 TCP 连接并发送 FTP 命令；发送 HTTP 请求报文仅在访问 http:// 时发生。" },
{ id:"r2022上-30", source:"real", year:2022, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"下列端口号中，（　）是电子邮件发送协议默认的服务端口号。",
  options:["23","25","110","143"], answer:"B",
  analysis:"SMTP 是发送邮件协议，基于 TCP，默认端口 25；110 为 POP3、143 为 IMAP。" },
{ id:"r2022上-31", source:"real", year:2022, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"以下关于 IPv6 与 IPv4 比较的说法中，错误的是（　）。",
  options:["IPv4 的头部是变长的，IPv6 的头部是定长的","IPv6 与 IPv4 中均有头部校验和字段","IPv6 中的 Hop Limit 字段作用类似于 IPv4 中的 TTL 字段","IPv6 中的 Traffic Class 字段作用类似于 IPv4 中的 ToS 字段"], answer:"B",
  analysis:"IPv6 基本头定长 40 字节，且取消了头部校验和字段；Hop Limit 对应 TTL，Traffic Class 对应 ToS。" },
{ id:"r2022上-32", source:"real", year:2022, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"在 DNS 服务器中，区域的邮件服务器及其优先级由（　）资源记录定义。",
  options:["SOA","NS","PTR","MX"], answer:"D",
  analysis:"MX（邮件交换）记录定义区域的邮件服务器及其优先级。" },
{ id:"r2022上-33", source:"real", year:2022, sem:"上", paper:"上午", point:"操作系统", diff:1,
  stem:"在 Linux 中，可以使用（　）命令创建一个文件目录。",
  options:["mkdir","md","chmod","rmdir"], answer:"A",
  analysis:"mkdir 创建目录；md 是 DOS 命令；chmod 改权限；rmdir 删除目录。" },
{ id:"r2022上-34", source:"real", year:2022, sem:"上", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"在 Windows 中，DHCP 客户端手动更新租期时使用的命令是（　）。",
  options:["ipconfig/release","ipconfig/renew","ipconfig/showclassid","ipconfig/setclassid"], answer:"B",
  analysis:"ipconfig /renew 向 DHCP 服务器重新请求/刷新 IP 地址；/release 为释放地址。" },
{ id:"r2022上-35", source:"real", year:2022, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"Windows Server 2008 R2 上配置（　）服务器前需要先安装 IIS 服务。",
  options:["DHCP","DNS","Web","传真"], answer:"C",
  analysis:"IIS 提供 Web、FTP、SMTP 等服务，配置 Web 服务器需先安装 IIS。" },
{ id:"r2022上-36", source:"real", year:2022, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"客户端用于向 DHCP 服务器请求 IP 地址配置信息的第一个报文是（　）。",
  options:["Dhcpdiscover","Dhcpoffer","Dhcpack","Dhcpnak"], answer:"A",
  analysis:"DHCP 客户端首次以广播发送 Dhcpdiscover 发现报文寻找服务器。" },
{ id:"r2022上-37", source:"real", year:2022, sem:"上", paper:"上午", point:"应用层协议", diff:1,
  stem:"服务器提供 WEB 服务，本地默认监听（　）端口。",
  options:["8008","8080","8800","80"], answer:"D",
  analysis:"HTTP（Web 服务）默认监听 TCP 80 端口。" },
{ id:"r2022上-38", source:"real", year:2022, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"用户在 PC 上安装使用邮件客户端，希望同步客户端和服务器上的操作，需使用的协议是（　）。",
  options:["POP3","IMAP","HTTPS","SMTP"], answer:"B",
  analysis:"IMAP4 在服务器上保留邮件副本并支持多文件夹、多设备同步；POP3 仅下载到本地单文件夹。" },
{ id:"r2022上-39", source:"real", year:2022, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"（　）命令不能获得主机域名（abc.com）对应的 IP 地址。",
  options:["ping abc.com","nslookup -qt=a abc.com","tracert abc.com","route abc.com"], answer:"D",
  analysis:"ping、tracert、nslookup 域名时都会先解析域名得到 IP；route 是路由表查看命令，不做域名解析。" },
{ id:"r2022上-40", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"通过在出口防火墙上配置（　）功能，可以阻止外部未授权用户访问内部网络。",
  options:["ACL","SNAT","入侵检测","防病毒"], answer:"B",
  analysis:"出口做源 NAT（SNAT/PAT）后，内部主机以转换后的公网地址访问外部，外部无法主动向内发起连接，从而阻止未授权访问。" },
{ id:"r2022上-41", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:4,
  stem:"以下 linux 命令中，（　）可以实现允许 IP 为 10.0.0.2 的客户端访问本机 tcp 22 端口。",
  options:["iptables -I INPUT -d 10.0.0.2 -p tcp --sport 22 -j DROP","iptables -I INPUT -s 10.0.0.2 -p tcp --sport 22 -j DROP","iptables -I INPUT -d 10.0.0.2 -p tcp --sport 22 -j ACCEPT","iptables -I INPUT -s 10.0.0.2 -p tcp --sport 22 -j ACCEPT"], answer:"D",
  analysis:"允许源地址为 10.0.0.2 的报文，应使用 -s 指定源地址，且动作设为 ACCEPT。" },
{ id:"r2022上-42", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:5,
  stem:"A 从证书颁发机构 X1 获得证书，B 从证书颁发机构 X2 获得证书。假设使用 X.509 证书，X2《X1》表示 X2 签署的 X1 的证书，A 可以使用证书链来获取 B 的公钥，则该链的正确顺序是（　）。",
  options:["X2《X1》X1《B》","X2《X1》X2《A》","X1《X2》X2《B》","X1《X2》X2《A》"], answer:"C",
  analysis:"A 先在自己的发证机构 X1 验证上级证书 X1《X2》，再到 X2 处取得 B 的证书 X2《B》，从而得到 B 的公钥。" },
{ id:"r2022上-43", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"在我国自主研发的商用密码标准算法中，用于分组加密的是（　）。",
  options:["SM2","SM3","SM4","SM9"], answer:"C",
  analysis:"SM4 是分组对称加密算法；SM2 为公钥算法，SM3 为杂凑算法，SM9 为标识密码算法。" },
{ id:"r2022上-44", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"SQL 注入是常见的 Web 攻击，以下不能够有效防御 SQL 注入的手段是（　）。",
  options:["对用户输入做关键字过滤","部署 Web 应用防火墙进行防护","部署入侵检测系统阻断攻击","定期扫描系统漏洞并及时修复"], answer:"C",
  analysis:"入侵检测系统（IDS）以检测、告警为主，不能实时阻断 SQL 注入；关键字过滤、WAF、漏洞修复均可有效防御。" },
{ id:"r2022上-45", source:"real", year:2022, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"SNMP 管理的网络关键组件不包括（　）。",
  options:["网络管理系统","被管理的设备","代理者","系统管理员"], answer:"D",
  analysis:"SNMP 管理网络由网络管理系统（NMS）、被管设备、代理（Agent）三部分组成，不含系统管理员。" },
{ id:"r2022上-46", source:"real", year:2022, sem:"上", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"在 Windows 系统中通过（　）查看本地 DNS 缓存。",
  options:["ipconfig/all","ipconfig/renew","ipconfig/flushdns","ipconfig/displaydns"], answer:"D",
  analysis:"ipconfig /displaydns 显示本地 DNS 缓存内容；/flushdns 用于清除缓存。" },
{ id:"r2022上-47", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"下面说法中，能够导致 BGP 邻居关系无法建立的是（　）。",
  options:["邻居的 AS 号配置错误","IBGP 邻居没有进行物理直连","在全互联的 IBGP 邻居关系中开启了 BGP 同步","两个 BGP 邻居之间的更新时间不一致"], answer:"A",
  analysis:"BGP 邻居 AS 号配错会导致邻居关系无法建立；IBGP 可非直连、更新时间不一致会协商取较小值、开启同步不影响邻居建立。" },
{ id:"r2022上-48", source:"real", year:2022, sem:"上", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"缺省状态下，SNMP 协议代理进程使用（　）端口向 NMS 发送告警信息。",
  options:["161","162","163","164"], answer:"B",
  analysis:"代理向管理站发送 Trap 告警，目的端口为 162；代理自身监听 161 接收轮询。" },
{ id:"r2022上-49", source:"real", year:2022, sem:"上", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"网络设备发生故障时，会向网络管理系统发送（　）类型的 SNMP 报文。",
  options:["trap","get-response","set-request","get-request"], answer:"A",
  analysis:"被管对象检测到差错时主动向管理站发送 Trap 报文报告事件。" },
{ id:"r2022上-50", source:"real", year:2022, sem:"上", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"能够容纳 200 台客户机的 IP 地址段，其网络位最长是（　）位。",
  options:["21","22","23","24"], answer:"D",
  analysis:"容纳 200 台主机需主机位 8 位（2^8-2=254），对应网络位 32-8=24 位。" },
{ id:"r2022上-51", source:"real", year:2022, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"网管员对 192.168.27.0/24 网段使用 27 位掩码进行了子网划分，下列地址中与 IP 地址 192.168.27.45 处于同一个网络的是（　）。",
  options:["192.168.27.16","192.168.27.35","192.168.27.30","192.168.27.65"], answer:"B",
  analysis:"/27 块大小 32，192.168.27.45 落在 32~63 子网，网络号 192.168.27.32，选项中仅 .35 同在此子网。" },
{ id:"r2022上-52", source:"real", year:2022, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"接题干，对 192.168.27.0/24 使用 27 位掩码划分子网，与 192.168.27.45 同网的子网，其网络号是（　）。",
  options:["192.168.27.0","192.168.27.32","192.168.27.64","192.168.27.128"], answer:"B",
  analysis:"/27 块大小 32，.45 所在子网网络号为 192.168.27.32（范围 .32~.63）。" },
{ id:"r2022上-53", source:"real", year:2022, sem:"上", paper:"上午", point:"IP地址与子网", diff:1,
  stem:"下列 IP 地址中属于私有地址的是（　）。",
  options:["10.10.1.10","172.0.16.248","172.15.32.4","192.186.2.254"], answer:"A",
  analysis:"私有地址段为 10.0.0.0/8、172.16.0.0/12（172.16~172.31）、192.168.0.0/16；仅 10.10.1.10 属于其中。" },
{ id:"r2022上-54", source:"real", year:2022, sem:"上", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"公司要为 900 个终端分配 IP 地址，下面的地址分配方案中，在便于管理的前提下，最节省网络资源的方案是（　）。",
  options:["使用 B 类地址段 172.16.0.0/16","任意分配 4 个 C 类地址段","将 192.168.1.0、192.168.2.0、192.168.3.0、192.168.4.0 进行聚合","将 192.168.32.0、192.168.33.0、192.168.34.0、192.168.35.0 进行聚合"], answer:"D",
  analysis:"900 台需 /22（约 1022 主机）。32~35 聚合为 192.168.32.0/22 恰好满足且无浪费；1~4 聚合为 192.168.1.0/22 与要求的起始不符，且 172.16/16 浪费过大。" },
{ id:"r2022上-55", source:"real", year:2022, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"对命令片段“undo negotiation auto；speed 1000；duplex half”，以下说法正确的是（　）。",
  options:["配置接口默认为全双工模式","配置接口速率默认为1000Kbit/s","配置接口速率自协商","配置接口在非自协商模式下为半双工模式"], answer:"D",
  analysis:"undo negotiation auto 关闭自协商，随后手工指定 speed 1000、duplex half，即非自协商下工作于半双工。" },
{ id:"r2022上-56", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"在 display ip routing-table 输出中，描述路由优先级的字段是（　）。",
  options:["Proto","Pre","Cost","Flags"], answer:"B",
  analysis:"Pre（Preference）字段表示路由协议优先级；Proto 为协议、Cost 为开销、Flags 为标志位。" },
{ id:"r2022上-57", source:"real", year:2022, sem:"上", paper:"上午", point:"网络层与路由", diff:1,
  stem:"显示 OSPF 邻居信息的命令是（　）。",
  options:["display ospf interface","display ospf routing","display ospf peer","display ospf lsdb"], answer:"C",
  analysis:"display ospf peer 用于查看 OSPF 邻居信息。" },
{ id:"r2022上-58", source:"real", year:2022, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以下关于 VLAN 的描述中，不正确的是（　）。",
  options:["VLAN 的主要作用是隔离广播域","不同 VLAN 间须跨三层互通","VLAN ID 可以使用范围为 1～4095","VLAN1 不用创建且不能删除"], answer:"C",
  analysis:"可用 VLAN ID 范围为 1～4094（4095 保留），并非到 4095。" },
{ id:"r2022上-59", source:"real", year:2022, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"使用命令“vlan batch 30 40”和“vlan batch 30 to 40”分别创建的 VLAN 数量是（　）。",
  options:["11 和 2","2 和 2","11 和 11","2 和 11"], answer:"D",
  analysis:"“30 40”创建 VLAN30、VLAN40 共 2 个；“30 to 40”创建 VLAN30~40 共 11 个。" },
{ id:"r2022上-60", source:"real", year:2022, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"命令“policy-vlan mac-address 0-1-1 ip 10.1.1.1 priority 7”划分 VLAN 的方式是（　）。",
  options:["基于策略划分","基于 MAC 划分","基于 IP 子网划分","基于网络层协议划分"], answer:"A",
  analysis:"policy-vlan 组合 MAC、IP 等多个条件，全部匹配才添加 VLAN 标签，属于基于策略（组合条件）划分 VLAN。" },
{ id:"r2022上-61", source:"real", year:2022, sem:"上", paper:"上午", point:"局域网与交换", diff:1,
  stem:"存储转发式交换机中运行生成树协议（STP）可以（　）。",
  options:["向端口连接的各个站点发送请求以便获取其MAC地址","阻塞一部分端口，避免形成环路","找不到目的地址时广播数据帧","通过选举产生多个没有环路的生成树"], answer:"B",
  analysis:"STP 通过阻塞部分冗余端口，将物理有环的网络修剪成无环的树形逻辑拓扑，防止二层环路。" },
{ id:"r2022上-62", source:"real", year:2022, sem:"上", paper:"上午", point:"存储与新技术", diff:2,
  stem:"在 5G 关键技术中，将传统互联网控制平面与数据平面分离，使网络的灵活性、可管理性和可扩展性大幅提升的是（　）。",
  options:["软件定义网络（SDN）","大规模多输入多输出（MIMO）","网络功能虚拟化（NFV）","长期演进（LTE）"], answer:"A",
  analysis:"SDN 的核心思想是控制平面与数据（转发）平面分离，通过标准化接口统一管理转发设备。" },
{ id:"r2022上-63", source:"real", year:2022, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"以下关于二进制指数退避算法的描述中，正确的是（　）。",
  options:["每次站点等待的时间是固定的，即上次的2倍","后一次退避时间一定比前一次长","发生冲突不一定是站点发生了资源抢占","通过扩大退避窗口杜绝了再次冲突"], answer:"C",
  analysis:"退避时间在 [0,2^k-1] 中随机选取，并非固定加倍或一定变长；扩大窗口只是降低而非杜绝再冲突概率；冲突也可能由其他原因引发。" },
{ id:"r2022上-64", source:"real", year:2022, sem:"上", paper:"上午", point:"无线网络", diff:3,
  stem:"某无线路由器，在 2.4GHz 频段上配置了 2 个信道，使用（　）信道间干扰最小。",
  options:["1 和 3","4 和 7","6 和 10","7 和 12"], answer:"D",
  analysis:"2.4GHz 互不重叠信道间隔 5（如 1/6/11）。选项中 7 与 12 间隔 5，重叠最小。" },
{ id:"r2022上-65", source:"real", year:2022, sem:"上", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"以下关于层次化网络设计模型的描述中，不正确的是（　）。",
  options:["终端用户网关通常部署在核心层，实现不同区域间的数据高速转发","流量负载和 VLAN 间路由在汇聚层实现","MAC 地址过滤、路由发现在接入层实现","接入层连接无线 AP 等终端设备"], answer:"A",
  analysis:"终端用户网关通常部署在汇聚层，而非核心层；核心层负责高速无阻塞转发。" },
{ id:"r2022上-66", source:"real", year:2022, sem:"上", paper:"上午", point:"存储与新技术", diff:3,
  stem:"某存储系统规划配置 25 块 8TB 磁盘，创建 2 个 RAID6 组，配置 1 块热备盘，则该存储系统实际存储容量是（　）。",
  options:["200TB","192TB","176TB","160TB"], answer:"D",
  analysis:"去掉 1 块热备盘剩 24 块，分 2 个 RAID6 组各 12 块；RAID6 每组可用 (12-2)×8=80TB，两组共 160TB。" },
{ id:"r2022上-67", source:"real", year:2022, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:1,
  stem:"《中华人民共和国数据安全法》自（　）年 9 月 1 日起施行。",
  options:["2019","2020","2021","2022"], answer:"C",
  analysis:"《数据安全法》2021 年 6 月 10 日通过，自 2021 年 9 月 1 日起施行。" },
{ id:"r2022上-68", source:"real", year:2022, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"以下关于信息化项目成本估算的描述中，不正确的是（　）。",
  options:["项目成本估算指设备采购、劳务支出等直接用于项目建设的经费估算","项目成本估算需考虑项目工期要求的影响，工期要求越短成本越高","项目成本估算需考虑项目质量要求的影响，质量要求越高成本越高","项目成本估算过粗或过细都会影响项目成本"], answer:"A",
  analysis:"项目成本估算不仅含直接成本，还包括间接成本等，并非仅指直接用于建设的经费。" },
{ id:"r2022上-69", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) A network attack is an attempt to gain （　） access to an organization's network, with the objective of stealing data or performing other malicious activities.（网络攻击试图获得对组织网络的何种访问。）",
  options:["unauthorized","authorized","normal","frequent"], answer:"A",
  analysis:"网络攻击试图获得未授权(unauthorized)访问。" },
{ id:"r2022上-70", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) A （　）-of-service (DoS) attack is a cyber-attack that makes a machine or network resource unavailable to its intended users.（拒绝服务攻击，选固定搭配。）",
  options:["defense","denial","detection","decision"], answer:"B",
  analysis:"denial-of-service即DoS（拒绝服务），固定搭配，选denial。" },
{ id:"r2022上-71", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) In the case of a simple attack, a （　） could have a simple rule added to deny all incoming traffic from the attackers, based on protocols, ports, or IP addresses.（可添加规则拒绝攻击者流量的设备。）",
  options:["firewall","router","gateway","switch"], answer:"A",
  analysis:"防火墙(firewall)可按协议、端口或源IP配置规则，拒绝来自攻击者的入站流量。" },
{ id:"r2022上-72", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) In a （　） DoS (DDoS) attack, the incoming traffic flooding the victim originates from many different sources.（DDoS中D的含义。）",
  options:["damaged","descriptive","distributed","demanding"], answer:"C",
  analysis:"DDoS即distributed denial-of-service（分布式拒绝服务），选distributed。" },
{ id:"r2022上-73", source:"real", year:2022, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形) In a DDoS attack, the incoming traffic flooding the victim originates from （　） different sources, making it impossible to stop by blocking a single source.（攻击流量来自多少个源。）",
  options:["two","many","much","ten"], answer:"B",
  analysis:"DDoS流量来自许多(many)不同源；sources为可数名词复数，用many而非much。" }
]);
