/* 真题库 · 2024 下半年 */
/* 来源：B站软考网工学堂《2024年11月网工综合知识参考答案》题干回忆版，答案依据网络原理/标准知识核对 */
/* 说明：跳过 Q13(两主机平均重传次数计算存疑)、Q18(题干开销计算残缺)、Q24/Q45/Q46/Q67(依赖拓扑/截图无法复现) */
REAL_BANK = REAL_BANK.concat([
{ id:"r2024下-01", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形 CND) Computer Network (1) refers to strategies to secure data within a network... (1)应填（　）。",
  options:["Description","Defection","Detection","Defense"], answer:"D",
  analysis:"CND=Computer Network Defense(网络防御)。" },
{ id:"r2024下-02", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形 CND) ...training programs to protect against potential (2). (2)应填（　）。",
  options:["Actions","Access","Operations","Attacks"], answer:"D",
  analysis:"保护系统免受潜在攻击(attacks)。" },
{ id:"r2024下-03", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形 CND) ...security solutions can contribute to CND, including (3), VPNs, access control systems. (3)应填（　）。",
  options:["Firewalls","Gateways","Routers","Switches"], answer:"A",
  analysis:"网络安全方案包括防火墙(firewalls)、VPN、访问控制。" },
{ id:"r2024下-04", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形 CND) CND involves protection, detection, and reaction. (4) provides a foundation for the program. (4)应填（　）。",
  options:["Defense","Protection","Reaction","Detection"], answer:"B",
  analysis:"防护(protection)是整个安全体系的基础底座。" },
{ id:"r2024下-05", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"(英语完形 CND) ...the (5) includes taking immediate steps to stop an incident in progress. (5)应填（　）。",
  options:["Attack","Protection","Detection","Reaction"], answer:"D",
  analysis:"反应(reaction)环节包括立即采取措施阻止正在发生的事件。" },
{ id:"r2024下-06", source:"real", year:2024, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"广播网络中所有路由器运行OSPF，R1、R2接口优先级为0，R3为100，R4为101，则（　）被选举为DR。",
  options:["R2","R3","R4","R1"], answer:"C",
  analysis:"DR选举优先级高者胜，R4优先级101最高，故选R4。" },
{ id:"r2024下-07", source:"real", year:2024, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"(接上题)R1和R2接口优先级为0，其OSPF邻居状态为（　）。",
  options:["2-Way","Full","Init","Exstart"], answer:"A",
  analysis:"优先级为0不参与DR/BDR选举，成为DROTHER，与其他DROTHER保持2-Way状态。" },
{ id:"r2024下-08", source:"real", year:2024, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"下列高速以太网连接技术中，传输距离超过10km的是（　）。",
  options:["1000BASE-CX","1000BASE-ZX","1000BASE-LX","1000BASE-FX"], answer:"B",
  analysis:"1000BASE-ZX用单模长距光模块，可达数十公里；LX约5km，FX约2km。" },
{ id:"r2024下-09", source:"real", year:2024, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"IPv4地址10.10.216.18/20的网络地址是（　）。",
  options:["10.10.216.0","10.10.210.0","10.10.210.32","10.10.208.0"], answer:"D",
  analysis:"/20块大小16，216/16=13.5→13×16=208，网络号10.10.208.0。" },
{ id:"r2024下-10", source:"real", year:2024, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"把一部分磁盘空间充当内存使用，避免程序太大或太多导致内存耗尽，该技术称为（　）。",
  options:["虚拟内存","动态存储","分级存储","高速缓存"], answer:"A",
  analysis:"虚拟内存用磁盘换出页扩展可用逻辑内存。" },
{ id:"r2024下-11", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"RSA加密算法的安全性依赖于（　）问题的困难性。",
  options:["大整数分解","子集合","合数剩余判定","离散对数"], answer:"A",
  analysis:"RSA基于大整数分解难题；离散对数是ECC/Diffie-Hellman。" },
{ id:"r2024下-12", source:"real", year:2024, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中要在指定文件中查找目标文字，可以用（　）命令。",
  options:["grep","find","search","wget"], answer:"A",
  analysis:"grep在文件内容中检索匹配行；find按文件名查找。" },
{ id:"r2024下-13", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"在量子通信领域，为实现信息的绝对安全传输，通常采用（　）。",
  options:["经典电磁波通过光纤传输","纠缠态量子比特通过自由空间传输","量子隐形状态无需物理介质通过量子纠缠","单个光子通过超低损耗单模光纤传输"], answer:"D",
  analysis:"QKD(BB84)用单光子在单模光纤上传输，物理上保证安全。" },
{ id:"r2024下-14", source:"real", year:2024, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"网络信息系统的可靠性测度不包括（　）。",
  options:["完整性","有效性","抗毁性","生存性"], answer:"A",
  analysis:"可靠性三测度为有效性、抗毁性、生存性；完整性属信息安全范畴。" },
{ id:"r2024下-15", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"下列关于交换机堆叠的说法正确的是（　）。",
  options:["Master故障后，Slave中优先级值最大的被选为Master承担控制层面","堆叠就是将多台交换机相互级联","Master和Backup/Slave共同承担数据转发","必须使用专用堆叠卡和堆叠线缆"], answer:"A",
  analysis:"堆叠主设备故障，备用主控(优先级高的Slave)接管控制平面；堆叠非简单级联。" },
{ id:"r2024下-16", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"VLAN技术所依据的协议是（　）。",
  options:["IEEE802.15","IEEE802.3","IEEE802.11","IEEE802.1q"], answer:"D",
  analysis:"VLAN标签由IEEE802.1q定义。" },
{ id:"r2024下-17", source:"real", year:2024, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"下列路由协议使用'基于跳数计算路由算法'的是（　）。",
  options:["OSPF","IS-IS","RIP","OSPFv3"], answer:"C",
  analysis:"RIP以跳数为度量；OSPF/IS-IS用链路开销。" },
{ id:"r2024下-18", source:"real", year:2024, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"下列概念与操作系统并发无关的是（　）。",
  options:["时间片轮转","虚拟存储器","优先级调度","上下文切换"], answer:"B",
  analysis:"虚拟存储器是内存管理技术，与并发无直接关系；时间片轮转/优先级调度/上下文切换均为并发机制。" },
{ id:"r2024下-19", source:"real", year:2024, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"下列存储器类型中，掉电后存储的数据会丢失的是（　）。",
  options:["SDRAM","eMMC","SSD","HDD"], answer:"A",
  analysis:"SDRAM是易失内存，掉电丢失；其余为非易失存储。" },
{ id:"r2024下-20", source:"real", year:2024, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"静态路由的缺点是（　）。",
  options:["不支持IPv6","路由收敛慢","不能灵活适应网络结构变化","必须运行路由协议才能生成路由表"], answer:"C",
  analysis:"静态路由手工配置，拓扑变化时不能自动调整，需人工维护。" },
{ id:"r2024下-21", source:"real", year:2024, sem:"下", paper:"上午", point:"网络体系结构", diff:3,
  stem:"数据链路层采用退N帧(GBN)协议，发送窗口大小为32，则至少需要（　）位序列号。",
  options:["6位","4位","7位","5位"], answer:"A",
  analysis:"GBN窗口≤2^(n-1)，2^(n-1)≥32→n-1≥5→n=6位。" },
{ id:"r2024下-22", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"SW1/SW2配置Eth-Trunk、mode manual load-balance、load-balance src-dst-ip，实现的功能是（　）。",
  options:["配置了跨设备链路聚合实现链路冗余","配置了负载分担模式，两条链路共同承担流量","配置了基于LACP的链路聚合模式","两聚合组编号不一致无法生效"], answer:"B",
  analysis:"manual load-balance为手工负载分担，按src-dst-ip哈希把流量分担到两条成员链路。" },
{ id:"r2024下-23", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"交换机二层环路后可能产生的故障现象不包括（　）。",
  options:["远程管理口无法登录","命令行操作变得卡顿","下联终端访问网络慢或无法访问","接口指示灯由绿灯变为黄灯"], answer:"D",
  analysis:"环路导致广播风暴、CPU高、管理卡顿；接口灯颜色变化不是环路典型现象。" },
{ id:"r2024下-24", source:"real", year:2024, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"将192.168.20.0~23.0中两个C类聚合为不少于400个可用IP的地址段，最节约地址的方案是（　）。",
  options:["聚合21.0、22.0为21.0/23","聚合21.0、23.0为20.0/22","聚合20.0、21.0为20.0/23","聚合20.0、22.0为20.0/22"], answer:"C",
  analysis:"需≥400主机→/23(510可用)；选相邻20.0和21.0聚合为20.0/23最节约。" },
{ id:"r2024下-25", source:"real", year:2024, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"在采用OFDM的5G网络中，调制解调器如何处理多径干扰？（　）。",
  options:["增加发射功率覆盖所有路径","将可用带宽划分为多个正交子载波，每个携带部分数据","使用单一载波并增加带宽","引入时间延迟同步不同路径信号"], answer:"B",
  analysis:"OFDM把信道分成许多正交子载波并行传输，抗多径。" },
{ id:"r2024下-26", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"UTM(统一威胁管理系统)的功能不包括（　）。",
  options:["重要数据加密和备份","恶意软件过滤","访问控制","垃圾邮件拦截"], answer:"A",
  analysis:"UTM集成防火墙、防病毒、反垃圾邮件、Web过滤；数据加密备份不是其功能。" },
{ id:"r2024下-27", source:"real", year:2024, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"统计时分多路复用(STDM)中，某用户帧到达率远高于其他用户，为防止独占信道通常会（　）。",
  options:["确保每个用户至少有一个最小保证时隙","拒绝该用户的帧直到其他用户传完","强制降低该用户传输速率","用缓冲区存储等待帧但不调时隙分配"], answer:"A",
  analysis:"STDM通过为每用户预留最小保证时隙防止个别用户独占信道。" },
{ id:"r2024下-28", source:"real", year:2024, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"电子邮件SMTP传输在（　）的支持下确保内容包括文字、图像等多媒体。",
  options:["MIMD","MIME","HTML","ASCII"], answer:"B",
  analysis:"MIME扩展SMTP支持多媒体邮件内容。" },
{ id:"r2024下-29", source:"real", year:2024, sem:"下", paper:"上午", point:"网络体系结构", diff:2,
  stem:"每个节点都直接连接到相邻两个节点，形成物理或逻辑环的局域网拓扑是（　）。",
  options:["以太网","令牌总线","标签交换","WiFi"], answer:"B",
  analysis:"令牌总线/令牌环按环型拓扑传递令牌。" },
{ id:"r2024下-30", source:"real", year:2024, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"下列IPv6数据报头字段在IPv4报头中无对应功能的是（　）。",
  options:["Payload Length","Traffic Class","Hop Limit","Flow Label"], answer:"D",
  analysis:"Flow Label(流标签)是IPv6新增字段，IPv4无对应。" },
{ id:"r2024下-31", source:"real", year:2024, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"三层接口配置 dhcp select relay / dhcp relay server-ip 192.168.1.253，其作用是（　）。",
  options:["配置192.168.1.253为非信任DHCP服务器","配置DHCP中继","使能全局DHCP并配置服务器IP","三层接口无法转发广播故配置无效"], answer:"B",
  analysis:"dhcp select relay配置DHCP中继，跨网段转发DHCP广播到指定服务器。" },
{ id:"r2024下-32", source:"real", year:2024, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"海明码中信息位长度为7，为纠正单个错误至少需要添加（　）位校验位。",
  options:["7","14","4","3"], answer:"C",
  analysis:"须2^r ≥ 7+r+1，r=3→8<11不满足，r=4→16≥12满足，故4位。" },
{ id:"r2024下-33", source:"real", year:2024, sem:"下", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"路由器执行 management-port isolate enable，其作用是（　）。",
  options:["允许访问路由器管理接口","全局开启管理接口流量抑制","开启管理接口流量统计","限制管理接口和业务接口之间的流量转发"], answer:"D",
  analysis:"management-port isolate隔离管理接口，限制管理口与业务口之间互访流量。" },
{ id:"r2024下-34", source:"real", year:2024, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"IP报文TTL减至0时，路由器将发送ICMP消息（　）。",
  options:["Destination Unreachable","TTL Exceeded","Parameter Problem","Source Quench"], answer:"B",
  analysis:"TTL超时发ICMP Time Exceeded(Type 11)。" },
{ id:"r2024下-35", source:"real", year:2024, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"营业部分配网络号10.10.7.64/26，该网络有（　）个可用IP地址。",
  options:["32","70","62","30"], answer:"C",
  analysis:"/26共64个地址，去掉网络号和广播，可用62个。" },
{ id:"r2024下-36", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下列关于RSTP的说法正确的是（　）。",
  options:["端口处于discarding状态即可转发流量","依靠计时器超时确定根端口和指定端口","采用P/A机制实现快速收敛","优先级数值大的交换机被选为根桥"], answer:"C",
  analysis:"RSTP用Proposal/Agreement快速握手实现快速收敛；discarding不转发，根桥按优先级+MAC最小。" },
{ id:"r2024下-37", source:"real", year:2024, sem:"下", paper:"上午", point:"传输层", diff:2,
  stem:"UDP段可容纳的最大负载是（　）字节。",
  options:["65535","4096","65527","1024"], answer:"C",
  analysis:"UDP总长度字段16位最大65535，减8字节首部得最大负载65527。" },
{ id:"r2024下-38", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下列关于在交换机上配置VLAN的说法正确的是（　）。",
  options:["交换机中VLAN均有对应VLANIF接口","可用VLAN编号范围是0-4096","交换机中所有VLAN均可删除","VLAN数量与物理接口数量无关"], answer:"D",
  analysis:"VLAN是逻辑概念，数量与物理接口数无关；只有三层VLANIF，VLAN1不可删，范围1-4094。" },
{ id:"r2024下-39", source:"real", year:2024, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"WiFi7标准将最大信道带宽扩展到（　）MHz，最大吞吐量超30Gbps。",
  options:["320","240","160","180"], answer:"A",
  analysis:"WiFi7(802.11be)最大信道带宽320MHz。" },
{ id:"r2024下-40", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下列关于VLAN间通信的说法正确的是（　）。",
  options:["不同VLAN可用专用线缆直接连接通信","同交换机相同VLAN间通信必须通过三层","不同VLAN跨交换机通信必须通过三层","同交换机不同VLAN间通信无需VLANIF"], answer:"C",
  analysis:"不同VLAN是不同广播域，跨交换机互访必须经三层(路由器/VLANIF)。" },
{ id:"r2024下-41", source:"real", year:2024, sem:"下", paper:"上午", point:"广域网与接入", diff:3,
  stem:"PON中ONU到OLT上行、OLT到ONU下行的复用方式分别是（　）。",
  options:["广播和FDMA","TDMA和FDMA","广播和FDMA","TDMA和广播"], answer:"D",
  analysis:"PON下行OLT广播给所有ONU，上行ONU用TDMA时分复用共享上行。" },
{ id:"r2024下-42", source:"real", year:2024, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"计算机体系使用总线结构，有助于（　）。",
  options:["减少通信传输线的条数","减少通信传输量","提高通信传输速度","提高通信安全性"], answer:"A",
  analysis:"总线结构用一组公共线路连接各部件，减少传输线数量。" },
{ id:"r2024下-43", source:"real", year:2024, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"为项目过程中可能存在的各类风险制定处理预案，属于（　）。",
  options:["风险管理规划","风险量化","风险监控","风险识别"], answer:"A",
  analysis:"为风险制定应对预案属风险管理规划过程。" },
{ id:"r2024下-44", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"交换机收到一个帧，其目的MAC不在转发表中，交换机将（　）。",
  options:["在输入端口复制该帧","丢弃该帧","洪泛该帧到其它所有端口","在上联端口复制该帧"], answer:"C",
  analysis:"未知单播帧向除入端口外所有端口洪泛。" },
{ id:"r2024下-45", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"下列关于MUX VLAN的说法正确的是（　）。",
  options:["MUX VLAN是三层交换机才支持的功能","隔离型子VLAN仅可与主VLAN通信，且与同VLAN内其他接口无法通信","2个互通型VLAN之间的接口可以相互通信","MUX VLAN是将多个VLAN聚合成一个逻辑VLAN共用网关"], answer:"B",
  analysis:"隔离型(separate)从VLAN只能与主VLAN通信，彼此之间二层隔离。" },
{ id:"r2024下-46", source:"real", year:2024, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"Linux中主机名到IP地址的映射包含在（　）配置文件中。",
  options:["/etc/networks","/etc/hostname","/etc/hosts","/etc/resolv.conf"], answer:"C",
  analysis:"/etc/hosts静态记录主机名到IP映射；resolv.conf配DNS。" },
{ id:"r2024下-47", source:"real", year:2024, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"某IPv4地址所在网络的广播地址是192.168.3.255，该网络地址可能是（　）。",
  options:["192.168.51.0","192.168.0.0","192.168.216.0","192.168.28.0"], answer:"B",
  analysis:"/22网络192.168.0.0~3.255，广播地址恰为192.168.3.255，故网络号192.168.0.0。" },
{ id:"r2024下-48", source:"real", year:2024, sem:"下", paper:"上午", point:"网络体系结构", diff:3,
  stem:"数据链路层采用滑动窗口可靠传输，发生帧丢失时对同步控制的影响是（　）。",
  options:["依赖更高层协议处理帧丢失","同步控制完全失效需重建连接","同步控制不受影响但导致重传和拥塞","通过自动重传请求(ARQ)机制恢复"], answer:"D",
  analysis:"滑动窗口协议通过ARQ(超时/否认重传)恢复丢失帧，保持同步。" },
{ id:"r2024下-49", source:"real", year:2024, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"依《个人信息保护法》，个人信息处理者应主动删除个人信息的情形不包括（　）。",
  options:["处理目的已实现或无法实现","法律、行政法规规定的保护期限未届满","处理者停止提供产品或服务","处理者违反法律法规处理"], answer:"B",
  analysis:"保护期限未届满时不得删除，其余情形应主动删除。" },
{ id:"r2024下-50", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"下列加密算法可以抵抗潜在量子计算攻击的是（　）。",
  options:["AES","RSA","同态加密","格基加密"], answer:"D",
  analysis:"格基加密是后量子密码，可抵抗量子计算攻击；RSA/AES会被Shor/Grover威胁。" },
{ id:"r2024下-51", source:"real", year:2024, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"下列关于SNMP的说法正确的是（　）。",
  options:["可对不同设备统一管理，管理成本低","采用TCP承载保障可靠","v2c在v1基础上重新定义管理框架和安全机制","v3专为IPv6设计不支持IPv4"], answer:"A",
  analysis:"SNMP跨厂商统一网管成本低；基于UDP，v3才增强安全且支持IPv4/IPv6。" },
{ id:"r2024下-52", source:"real", year:2024, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"依《数据安全法》，国家（　）负责统筹协调网络数据安全和相关监管工作。",
  options:["网信部门","工信部门","公安机关","检察机关"], answer:"A",
  analysis:"国家网信部门统筹协调网络数据安全和监管。" },
{ id:"r2024下-53", source:"real", year:2024, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"下列属于BGP路由协议防环措施的是（　）。",
  options:["从EBGP收到的路由不转发给另一EBGP邻居","从IBGP收到路由转发EBGP时修改下一跳","设置最大跳数不超过15","从IBGP收到的路由不转发给另一IBGP邻居"], answer:"D",
  analysis:"BGP水平分割：从IBGP邻居学到的路由不再发给其他IBGP邻居，防AS内环路。" },
{ id:"r2024下-54", source:"real", year:2024, sem:"下", paper:"上午", point:"传输层", diff:3,
  stem:"主机A向B发长度L字节文件，TCP MSS=1460，在序号不重复使用前提下L最大值是（　）。",
  options:["2^16-1","216","2^32","2^32-1"], answer:"C",
  analysis:"TCP序号32位共2^32个，每个字节占一个序号，故最大传输字节数2^32。" },
{ id:"r2024下-55", source:"real", year:2024, sem:"下", paper:"上午", point:"网络体系结构", diff:2,
  stem:"在SDN体系中，OpenFlow协议主要用于（　）。",
  options:["网络设备之间的通信","网络设备远程管理","网络设备配置","网络设备与控制平面之间的通信"], answer:"D",
  analysis:"OpenFlow是控制器(控制平面)与交换机(数据平面)之间的南向协议。" },
{ id:"r2024下-56", source:"real", year:2024, sem:"下", paper:"上午", point:"存储与新技术", diff:3,
  stem:"下列关于光纤FC交换机的说法错误的是（　）。",
  options:["用ZONE划分逻辑通道，不同ZONE设备无法互通","将存储设备、服务器组成光纤通道网络","FC交换机与以太网交换机相同都基于IP协议工作","FC交换机相比以太网交换机低延迟、无损坏传输"], answer:"C",
  analysis:"FC(Fibre Channel)是专用存储网络协议，不基于IP工作，故C错误。" },
{ id:"r2024下-57", source:"real", year:2024, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"RFID技术在物联网中主要实现（　）功能。",
  options:["感知","计算","数据传输","标识"], answer:"D",
  analysis:"RFID通过射频识别为物体提供唯一标识。" },
{ id:"r2024下-58", source:"real", year:2024, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"在NFV环境中，（　）负责执行虚拟化的网络功能。",
  options:["VNF","VNFM","MANO","NFVI"], answer:"A",
  analysis:"VNF(虚拟网络功能)即虚拟化后的网络功能实体；VNFM负责管理，MANO编排，NFVI基础设施。" },
{ id:"r2024下-59", source:"real", year:2024, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"若要为一个域名做IPv6地址映射，需要在DNS中添加（　）记录。",
  options:["A","CNAME","NS","AAAA"], answer:"D",
  analysis:"AAAA记录用于域名到IPv6地址。" },
{ id:"r2024下-60", source:"real", year:2024, sem:"下", paper:"上午", point:"IP地址与子网", diff:1,
  stem:"IPv6中的环回地址是（　）。",
  options:["2001::1","127.0.0.1","FE80::/10","::1"], answer:"D",
  analysis:"IPv6环回地址为::1。" },
{ id:"r2024下-61", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"安全日志显示访问 .../login/...pdf,\*/(55521)，说明该主机受到（　）攻击。",
  options:["SQL注入","DDoS","蠕虫病毒","XSS"], answer:"A",
  analysis:"登录URL中带pdf路径及通配符注入特征，属SQL注入尝试。" },
{ id:"r2024下-62", source:"real", year:2024, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"R1、R2建立EBGP邻居，R1查看R2处于Established状态，该状态含义是（　）。",
  options:["邻居关系已经正常建立","路由不可达","重传定时器超时","在等待TCP三次握手"], answer:"A",
  analysis:"BGP Established表示TCP连接和OPEN协商完成，邻居已正常建立。" },
{ id:"r2024下-63", source:"real", year:2024, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"访问HTTP和HTTPS连接分别使用的端口是（　）。",
  options:["443和80","80和443","80和80","443和443"], answer:"B",
  analysis:"HTTP默认80，HTTPS默认443。" },
{ id:"r2024下-64", source:"real", year:2024, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"为保护WLAN用户隐私、便于用户扫描连接临时组建的无线网络，应开启（　）功能。",
  options:["AP isolation","SNTP","Repeater","SSID隐藏"], answer:"D",
  analysis:"隐藏SSID(不广播信标)增强隐私，用户手动输入SSID连接。" },
{ id:"r2024下-65", source:"real", year:2024, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"在网络工程的需求获取过程中，（　）是关键。",
  options:["设计","沟通","选型","运维"], answer:"B",
  analysis:"需求获取的关键是与用户充分沟通。" },
{ id:"r2024下-66", source:"real", year:2024, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在Windows操作系统中，可以使用（　）命令登录到远程主机进行系统管理。",
  options:["shell","telnet","TTL","SSH"], answer:"B",
  analysis:"telnet是传统远程登录管理命令(23端口)。" },
{ id:"r2024下-67", source:"real", year:2024, sem:"下", paper:"上午", point:"网络体系结构", diff:2,
  stem:"OSI/RM表示层定义的数据压缩、加密等功能在TCP/IP模型中实际由（　）层实现。",
  options:["物理层","应用层","传输层","网络层"], answer:"B",
  analysis:"TCP/IP无表示层，压缩加密等在应用层由应用协议(如HTTPS)实现。" },
{ id:"r2024下-68", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"ARP病毒通过（　）影响网络通信。",
  options:["拦截和篡改IP数据包","SYN泛洪占用带宽导致拥塞","伪造ARP请求或应答欺骗网络中设备","加密网络流量使其无法解析"], answer:"C",
  analysis:"ARP欺骗伪造ARP应答，把网关/目标MAC指向攻击者，实施中间人攻击。" },
{ id:"r2024下-69", source:"real", year:2024, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"数字证书的作用是（　）。",
  options:["隐藏用户私钥","防止用户公钥泄露","保障数据完整性","绑定实体与公钥"], answer:"D",
  analysis:"数字证书由CA签名，把实体身份与其公钥绑定，用于身份鉴别。" },
{ id:"r2024下-70", source:"real", year:2024, sem:"下", paper:"上午", point:"局域网与交换", diff:4,
  stem:"某大型以太网只有两个主机，它们同时发送帧，形成碰撞后按截断二进制指数退避算法进行重传。重传次数记为i，i=1，2，3，……。则一个主机成功发送数据之前的平均重传次数约为（　）。",
  options:["1","4.75","1.64","3.25"], answer:"C",
  analysis:"两主机每次碰撞后从[0,2^i-1]随机选退避时隙，第i次重传概率(1/2)^(i-1)，对成功概率求期望E=Σi·P(第i次成功)≈1.64。" },
{ id:"r2024下-71", source:"real", year:2024, sem:"下", paper:"上午", point:"数据通信基础", diff:5,
  stem:"基于L的最大值，假设运输层、网络层和数据链路层所用的首部开销共66字节，链路的数据率为10Mbit/s，则发送该文件所需的最短时间为（　）。",
  options:["3591.29s","3435.97s","429.49s","448.91s"], answer:"A",
  analysis:"L最大为TCP序号空间2^32字节，MSS=1460字节，每段总长1460+66=1526字节；总比特数÷10Mbps≈3591.29s。" }
]);
