/* 真题库 · 2023 下半年 */
/* 来源：book118《2023下半年软考网工上午题真题与参考答案》为主，CSDN考友版交叉核对1-17 */
/* 说明：2023起机考，本套仅公开1-39题；Q19(EIGRP/路径矢量答案存疑)、Q23(题干残缺)、Q29(拓扑图题)未收录 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2023下-01", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"EIGRP中某路由器收到两条路径：路径1带宽100Mbps、延迟2ms，路径2带宽50Mbps、延迟4ms。EIGRP用带宽和延迟综合度量，最佳路径是（　）。",
  options:["路径1和路径2的平均值","路径2","路径1和路径2的和","路径1"], answer:"D",
  analysis:"EIGRP度量=带宽(最小)+延迟，路径1带宽更大、延迟更小，度量更优，故选路径1。" },
{ id:"r2023下-02", source:"real", year:2023, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"在5G技术中，（　）特性允许多个设备同时连接网络并获得高速数据传输。",
  options:["网络切片","大规模多输入多输出(Massive MIMO)","正交频分多址","波束成形"], answer:"B",
  analysis:"大规模MIMO通过多天线多流，显著提升单小区并发接入用户数和容量。" },
{ id:"r2023下-03", source:"real", year:2023, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"网络系统的维护问题最早应在（　）阶段提出。",
  options:["可行性分析","需求分析","概要设计","系统测试"], answer:"B",
  analysis:"可维护性需求应在需求分析阶段就纳入考虑。" },
{ id:"r2023下-04", source:"real", year:2023, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在Linux系统中，硬盘、U盘等由文件系统管理的设备属于（　）。",
  options:["字符设备","网络设备","虚拟设备","块设备"], answer:"D",
  analysis:"磁盘等以块为单位随机访问，属块设备；字符设备如键盘/串口。" },
{ id:"r2023下-05", source:"real", year:2023, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"关于SNMP，下列说法错误的是（　）。",
  options:["采用轮询机制","可自定义MIB或SMI","代理进程接收信息使用161端口","基于TCP协议"], answer:"D",
  analysis:"SNMP基于UDP(161/162)而非TCP，故D错误。" },
{ id:"r2023下-06", source:"real", year:2023, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"一个进程被唤醒，意味着该进程（　）。",
  options:["占有了CPU","变成了就绪态","优先级最大","资源不可访问"], answer:"B",
  analysis:"唤醒即等待事件完成，进程由阻塞态进入就绪态，等待调度。" },
{ id:"r2023下-07", source:"real", year:2023, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"下列关于HTTP和HTTPS的说法中错误的是（　）。",
  options:["HTTPS响应速度比HTTP更快","HTTPS需要SSL证书","HTTP是明文传输","两者都基于TCP连接"], answer:"A",
  analysis:"HTTPS因加解密握手开销比HTTP更慢，故A错误。" },
{ id:"r2023下-08", source:"real", year:2023, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"基于MD5哈希密码的挑战-响应机制进行身份验证的协议是（　）。",
  options:["NTLM","MS-CHAP","CHAP","PAP"], answer:"C",
  analysis:"CHAP用MD5做挑战-响应；PAP明文传输。" },
{ id:"r2023下-09", source:"real", year:2023, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"DHCP服务器收到客户端DHCPDiscover报文后，使用（　）报文回应。",
  options:["DHCPOffer","DHCPAck","DHCPNak","DHCPRequest"], answer:"A",
  analysis:"DHCPDiscover→服务器回DHCPOffer提供IP。" },
{ id:"r2023下-10", source:"real", year:2023, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"当一封电子邮件发送失败时，（　）。",
  options:["邮件系统删除邮件并返回无法送达原因","邮件系统一直投递直至送达","退回邮件但不给出无法送达原因","退回邮件并给出无法送达的原因"], answer:"D",
  analysis:"发送失败时系统退信并在DSN中给出无法送达原因。" },
{ id:"r2023下-11", source:"real", year:2023, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"下列关于FAT AP无线组网的说法中错误的是（　）。",
  options:["组网成本较低","FAT AP可为终端提供DHCP服务","FAT AP可提供跨AP的L3漫游","适合家庭或小规模网络"], answer:"C",
  analysis:"FAT AP独立工作，无法提供跨AP的L3漫游(需FIT AP+AC)；成本低适合小网。" },
{ id:"r2023下-12", source:"real", year:2023, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下列关于VLAN分割网络的说法中，错误的是（　）。",
  options:["抑制广播","物理隔离","设计具有灵活性","简化网络管理"], answer:"B",
  analysis:"VLAN是逻辑隔离而非物理隔离，故B错误。" },
{ id:"r2023下-13", source:"real", year:2023, sem:"下", paper:"上午", point:"广域网与接入", diff:1,
  stem:"PON系统组成包括光线路终端(OLT)、光分配网络(ODN)和（　）三大部分。",
  options:["OBD","ONU","OTN","ODF"], answer:"B",
  analysis:"PON三要素：OLT、ODN、ONU(光网络单元)。" },
{ id:"r2023下-14", source:"real", year:2023, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"可以使用（　）命令显示Linux系统当前用户的工作目录。",
  options:["#rd","#where","#pwd","#md"], answer:"C",
  analysis:"pwd打印当前工作目录。" },
{ id:"r2023下-15", source:"real", year:2023, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"分布式存储系统规划时至少要设计（　）个节点。",
  options:["5","4","3","2"], answer:"C",
  analysis:"分布式存储为保证副本高可用，至少3个节点(可容忍1节点故障)。" },
{ id:"r2023下-16", source:"real", year:2023, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"当计算机突然断电时，（　）中存储的信息会丢失。",
  options:["光盘","ROM","RAM","硬盘"], answer:"C",
  analysis:"RAM易失，断电丢失；ROM/硬盘/光盘非易失。" },
{ id:"r2023下-17", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"Ping命令中TTL(Time to Live)字段用于（　）。",
  options:["测量网络延迟","识别主机操作系统类型","控制数据包的生存时间","检测网络环路"], answer:"C",
  analysis:"TTL每经一路由器减1，减为0丢弃，控制报文生存时间防环路。" },
{ id:"r2023下-18", source:"real", year:2023, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"根据Kerckhoffs原则，密码系统的安全性主要依赖于（　）。",
  options:["解密算法","通信双方","加密算法","密钥"], answer:"D",
  analysis:"Kerckhoffs原则：即使算法公开，只要密钥保密系统仍安全，安全性依赖密钥。" },
{ id:"r2023下-19", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"可以显示当前TCP/IP网络连接情况和有关统计信息的指令是（　）。",
  options:["ipconfig","tracert","ping","netstat"], answer:"D",
  analysis:"netstat显示网络连接、端口和统计信息。" },
{ id:"r2023下-20", source:"real", year:2023, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"结构化综合布线中，工作区子系统的信息插座应距离地面（　）。",
  options:["5cm","30cm","15cm","60cm"], answer:"B",
  analysis:"工作区信息插座距地面约30cm(规范高度)。" },
{ id:"r2023下-21", source:"real", year:2023, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"下列能够有效减少SQL注入攻击对Web应用威胁的操作是（　）。",
  options:["对数据库进行加密","定期备份数据库","启用WAF","将数据库和Web服务器分离部署"], answer:"C",
  analysis:"WAF专门检测阻断SQL注入等Web应用层攻击。" },
{ id:"r2023下-22", source:"real", year:2023, sem:"下", paper:"上午", point:"无线网络", diff:1,
  stem:"802.11规定AP需周期性发送包含SSID和MAC地址的帧是（　）。",
  options:["控制帧","数据帧","响应帧","信标帧"], answer:"D",
  analysis:"AP周期性发送Beacon(信标帧)广播SSID和能力信息。" },
{ id:"r2023下-23", source:"real", year:2023, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"在交换机上执行 undo mac-address blackhole 命令，其作用是（　）。",
  options:["删除配置的黑洞MAC地址表项","为用户接口配置端口安全","禁止用户接口透传VLAN","关闭接口MAC学习功能"], answer:"A",
  analysis:"undo mac-address blackhole 删除黑洞MAC表项。" },
{ id:"r2023下-24", source:"real", year:2023, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"进程有就绪态、运行态、阻塞态，其中（　）的变化不可能直接发生。",
  options:["就绪态到运行态","阻塞态到就绪态","运行态到阻塞态","阻塞态到运行态"], answer:"D",
  analysis:"阻塞态进程必须先经就绪态再被调度运行，不能直接到运行态。" },
{ id:"r2023下-25", source:"real", year:2023, sem:"下", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"某主机无法访问网站，ping显示'Reply from ...: Destination net unreachable'，可能原因是（　）。",
  options:["该主机IP地址配置错误","该主机网关配置错误","该主机的连接请求被拦截","该主机DNS配置错误"], answer:"C",
  analysis:"返回'Destination net unreachable'且本机即回，通常是本机防火墙/安全软件拦截了出站请求。" },
{ id:"r2023下-26", source:"real", year:2023, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"下列关于telnet的描述错误的是（　）。",
  options:["telnet默认端口是23","访问远端设备时本地防火墙入站规则要允许telnet访问","必须知道远程主机的IP或域名","本地计算机要有telnet客户端程序"], answer:"B",
  analysis:"访问远端设备时应放行本地出站规则；'本地入站规则要允许telnet'描述错误。" },
{ id:"r2023下-27", source:"real", year:2023, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"项目管理的三重约束不包括（　）。",
  options:["项目时间约束","项目范围约束","项目收益约束","项目成本约束"], answer:"C",
  analysis:"项目三重约束是范围、时间、成本；收益约束不属于。" },
{ id:"r2023下-28", source:"real", year:2023, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"某主机从DHCP服务器自动获取到IP为169.254.x.x，可能原因是（　）。",
  options:["区域内有多台DHCP服务器","DHCP服务器分配的保留IP","该网段内的DHCP服务器不工作","DHCP服务器地址池设置错误"], answer:"C",
  analysis:"169.254.x.x是APIPA自动私有地址，说明DHCP服务器不工作/无响应。" },
{ id:"r2023下-29", source:"real", year:2023, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"CSMA/CD中往返时延100微秒，若发生碰撞，设备需在不超过（　）时间内检测到碰撞。",
  options:["150微秒","50微秒","200微秒","100微秒"], answer:"B",
  analysis:"依考友版答案，碰撞检测窗口取往返时延一半(50μs)内即可检测。" },
{ id:"r2023下-30", source:"real", year:2023, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"DNS是互联网最常见的流量调度方式，其本质是使用（　）资源记录实现的。",
  options:["A","CNAME","AAAA","PTR"], answer:"A",
  analysis:"DNS轮询负载均衡通过为同一域名配置多条A记录实现。" },
{ id:"r2023下-31", source:"real", year:2023, sem:"下", paper:"上午", point:"网络体系结构", diff:2,
  stem:"（　）技术可实现两层VLAN标签封装，即内部标签和外部标签。",
  options:["VxLAN","Untag VLAN","VLAN-TAG","QinQ"], answer:"D",
  analysis:"QinQ(802.1ad)打两层VLAN标签(S-TAG/C-TAG)；VxLAN是MAC-in-UDP隧道。" },
{ id:"r2023下-32", source:"real", year:2023, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"国密SSL数字证书所采用的签名算法是（　）。",
  options:["RSA","ECC","SM3","SM3WithSM2"], answer:"D",
  analysis:"国密SSL证书用SM2签名、SM3摘要，即SM3WithSM2。" },
{ id:"r2023下-33", source:"real", year:2023, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"可以使用（　）命令在Linux系统中更改一个文件的权限设置。",
  options:["attrib","change","chmod","file"], answer:"C",
  analysis:"chmod修改文件权限。" },
{ id:"r2023下-34", source:"real", year:2023, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"SNMP协议中，用于向管理站发送紧急告警消息的是（　）。",
  options:["TRAP","GET-RESPONSE","GET-REQUEST","INFORM"], answer:"A",
  analysis:"Trap是代理主动向管理站上报的紧急告警。" },
{ id:"r2023下-35", source:"real", year:2023, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"在CPU和主存之间设计Cache的目的是（　）。",
  options:["增大主存带宽","扩大主存容量","提升CPU访问主存的效率","提升DMA访问主存效率"], answer:"C",
  analysis:"Cache缓解CPU与主存速度差，提升CPU访存效率。" },
{ id:"r2023下-36", source:"real", year:2023, sem:"下", paper:"上午", point:"网络规划与布线", diff:1,
  stem:"在双绞线中STP和UTP分别代表（　）。",
  options:["非屏蔽双绞线和屏蔽双绞线","铠装线缆和非铠装线缆","屏蔽双绞线和非屏蔽双绞线","3类线和5类线"], answer:"C",
  analysis:"STP=屏蔽双绞线(Shielded Twisted Pair)，UTP=非屏蔽双绞线(Unshielded Twisted Pair)。" },
{ id:"r2023下-37", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"（　）使用了与 BGP 协议类似的路径矢量算法来选择最佳路径。",
  options:["OSPF 最短路径优先","IS-IS 中间系统到中间系统","RIP 路由信息协议","EIGRP 增强型内部网关路由协议"], answer:"D",
  analysis:"EIGRP 采用 DUAL 算法，属路径矢量（距离矢量增强）；BGP 为路径矢量，RIP 为距离矢量，OSPF/IS-IS 为链路状态。" },
{ id:"r2023下-38", source:"real", year:2023, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"下列 IP 地址中，属于网络号（主机位全 0）的是（　）。",
  options:["192.16.10.126/26","10.0.2.160/24","172.16.26.0/23","192.168.5.128/22"], answer:"C",
  analysis:"172.16.26.0/23 块大小 2，第三字节偶数为网段起点，26.0 为主机位全 0 的网络号；其余均为主机地址。" },
{ id:"r2023下-39", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:4,
  stem:"某网络中 4 台路由器通过四条以太网网段（10.0.1.0/24、10.0.2.0/24、10.0.4.0/24、10.0.3.0/24）互连，所有接口均运行 OSPF，则整个网络中选举（　）个 DR。",
  options:["4","2","3","1"], answer:"A",
  analysis:"每条广播型以太网网段都独立选举一个 DR，共 4 个网段，故选举 4 个 DR。" },
{ id:"r2023下-40", source:"real", year:2023, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"关于 VLAN 说法错误的是（　）。",
  options:["按连接交换机设备的 MAC 地址定义 VLAN 成员是一种动态 VLAN","VLAN 的划分不受用户所在物理位置和物理网段的限制","VLAN 以交换式网络为基础","在 VLAN ID 标准范围内，可用于 Ethernet 的 VLAN ID 为 10~1000"], answer:"D",
  analysis:"802.1q 的 VLAN ID 可用范围是 1~4094，并非 10~1000。" },
{ id:"r2023下-41", source:"real", year:2023, sem:"下", paper:"上午", point:"数据通信基础", diff:1,
  stem:"常用光功率的单位为（　）。",
  options:["mw","dBm","dB","dBu"], answer:"B",
  analysis:"光功率常用 dBm（分贝毫瓦）；dB 为相对比值，mw 为瓦数但光工程以 dBm 计。" },
{ id:"r2023下-42", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"在 RIP 路由协议中，当路由跳数达到（　）时，目的地被标记为路由不可达。",
  options:["16","14","15","13"], answer:"A",
  analysis:"RIP 最大有效跳数为 15，跳数等于 16 即标记为不可达。" },
{ id:"r2023下-43", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"RIP 在更新维护路由时，若老化时间内未收到邻居更新报文即认为该路由不可达，使用的是（　）定时器。",
  options:["垃圾收集定时器 Garbage-collect","抑制定时器 Suppress","老化定时器 Age","更新定时器 Update"], answer:"C",
  analysis:"Age（Invalid）老化定时器超时即标记路由不可达；Update 周期发送，Garbage-collect 负责删除，Suppress 防环。" },
{ id:"r2023下-44", source:"real", year:2023, sem:"下", paper:"上午", point:"网络体系结构", diff:1,
  stem:"（　）不属于数据链路层的功能。",
  options:["路由选择","帧同步","差错检测","建立连接"], answer:"A",
  analysis:"路由选择是网络层功能；数据链路层负责成帧、帧同步、差错检测与链路连接建立。" },
{ id:"r2023下-45", source:"real", year:2023, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"电子邮件所使用的 SMTP 协议的默认端口为（　）。",
  options:["21","25","53","23"], answer:"B",
  analysis:"SMTP 默认 TCP 25；21 为 FTP，53 为 DNS，23 为 Telnet。" },
{ id:"r2023下-46", source:"real", year:2023, sem:"下", paper:"上午", point:"传输层", diff:4,
  stem:"某 TCP 连接拥塞窗口为 4000 字节，发生丢包进入快恢复时，拥塞窗口新值为（　）。",
  options:["2000 字节","1800 字节","2100 字节","1900 字节"], answer:"A",
  analysis:"快恢复时 ssthresh=cwnd/2，新 cwnd 设为 ssthresh=4000/2=2000 字节。" },
{ id:"r2023下-47", source:"real", year:2023, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"在交换机上执行 display stp topology-change 命令，其作用是（　）。",
  options:["查看端口 TC/TCN 报文收发计数","查看桥的生成树状态详细信息","查看运行生成树协议的异常端口信息","查看 MSTP 拓扑变化相关的统计信息"], answer:"D",
  analysis:"display stp topology-change 查看 MSTP 拓扑变化（TC/TCN）相关统计信息。" },
{ id:"r2023下-48", source:"real", year:2023, sem:"下", paper:"上午", point:"数据通信基础", diff:1,
  stem:"16-QAM 调制可以在每个符号上传输（　）个比特。",
  options:["4","2","16","8"], answer:"A",
  analysis:"log2(16)=4，每个 16-QAM 符号携带 4 bit。" },
{ id:"r2023下-49", source:"real", year:2023, sem:"下", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"下列关于网络冗余设计的说法中正确的是（　）。",
  options:["主备切换应由管理员手动切换并尽量缩短切换时间","备用路径冗余方案可有效提高网络性能","VRRP 主备链路可实现多链路流量负载分担","网络虚拟化可以实现网络冗余"], answer:"D",
  analysis:"冗余应自动切换；备用路径平时不工作不提升性能；单组 VRRP 主备不负载分担；网络虚拟化可实现设备冗余。" },
{ id:"r2023下-50", source:"real", year:2023, sem:"下", paper:"上午", point:"IP地址与子网", diff:2,
  stem:"在 IPv6 地址中，全球单播地址的前缀是（　）。",
  options:["FE00::/12","FE::/10","2000::/3","FFFF::/10"], answer:"C",
  analysis:"IPv6 全球单播地址前缀为 2000::/3；FE80::/10 为链路本地地址。" },
{ id:"r2023下-51", source:"real", year:2023, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"以下调制方式中，调制效率最高的是（　）。",
  options:["16-QAM","BPSK","QPSK","64-QAM"], answer:"D",
  analysis:"BPSK=1bit、QPSK=2bit、16-QAM=4bit、64-QAM=6bit/符号，64-QAM 效率最高。" },
{ id:"r2023下-52", source:"real", year:2023, sem:"下", paper:"上午", point:"无线网络", diff:3,
  stem:"下列关于 WEP 无线加密技术的说法中，错误的是（　）。",
  options:["WEP 密钥最长为 128 位","WEP 使用 RC4 加密算法","WEP 密钥由初始向量+用户指定字符串+校验值组成","WEP 的初始向量在特定情况下可能出现重复值"], answer:"A",
  analysis:"WEP 用户密钥有效最长为 104 位（加 24 位 IV 后对外称 128 位），并非 128 位密钥；IV 仅 24 位会重复。" },
{ id:"r2023下-53", source:"real", year:2023, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"下列关于网络安全等级保护的说法中，错误的是（　）。",
  options:["信息系统定级时需明确定级备案的责任部门和责任人","信息系统在规划设计阶段就需要定级","二级以上（含二级）定级后需到公安机关备案","一级至五级定级时均需安全专家对定级结果进行论证和审定"], answer:"D",
  analysis:"三级及以上系统才需专家评审论证，并非一至五级全部都要。" },
{ id:"r2023下-54", source:"real", year:2023, sem:"下", paper:"上午", point:"网络体系结构", diff:1,
  stem:"在 OSI 模型中，TCP 协议对应的是（　）。",
  options:["物理层","数据链路层","传输层","网络层"], answer:"C",
  analysis:"TCP/UDP 工作在传输层；IP 工作在网络层。" },
{ id:"r2023下-55", source:"real", year:2023, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"某园区网用户无法访问 202.145.12.35，在 Windows 平台下可用（　）命令判断故障是否在园区网内部。",
  options:["netstat 202.145.12.35","arp 202.145.12.35","ping 202.145.12.35","tracert 202.145.12.35"], answer:"D",
  analysis:"tracert 逐跳路由跟踪，可定位中断发生在哪一跳，从而判断故障在内网还是外网。" },
{ id:"r2023下-56", source:"real", year:2023, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"网络管理工作站通过 SNMP 管理设备，当被管设备发生故障时，工作站将会收到（　）报文。",
  options:["Set-Request","Trap","Get-Request","Get-Response"], answer:"B",
  analysis:"设备故障时代理主动向管理站发送 Trap 报文上报告警。" },
{ id:"r2023下-57", source:"real", year:2023, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"计算机的三大总线不包括（　）。",
  options:["数据总线","通信总线","地址总线","控制总线"], answer:"B",
  analysis:"CPU 三大总线为数据总线、地址总线、控制总线；通信总线不属于内部三大总线。" },
{ id:"r2023下-58", source:"real", year:2023, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"STP 协议中，（　）机制用于决定每个网段上的指定端口（Designated Port）。",
  options:["根路径成本 Root Path Cost","端口优先级 Port Priority","根桥标识 Root Bridge ID","桥优先级 Bridge Priority"], answer:"A",
  analysis:"网段上比较各网桥到根桥的根路径成本（RPC），RPC 最小者的端口为该网段指定端口。" },
{ id:"r2023下-59", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"在 BGP 协议中，路由决策过程的最后一个步骤是（　）。",
  options:["路径属性修改","路由策略应用","路由信息发布","路径属性筛选"], answer:"C",
  analysis:"BGP 选路流程为接收→策略过滤/属性修改/筛选，最后把优选路由对外发布。" },
{ id:"r2023下-60", source:"real", year:2023, sem:"下", paper:"上午", point:"广域网与接入", diff:3,
  stem:"下列光纤接入技术中，没有采用 TDMA（时分多址）来实现上行信号传输的是（　）。",
  options:["GPON","EPON","XG-PON","WDM-PON"], answer:"D",
  analysis:"GPON/EPON/XG-PON 上行均用 TDMA；WDM-PON 各 ONU 使用不同波长（波分），不采用 TDMA。" },
{ id:"r2023下-61", source:"real", year:2023, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"《中华人民共和国数据安全法》适用于在（　）开展数据处理活动及其安全监管。",
  options:["我国境内及境外","我国境外","我国境内","我国境内的局部地区"], answer:"C",
  analysis:"《数据安全法》适用于在我国境内开展的数据处理活动及其安全监管。" },
{ id:"r2023下-62", source:"real", year:2023, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"在 Windows 系统中，DNS 所使用的端口号是（　）。",
  options:["25","65","35","53"], answer:"D",
  analysis:"DNS 使用 UDP/TCP 53 端口。" },
{ id:"r2023下-63", source:"real", year:2023, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"下列关于《个人信息保护法》的描述中，不正确的是（　）。",
  options:["处理个人信息应遵循合法、正当、必要和诚信原则","个人一旦同意他人处理其个人信息，就无权再反悔","任何组织、个人不得非法收集、使用、加工、传输他人个人信息","为公共利益实施新闻报道，可在合理范围内不经个人同意处理信息"], answer:"B",
  analysis:"个人信息主体有权撤回同意，并非一旦同意即不能反悔。" },
{ id:"r2023下-64", source:"real", year:2023, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"SDN 完形：Software-defined networking (SDN) technology is an approach to (　) management that enables dynamic, programatically efficient network configuration.",
  options:["resource","device","memory","network"], answer:"D",
  analysis:"SDN 是一种网络（network）管理方式，可动态、可编程地配置网络。" },
{ id:"r2023下-65", source:"real", year:2023, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"SDN 完形：...in a manner more akin to (　) computing than to traditional network management.",
  options:["parallel","grid","distributed","cloud"], answer:"D",
  analysis:"SDN 的管理模式更类似于云（cloud）计算。" },
{ id:"r2023下-66", source:"real", year:2023, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"SDN 完形：...enabling the network control to become directly (　) and the underlying infrastructure to be abstracted from applications.",
  options:["configurable","programmable","transformable","adaptable"], answer:"B",
  analysis:"SDN 将控制与转发分离，使控制平面直接可编程（programmable）。" },
{ id:"r2023下-67", source:"real", year:2023, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"SDN 完形：SDN was commonly associated with the (　) protocol since the protocol's emergence in 2011.",
  options:["OpenFlow","OpenVPN","OpenNet","OpenAI"], answer:"A",
  analysis:"SDN 标志性协议是 2011 年出现的 OpenFlow。" },
{ id:"r2023下-68", source:"real", year:2023, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"SDN 完形：When using SDN for multimedia traffic, an important aspect is the (　) of Experience (QoE) estimation.",
  options:["Quality","Query","Queue","Quantity"], answer:"A",
  analysis:"QoE 即 Quality of Experience（体验质量）。" },
{ id:"r2023下-69", source:"real", year:2023, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"对 IPv4 地址段 192.168.10.0/24 划分子网，要求每个子网至少 50 个可用 IP 地址，其主机位数最少需要（　）位。",
  options:["7","5","8","6"], answer:"D",
  analysis:"2^h-2≥50 得 h≥6，故最少 6 位主机位，子网掩码 255.255.255.192（/26）。" },
{ id:"r2023下-70", source:"real", year:2023, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"接上题，192.168.10.0/24 按每子网至少 50 主机位划分后，（　）属于所划分子网的网络号。",
  options:["192.168.10.32","192.168.10.0","192.168.10.160","192.168.10.96"], answer:"B",
  analysis:"/26 块大小 64，子网网络号为 0、64、128、192；选项中 192.168.10.0 是第一个子网网络号。" },
{ id:"r2023下-71", source:"real", year:2023, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"网络地址范围 172.24.0.0~172.24.7.0 可以聚合为（　）。",
  options:["172.24.0.0/21","172.24.0.0/24","172.24.0.0/20","172.24.0.0/16"], answer:"A",
  analysis:"共 8 个 C 类（0~7），块大小 8，聚合为 172.24.0.0/21。" },
{ id:"r2023下-72", source:"real", year:2023, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"接上题，聚合后的 172.24.0.0/21 网络中共有（　）个可用主机地址。",
  options:["2048","2056","2032","2046"], answer:"D",
  analysis:"/21 共 2^11=2048 个地址，减去网络号和广播地址，可用主机 2046 个。" }
]);
