/* 真题库 · 2021 下半年（11月） */
REAL_BANK = REAL_BANK.concat([
{ id:"r2021下-01", source:"real", year:2021, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"微机系统中，（　）不属于 CPU 的运算器组成部件。",
  options:["程序计数器","累加寄存器","多路转换器","ALU 单元"], answer:"A",
  analysis:"程序计数器 PC 用于对下一条指令寻址，属于控制器；累加寄存器、多路转换器、ALU 均属运算器。" },
{ id:"r2021下-02", source:"real", year:2021, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"Python 语言的特点不包括（　）。",
  options:["跨平台、开源","编译型","支持面向对象程序设计","动态编程"], answer:"B",
  analysis:"Python 是解释型、动态语言，跨平台开源并支持面向对象；需先编译后运行不是其特点。" },
{ id:"r2021下-03", source:"real", year:2021, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"软件测试时，白盒测试不能发现（　）。",
  options:["代码路径中的错误","死循环","逻辑错误","功能错误"], answer:"D",
  analysis:"白盒测试依据程序内部逻辑设计用例，可发现代码路径、死循环、逻辑错误；功能是否符合需求由黑盒测试发现。" },
{ id:"r2021下-04", source:"real", year:2021, sem:"下", paper:"上午", point:"存储与新技术", diff:1,
  stem:"云计算有多种部署模型，当云按照服务方式提供给大众时，称为（　）。",
  options:["公有云","私有云","专属云","混合云"], answer:"A",
  analysis:"公有云面向公众/大众提供服务；私有云面向单个组织，混合云为二者组合。" },
{ id:"r2021下-05", source:"real", year:2021, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:3,
  stem:"某工厂使用一个软件系统使质检过程自动化，并逐步替代人工质检。该系统属于（　）。",
  options:["面向作业处理的系统","面向管理控制的系统","面向决策计划的系统","面向数据汇总的系统"], answer:"B",
  analysis:"面向作业处理即作业自动化；质检自动化并替代人工属于管理控制层面的自动化，即面向管理控制的系统。" },
{ id:"r2021下-06", source:"real", year:2021, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"外包是一种合同协议。外包合同中的关键核心文件是（　）。",
  options:["技术等级协议（TLA）","服务等级协议（SLA）","项目执行协议（PEA）","企业管理协议（EMA）"], answer:"B",
  analysis:"外包合同的关键核心文件是服务等级协议 SLA，约定服务质量与级别。" },
{ id:"r2021下-07", source:"real", year:2021, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:3,
  stem:"数据标准化的对象是数据元素和元数据。以下①～⑥中，（　）属于数据标准化主要包括的三个阶段。①数据元素标准阶段 ②元数据标准阶段 ③业务建模阶段 ④软件安装部署阶段 ⑤数据规范化阶段 ⑥文档规范化阶段",
  options:["①②③","③⑤⑥","④⑤⑥","①③⑤"], answer:"B",
  analysis:"数据标准化三阶段为业务建模阶段、数据规范化阶段、文档规范化阶段，即③⑤⑥。" },
{ id:"r2021下-08", source:"real", year:2021, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"在软件开发过程中，系统测试阶段的测试目标来自于（　）阶段。",
  options:["需求分析","概要设计","详细设计","软件实现"], answer:"A",
  analysis:"系统测试以验证系统是否满足需求为目标，其测试目标来源于需求分析阶段。" },
{ id:"r2021下-09", source:"real", year:2021, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"信息系统的文档是开发人员与用户交流的工具。在系统规划和系统分析阶段，用户与系统分析人员交流所使用的文档不包括（　）。",
  options:["可行性研究报告","总体规划报告","项目开发计划","用户使用手册"], answer:"D",
  analysis:"系统规划/分析阶段软件尚未开发，用户使用手册是系统交付后才编写的文档。" },
{ id:"r2021下-10", source:"real", year:2021, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"（　）是构成我国保护计算机软件著作权的两个基本法律文件。",
  options:["《计算机软件保护条例》和《软件法》","《中华人民共和国著作权法》和《软件法》","《中华人民共和国著作权法》和《计算机软件保护条例》","《中华人民共和国版权法》和《中华人民共和国著作权法》"], answer:"C",
  analysis:"《中华人民共和国著作权法》与《计算机软件保护条例》是保护软件著作权的两个基本法律文件。" },
{ id:"r2021下-11", source:"real", year:2021, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"在光纤通信中，（　）设备可以将光信号放大进行远距离传输。",
  options:["光纤中继器","光纤耦合器","光发信机","光检测器"], answer:"A",
  analysis:"光纤中继器对光信号进行补偿放大以延长传输距离；耦合器用于分路/合路，发信机/检测器实现光电转换。" },
{ id:"r2021下-12", source:"real", year:2021, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"在 10GBase-ER 标准中，使用单模光纤最大传输距离是（　）。",
  options:["300 米","5 公里","10 公里","40 公里"], answer:"D",
  analysis:"10GBase-ER（超长距）采用 1550nm 单模光纤，最大传输距离约 40 公里；LR 为 10 公里。" },
{ id:"r2021下-13", source:"real", year:2021, sem:"下", paper:"上午", point:"网络体系结构", diff:1,
  stem:"在 OSI 参考模型中，传输层处理的数据单位是（　）。",
  options:["比特","帧","分组","报文"], answer:"D",
  analysis:"传输层数据单元为报文/段（Segment）；网络层为分组，数据链路层为帧，物理层为比特。" },
{ id:"r2021下-14", source:"real", year:2021, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"某信道采用 4 幅度 8 相位调制，最大可以组成（　）种码元。",
  options:["5","10","16","32"], answer:"D",
  analysis:"4 种幅度与 8 种相位组合，码元种类=4×8=32 种。" },
{ id:"r2021下-15", source:"real", year:2021, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"接题干，若此信道信号的码元宽度为 10 微秒，则数据速率为（　）kb/s。",
  options:["50","100","500","1000"], answer:"C",
  analysis:"波特率=1/10μs=100000 波特，每位信息量 log2(32)=5，数据速率=100000×5=500kb/s。" },
{ id:"r2021下-16", source:"real", year:2021, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"使用 ADSL 接入电话网采用的认证协议是（　）。",
  options:["802.1x","802.5","PPPoA","PPPoE"], answer:"D",
  analysis:"ADSL 通常采用 PPPoE（以太网上的点对点协议）进行拨号认证接入。" },
{ id:"r2021下-17", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"在主机上禁止（　）协议，可以不响应来自别的主机的 Ping 包。",
  options:["UDP","ICMP","TLS","ARP"], answer:"B",
  analysis:"Ping 基于 ICMP，禁止 ICMP 后主机即不响应别人的 Echo 请求。" },
{ id:"r2021下-18", source:"real", year:2021, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"HDLC 协议中，帧的编号和应答号存放在（　）字段中。",
  options:["标志","地址","控制","数据"], answer:"C",
  analysis:"HDLC 控制字段承载 N(S) 发送帧序号与 N(R) 应答序号。" },
{ id:"r2021下-19", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"在 OSPF 路由协议中，路由器在（　）进行链路状态广播。",
  options:["固定30秒后周期性地","固定60秒后周期性地","收到对端请求后","链路状态发生改变后"], answer:"D",
  analysis:"OSPF 是链路状态协议，当链路状态发生变化时才洪泛 LSA，而非周期性固定广播。" },
{ id:"r2021下-20", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"ARP 报文分为 ARP Request 和 ARP Response，其中 ARP Request 采用（　）进行传送。",
  options:["广播","组播","多播","单播"], answer:"A",
  analysis:"ARP 请求在局域网内广播发送，以询问目标 IP 对应的 MAC。" },
{ id:"r2021下-21", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"接题干，ARP Response 采用（　）进行传送。",
  options:["广播","组播","多播","单播"], answer:"D",
  analysis:"只有目标主机识别到被请求，单独以单播方式回应请求者。" },
{ id:"r2021下-22", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"Ping 使用了（　）类型的 ICMP 查询报文。",
  options:["Echo Reply","Host Unreachable","Redirect for Host","Source Quench"], answer:"A",
  analysis:"Ping 基于 ICMP Echo（Echo Request/Echo Reply）查询报文；其余选项为差错或控制报文。" },
{ id:"r2021下-23", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于路由协议的叙述中，错误的是（　）。",
  options:["路由协议是通过执行一个算法来完成路由选择的一种协议","动态路由协议可以分为距离向量路由协议和链路状态路由协议","路由协议是一种允许数据包在主机之间传送信息的协议","路由器之间可以通过路由协议学习网络的拓扑结构"], answer:"C",
  analysis:"路由协议用于在路由器之间交换路由信息、构建路由表，并非“允许数据包在主机间传送信息”的协议。" },
{ id:"r2021下-24", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于 RIPv2 对于 RIPv1 改进的说法中，错误的是（　）。",
  options:["RIPv2 是基于链路状态的路由协议","RIPv2 可以支持 VLSM","RIPv2 可以支持认证，有明文和 MD5 两种方式","RIPv2 采用的是组播更新"], answer:"A",
  analysis:"RIPv2 仍是基于距离矢量（Bellman-Ford）的路由协议，并非链路状态。" },
{ id:"r2021下-25", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于 OSPF 路由协议的说法中，错误的是（　）。",
  options:["OSPF 是基于分布式的链路状态协议","OSPF 是一种内部网关路由协议","OSPF 可以用于自治系统之间的路由选择","OSPF 为减少洪泛链路状态的信息量，可以将自治系统划分为更小的区域"], answer:"C",
  analysis:"OSPF 是内部网关协议（IGP），用于自治系统内部；自治系统之间的路由选择由 BGP 完成。" },
{ id:"r2021下-26", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"以下关于 IS-IS 路由协议的说法中，错误的是（　）。",
  options:["IS-IS 是基于距离矢量的路由协议","IS-IS 属于内部网关路由协议","IS-IS 路由协议将自治系统分为骨干区域和非骨干区域","IS-IS 路由协议中 Level-2 路由器可以和不同区域的 Level-2 或 Level-1-2 路由器形成邻居关系"], answer:"A",
  analysis:"IS-IS 是基于链路状态的 IGP，与 OSPF 类似使用 SPF 算法，并非距离矢量。" },
{ id:"r2021下-27", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于 BGP 路由协议的说法中，错误的是（　）。",
  options:["BGP 协议是一种外部网关协议","BGP 协议为保证可靠性使用 TCP 作为承载协议，使用端口号是179","BGP 协议使用 keep-alive 报文周期性地证实邻居站的连通性","BGP 协议不支持路由汇聚功能"], answer:"D",
  analysis:"BGP 路由表庞大，正是通过路由聚合（汇聚）减少资源占用，故“不支持汇聚”说法错误。" },
{ id:"r2021下-28", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"下列协议中，使用明文传输的是（　）。",
  options:["SSH","Telnet","SFTP","HTTPS"], answer:"B",
  analysis:"Telnet 明文传输账号口令；SSH、SFTP、HTTPS 均为加密传输。" },
{ id:"r2021下-29", source:"real", year:2021, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"在浏览器地址栏输入 ftp://ftp.tsinghua.edu.cn/ 进行访问时，首先执行的操作是（　）。",
  options:["域名解析","建立控制命令连接","建立文件传输连接","发送 FTP 命令"], answer:"A",
  analysis:"浏览器仅凭域名不知道服务器 IP，需先做域名解析，再建立连接、发送 FTP 命令。" },
{ id:"r2021下-30", source:"real", year:2021, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"下列端口号中，不属于常用电子邮件协议默认使用的端口的是（　）。",
  options:["23","25","110","143"], answer:"A",
  analysis:"25 为 SMTP、110 为 POP3、143 为 IMAP；23 是 Telnet 端口，与邮件无关。" },
{ id:"r2021下-31", source:"real", year:2021, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在 Linux 中，用于解析主机域名的文件是（　）。",
  options:["/dev/host.conf","/etc/hosts","/dev/resolv.conf","/etc/resolv.conf"], answer:"B",
  analysis:"/etc/hosts 提供本地主机名到 IP 的静态映射解析；/etc/resolv.conf 指定 DNS 服务器地址。" },
{ id:"r2021下-32", source:"real", year:2021, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在 Linux 中，可以使用命令（　）将文件 abc.txt 拷贝到目录 /home/my/office 中，且保留原文件访问权限。",
  options:["cp -l abc.txt /home/my/office","cp -p abc.txt /home/my/office","cp -R abc.txt /home/my/office","cp -f abc.txt /home/my/office"], answer:"B",
  analysis:"cp -p 除内容外还复制修改时间和访问权限；-l 建硬链接、-R 递归、-f 不提示强制覆盖。" },
{ id:"r2021下-33", source:"real", year:2021, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在 Linux 中，使用命令“chmod -R 777 /home/abc”将目录访问权限设为可读、可写、可执行，命令中的 777 表示（　）。",
  options:["属主/属组/其他均为可读可写可执行","属主可读可写，其余只读","仅属主可读可写可执行","所有用户只读"], answer:"A",
  analysis:"r=4、w=2、x=1，7=rwx；777 表示属主、属组、其他全部可读可写可执行。" },
{ id:"r2021下-34", source:"real", year:2021, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"在 Windows 中，DNS 客户端手工向服务器注册时使用的命令是（　）。",
  options:["ipconfig/release","ipconfig/flushdns","ipconfig/displaydns","ipconfig/registerdns"], answer:"D",
  analysis:"ipconfig /registerdns 用于 DNS 客户端手工向服务器动态注册。" },
{ id:"r2021下-35", source:"real", year:2021, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"Windows Server 2008 R2 上内嵌的 Web 服务器是（　）服务器。",
  options:["IIS","Apache","Tomcat","Nginx"], answer:"A",
  analysis:"Windows Server 2008 R2 内嵌的 Web 服务器为 IIS（7.5）。" },
{ id:"r2021下-36", source:"real", year:2021, sem:"下", paper:"上午", point:"网络管理与监控", diff:4,
  stem:"Windows 命令行执行 nslookup 后回显中包含 primary name server、responsible mail addr、serial、refresh、retry、expire、default TTL 等 SOA 信息，应使用的命令是（　）。",
  options:["nslookup -type=A xxx.edu.cn","nslookup -type=CNAME xxx.edu.cn","nslookup -type=NS xxx.edu.cn","nslookup -type=PTR xxx.edu.cn"], answer:"C",
  analysis:"查询 NS 记录时会同时返回该区域的主域名服务器及 SOA（含 serial/refresh/retry/expire 等）信息。" },
{ id:"r2021下-37", source:"real", year:2021, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"用户使用 ftp:// 访问某文件服务，默认通过目标端口为（　）的请求报文建立连接。",
  options:["20","21","22","23"], answer:"B",
  analysis:"FTP 控制连接默认使用 21 端口；20 为数据端口。" },
{ id:"r2021下-38", source:"real", year:2021, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"接题干，FTP 默认通过（　）建立连接。",
  options:["TCP","UDP","HTTP","FTP"], answer:"A",
  analysis:"FTP 面向连接、可靠传输，基于 TCP。" },
{ id:"r2021下-39", source:"real", year:2021, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"以下关于电子邮件服务的说法中，正确的是（　）。",
  options:["收到的邮件会即时自动地存储在预定目录中","电子邮件需要用户手动接收","不同操作系统使用不同的默认端口","电子邮件地址格式允许用户自定义"], answer:"A",
  analysis:"邮件到达后由服务器自动存储在用户预定信箱目录；各系统默认端口一致，地址格式为 user@domain 标准形式。" },
{ id:"r2021下-40", source:"real", year:2021, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"用户可以使用（　）向 DHCP 服务器重新请求 IP 地址配置。",
  options:["ipconfig/renew","ipconfig/release","ipconfig/reconfig","ipconfig/reboot"], answer:"A",
  analysis:"ipconfig /renew 用于向 DHCP 服务器重新请求/续租 IP 地址。" },
{ id:"r2021下-41", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"在防火墙域间安全策略中，不是 outbound 方向数据流的是（　）。",
  options:["从 Trust 区域到 Local 区域的数据流","从 Trust 区域到 Untrust 区域的数据流","从 Trust 区域到 DMZ 区域的数据流","从 DMZ 区域到 Untrust 区域的数据流"], answer:"A",
  analysis:"安全域优先级 Local>Trust>DMZ>Untrust，outbound 为由高到低；Trust 到 Local 是由低到高，属 inbound。" },
{ id:"r2021下-42", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"PKI 公钥证书（PKC）主要用于确保（　）的合法性。",
  options:["主体私钥","CA 私钥","主体公钥","CA 公钥"], answer:"C",
  analysis:"公钥证书由 CA 数字签名，证明证书主体公钥与身份的绑定关系。" },
{ id:"r2021下-43", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"AES 是一种（　）。",
  options:["公钥加密算法","流密码算法","分组加密算法","消息摘要算法"], answer:"C",
  analysis:"AES 是对称分组加密算法（分组长度 128 位）。" },
{ id:"r2021下-44", source:"real", year:2021, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"以下关于 HTTPS 的描述中，正确的是（　）。",
  options:["HTTPS 和 SHTTP 是同一个协议的不同简称","HTTPS 服务器端使用的缺省 TCP 端口是110","HTTPS 是传输层协议","HTTPS 是 HTTP 和 SSL/TLS 的组合"], answer:"D",
  analysis:"HTTPS 在 HTTP 基础上加入 SSL/TLS，默认端口 443，属应用层协议。" },
{ id:"r2021下-45", source:"real", year:2021, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"与 SNMP 所采用的传输层协议相同的是（　）。",
  options:["HTTP","SMTP","FTP","DNS"], answer:"D",
  analysis:"SNMP 基于 UDP，DNS 查询也基于 UDP（53）；HTTP/SMTP/FTP 基于 TCP。" },
{ id:"r2021下-46", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"交换机的二层转发表（MAC 地址表）空间被占满，清空后短时间内仍然会被占满，造成这种现象的原因可能是（　）。",
  options:["交换机内存故障","存在环路造成广播风暴","接入设备过多","利用虚假的 MAC 进行攻击"], answer:"D",
  analysis:"MAC 泛洪攻击通过伪造大量源 MAC 不断让交换机学习，导致 MAC 表溢出。" },
{ id:"r2021下-47", source:"real", year:2021, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"PC1 的用户在浏览器地址栏输入 www.abc.com 不能获取响应页面，而输入 61.102.58.77 可以正常打开 Web 页面，则导致该现象的可能是（　）。",
  options:["域名解析失败","网关配置错误","PC1 网络参数配置错误","路由配置错误"], answer:"A",
  analysis:"用 IP 能访问而域名不能，说明连通性正常、问题出在域名（DNS）解析。" },
{ id:"r2021下-48", source:"real", year:2021, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"某数据中心做存储系统设计，从性价比角度考量，最合适的冗余方式是（　）。",
  options:["RAID 0","RAID 1","RAID 5","RAID 10"], answer:"C",
  analysis:"RAID5 兼顾性能与冗余、磁盘利用率高，性价比最优。" },
{ id:"r2021下-49", source:"real", year:2021, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"接题干，该 RAID 配备 N 块磁盘时，实际可用数为（　）块。",
  options:["N","N-1","N/2","N/4"], answer:"B",
  analysis:"RAID5 用一块磁盘容量存放校验信息，实际可用 (N-1) 块。" },
{ id:"r2021下-50", source:"real", year:2021, sem:"下", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"下面的 IP 地址中，能够作为主机地址的是（　）。",
  options:["168.254.0.243/30","10.20.30.40/29","172.16.18.0/22","192.168.11.191/26"], answer:"C",
  analysis:"主机地址不能为网络号或广播地址。A 为广播、B 为网络地址、D 为广播；C 主机位不全 0 或全 1，可用。" },
{ id:"r2021下-51", source:"real", year:2021, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"下面的 IP 地址中，不属于同一网络的是（　）。",
  options:["172.20.34.28/21","172.20.39.100/21","172.20.32.176/21","172.20.40.177/21"], answer:"D",
  analysis:"/21 块大小 8，前三者第三字节落在 32~39 网段；40 落在 40~47 网段，与前三者不同。" },
{ id:"r2021下-52", source:"real", year:2021, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"某公司最大的局域网可容纳 200 个主机，最小的局域网可容纳 20 个主机。用可变长子网掩码划分子网，其最长的掩码为（　）位。",
  options:["24","25","26","27"], answer:"D",
  analysis:"容纳 20 台需主机位 5 位（2^5-2=30），对应掩码 32-5=27 位，即最长掩码。" },
{ id:"r2021下-53", source:"real", year:2021, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"接题干，其最短的掩码为（　）位。",
  options:["24","25","26","27"], answer:"A",
  analysis:"容纳 200 台需主机位 8 位（2^8-2=254），对应掩码 32-8=24 位，即最短掩码。" },
{ id:"r2021下-54", source:"real", year:2021, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"PC1 的 IP 地址为 192.168.5.16，PC2 的 IP 地址为 192.168.5.100，PC1 和 PC2 在同一网段中，其子网掩码可能是（　）。",
  options:["255.255.255.240","255.255.255.224","255.255.255.192","255.255.255.128"], answer:"D",
  analysis:"16 与 100 均落在 0~127 块（/25），只有掩码 255.255.255.128 使二者同网段。" },
{ id:"r2021下-55", source:"real", year:2021, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"华为命令“observe-port 1 interface GigabitEthernet 0/0/1；interface GigabitEthernet 0/0/2；port-mirroring to observe-port 1 inbound”的含义是（　）。",
  options:["配置端口镜像","配置链路聚合","配置逻辑接口","配置访问控制策略"], answer:"A",
  analysis:"observe-port 配置观察（镜像目的）端口，port-mirroring 将业务端口流量镜像到观察端口，即端口镜像。" },
{ id:"r2021下-56", source:"real", year:2021, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"使用（　）命令可以显示 OSPF 接口信息。",
  options:["display ospf error","display this","display ospf brief","display ospf interface"], answer:"D",
  analysis:"display ospf interface 用于查看 OSPF 接口信息。" },
{ id:"r2021下-57", source:"real", year:2021, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"GVRP 是跨交换机进行 VLAN 动态注册和删除的协议，关于对 GVRP 描述不准确的是（　）。",
  options:["GVRP 是 GARP 的一种应用，由 IEEE 制定","交换机之间的协议报文交互必须在 VLAN Trunk 链路上进行","GVRP 协议所支持的 VLAN ID 范围为1-1001","GVRP 配置时需要在每一台交换机上建立 VLAN"], answer:"C",
  analysis:"GVRP 支持的 VLAN ID 范围为 1~4094，而非 1~1001；其动态注册特性无需在每台交换机手工建 VLAN。" },
{ id:"r2021下-58", source:"real", year:2021, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"使用命令 vlan batch 10 15 to 19 25 28 to 30 创建了（　）个 VLAN。",
  options:["6","10","5","9"], answer:"B",
  analysis:"VLAN10、15~19（5个）、25、28~30（3个），合计 1+5+1+3=10 个。" },
{ id:"r2021下-59", source:"real", year:2021, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"VLAN 帧（以太网帧）的最小帧长是（　）字节。",
  options:["60","64","1518","1522"], answer:"B",
  analysis:"以太网最小帧长为 64 字节；1518/1522 为最大帧长。" },
{ id:"r2021下-60", source:"real", year:2021, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"接题干，VLAN 帧中表示帧优先级的字段是（　）。",
  options:["Type","PRI","CFI","VID"], answer:"B",
  analysis:"802.1Q 标签中 PRI（Priority）3 位表示帧优先级。" },
{ id:"r2021下-61", source:"real", year:2021, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"与 CSMA 相比，CSMA/CD（　）。",
  options:["充分利用传播延迟远小于传输延迟的特性，减少了冲突后信道的浪费","将冲突的产生控制在传播时间内，减少了冲突的概率","在发送数据前和发送数据过程中侦听信道，不会产生冲突","站点竞争信道，提高了信道的利用率"], answer:"A",
  analysis:"CSMA/CD 在发送过程中持续侦听，一旦冲突立即停发，利用传播延迟远小于发送延迟的特点，减少冲突后信道资源浪费。" },
{ id:"r2021下-62", source:"real", year:2021, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"采用 CSMA/CD 进行介质访问，两个站点连续冲突 3 次后再次冲突的概率为（　）。",
  options:["1/2","1/4","1/8","1/16"], answer:"C",
  analysis:"截断二进制指数退避，冲突 3 次后 k=3，在 [0,2^3-1]=[0,7] 中随机等待，再次冲突概率 1/8。" },
{ id:"r2021下-63", source:"real", year:2021, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"下列通信技术标准中，使用频段相同的是（　）。",
  options:["802.11a 和 802.11b","802.11b 和 802.11g","802.11a 和 802.11g","802.11a 和 802.11n"], answer:"B",
  analysis:"802.11b 与 802.11g 均工作在 2.4GHz；802.11a 为 5GHz。" },
{ id:"r2021下-64", source:"real", year:2021, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"以下关于 Wi-Fi 6 的说法中，错误的是（　）。",
  options:["支持完整版的 MU-MIMO","理论吞吐量最高可达 9.6Gbps","遵从协议 802.11ax","工作频段仅在 5GHz"], answer:"D",
  analysis:"Wi-Fi 6（802.11ax）同时工作在 2.4GHz、5GHz（及 6GHz），并非仅 5GHz。" },
{ id:"r2021下-65", source:"real", year:2021, sem:"下", paper:"上午", point:"无线网络", diff:3,
  stem:"以下关于无线漫游的说法中，错误的是（　）。",
  options:["漫游是由 AP 发起的","漫游分为二层漫游和三层漫游","三层漫游必须在同一个 SSID","客户端在 AP 间漫游，AP 可以处于不同的 VLAN"], answer:"A",
  analysis:"无线漫游由无线终端 STA（客户端）发起，而非 AP。" },
{ id:"r2021下-66", source:"real", year:2021, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"在大型无线网络中，AP 通常通过 DHCP option（　）来获取 AC 的 IP 地址。",
  options:["43","60","66","138"], answer:"A",
  analysis:"AP 通过 DHCP Option 43 获取 AC 的 IP 地址列表。" },
{ id:"r2021下-67", source:"real", year:2021, sem:"下", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"网络规划中，冗余设计不能（　）。",
  options:["提高链路可靠性","增强负载能力","提高数据安全性","加快路由收敛"], answer:"D",
  analysis:"冗余设计通过备份链路提高可靠性、分担负载，但路由收敛速度取决于协议算法与网络规模，与冗余无关。" },
{ id:"r2021下-68", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"某公司局域网使用 DHCP 动态获取 10.10.10.0/24 网段的 IP 地址，某天大量终端获得了 192.168.1.0/24 网段的地址，可在接入交换机上配置（　）功能杜绝该问题再次出现。",
  options:["dhcp relay","dhcp snooping","mac-address static","arp static"], answer:"B",
  analysis:"出现非法（伪）DHCP 服务器分配错误地址段，可在接入交换机开启 DHCP Snooping 只信任合法 DHCP 服务器端口。" },
{ id:"r2021下-69", source:"real", year:2021, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"项目范围管理过程：①定义范围 ②核实范围 ③收集需求 ④控制范围 ⑤创建工作分解结构，其正确的流程顺序是（　）。",
  options:["②④①③⑤","①②④③⑤","③⑤①②④","③①⑤②④"], answer:"D",
  analysis:"范围管理顺序为：收集需求→定义范围→创建 WBS→核实范围→控制范围，即③①⑤②④。" },
{ id:"r2021下-70", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"Network security is the protection of the underlying networking infrastructure from （　） access, misuse, or theft.（网络安全保护底层网络基础设施，使其免遭未授权访问、滥用或窃取。）",
  options:["unauthorized","authorized","normal","frequent"], answer:"A",
  analysis:"与后文 misuse/theft 负面语境一致，应为 unauthorized（未授权）访问。" },
{ id:"r2021下-71", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"It involves creating a secure infrastructure for devices and applications to work in a （　） manner.（为设备与应用创建以安全方式工作的基础设施。）",
  options:["economical","secure","fair","efficient"], answer:"B",
  analysis:"全文围绕安全主题，应选 secure（安全的）。" },
{ id:"r2021下-72", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"Each network security layer implements （　） controls.（每个网络安全层都实施策略控制。）",
  options:["computing","translation","policies","simulations"], answer:"C",
  analysis:"实施策略（policies）控制，符合语义。" },
{ id:"r2021下-73", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"A （　） is a network device that monitors incoming and outgoing network traffic and decides whether to block specific traffic based on security rules.（一种依据安全规则监控并阻断流量的网络设备。）",
  options:["firewall","router","gateway","switch"], answer:"A",
  analysis:"监控进出流量并按规则决定是否阻断的设备是防火墙（firewall）。" },
{ id:"r2021下-74", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"A virtual （　） encrypts the connection from an endpoint to a network, often over the internet.（一种将端点到网络的连接加密的虚拟专用网络。）",
  options:["public","private","personal","political"], answer:"B",
  analysis:"virtual private network（VPN，虚拟专用网络），选 private。" },
{ id:"r2021下-75", source:"real", year:2021, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"Linux防火墙iptables命令的-P参数表示（　）。",
  options:["协议","表","策略","跳转"], answer:"C",
  analysis:"iptables中大写-P等价于--policy，用于设置链的默认策略；小写-p才表示protocol（协议），勿混淆。" }
]);
