/* 真题库 · 2014 上半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2014上-01", source:"real", year:2014, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"在CPU中，常用来为ALU执行算术逻辑运算提供数据并暂存运算结果的寄存器是（　）。",
  options:["程序计数器","状态寄存器","通用寄存器","累加寄存器"], answer:"D",
  analysis:"累加寄存器(AC)为ALU提供工作区，暂存操作数与运算结果。" },
{ id:"r2014上-02", source:"real", year:2014, sem:"上", paper:"上午", point:"计算机硬件", diff:2,
  stem:"某机器字长为n，最高位是符号位，其定点整数的最大值为（　）。",
  options:["2^n-1","2^(n-1)-1","2^n","以上都不对"], answer:"B",
  analysis:"n位字长含1位符号位，数值位n-1位，最大正数为2^(n-1)-1。" },
{ id:"r2014上-03", source:"real", year:2014, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"通常可将执行一条指令分为取指、分析、执行3步。取指4△t、分析2△t、执行3△t，按顺序方式执行完600条指令所需时间为（　）△t。",
  options:["2400","3000","3600","5400"], answer:"D",
  analysis:"顺序执行每条(4+2+3)=9△t，600×9=5400△t。" },
{ id:"r2014上-04", source:"real", year:2014, sem:"上", paper:"上午", point:"计算机硬件", diff:4,
  stem:"承上，若按执行第i条、分析第i+1条、取指第i+2条重叠的流水线方式执行，则执行完600条指令所需时间为（　）△t。",
  options:["2400","2405","3600","3009"], answer:"B",
  analysis:"流水线首条9△t，以后每隔最长段4△t出结果：9+599×4=2405△t。" },
{ id:"r2014上-05", source:"real", year:2014, sem:"上", paper:"上午", point:"计算机硬件", diff:3,
  stem:"若用256K×8bit的存储器芯片，构成地址40000000H到400FFFFFH且按字节编址的内存区域，则需（　）片芯片。",
  options:["4","8","16","32"], answer:"A",
  analysis:"地址空间=400FFFFFH-40000000H+1=100000H=1MB；每片256KB，需1MB/256KB=4片。" },
{ id:"r2014上-06", source:"real", year:2014, sem:"上", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"以下关于进度管理工具Gantt图的叙述中，不正确的是（　）。",
  options:["能清晰地表达每个任务的开始时间、结束时间和持续时间","能清晰地表达任务之间的并行关系","不能清晰地确定任务之间的依赖关系","能清晰地确定影响进度的关键任务"], answer:"D",
  analysis:"Gantt图能表达进度与并行关系，但不能清晰表达依赖关系和关键路径。" },
{ id:"r2014上-07", source:"real", year:2014, sem:"上", paper:"上午", point:"操作系统", diff:3,
  stem:"若文件系统目录结构如图（当前工作目录为swshare，要访问文件fault.swf），则该文件的全文件名是（　）。",
  options:["fault.swf","flash\\fault.swf","swshare\\flash.swf","\\swshare\\flash\\fault.swf"], answer:"D",
  analysis:"全文件名(绝对路径)从根开始：\\swshare\\flash\\fault.swf。" },
{ id:"r2014上-08", source:"real", year:2014, sem:"上", paper:"上午", point:"操作系统", diff:3,
  stem:"承上，当前工作目录为swshare，访问flash子目录下的fault.swf，相对路径和绝对路径分别为（　）。",
  options:["swshare\\flash 和 \\flash\\","flash\\ 和 \\swshare\\flash\\","\\swshare\\flash\\ 和 flash\\","\\flash\\ 和 \\swshare\\flash\\"], answer:"B",
  analysis:"相对路径(从swshare)为flash\\，绝对路径为\\swshare\\flash\\。" },
{ id:"r2014上-09", source:"real", year:2014, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"在引用调用方式下进行函数调用，是将（　）。",
  options:["实参的值传递给形参","实参的地址传递给形参","形参的值传递给实参","形参的地址传递给实参"], answer:"B",
  analysis:"引用调用传递实参地址，形参指向实参，对形参的修改即修改实参。" },
{ id:"r2014上-10", source:"real", year:2014, sem:"上", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"王某买了一幅美术作品原件，则他享有该美术作品的（　）。",
  options:["著作权","所有权","展览权","所有权与展览权"], answer:"D",
  analysis:"取得美术作品原件，取得原件所有权及展览权，但著作权仍归作者。" },
{ id:"r2014上-11", source:"real", year:2014, sem:"上", paper:"上午", point:"广域网与接入", diff:2,
  stem:"路由器连接帧中继网络的接口是（　）。",
  options:["AUI接口","RJ-45接口","Console接口","Serial接口"], answer:"D",
  analysis:"帧中继、PPP等广域网链路使用串行(Serial)接口。" },
{ id:"r2014上-12", source:"real", year:2014, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"路由器连接双绞线以太网的接口是（　）。",
  options:["AUI接口","RJ-45接口","Console接口","Serial接口"], answer:"B",
  analysis:"双绞线以太网使用RJ-45接口。" },
{ id:"r2014上-13", source:"real", year:2014, sem:"上", paper:"上午", point:"数据通信基础", diff:3,
  stem:"在地面相距2000公里的两地间通过电缆传输4000比特长的数据包，数据速率64Kb/s，从开始发送到接收完成需要的时间为（　）。",
  options:["48ms","640ms","32.5ms","72.5ms"], answer:"D",
  analysis:"发送时延=4000/64000=62.5ms；传播时延≈2000km/20万km/s=10ms；共72.5ms。" },
{ id:"r2014上-14", source:"real", year:2014, sem:"上", paper:"上午", point:"数据通信基础", diff:2,
  stem:"海明码是一种纠错编码，一对有效码字之间的海明距离是（　）。",
  options:["两个码字的比特数之和","两个码字的比特数之差","两个码字之间相同的比特数","两个码字之间不同的比特数"], answer:"D",
  analysis:"海明距离为两码字对应位取值不同的位数。" },
{ id:"r2014上-15", source:"real", year:2014, sem:"上", paper:"上午", point:"数据通信基础", diff:4,
  stem:"承上，若信息为6位，要求纠正1位错，按海明编码规则需增加的校验位是（　）位。",
  options:["3","4","5","6"], answer:"B",
  analysis:"纠错1位需2^k ≥ m+k+1，m=6，k=4(2^4=16≥11)。" },
{ id:"r2014上-16", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"IPv4的D类地址是组播地址，其中224.0.0.1代表（　）。",
  options:["DHCP服务器","RIPv2路由器","本地子网中的所有主机","OSPF路由器"], answer:"C",
  analysis:"224.0.0.1代表本子网上的所有主机(all hosts)。" },
{ id:"r2014上-17", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"IPv4的D类组播地址中，224.0.0.5代表（　）。",
  options:["DHCP服务器","RIPv2路由器","本地子网中的所有主机","OSPF路由器"], answer:"D",
  analysis:"224.0.0.5是OSPFv2路由器的组播地址(AllSPFRouters)。" },
{ id:"r2014上-18", source:"real", year:2014, sem:"上", paper:"上午", point:"网络体系结构", diff:3,
  stem:"按IETF区分服务(DiffServ)规范，边界路由器要根据IP协议头中的（　）字段为每个IP分组打上DS码点标记。",
  options:["目标地址","源地址","服务类型","段偏置值"], answer:"C",
  analysis:"DSCP位于IPv4头部的服务类型(TOS)字段(现为DS字段)。" },
{ id:"r2014上-19", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"ICMP协议属于因特网中的（　）协议。",
  options:["数据链路层","网络层","传输层","会话层"], answer:"B",
  analysis:"ICMP是网络层协议，与IP同层。" },
{ id:"r2014上-20", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"ICMP协议数据单元封装在（　）中传送。",
  options:["以太帧","TCP段","UDP数据报","IP数据报"], answer:"D",
  analysis:"ICMP报文作为IP数据报的数据部分封装。" },
{ id:"r2014上-21", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"TCP/IP网络中最早使用的动态路由协议是（　）协议。",
  options:["RIP","OSPF","PPP","IS-IS"], answer:"A",
  analysis:"RIP是最早的内部网关动态路由协议之一。" },
{ id:"r2014上-22", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"承上，这种协议基于（　）算法来计算路由。",
  options:["路由信息","链路状态","距离矢量","最短通路"], answer:"C",
  analysis:"RIP基于距离矢量(Bellman-Ford)算法，以跳数为度量。" },
{ id:"r2014上-23", source:"real", year:2014, sem:"上", paper:"上午", point:"局域网与交换", diff:3,
  stem:"动态划分VLAN的方法中不包括（　）。",
  options:["网络层协议","网络层地址","交换机端口","MAC地址"], answer:"C",
  analysis:"按交换机端口划分VLAN属于静态划分，不是动态划分方法。" },
{ id:"r2014上-24", source:"real", year:2014, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"在局域网中划分VLAN，不同VLAN之间必须通过（　）连接才能互相通信。",
  options:["中继端口","动态端口","接入端口","静态端口"], answer:"A",
  analysis:"跨VLAN通信需经Trunk(中继)端口或三层设备。" },
{ id:"r2014上-25", source:"real", year:2014, sem:"上", paper:"上午", point:"局域网与交换", diff:2,
  stem:"承上，属于各个VLAN的数据帧必须同时打上不同的（　）。",
  options:["VLAN优先级","VLAN标记","用户标识","用户密钥"], answer:"B",
  analysis:"Trunk链路上帧携带802.1Q VLAN标记以区分VLAN。" },
{ id:"r2014上-26", source:"real", year:2014, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"城域以太网中，IEEE802.1ad定义的运营商网桥协议基本技术是在以太帧中插入（　）字段。",
  options:["运营商VLAN标记","运营商虚电路标识","用户VLAN标记","用户帧类型标记"], answer:"A",
  analysis:"802.1ad(Q-in-Q)在用户VLAN标签外再插入一层运营商VLAN标签。" },
{ id:"r2014上-27", source:"real", year:2014, sem:"上", paper:"上午", point:"广域网与接入", diff:3,
  stem:"承上，这种技术被称为（　）技术。",
  options:["Q-in-Q","IP-in-IP","NAT-in-NAT","MAC-in-MAC"], answer:"A",
  analysis:"双层VLAN标签技术称为Q-in-Q(802.1ad)。" },
{ id:"r2014上-28", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"网络配置如图(Router接口202.168.2.1/24、202.168.1.254/30，DNS服务器202.168.1.2)。在Router中配置网络1访问DNS服务器主机路由的命令是（　）。",
  options:["ip route 202.168.1.2 255.255.255.0 202.168.1.2","ip route 202.168.1.2 255.255.255.255 202.168.1.2","ip route 0.0.0.0 0.0.0.0 202.168.1.253","ip route 255.255.255.255 0.0.0.0 202.168.1.254"], answer:"B",
  analysis:"主机路由目的主机掩码为255.255.255.255，下一跳指向同网段可达地址。" },
{ id:"r2014上-29", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:2,
  stem:"承上，网络1访问Internet的默认路由命令是（　）。",
  options:["ip route 202.168.1.2 255.255.255.0 202.168.1.2","ip route 202.168.1.2 255.255.255.255 202.168.1.2","ip route 0.0.0.0 0.0.0.0 202.168.1.253","ip route 255.255.255.255 0.0.0.0 202.168.1.254"], answer:"C",
  analysis:"默认路由为0.0.0.0 0.0.0.0，下一跳指向出口对端202.168.1.253。" },
{ id:"r2014上-30", source:"real", year:2014, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"与HTTP1.0相比，HTTP1.1的优点不包括（　）。",
  options:["减少了RTTs数量","支持持久连接","减少了TCP慢启动次数","提高了安全性"], answer:"D",
  analysis:"HTTP1.1支持持久连接、减少RTT与慢启动；安全性需HTTPS/TLS保证，非其优点。" },
{ id:"r2014上-31", source:"real", year:2014, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"在运行Linux的服务器中使用BIND配置域名服务，其主配置文件存放在（　）。",
  options:["name.conf","named.conf","dns.conf","dnsd.conf"], answer:"B",
  analysis:"BIND主配置文件为/etc/named.conf。" },
{ id:"r2014上-32", source:"real", year:2014, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"在Linux系统中，root用户执行 shutdown -r now 命令，系统将会（　）。",
  options:["重新启动","进入单用户模式","休眠","关机"], answer:"A",
  analysis:"-r表示reboot，shutdown -r now立即重启。" },
{ id:"r2014上-33", source:"real", year:2014, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"结构化综合布线系统中的干线子系统是指（　）。",
  options:["管理楼层内各种设备的子系统","连接各个建筑物的子系统","工作区信息插座之间的线缆子系统","实现楼层设备间连接的子系统"], answer:"D",
  analysis:"干线(垂直)子系统连接各楼层设备间；建筑群子系统连接建筑物。" },
{ id:"r2014上-34", source:"real", year:2014, sem:"上", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"生产管理系统采用B/S方式，经常上网用户100个，每用户每分钟平均产生11个事务，平均事务量0.06MB，则该系统需要的传输速率为（　）。",
  options:["5.28Mb/s","8.8Mb/s","66Mb/s","528Mb/s"], answer:"B",
  analysis:"100×11×0.06=66MB/min=1.1MB/s=8.8Mb/s。" },
{ id:"r2014上-35", source:"real", year:2014, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"在Windows命令行进入nslookup交互方式后键入 set type=mx，这样的设置可以（　）。",
  options:["切换到指定的域名服务器","查询邮件服务器的地址","由地址查找对应的域名","查询域名对应的各种资源"], answer:"B",
  analysis:"type=mx指定查询邮件交换(MX)记录。" },
{ id:"r2014上-36", source:"real", year:2014, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"FTP提供了丰富的命令，用来更改本地计算机工作目录的命令是（　）。",
  options:["get","list","lcd","!list"], answer:"C",
  analysis:"lcd用于改变本地工作目录；cd改变远端目录。" },
{ id:"r2014上-37", source:"real", year:2014, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"在进行域名解析的过程中，由（　）获取的解析结果耗时最短。",
  options:["主域名服务器","辅域名服务器","本地缓存","转发域名服务器"], answer:"C",
  analysis:"直接命中本地缓存无需网络往返，耗时最短。" },
{ id:"r2014上-38", source:"real", year:2014, sem:"上", paper:"上午", point:"应用层协议", diff:3,
  stem:"DNS通知(NOTIFY)是一种推进机制，其作用是使得（　）。",
  options:["辅助域名服务器及时更新信息","授权域名服务器向管区内发送公告","本地域名服务器发送域名解析申请","递归查询迅速返回结果"], answer:"A",
  analysis:"DNS NOTIFY通知辅服务器区域已变化，触发其主动拉取更新。" },
{ id:"r2014上-39", source:"real", year:2014, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"在DNS资源记录中，（　）记录类型的功能是把IP地址解析为主机名。",
  options:["A","NS","CNAME","PTR"], answer:"D",
  analysis:"PTR记录实现反向解析(IP→主机名)；A记录正向(域名→IP)。" },
{ id:"r2014上-40", source:"real", year:2014, sem:"上", paper:"上午", point:"应用层协议", diff:2,
  stem:"以下关于DHCP的描述中，正确的是（　）。",
  options:["DHCP客户机不可跨网段获取IP地址","DHCP客户机只能收到一个dhcpoffer","DHCP服务器可以把一个IP地址同时租借给两个网络的不同主机","DHCP服务器中可自行设定租约期"], answer:"D",
  analysis:"租约期由DHCP服务器管理员配置；跨网段需中继，可收到多个offer。" },
{ id:"r2014上-41", source:"real", year:2014, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"高级加密标准AES支持的3种密钥长度中不包括（　）。",
  options:["56","128","192","256"], answer:"A",
  analysis:"AES支持128/192/256位密钥；56位是DES的密钥长度。" },
{ id:"r2014上-42", source:"real", year:2014, sem:"上", paper:"上午", point:"网络安全", diff:2,
  stem:"在报文摘要算法MD5中，进行明文分组与填充时，明文报文按（　）位分组。",
  options:["128","256","512","1024"], answer:"C",
  analysis:"MD5按512位分组处理，输出128位摘要。" },
{ id:"r2014上-43", source:"real", year:2014, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"以下关于IPsec协议的描述中，正确的是（　）。",
  options:["IPsec认证头(AH)不提供数据加密服务","IPsec封装安全负荷(ESP)仅用于数据完整性和数据源认证","IPsec传输模式对原IP数据报重新封装并加新IP头","IPsec通过应用层Web服务器建立安全连接"], answer:"A",
  analysis:"AH只做认证与完整性，不加密；ESP才提供加密。" },
{ id:"r2014上-44", source:"real", year:2014, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"防火墙的工作层次决定其效率与安全，下面叙述正确的是（　）。",
  options:["工作层次越低，效率越高、安全性越高","工作层次越低，效率越低、安全性越低","工作层次越高，效率越高、安全性越低","工作层次越高，效率越低、安全性越高"], answer:"D",
  analysis:"工作层次越高(如应用层网关)检查越细，安全性越高但转发效率越低。" },
{ id:"r2014上-45", source:"real", year:2014, sem:"上", paper:"上午", point:"网络安全", diff:3,
  stem:"入侵检测系统中事件分析器判断是否入侵，其常用三种分析方法中不包括（　）。",
  options:["模式匹配","密文分析","数据完整性分析","统计分析"], answer:"B",
  analysis:"IDS常用模式匹配、统计分析、数据完整性分析；密文分析不是。" },
{ id:"r2014上-46", source:"real", year:2014, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"在Windows Server 2003环境中有本地用户和域用户，其中本地用户信息存储在（　）。",
  options:["本地计算机的SAM数据库","本地计算机的活动目录","域控制器的活动目录","域控制器的SAM数据库"], answer:"A",
  analysis:"本地用户账户存于本地SAM数据库；域用户存于域控制器的活动目录。" },
{ id:"r2014上-47", source:"real", year:2014, sem:"上", paper:"上午", point:"网络管理与监控", diff:4,
  stem:"管理站用SetRequest在RMON表中产生新行，若新行索引值与其他行不冲突，则代理产生新行，其状态对象值为（　）。",
  options:["createRequest","underCreate","valid","invalid"], answer:"A",
  analysis:"行建立状态从createRequest开始，管理站配置完成后转为valid(active)。" },
{ id:"r2014上-48", source:"real", year:2014, sem:"上", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"在SNMPc支持的设备访问方式中，只是用于对TCP服务进行轮询的方式是（　）。",
  options:["无访问模式","ICMP(Ping)","SNMPv1和v2c","SNMPv3"], answer:"A",
  analysis:"无访问模式(None)仅用于TCP服务端口探活，不做SNMP/Ping管理。" },
{ id:"r2014上-49", source:"real", year:2014, sem:"上", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"下列数据类型中，SNMPv2支持而SNMPv1不支持的是（　）。",
  options:["OCTET STRING","OBJECT descriptor","Unsigned32","Gauge32"], answer:"C",
  analysis:"SNMPv2新增Counter64和Unsigned32；Gauge32在v1已存在。" },
{ id:"r2014上-50", source:"real", year:2014, sem:"上", paper:"上午", point:"无线网络", diff:3,
  stem:"实验室无线路由器固定IP连校园网，使用一段时间后不定期出现不能访问互联网；测试无线路由器工作正常，且有线接入用户可访问互联网。最可能的原因是（　）。",
  options:["无线路由器配置错误","无线路由器硬件故障","内部或外部网络攻击","校园网接入故障"], answer:"C",
  analysis:"设备正常、有线正常且故障间歇出现，排除硬件/配置/链路，最可能是遭受网络攻击(如ARP/DHCP欺骗)。" },
{ id:"r2014上-51", source:"real", year:2014, sem:"上", paper:"上午", point:"操作系统", diff:2,
  stem:"校园网连运营商IP为202.117.113.3/30，本地网关192.168.1.254/24，本地计算机采用动态地址分配，应如何配置（　）。",
  options:["选取“自动获得IP地址”","配置本地计算机IP为192.168.1.x","配置本地计算机IP为202.115.113.x","在网络169.254.x.x中选一个不冲突IP"], answer:"A",
  analysis:"采用动态地址分配，应设置为自动获得IP地址(DHCP)。" },
{ id:"r2014上-52", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"下面的选项中，不属于网络202.113.100.0/21的地址是（　）。",
  options:["202.113.102.0","202.113.99.0","202.113.97.0","202.113.95.0"], answer:"D",
  analysis:"/21块范围96.0~103.255(第三字节96~103)；95.0不在范围内。" },
{ id:"r2014上-53", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"IP地址块112.56.80.192/26包含了（　）个主机地址。",
  options:["15","32","62","64"], answer:"C",
  analysis:"/26主机位6位，可用主机=2^6-2=62。" },
{ id:"r2014上-54", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"承上，不属于网络112.56.80.192/26的地址是（　）。",
  options:["112.56.80.202","112.56.80.191","112.56.80.253","112.56.80.195"], answer:"B",
  analysis:"该块范围192~255；191是上一子网广播地址，不属于本网。" },
{ id:"r2014上-55", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"下面的地址中属于单播地址的是（　）。",
  options:["125.221.191.255/18","192.168.24.123/30","200.114.207.94/27","224.0.0.23/16"], answer:"C",
  analysis:"A为定向广播、B为/30链路对端、D为D类组播；C是可用单播主机地址。" },
{ id:"r2014上-56", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"IPv6地址格式前缀表示地址类型或子网，60位前缀12AB:0000:0000:CD30有多种合法表示，下面不合法的是（　）。",
  options:["12AB:0000:0000:CD30:0000:0000:0000:0000/60","12AB::CD30:0:0:0:0/60","12AB:0:0:CD3/60","12AB:0:0:CD30::/60"], answer:"C",
  analysis:"压缩零后CD30写成CD3会把16位段从0CD30错写为0CD3，改变前缀，不合法。" },
{ id:"r2014上-57", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"IPv6新增加的任意播(anycast)地址（　）。",
  options:["可以用作源地址，也可以用作目标地址","只可以作为源地址，不能作为目标地址","代表一组接口的标识符","可以用作路由器或主机的源地址"], answer:"C",
  analysis:"任播地址标识一组接口，数据包送达最近一个接口；只能作目的地址。" },
{ id:"r2014上-58", source:"real", year:2014, sem:"上", paper:"上午", point:"无线网络", diff:3,
  stem:"所谓移动IP是指（　）。",
  options:["通过地址翻译技术改变主机的IP地址","一个主机的IP地址可以转移给另一个主机","移动主机通过在无线通信网中漫游来保持网络连接","移动主机在离开家乡网络的远程站点也可以联网工作"], answer:"D",
  analysis:"移动IP让移动主机使用家乡地址，在外地/远程站点仍可联网通信。" },
{ id:"r2014上-59", source:"real", year:2014, sem:"上", paper:"上午", point:"无线网络", diff:3,
  stem:"承上，实现移动IP的关键技术是（　）。",
  options:["移动主机具有一个可接入任何网络的通用IP地址","移动主机具有一个家乡网络地址并获取一个外地转交地址","移动主机通过全网管理中心申请网络接入服务","移动主机总是通过家乡网络地址获取接入服务"], answer:"B",
  analysis:"移动IP关键：家乡地址(固定)+外地转交地址(care-of address)，经家乡代理转发。" },
{ id:"r2014上-60", source:"real", year:2014, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"中国自主研发的3G通信标准是（　）。",
  options:["CDMA2000","TD-SCDMA","WCDMA","WiMAX"], answer:"B",
  analysis:"TD-SCDMA是我国提出的3G标准。" },
{ id:"r2014上-61", source:"real", year:2014, sem:"上", paper:"上午", point:"无线网络", diff:2,
  stem:"IEEE802.11规定了多种WLAN标准，其中（　）与其他标准采用的频段不同，因而不能兼容。",
  options:["IEEE802.11a","IEEE802.11b","IEEE802.11g","IEEE802.11n"], answer:"A",
  analysis:"802.11a工作在5GHz，b/g/n主要在2.4GHz，故a与b不兼容。" },
{ id:"r2014上-62", source:"real", year:2014, sem:"上", paper:"上午", point:"无线网络", diff:3,
  stem:"IEEE802.11定义的Ad Hoc网络由无线移动结点组成对等网，其特点是（　）。",
  options:["每个结点既是主机，又是交换机","每个结点既是主机，又是路由器","每个结点都必须通过中心结点才能互相通信","每个结点都发送IP广播包与其他结点通信"], answer:"B",
  analysis:"Ad Hoc无中心，结点既作主机又作路由器转发报文。" },
{ id:"r2014上-63", source:"real", year:2014, sem:"上", paper:"上午", point:"无线网络", diff:3,
  stem:"承上，这种网络中使用的DSDV(Destination-Sequenced Distance Vector)路由协议是一种（　）。",
  options:["洪泛式路由协议","随机式路由协议","链路状态路由协议","距离矢量路由协议"], answer:"D",
  analysis:"DSDV是按需前的表驱动距离矢量协议，基于Bellman-Ford并带序列号防环。" },
{ id:"r2014上-64", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"OSPF将网络划分为不同类型区域，其中标准区域(骨干以外普通区域)的特点是（　）。",
  options:["不接受本地AS之外路由信息，也不接受其他区域汇总信息","不接受本地AS之外路由信息，对外网目标用默认路由","可以接收任何链路更新信息和路由汇总信息","可学习其他AS路由信息，对本区域用默认路由"], answer:"C",
  analysis:"标准区域可接收LSA及区域间汇总路由，是普通的传输区域。" },
{ id:"r2014上-65", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"承上，存根区域(stub)的特点是（　）。",
  options:["不接受本地AS之外路由信息，也不接受其他区域汇总信息","不接受本地AS之外路由信息，对本地AS之外目标采用默认路由","可以接收任何链路更新信息和路由汇总信息","可学习其他AS路由信息，对本区域用默认路由"], answer:"B",
  analysis:"stub区域屏蔽外部ASE LSA，到外网以默认路由代替。" },
{ id:"r2014上-66", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"NAT技术中，假设内网地址数m、外网地址数n，若m>n，则这种技术叫做（　）。",
  options:["动态地址翻译","静态地址翻译","地址伪装","地址变换"], answer:"A",
  analysis:"多对一/多对少的动态地址翻译(PAT/多对多动态NAT)。" },
{ id:"r2014上-67", source:"real", year:2014, sem:"上", paper:"上午", point:"网络层与路由", diff:3,
  stem:"承上，若m>n且n=1，则这种技术叫做（　）。",
  options:["动态地址翻译","静态地址翻译","地址伪装(NAPT)","地址变换"], answer:"C",
  analysis:"仅1个公网地址时所有内网主机共享，即地址伪装/PAT(NAPT)。" },
{ id:"r2014上-68", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"CIDR中，2048个C类网络组成地址块192.24.0.0~192.31.255.0，其超网号应为（　）。",
  options:["192.24.0.0","192.31.255.0","192.31.0.0","192.24.255.0"], answer:"A",
  analysis:"起始地址192.24.0.0作为超网号。" },
{ id:"r2014上-69", source:"real", year:2014, sem:"上", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"承上，其地址掩码应为（　）。",
  options:["255.255.248.0","255.255.255.0","255.255.0.0","255.248.0.0"], answer:"D",
  analysis:"2048=2^11个C类，掩码前缀=24-11=13位，即255.248.0.0。" },
{ id:"r2014上-70", source:"real", year:2014, sem:"上", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"网络系统设计过程中，物理网络设计阶段的任务是（　）。",
  options:["依据逻辑网络设计的要求，确定设备的具体物理分布和运行环境","分析现有网络和新网络的各类资源分布，掌握网络所处状态","根据需求规范和通信规范，实施资源分配和安全规划","理解网络应具有的功能和性能，设计出符合用户需求的网络"], answer:"A",
  analysis:"物理设计确定设备安装位置、线缆、机房环境等物理实现。" },
{ id:"r2014上-71", source:"real", year:2014, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"The traditional way of allocating a single channel among multiple competing users is to chop up its (　) by using one of the multiplexing schemes such as FDM.（选最贴切的词）",
  options:["capability","capacity","ability","power"], answer:"B",
  analysis:"chop up its capacity(容量)，指频分复用把信道带宽划分。" },
{ id:"r2014上-72", source:"real", year:2014, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"Since each user has a private frequency (　), there is no interference among users.（选最贴切的词）",
  options:["band","range","domain","assignment"], answer:"A",
  analysis:"private frequency band(频段)，各用户独占频段互不干扰。" },
{ id:"r2014上-73", source:"real", year:2014, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"...each of which has a steady stream or a heavy load of (　), this division is a simple and efficient allocation mechanism.（选最贴切的词）",
  options:["traffic","data","information","communications"], answer:"A",
  analysis:"heavy load of traffic(流量)，指持续稳定的业务流。" },
{ id:"r2014上-74", source:"real", year:2014, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"However, when the number of senders is large and varying or the traffic is (　), FDM presents some problems.（选最贴切的词）",
  options:["continuous","steady","bursty","flow"], answer:"C",
  analysis:"bursty(突发的)流量下固定分配频分复用会浪费频谱。" },
{ id:"r2014上-75", source:"real", year:2014, sem:"上", paper:"上午", point:"网络体系结构", diff:2,
  stem:"...if more than N users want to communicate, some of them will be denied (　) for lack of bandwidth.（选最贴切的词）",
  options:["allowance","connection","usage","permission"], answer:"D",
  analysis:"denied permission(被拒绝许可)，因带宽不足无法接入。" }
]);
