/* 真题库 · 2020 下半年（11月，与因疫情取消的上半年合并举行） */
REAL_BANK = REAL_BANK.concat([
{ id:"r2020下-01", source:"real", year:2020, sem:"下", paper:"上午", point:"存储与新技术", diff:1,
  stem:"关系型数据库采用（　）解决数据并发性引起的冲突。",
  options:["锁机制","表索引","分区表","读写分离"], answer:"A",
  analysis:"关系型数据库通过锁机制（行锁/表锁）协调并发访问，解决并发冲突。" },
{ id:"r2020下-02", source:"real", year:2020, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"把模块按照系统设计说明书的要求组合起来进行测试，属于（　）。",
  options:["单元测试","集成测试","确认测试","系统测试"], answer:"B",
  analysis:"将已通过单元测试的模块按设计组装起来进行的测试为集成测试。" },
{ id:"r2020下-03", source:"real", year:2020, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"虚拟存储体系由（　）两级存储器构成。",
  options:["主存-辅存","寄存器-Cache","寄存器-主存","Cache-主存"], answer:"A",
  analysis:"虚拟存储建立在主存与辅存两级之上，通过部分装入与调入调出实现逻辑上的扩充。" },
{ id:"r2020下-04", source:"real", year:2020, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"下列操作系统中，不是基于 Linux 内核的是（　）。",
  options:["AIX","CentOS","红旗","中标麒麟"], answer:"A",
  analysis:"AIX 是 IBM 的 UNIX 操作系统；CentOS、红旗、中标麒麟均为 Linux 内核发行版。" },
{ id:"r2020下-05", source:"real", year:2020, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"8086 微处理器中执行单元（EU）负责指令的执行，它主要包括（　）。",
  options:["ALU 运算器、输入输出控制电路、状态寄存器","ALU 运算器、通用寄存器、状态寄存器","通用寄存器、输入输出控制电路、状态寄存器","ALU 运算器、输入输出控制电路、通用寄存器"], answer:"B",
  analysis:"8086 执行单元 EU 由 ALU、通用寄存器组和状态标志（PSW）寄存器组成。" },
{ id:"r2020下-06", source:"real", year:2020, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:1,
  stem:"使用白盒测试时，确定测试数据应根据（　）指定覆盖准则。",
  options:["程序的内部逻辑","程序的复杂程度","使用说明书","程序的功能"], answer:"A",
  analysis:"白盒测试依据程序内部逻辑结构设计用例并选用覆盖准则。" },
{ id:"r2020下-07", source:"real", year:2020, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"以下关于 RISC 指令系统基本概念的描述中，错误的是（　）。",
  options:["选取使用频率低的一些复杂指令，指令条数多","指令长度固定","指令功能简单","指令运行速度快"], answer:"A",
  analysis:"RISC 优先选用高频简单指令、指令条数少、长度固定；选取低频复杂指令、条数多是 CISC 的特征。" },
{ id:"r2020下-08", source:"real", year:2020, sem:"下", paper:"上午", point:"计算机硬件", diff:1,
  stem:"计算机上采用的 SSD（固态硬盘）实质上是（　）存储器。",
  options:["Flash","磁盘","磁带","光盘"], answer:"A",
  analysis:"SSD 由闪存（Flash）芯片构成，无机械结构。" },
{ id:"r2020下-09", source:"real", year:2020, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"信息安全强调信息/数据本身的安全属性，下面（　）不属于信息安全的属性。",
  options:["信息的秘密性","信息的完整性","信息的可用性","信息的实时性"], answer:"D",
  analysis:"信息安全三大基本属性为保密性（秘密性）、完整性、可用性；实时性不是其安全属性。" },
{ id:"r2020下-10", source:"real", year:2020, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"我国由（　）主管全国软件著作权登记管理工作。",
  options:["国家版权局","国家新闻出版署","国家知识产权局","地方知识产权局"], answer:"A",
  analysis:"国家版权局主管全国软件著作权登记管理工作。" },
{ id:"r2020下-11", source:"real", year:2020, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"8 条模拟信道采用 TDM 复用成 1 条数字信道，TDM 帧结构为 8 字节加 1 比特同步开销。若模拟信号频率范围为 10～16kHz，样本率至少为（　）样本/秒。",
  options:["8k","10k","20k","32k"], answer:"D",
  analysis:"由奈奎斯特准则，采样率≥2×最高信号频率=2×16k=32k 样本/秒。" },
{ id:"r2020下-12", source:"real", year:2020, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"接题干，此时数字信道的数据速率为（　）Mbps。",
  options:["0.52","0.65","1.30","2.08"], answer:"D",
  analysis:"8 信道×8bit×32000=2.048Mbps，加 32000bit/s 同步开销≈2.08Mbps。" },
{ id:"r2020下-13", source:"real", year:2020, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"在异步传输中，1 位起始位、7 位数据位、2 位停止位、1 位校验位，每秒传输 200 字符，采用曼彻斯特编码，有效数据速率是（　）kb/s。",
  options:["1.2","1.4","2.2","2.4"], answer:"B",
  analysis:"有效数据位为每字符 7 位：200×7=1400b/s=1.4kb/s。" },
{ id:"r2020下-14", source:"real", year:2020, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"接题干，该异步传输采用曼彻斯特编码时的最大波特率为（　）Baud。",
  options:["700","2200","1400","4400"], answer:"D",
  analysis:"每字符共 11 位，比特率=200×11=2200b/s；曼彻斯特编码每位 2 次跳变，波特率=2×2200=4400Baud。" },
{ id:"r2020下-15", source:"real", year:2020, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"在卫星通信中，通常采用的差错控制机制为（　）。",
  options:["停等 ARQ","后退 N 帧 ARQ","选择重发 ARQ","最大限额 ARQ"], answer:"C",
  analysis:"卫星链路长、误码率高，通常采用选择重发 ARQ，只重传出错帧以提高效率。" },
{ id:"r2020下-16", source:"real", year:2020, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"以下千兆以太网标准中，支持 1000m 以上传输距离的是（　）。",
  options:["1000BASE-T","1000BASE-CX","1000BASE-SX","1000BASE-LX"], answer:"D",
  analysis:"1000BASE-LX 采用单模光纤可传输数公里（>1000m）；T/CX/SX 距离均较短。" },
{ id:"r2020下-17", source:"real", year:2020, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"综合布线系统中，用于连接各层配线室，并连接主配线室的子系统为（　）。",
  options:["工作区子系统","水平子系统","垂直（干线）子系统","管理子系统"], answer:"C",
  analysis:"垂直（干线）子系统连接各楼层配线间与主设备间（主配线室）。" },
{ id:"r2020下-18", source:"real", year:2020, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"光纤传输测试指标中，回波损耗是指（　）。",
  options:["信号反射引起的衰减","传输距离引起的发射端与接收端能量差","光信号通过活动连接器之后功率的减少","传输数据时线对间信号的相互泄漏"], answer:"A",
  analysis:"回波损耗由阻抗不匹配引起的信号反射造成，反映反射导致的衰减。" },
{ id:"r2020下-19", source:"real", year:2020, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"以 100Mb/s 以太网连接的站点 A 和 B 相隔 2000m，通过停等机制进行数据传输，传播速率为 200m/μs，有效的传输速率为（　）Mb/s。",
  options:["80.8","82.9","90.1","92.3"], answer:"A",
  analysis:"停等信道利用率=T0/(T0+2Tp)，传播时延 Tp=2000/200=10μs，帧发送 T0=1500×8/1e8≈120μs，有效率≈120/(120+20)×100≈80.8Mb/s。" },
{ id:"r2020下-20", source:"real", year:2020, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"采用 ADSL 接入互联网，计算机需要通过（　）和分离器连接到电话入户接线盒。",
  options:["ADSL 交换机","Cable Modem","ADSL Modem","无线路由器"], answer:"C",
  analysis:"ADSL 用户端通过 ADSL Modem 与分离器（话音数据分离）连接入户线。" },
{ id:"r2020下-21", source:"real", year:2020, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"在 HFC 网络中，用户通过（　）接入 CATV 网络。",
  options:["ADSL 交换机","Cable Modem","ADSL Modem","无线路由器"], answer:"B",
  analysis:"HFC 基于有线电视同轴电缆，用户通过 Cable Modem 接入。" },
{ id:"r2020下-22", source:"real", year:2020, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"某 IP 网络中路由器各连接一个网段，下列说法中正确的是（　）。",
  options:["共有2个冲突域","共有2个广播域","计算机 S 和计算机 T 构成冲突域","计算机 Q 查找 R 的 MAC 地址时 ARP 报文会传播到 S"], answer:"B",
  analysis:"路由器隔离广播域，每路由器接口为一个广播域；本题网络共有 2 个广播域。" },
{ id:"r2020下-23", source:"real", year:2020, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"采用 HDLC 协议进行数据传输时，RNR 5 表明（　）。",
  options:["拒绝编号为5的帧","下一个接收的帧编号应为5，但接收器未准备好，暂停接收","后退N帧重传编号为5的帧","选择性拒绝编号为5的帧"], answer:"B",
  analysis:"RNR（接收未准备好）表示对方应暂停发送，N(R)=5 表示下一个期望接收的帧序号为5。" },
{ id:"r2020下-24", source:"real", year:2020, sem:"下", paper:"上午", point:"传输层", diff:3,
  stem:"若主机采用以太网接入 Internet，TCP 段格式中数据字段最大长度为（　）字节。",
  options:["20","1460","1500","65535"], answer:"B",
  analysis:"以太网 MTU=1500，减去 IP 头 20 字节与 TCP 头 20 字节，TCP 数据最大 1460 字节。" },
{ id:"r2020下-25", source:"real", year:2020, sem:"下", paper:"上午", point:"传输层", diff:3,
  stem:"TCP 采用拥塞窗口（cwnd）进行拥塞控制。以下关于 cwnd 的说法中正确的是（　）。",
  options:["首部中的窗口字段存放 cwnd 的值","每个段包含的数据只要不超过 cwnd 值就可以发送了","cwnd 值由对方指定","cwnd 值存放在本地"], answer:"D",
  analysis:"cwnd 由本端拥塞控制算法维护、仅存于本地；首部窗口字段是接收方通告的 rwnd，非 cwnd。" },
{ id:"r2020下-26", source:"real", year:2020, sem:"下", paper:"上午", point:"传输层", diff:1,
  stem:"UDP 头部的大小为（　）字节。",
  options:["8","16","20","32"], answer:"A",
  analysis:"UDP 首部固定 8 字节（源端口、目的端口、长度、校验和各 2 字节）。" },
{ id:"r2020下-27", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:1,
  stem:"为了控制 IP 数据报在网络中无限转发，在 IPv4 数据报首部中设置了（　）字段。",
  options:["标识符","首部长度","生存期（TTL）","总长度"], answer:"C",
  analysis:"TTL 每经一跳减 1，减到 0 即丢弃报文，防止环路中无限转发。" },
{ id:"r2020下-28", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"Telnet 是用于远程访问服务器的常用协议。下列关于 Telnet 的描述中，不正确的是（　）。",
  options:["可传输数据和口令","默认端口号是23","一种安全的通信协议","用 TCP 作为传输层协议"], answer:"C",
  analysis:"Telnet 明文传输账号口令，并不安全；默认端口 23、基于 TCP。" },
{ id:"r2020下-29", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"使用电子邮件客户端从服务器下载邮件，能实现邮件的移动、删除等操作在客户端和邮箱上更新同步，所使用的电子邮件接收协议是（　）。",
  options:["SMTP","POP3","IMAP4","MIME"], answer:"C",
  analysis:"IMAP4 在服务器上保留邮件并同步客户端操作（移动/删除等）；POP3 仅下载到本地。" },
{ id:"r2020下-30", source:"real", year:2020, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在 Linux 系统中，DNS 配置文件的（　）参数，用于确定 DNS 服务器地址。",
  options:["nameserver","domain","search","sortlist"], answer:"A",
  analysis:"/etc/resolv.conf 中 nameserver 用于指定 DNS 服务器地址。" },
{ id:"r2020下-31", source:"real", year:2020, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在 Linux 系统中，要将文件复制到另一个目录中，为防止意外覆盖相同文件名的文件，可使用（　）命令实现。",
  options:["cp -a","cp -i","cp -R","cp -f"], answer:"B",
  analysis:"cp -i 在覆盖前给出提示，避免意外覆盖同名文件。" },
{ id:"r2020下-32", source:"real", year:2020, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在 Linux 系统中，可在（　）文件中修改系统主机名。",
  options:["/etc/hostname","/etc/sysconfig","/dev/hostname","/dev/sysconfig"], answer:"A",
  analysis:"现代 Linux 在 /etc/hostname 中设置系统主机名。" },
{ id:"r2020下-33", source:"real", year:2020, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"Windows 命令提示符运行 nslookup www.softwaretest.com，回显为“Server: nsl.softwaretest.com，Address: 192.168.1.254，Non-authoritative answer: Name: www.softwaretest.com，Address: 10.10.1.3”。为该域名提供解析的 DNS 服务器 IP 地址是（　）。",
  options:["192.168.1.254","10.10.1.3","192.168.1.1","10.10.1.1"], answer:"A",
  analysis:"回显中 Server 后跟随的 Address 即为提供本次解析的 DNS 服务器地址 192.168.1.254。" },
{ id:"r2020下-34", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"Windows Server 2008 R2 上 IIS 7.5 能提供的服务有（　）。",
  options:["DHCP 服务","FTP 服务","DNS 服务","远程桌面服务"], answer:"B",
  analysis:"IIS 7.5 提供 Web、FTP 等服务；DHCP/DNS/远程桌面是独立角色服务。" },
{ id:"r2020下-35", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"某网络上 MAC 地址为 00-FF-78-ED-20-DE 的主机，首次向网络上的 DHCP 服务器发送（　）报文以请求 IP 地址配置。",
  options:["DhcpDiscover","DhcpRequest","DhcpOffer","DhcpAck"], answer:"A",
  analysis:"DHCP 客户端首次请求时以广播发送 DhcpDiscover 发现报文。" },
{ id:"r2020下-36", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:4,
  stem:"接题干，该 DHCP 首次请求报文的源 MAC 地址和源 IP 地址分别是（　）。",
  options:["全 0 的 MAC 和 0.0.0.0","全 0 的 MAC 和 255.255.255.255","00-FF-78-ED-20-DE 和 0.0.0.0","00-FF-78-ED-20-DE 和 255.255.255.255"], answer:"C",
  analysis:"主机尚无 IP，源 IP 为 0.0.0.0、目的广播 255.255.255.255；源 MAC 为自身真实网卡 MAC。" },
{ id:"r2020下-37", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"用户在登录 FTP 服务器的过程中，建立 TCP 连接时使用的默认端口号是（　）。",
  options:["20","21","22","23"], answer:"B",
  analysis:"FTP 控制连接默认端口 21。" },
{ id:"r2020下-38", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"用户使用域名访问某网站时，是通过（　）得到目的主机的 IP 地址。",
  options:["HTTP","ARP","DNS","ICMP"], answer:"C",
  analysis:"DNS 完成域名到 IP 地址的解析。" },
{ id:"r2020下-39", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"在 DNS 的资源记录中，类型 A（　）。",
  options:["表示 IP 地址到主机名的映射","表示主机名到 IP 地址的映射","指定授权服务器","指定区域邮件服务器"], answer:"B",
  analysis:"A 记录实现主机名到 IPv4 地址的映射；PTR 为反向映射。" },
{ id:"r2020下-40", source:"real", year:2020, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"下列关于防火墙技术的描述中，正确的是（　）。",
  options:["防火墙不能支持网络地址转换","防火墙通常部署在企业内部网和 Internet 之间","防火墙可以查、杀各种病毒","防火墙可以过滤垃圾邮件"], answer:"B",
  analysis:"防火墙通常部署在内网与 Internet 之间做访问控制；可支持 NAT，但查杀病毒、过滤垃圾邮件不是其基础功能。" },
{ id:"r2020下-41", source:"real", year:2020, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"SHA-256 是（　）算法。",
  options:["加密","数字签名","认证","报文摘要"], answer:"D",
  analysis:"SHA-256 是安全散列（报文摘要）算法，输出 256 位摘要。" },
{ id:"r2020下-42", source:"real", year:2020, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"根据 ITU-T X.509 规定，数字证书一般格式中包含认证机构的签名，该数据域的作用是（　）。",
  options:["用于标识颁发证书的权威机构 CA","用于指示建立和签署证书的 CA 的 X.509 名字","用于防止证书的伪造","用于传递 CA 的公钥"], answer:"C",
  analysis:"CA 对证书的数字签名用于校验证书完整性、防止证书被伪造篡改。" },
{ id:"r2020下-43", source:"real", year:2020, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"以下关于三重 DES 加密算法的描述中，正确的是（　）。",
  options:["三重 DES 加密使用两个不同密钥进行三次加密","三重 DES 加密使用三个不同密钥进行三次加密","三重 DES 加密的密钥长度是 DES 密钥长度的三倍","三重 DES 加密使用一个密钥进行三次加密"], answer:"A",
  analysis:"3DES 常用两到三个 56 位密钥，标准 EDE 模式可使用两个不同密钥实现三次加密。" },
{ id:"r2020下-44", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"以下关于 HTTP 和 HTTPS 的描述中，不正确的是（　）。",
  options:["部署 HTTPS 需要到 CA 申请证书","HTTP 信息采用明文传输，HTTPS 则采用 SSL 加密传输","HTTP 和 HTTPS 使用的默认端口都是80","HTTPS 由 SSL+HTTP 构建，比 HTTP 安全"], answer:"C",
  analysis:"HTTP 默认 80，HTTPS 默认 443，二者端口并不都是 80。" },
{ id:"r2020下-45", source:"real", year:2020, sem:"下", paper:"上午", point:"网络管理与监控", diff:3,
  stem:"假设有一个 LAN，每 10 分钟轮询所有被管理设备一次，单个轮询需要时间约为 0.2s，则该管理站最多可支持（　）个设备。",
  options:["4500","4000","3500","3000"], answer:"D",
  analysis:"10 分钟=600s，每设备轮询 0.2s，最多设备数=600/0.2=3000。" },
{ id:"r2020下-46", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"某主机能够 ping 通网关，但 ping 外网主机 IP 地址时显示“目标主机不可达”，出现该故障的原因可能是（　）。",
  options:["本机 TCP/IP 协议安装错误","域名服务工作不正常","网关路由错误","本机路由错误"], answer:"C",
  analysis:"能 ping 通网关说明本网连通正常；外网不可达通常是网关缺少到达外网的路由（网关路由错误）。" },
{ id:"r2020下-47", source:"real", year:2020, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"Windows 系统中的 SNMP 服务程序包括 SNMPService 和 SNMPTrap 两个，其中 SNMPTrap 的作用是（　）。",
  options:["处理本地计算机上的陷入信息","被管对象检测到差错，发送给管理站","接收本地或远程 SNMP 代理发送的陷入信息","处理远程计算机发来的陷入信息"], answer:"B",
  analysis:"SNMPTrap 代理在被管对象检测到差错/事件时，主动向管理站发送 Trap 陷入报文。" },
{ id:"r2020下-48", source:"real", year:2020, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"某主机 IP 地址为 192.168.88.156，网络故障表现为时断时续，抓包分析发现网络上大量重复的 Who has（ARP 请求）与 Is at（ARP 响应）广播，该主机故障的原因可能是（　）。",
  options:["网关地址配置不正确","DNS 配置不正确或者工作不正常","该网络遭到 ARP 病毒的攻击","该主机网卡硬件故障"], answer:"C",
  analysis:"大量异常 ARP 请求/响应广播刷屏，是 ARP 欺骗/病毒攻击的典型抓包特征。" },
{ id:"r2020下-49", source:"real", year:2020, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"Windows 中标准的 SNMP Service 和 SNMP Trap 分别使用的默认 UDP 端口是（　）。",
  options:["25 和 26","160 和 161","161 和 162","161 和 160"], answer:"C",
  analysis:"SNMP 代理服务使用 UDP 161 接收轮询，Trap 报文使用 UDP 162 上报。" },
{ id:"r2020下-50", source:"real", year:2020, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"公司为服务器分配了 IP 地址段 121.21.35.192/28，下面的 IP 地址中，不能作为 Web 服务器地址的是（　）。",
  options:["121.21.35.204","121.21.35.205","121.21.35.206","121.21.35.207"], answer:"D",
  analysis:"/28 块大小 16，网络 192.168.35.192、广播 121.21.35.207；广播地址不能分配给主机。" },
{ id:"r2020下-51", source:"real", year:2020, sem:"下", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"使用 CIDR 将 202.145.27.0/24、202.145.29.0/24、202.145.31.0/24 和 202.145.33.0/24 汇总为一个超网地址，其地址为（　）。",
  options:["202.145.27.0/20","202.145.0.0/20","202.145.0.0/18","202.145.32.0/19"], answer:"C",
  analysis:"27~33 跨度需对齐到第三字节前 2 位，共同前缀为 00，聚合为 202.145.0.0/18（覆盖 0~63）。" },
{ id:"r2020下-52", source:"real", year:2020, sem:"下", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"接题干的 202.145.0.0/18 超网，下面（　）不属于该地址段。",
  options:["202.145.20.255","202.145.35.177","202.145.60.210","202.145.64.1"], answer:"D",
  analysis:"/18 覆盖第三字节 0~63；202.145.64.1 的第三字节 64 超出范围，不属于该超网。" },
{ id:"r2020下-53", source:"real", year:2020, sem:"下", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"接题干，4 个 C 类地址汇聚成 202.145.0.0/18 后，地址空间是原来的（　）倍。",
  options:["2","4","8","16"], answer:"D",
  analysis:"/18 覆盖 2^(24-18)=64 个 C 类块，原为 4 个，64/4=16 倍。" },
{ id:"r2020下-54", source:"real", year:2020, sem:"下", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"下面的 IP 地址中，可以用作主机 IP 地址的是（　）。",
  options:["92.168.15.255/20","172.16.23.255/20","172.20.83.255/22","202.100.10.15/28"], answer:"B",
  analysis:"A/C/D 分别为各自子网的广播地址；172.16.23.255/20 的广播是 172.16.31.255，故 .23.255 可用作主机地址。" },
{ id:"r2020下-55", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"OSPF 协议相对于 RIP 的优势在于（　）。①没有跳数的限制 ②支持可变长子网掩码（VLSM）③支持网络规模大 ④收敛速度快",
  options:["①③④","①②③","①②③④","①②"], answer:"C",
  analysis:"OSPF 无跳数限制、支持 VLSM、适合大规模网络、链路状态更新收敛快，四项均为其相对 RIP 的优势。" },
{ id:"r2020下-56", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"OSPF 协议中 DR 的作用范围是（　）。",
  options:["一个 area","一个网段","一台路由器","运行 OSPF 协议的网络"], answer:"B",
  analysis:"DR/BDR 只在其所在的广播型网段（一个子网）内起作用。" },
{ id:"r2020下-57", source:"real", year:2020, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"GVRP 定义的四种定时器中缺省值最小的是（　）。",
  options:["Hold 定时器","Join 定时器","Leave 定时器","LeaveAll 定时器"], answer:"A",
  analysis:"四种定时器中 Hold 定时器缺省值最小，用于对 GVRP 声明进行短暂缓存。" },
{ id:"r2020下-58", source:"real", year:2020, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"命令“system-view；vlan 10；vlan10 name huawei；quit”的含义是（　）。",
  options:["创建了两个VLAN","恢复接口上VLAN缺省配置","配置VLAN的名称","恢复当前VLAN名称的缺省值"], answer:"C",
  analysis:"在 VLAN10 视图下用 name 命令为该 VLAN 命名为 huawei。" },
{ id:"r2020下-59", source:"real", year:2020, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"（　）的含义是一台交换机上的 VLAN 配置信息可以传播、复制到网络中相连的其他交换机上。",
  options:["中继端口","VLAN 中继","VLAN 透传","SuperVLAN"], answer:"B",
  analysis:"VLAN 中继（Trunk）使 VLAN 配置信息跨交换机传播、多 VLAN 共享一条链路。" },
{ id:"r2020下-60", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"以下关于 BGP 的说法中，正确的是（　）。",
  options:["BGP 是一种链路状态协议","BGP 通过 UDP 发布路由信息","BGP 依据延迟来计算网络代价","BGP 能够检测路由循环"], answer:"D",
  analysis:"BGP 是路径矢量外部网关协议、基于 TCP 179、依据 AS_PATH 等属性选路，并能通过 AS_PATH 检测路由环路。" },
{ id:"r2020下-61", source:"real", year:2020, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"快速以太网 100BASE-T4 采用的传输介质为（　）。",
  options:["3 类 UTP","5 类 UTP","光纤","同轴电缆"], answer:"A",
  analysis:"100BASE-T4 使用 4 对 3 类（或以上）非屏蔽双绞线。" },
{ id:"r2020下-62", source:"real", year:2020, sem:"下", paper:"上午", point:"局域网与交换", diff:1,
  stem:"CSMA/CD 采用的介质访问技术属于资源的（　）。",
  options:["轮流使用","固定分配","竞争使用","按需分配"], answer:"C",
  analysis:"CSMA/CD 中各站点竞争使用信道，冲突后退避重传，属于竞争型介质访问。" },
{ id:"r2020下-63", source:"real", year:2020, sem:"下", paper:"上午", point:"无线网络", diff:2,
  stem:"WLAN 接入安全控制中，采用的安全措施不包括（　）。",
  options:["SSID 访问控制","CA 认证","物理地址过滤","WPA2 安全认证"], answer:"B",
  analysis:"WLAN 常用安全措施有 SSID 隐藏/控制、MAC 地址过滤、WPA/WPA2 认证；CA 证书认证不是其常规接入安全措施。" },
{ id:"r2020下-64", source:"real", year:2020, sem:"下", paper:"上午", point:"无线网络", diff:1,
  stem:"下列 IEEE 802.11 系列标准中，WLAN 的传输速率达到 300Mbps 的是（　）。",
  options:["802.11a","802.11b","802.11g","802.11n"], answer:"D",
  analysis:"802.11n 采用 MIMO，速率可达 300Mbps（甚至 600Mbps）。" },
{ id:"r2020下-65", source:"real", year:2020, sem:"下", paper:"上午", point:"存储与新技术", diff:3,
  stem:"某单位计划购置容量需求为 60TB 的存储设备，配置一个 RAID5 组，并配置一块全局热备盘，至少需要（　）块单块容量为 4TB 的磁盘。",
  options:["15","16","17","18"], answer:"C",
  analysis:"RAID5 可用 (n-1)×4TB≥60TB → n-1≥15 → n≥16；再加 1 块全局热备盘共 17 块。" },
{ id:"r2020下-66", source:"real", year:2020, sem:"下", paper:"上午", point:"网络规划与布线", diff:1,
  stem:"对某银行业务系统的网络方案设计时，应该优先考虑（　）原则。",
  options:["开放性","先进性","经济性","高可用性"], answer:"D",
  analysis:"银行业务对业务连续性要求极高，网络设计应优先考虑高可用性。" },
{ id:"r2020下-67", source:"real", year:2020, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"在项目管理过程中，变更总是不可避免，作为项目经理应该让项目干系人认识到（　）。",
  options:["在项目设计阶段，变更成本较低","在项目实施阶段，变更成本较低","项目变更应该由项目经理批准","应尽量满足建设方要求，不需要进行变更控制"], answer:"A",
  analysis:"项目越早期（设计阶段）变更代价越小，应尽早变更、加强变更控制。" },
{ id:"r2020下-68", source:"real", year:2020, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"进行项目风险评估最关键的时间点是（　）。",
  options:["计划阶段","计划发布后","设计阶段","项目出现问题时"], answer:"A",
  analysis:"应在项目计划阶段就进行风险识别与评估，越早越主动有效。" },
{ id:"r2020下-69", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"The Address Resolution Protocol (ARP) lies between layers （　） of the OSI model.（ARP 位于 OSI 模型哪两层之间。）",
  options:["1 And 2","2 And 3","3 And 4","4 And 5"], answer:"B",
  analysis:"ARP 介于数据链路层（2）与网络层（3）之间，用于由 IP 求 MAC。" },
{ id:"r2020下-70", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"ARP finds the （　） address of a host from its known address.（ARP 由已知地址查找主机的哪种地址。）",
  options:["IP","logical","hardware","network"], answer:"C",
  analysis:"ARP 由已知 IP 地址查找主机的硬件（MAC）地址。" },
{ id:"r2020下-71", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"接题干，ARP 是从已知的（　）地址进行查找。",
  options:["IP","physical","MAC","logical"], answer:"A",
  analysis:"已知目标 IP 地址，ARP 据此查询对应的 MAC。" },
{ id:"r2020下-72", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"If there is no entry in its ARP cache, the source device sends a （　） message to every device on the network.（缓存无条目时源主机向全网发送何种报文。）",
  options:["unicast","multicast","broadcast","point-to-point"], answer:"C",
  analysis:"缓存未命中时源主机以广播（broadcast）方式发送 ARP 请求。" },
{ id:"r2020下-73", source:"real", year:2020, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"The source device adds the （　） device MAC address to its ARP table for future reference.（源主机把谁的 MAC 加入 ARP 表。）",
  options:["source","destination","gateway","proxy"], answer:"B",
  analysis:"收到回应后，源主机把目的（destination）设备的 MAC 地址记入 ARP 缓存备用。" },
{ id:"r2020下-74", source:"real", year:2020, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"Cookie为客户端持久保持数据提供了方便，但也存在一定的弊端。下列选项中，不属于Cookie弊端的是（　）。",
  options:["增加流量消耗","明文传输，存在安全性隐患","存在敏感信息泄露风险","保存访问站点的缓存数据"], answer:"D",
  analysis:"Cookie随HTTP请求明文传输，会增加流量消耗并带来安全与敏感信息泄露风险；保存站点缓存数据是其功能本身而非弊端。" },
{ id:"r2020下-75", source:"real", year:2020, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"交换设备上配置STP的基本功能包括（　）。①将设备的生成树工作模式配置成STP ②配置根桥和备份根桥设备 ③配置端口的路径开销值，实现将该端口阻塞 ④使能STP，实现环路消除",
  options:["①③④","①②③","①②③④","①②"], answer:"C",
  analysis:"STP基本配置包括配置生成树工作模式、指定根桥与备份根桥、调整端口路径开销以控制端口阻塞、并使能STP消除环路。" }
]);
