/* 真题库 · 2019 下半年 */
REAL_BANK = REAL_BANK.concat([
{ id:"r2019下-01", source:"real", year:2019, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"在CPU内外常设置多级高速缓存(Cache)，其主要目的是（　）。",
  options:["扩大主存的存储容量","提高CPU访问主存数据或指令的效率","扩大存储系统的容量","提高CPU访问外存储器的速度"], answer:"B",
  analysis:"Cache存放CPU频繁访问的主存内容，以提高CPU访问主存数据/指令的效率，而非扩大容量或访问外存。" },
{ id:"r2019下-02", source:"real", year:2019, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"计算机运行过程中，进行中断处理时需保存现场，其目的是（　）。",
  options:["防止丢失中断处理程序的数据","防止对其他程序的数据造成破坏","能正确返回到被中断的程序继续执行","能为中断处理程序提供所需的数据"], answer:"C",
  analysis:"保存断点与寄存器现场，使中断服务结束后能正确返回被中断程序继续执行。" },
{ id:"r2019下-03", source:"real", year:2019, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"内存按字节编址，地址从A0000H到CFFFFH，共有（　）字节。",
  options:["80KB","96KB","160KB","192KB"], answer:"D",
  analysis:"CFFFFH-A0000H+1=30000H=196608B=192KB。" },
{ id:"r2019下-04", source:"real", year:2019, sem:"下", paper:"上午", point:"计算机硬件", diff:3,
  stem:"承上，若用存储容量为64K×8bit的存储器芯片构成该内存空间，至少需要（　）片。",
  options:["2","3","5","8"], answer:"B",
  analysis:"总容量192KB，每片64KB，需192/64=3片。" },
{ id:"r2019下-05", source:"real", year:2019, sem:"下", paper:"上午", point:"计算机硬件", diff:2,
  stem:"衡量系统可靠性的指标是（　）。",
  options:["周转时间和故障率λ","周转时间和吞吐量","平均无故障时间MTBF和故障率λ","平均无故障时间MTBF和吞吐量"], answer:"C",
  analysis:"可靠性用平均无故障时间MTBF与故障率λ衡量；周转时间、吞吐量属性能指标。" },
{ id:"r2019下-06", source:"real", year:2019, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:3,
  stem:"李某受非任职单位委托，利用该单位实验室、实验材料和技术资料开发了一项软件产品。对该软件的权利归属，表达正确的是（　）。",
  options:["该项软件属于委托单位","若该单位与李某对软件的归属有特别约定的，则遵从约定；无约定的，原则上归属李某","取决该软件是否属于该单位分派给李某的","无论有无特别约定，该软件都属于李某"], answer:"B",
  analysis:"委托开发软件著作权由双方约定；无约定的，原则上归受托人(李某)享有。" },
{ id:"r2019下-07", source:"real", year:2019, sem:"下", paper:"上午", point:"法律法规与知识产权", diff:2,
  stem:"李工是某软件公司的软件设计师，每当软件开发完成均按公司规定申请软件著作权，该软件的著作权（　）。",
  options:["应由李工享有","应由公司和李工共同享有","应由公司享有","除署名权以外，著作权的其他权利由李工享有"], answer:"C",
  analysis:"职务作品，针对本职工作开发并由公司承担责任，著作权由公司享有。" },
{ id:"r2019下-08", source:"real", year:2019, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在磁盘调度管理中，通常（　）。",
  options:["先进行旋转调度，再进行移臂调度","在访问不同柱面的信息时，只需要进行旋转调度","先进行移臂调度，再进行旋转调度","在访问同一磁道的信息时，只需要进行移臂调度"], answer:"C",
  analysis:"磁盘调度先移臂(柱面)定位再旋转(扇区)调度；同一磁道只需旋转调度。" },
{ id:"r2019下-09", source:"real", year:2019, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"以下关于CMM的叙述中，不正确的是（　）。",
  options:["CMM是指软件过程能力成熟度模型","CMM根据软件过程的不同成熟度划分了5个等级，其中1级被认为成熟度最高，5级最低","CMMI的任务是将已有的几个CMM模型结合在一起，使之构造成为“集成模型”","采用更成熟的CMM模型，一般来说可以提高最终产品的质量"], answer:"B",
  analysis:"CMM共5级，1级最低、5级最高，B说法相反。" },
{ id:"r2019下-10", source:"real", year:2019, sem:"下", paper:"上午", point:"系统开发与项目管理", diff:2,
  stem:"编译和解释是实现高级程序设计语言的两种基本方式，（　）是这两种方式的主要区别。",
  options:["是否进行代码优化","是否进行语法分析","是否生成中间代码","是否生成目标代码"], answer:"D",
  analysis:"编译生成独立目标代码后执行，解释不生成目标代码而直接执行源程序。" },
{ id:"r2019下-11", source:"real", year:2019, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"传输信道频率范围为10~16MHz，采用QPSK调制，支持的最大速率为（　）Mbps。",
  options:["12","16","24","32"], answer:"C",
  analysis:"信道带宽=16-10=6MHz，QPSK每码元2bit，按奈奎斯特C=2×6×log2(4)=24Mbps。" },
{ id:"r2019下-12", source:"real", year:2019, sem:"下", paper:"上午", point:"数据通信基础", diff:2,
  stem:"以太网采用的编码技术为（　）。",
  options:["曼彻斯特","差分曼彻斯特","归零码","多电平编码"], answer:"A",
  analysis:"传统以太网(10BASE-T)采用曼彻斯特编码，自带时钟同步。" },
{ id:"r2019下-13", source:"real", year:2019, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"HFC网络中，从运营商到小区采用的接入介质为（　）。",
  options:["双绞线","红外线","同轴电缆","光纤"], answer:"D",
  analysis:"HFC为混合光纤同轴网，运营商到小区用光纤，小区入户用同轴电缆。" },
{ id:"r2019下-14", source:"real", year:2019, sem:"下", paper:"上午", point:"广域网与接入", diff:2,
  stem:"承上，小区入户采用的接入介质为（　）。",
  options:["双绞线","红外线","同轴电缆","光纤"], answer:"C",
  analysis:"HFC小区入户采用同轴电缆。" },
{ id:"r2019下-15", source:"real", year:2019, sem:"下", paper:"上午", point:"局域网与交换", diff:2,
  stem:"下列千兆以太网标准中，传输距离最长的是（　）。",
  options:["1000BASE-T","1000BASE-CX","1000BASE-SX","1000BASE-LX"], answer:"D",
  analysis:"1000BASE-LX为单模/多模长距光纤，可达数千米，距离最长。" },
{ id:"r2019下-16", source:"real", year:2019, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"CRC是链路层常用的检错码，若生成多项式为X^5+X^3+1，传输数据10101110，得到的CRC校验码是（　）。",
  options:["01000","01001","1001","1000"], answer:"A",
  analysis:"生成多项式5次，校验码5位；按模2除法计算余数为01000。" },
{ id:"r2019下-17", source:"real", year:2019, sem:"下", paper:"上午", point:"数据通信基础", diff:4,
  stem:"某局域网采用CSMA/CD协议，数据速率10Mbps，主机甲乙距离2km，信号传播速度200m/μs。若甲乙发送数据时发生冲突，从开始发送数据起，到两台主机均检测到冲突时刻为止，最短需经过的时间是（　）μs。",
  options:["10","20","30","40"], answer:"A",
  analysis:"单程传播延时=2000m/200m/μs=10μs，对应冲突检测的最短传播时间窗。" },
{ id:"r2019下-18", source:"real", year:2019, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"以太网中，主机甲和主机乙采用停等差错控制方式进行数据传输，应答帧大小为（　）字节。",
  options:["16","32","64","128"], answer:"C",
  analysis:"停等ARQ的应答帧为以太网帧，最小帧长64字节。" },
{ id:"r2019下-19", source:"real", year:2019, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"采用HDLC协议进行数据传输时，监控帧(S)的作用是（　）。",
  options:["传输数据并对对端信息帧进行捎带应答","进行链路设置、连接管理等链路控制","采用后退N帧或选择性重传进行差错控制","进行介质访问控制"], answer:"C",
  analysis:"S帧(监控帧)用于链路差错与流量控制，如RR/RNR/REJ/SREJ。" },
{ id:"r2019下-20", source:"real", year:2019, sem:"下", paper:"上午", point:"数据通信基础", diff:3,
  stem:"承上，无编号帧(U)的作用是（　）。",
  options:["传输数据并对对端信息帧进行捎带应答","进行链路设置、连接管理等链路控制","采用后退N帧或选择性重传进行差错控制","进行介质访问控制"], answer:"B",
  analysis:"U帧(无编号帧)用于链路建立、拆除等管理控制。" },
{ id:"r2019下-21", source:"real", year:2019, sem:"下", paper:"上午", point:"传输层", diff:4,
  stem:"TCP采用慢启动进行拥塞控制，若TCP在某轮拥塞窗口为8时出现拥塞，经过4个均成功收到应答，此时拥塞窗口为（　）。",
  options:["5","6","7","8"], answer:"B",
  analysis:"拥塞后慢启动重传，cwnd由1指数增长，经4次成功ACK后增至6。" },
{ id:"r2019下-22", source:"real", year:2019, sem:"下", paper:"上午", point:"传输层", diff:2,
  stem:"建立TCP连接时，被动打开一端在收到对端SYN前所处的状态为（　）。",
  options:["LISTEN","CLOSED","SYN_RECEIVED","LAST_ACK"], answer:"A",
  analysis:"被动打开后监听连接请求，处于LISTEN状态。" },
{ id:"r2019下-23", source:"real", year:2019, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"IP数据报分段和重装配要用到报文ID、数据长度、段偏置值和MF标志等字段，其中（　）的作用是指示每一分段在原报文中的位置。",
  options:["段偏置值","MF标志","报文ID","数据长度"], answer:"A",
  analysis:"段偏置值(Fragment Offset)指示该分段在原报文中的位置。" },
{ id:"r2019下-24", source:"real", year:2019, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"承上，若某个段是原报文的最后一个分段，其（　）值为“0”。",
  options:["段偏置值","MF标志","报文ID","数据长度"], answer:"B",
  analysis:"MF=0表示这是最后一个分段；MF=1表示后面还有分段。" },
{ id:"r2019下-25", source:"real", year:2019, sem:"下", paper:"上午", point:"传输层", diff:1,
  stem:"端口号的作用是（　）。",
  options:["流量控制","ACL过滤","建立连接","对应用层进程的寻址"], answer:"D",
  analysis:"端口号用于标识传输层之上的应用进程，实现端到端进程寻址。" },
{ id:"r2019下-26", source:"real", year:2019, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"OSPF报文采用（　）协议进行封装。",
  options:["IP","ARP","UDP","TCP"], answer:"A",
  analysis:"OSPF直接封装在IP中（协议号89），不使用UDP/TCP。" },
{ id:"r2019下-27", source:"real", year:2019, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"承上，OSPF以目标地址（　）发送到所有的OSPF路由器。",
  options:["224.0.0.1","224.0.0.2","224.0.0.5","224.0.0.8"], answer:"C",
  analysis:"OSPF组播地址224.0.0.5(allSPFRouters)。" },
{ id:"r2019下-28", source:"real", year:2019, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"使用Telnet协议进行远程登录时需要满足的条件不包括（　）。",
  options:["本地计算机上安装包含Telnet协议的客户端程序","必须知道远程主机的IP地址或域名","必须知道登录标识与口令","本地计算机防火墙入站规则设置允许Telnet访问"], answer:"D",
  analysis:"Telnet访问要求远程主机(服务器端)防火墙放行入站，而非本地入站规则。" },
{ id:"r2019下-29", source:"real", year:2019, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"Web页面访问过程中，在浏览器发出HTTP请求报文之前不可能执行的操作是（　）。",
  options:["查询本机DNS缓存，获取主机名对应的IP地址","发起DNS请求，获取主机名对应的IP地址","使用查询到的IP地址向目标服务器发起TCP连接","发送请求信息，获取将要访问的Web应用"], answer:"D",
  analysis:"HTTP请求报文本身才用于获取Web应用，发HTTP请求之前不可能先发送该请求信息。" },
{ id:"r2019下-30", source:"real", year:2019, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"下列协议中与电子邮件安全无关的是（　）。",
  options:["SSL","HTTPS","MIME","PGP"], answer:"C",
  analysis:"MIME是邮件内容编码格式，不提供安全；SSL/HTTPS/PGP用于邮件安全。" },
{ id:"r2019下-31", source:"real", year:2019, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux操作系统中，外部设备文件通常放在（　）目录中。",
  options:["/dev","/lib","/etc","/bin"], answer:"A",
  analysis:"Linux把设备当作文件，存放于/dev目录。" },
{ id:"r2019下-32", source:"real", year:2019, sem:"下", paper:"上午", point:"操作系统", diff:1,
  stem:"在Linux中，命令“chmod ugo+r file1.txt”的作用是（　）。",
  options:["修改file1.txt权限为所有者可读","修改file1.txt权限为所有用户可读","修改file1.txt权限为所有者不可读","修改file1.txt权限为所有用户不可读"], answer:"B",
  analysis:"ugo+r表示给用户(u)、组(g)、其他(o)都加读权限，即所有用户可读。" },
{ id:"r2019下-33", source:"real", year:2019, sem:"下", paper:"上午", point:"操作系统", diff:3,
  stem:"在Linux操作系统中，命令（　）可以正确关闭系统防火墙。",
  options:["chkconfig iptables off","chkconfig iptables stop","service iptables stop","service iptables off"], answer:"A",
  analysis:"chkconfig iptables off 关闭防火墙开机自启(关闭系统防火墙)；service iptables stop仅停止当前服务。" },
{ id:"r2019下-34", source:"real", year:2019, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"Windows Server 2008 R2默认未安装IIS，配置下列（　）服务前需先安装IIS服务。",
  options:["DHCP","DNS","FTP","传真"], answer:"C",
  analysis:"FTP服务依赖IIS；DHCP、DNS为独立服务器角色。" },
{ id:"r2019下-35", source:"real", year:2019, sem:"下", paper:"上午", point:"操作系统", diff:2,
  stem:"在Windows Server 2008 R2命令行窗口中，使用（　）命令显示DNS解析缓存。",
  options:["ipconfig /all","ipconfig /displaydns","ipconfig /flushdns","ipconfig /registerdns"], answer:"B",
  analysis:"ipconfig /displaydns显示DNS解析缓存；/flushdns清空缓存。" },
{ id:"r2019下-36", source:"real", year:2019, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"以下关于DHCP服务的说法中，正确的是（　）。",
  options:["在一个局域网中可以存在多台DHCP服务器","默认情况下，客户端要使用DHCP服务需指定DHCP服务器地址","默认情况下，客户端选择DHCP服务器所在网段的IP地址作为本地地址","在DHCP服务器上，只能使用同一网段的地址作为地址池"], answer:"A",
  analysis:"一个局域网中可存在多台DHCP服务器(DHCP集群/容错)。" },
{ id:"r2019下-37", source:"real", year:2019, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"在进行DNS查询时，首先向（　）进行域名查询，以获取对应的IP地址。",
  options:["主域名服务器","辅域名服务器","本地hosts文件","转发域名服务器"], answer:"C",
  analysis:"DNS解析先查本地hosts文件与本地缓存，再向本地DNS服务器查询。" },
{ id:"r2019下-38", source:"real", year:2019, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"在Windows中，可以使用（　）命令测试DNS正向解析功能。",
  options:["arp","nslookup","cernet","netstat"], answer:"B",
  analysis:"nslookup用于DNS解析测试。" },
{ id:"r2019下-39", source:"real", year:2019, sem:"下", paper:"上午", point:"应用层协议", diff:2,
  stem:"承上，要查看域名www.aaa.com所对应的主机IP地址，须将type值设置为（　）。",
  options:["a","ns","mx","cname"], answer:"A",
  analysis:"type=a查询主机A记录(域名到IPv4地址)。" },
{ id:"r2019下-40", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"代理服务器为局域网用户提供Internet访问时，不提供（　）服务。",
  options:["地址共享","数据缓存","数据转发","数据加密"], answer:"D",
  analysis:"代理服务器提供地址共享、缓存、转发，但不负责数据加密。" },
{ id:"r2019下-41", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:1,
  stem:"下列算法中，不属于公开密钥加密算法的是（　）。",
  options:["ECC","DSA","RSA","DES"], answer:"D",
  analysis:"DES是对称加密算法；ECC、DSA、RSA均为公钥(非对称)算法。" },
{ id:"r2019下-42", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"下面的安全协议中，（　）是替代SSL协议的一种安全协议。",
  options:["TLS","IPSec","SET","SSH"], answer:"A",
  analysis:"TLS是SSL的后继替代协议。" },
{ id:"r2019下-43", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"Kerberos系统中可通过在报文中加入（　）来防止重放攻击。",
  options:["会话密钥","时间戳","用户ID","私有密钥"], answer:"B",
  analysis:"Kerberos用时间戳(timestamp)使报文具有时效性，防止重放攻击。" },
{ id:"r2019下-44", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"甲、乙两个用户均向同一CA申请了数字证书，数字证书中包含（　）。",
  options:["用户的公钥","用户的私钥","CA的公钥","CA的私钥"], answer:"A",
  analysis:"数字证书由CA签发，绑定用户身份与其公钥，不含用户私钥。" },
{ id:"r2019下-45", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:3,
  stem:"以下关于数字证书的说法中，正确的是（　）。",
  options:["甲、乙用户需要得到CA的私钥，并据此得到CA为用户签署的证书","甲、乙用户如需互信，可相互交换数字证书","用户可以自行修改数字证书中的内容","用户需要数字证书加密保存"], answer:"B",
  analysis:"甲乙均信任同一CA，交换并验证对方证书即可互信；证书内容不可由用户自行修改。" },
{ id:"r2019下-46", source:"real", year:2019, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"ICMP差错报告报文格式中，除了类型、代码和校验和外，还需加上（　）。",
  options:["时间戳以表明发出的时间","出错报文的前64位数据以使源主机定位出错报文","子网掩码以确定所在局域网","回声请求与响应以判定路径是否畅通"], answer:"B",
  analysis:"ICMP差错报告中包含引起差错的IP数据报首部及前8字节(64bit)数据，供源主机定位。" },
{ id:"r2019下-47", source:"real", year:2019, sem:"下", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"逻辑网络设计是体现网络设计核心思想的关键阶段，下列选项中不属于逻辑网络设计内容的是（　）。",
  options:["网络结构设计","物理层技术选择","结构化布线设计","确定路由选择协议"], answer:"C",
  analysis:"结构化布线设计属于物理网络设计阶段，不属于逻辑设计。" },
{ id:"r2019下-48", source:"real", year:2019, sem:"下", paper:"上午", point:"应用层协议", diff:1,
  stem:"FTP的默认数据端口号是（　）。",
  options:["18","20","22","24"], answer:"B",
  analysis:"FTP控制端口21，默认数据端口20。" },
{ id:"r2019下-49", source:"real", year:2019, sem:"下", paper:"上午", point:"存储与新技术", diff:2,
  stem:"在RAID技术中，同一RAID组内允许任意两块硬盘同时出现故障仍然可以保证数据有效的是（　）。",
  options:["RAID5","RAID1","RAID6","RAID0"], answer:"C",
  analysis:"RAID6采用两个独立校验，允许任意两块磁盘同时故障。" },
{ id:"r2019下-50", source:"real", year:2019, sem:"下", paper:"上午", point:"无线网络", diff:3,
  stem:"无线局域网中采用不同帧间间隔划定优先级，通过冲突避免机制实现介质访问控制。其中RTS/CTS帧（　）。",
  options:["帧间间隔最短，具有较高优先级","帧间间隔最短，具有较低优先级","帧间间隔最长，具有较高优先级","帧间间隔最长，具有较低优先级"], answer:"A",
  analysis:"RTS/CTS使用短帧间间隔(SIFS)，优先级较高，可优先占用信道。" },
{ id:"r2019下-51", source:"real", year:2019, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"属于网络215.17.204.0/22的地址是（　）。",
  options:["215.17.208.200","215.17.206.10","215.17.203.0","115.17.224.0"], answer:"B",
  analysis:"/22第三字节块大小4，204.0~207.255范围，206.10落在此段。" },
{ id:"r2019下-52", source:"real", year:2019, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"主机地址202.115.2.160所在的网络是（　）。",
  options:["202.115.2.64/26","202.115.2.128/26","202.115.2.96/26","202.115.2.192/26"], answer:"B",
  analysis:"/26块大小64，160落在128~191段，网络为202.115.2.128/26。" },
{ id:"r2019下-53", source:"real", year:2019, sem:"下", paper:"上午", point:"IP地址与子网", diff:3,
  stem:"某端口的IP地址为61.116.7.131/26，则该IP地址所在网络的广播地址是（　）。",
  options:["61.116.7.255","61.116.7.129","61.116.7.191","61.116.7.252"], answer:"C",
  analysis:"/26网络为61.116.7.128，广播地址为下一段前一地址=61.116.7.191。" },
{ id:"r2019下-54", source:"real", year:2019, sem:"下", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"有4个网络地址：192.168.224.1、192.168.223.255、192.168.232.25和192.168.216.5，若子网掩码为255.255.240.0，则这4个地址分别属于（　）个子网。",
  options:["1","2","3","4"], answer:"B",
  analysis:"/20第三字节块大小16：224与232同属224.0段，223与216同属208.0段，共2个子网。" },
{ id:"r2019下-55", source:"real", year:2019, sem:"下", paper:"上午", point:"IP地址与子网", diff:4,
  stem:"承上，下面列出的地址对中，属于同一个子网的是（　）。",
  options:["192.168.224.1和192.168.223.255","192.168.223.255和192.168.232.25","192.168.232.25和192.168.216.5","192.168.223.255和192.168.216.5"], answer:"D",
  analysis:"192.168.223.255与192.168.216.5均属192.168.208.0/20。" },
{ id:"r2019下-56", source:"real", year:2019, sem:"下", paper:"上午", point:"网络层与路由", diff:3,
  stem:"IPv6协议数据单元由一个固定头部和若干个扩展头部以及上层协议负载组成。如果有多个扩展头部，第一个扩展头部为（　）。",
  options:["逐跳头部","路由选择头部","分段头部","认证头部"], answer:"A",
  analysis:"若存在逐跳选项头部(Hop-by-Hop)，它必须紧跟在固定基本头部之后，为第一个扩展头部。" },
{ id:"r2019下-57", source:"real", year:2019, sem:"下", paper:"上午", point:"网络管理与监控", diff:1,
  stem:"使用traceroute命令测试网络时可以（　）。",
  options:["检验链路协议是否运行正常","检验目标网络是否在路由表中","查看域名解析服务","显示分组到达目标路径上经过的各个路由器"], answer:"D",
  analysis:"traceroute(Tracert)逐跳显示分组到达目标所经过的路由器路径。" },
{ id:"r2019下-58", source:"real", year:2019, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"通常情况下，信息插座的安装位置距离地面的高度为（　）cm。",
  options:["10~20","20~30","30~50","50~70"], answer:"C",
  analysis:"综合布线中信息插座距地面高度一般为30~50cm。" },
{ id:"r2019下-59", source:"real", year:2019, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"计算机网络机房建设过程中，单独设置接地体时，安全接地电阻要求小于（　）。",
  options:["1Ω","4Ω","5Ω","10Ω"], answer:"B",
  analysis:"机房安全接地电阻要求小于4Ω。" },
{ id:"r2019下-60", source:"real", year:2019, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"确定网络的层次结构及各层采用的协议是网络设计中（　）阶段的主要任务。",
  options:["网络需求分析","网络体系结构设计","网络设备选型","网络安全性设计"], answer:"B",
  analysis:"网络体系结构(拓扑分层及各层协议)设计是该阶段主要任务。" },
{ id:"r2019下-61", source:"real", year:2019, sem:"下", paper:"上午", point:"局域网与交换", diff:3,
  stem:"在两台交换机间启用STP协议，其中SWA配置了STP root primary，SWB配置了STP root secondary，两交换机通过各自G0/0/1与G0/0/2端口相连。则（　）端口将被阻塞。",
  options:["SWA的G0/0/1","SWB的G0/0/2","SWB的G0/0/1","SWA的G0/0/2"], answer:"C",
  analysis:"SWA为根桥，其端口均为指定端口转发；SWB上到根桥路径开销较大的阻塞端口为SWB的G0/0/1。" },
{ id:"r2019下-62", source:"real", year:2019, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"RIPv1与RIPv2说法错误的是（　）。",
  options:["RIPv1是有类路由协议，RIPv2是无类路由协议","RIPv1不支持VLSM，RIPv2支持VLSM","RIPv1没有认证功能，RIPv2支持认证","RIPv1是组播更新，RIPv2是广播更新"], answer:"D",
  analysis:"RIPv1用广播(255.255.255.255)更新，RIPv2用组播(224.0.0.9)更新，D说反。" },
{ id:"r2019下-63", source:"real", year:2019, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"在华为设备上，显示路由表（含目的网络/掩码、协议、优先级、开销、标记、下一跳、出接口）的命令是（　）。",
  options:["display bgp paths","display ospf lsdb","display ip routing-table","display vlan"], answer:"C",
  analysis:"display ip routing-table用于查看IP路由表。" },
{ id:"r2019下-64", source:"real", year:2019, sem:"下", paper:"上午", point:"网络管理与监控", diff:2,
  stem:"承上，路由表输出中标识了路由标记(Route Flags)的列是（　）。",
  options:["Pre","Cost","Flags","Proto"], answer:"C",
  analysis:"Flags列即路由标记(Relay/Download to FIB等)。" },
{ id:"r2019下-65", source:"real", year:2019, sem:"下", paper:"上午", point:"网络层与路由", diff:2,
  stem:"OSPF协议是（　）。",
  options:["路径矢量协议","内部网关协议","距离矢量协议","外部网关协议"], answer:"B",
  analysis:"OSPF是链路状态的内部网关协议(IGP)；BGP为路径矢量的外部网关协议。" },
{ id:"r2019下-66", source:"real", year:2019, sem:"下", paper:"上午", point:"存储与新技术", diff:1,
  stem:"下列（　）接口不适用于SSD磁盘。",
  options:["SATA","IDE","PCIe","M.2"], answer:"B",
  analysis:"IDE(PATA)为老式并行接口，不适用于现代SSD；SSD常用SATA、PCIe、M.2。" },
{ id:"r2019下-67", source:"real", year:2019, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"三层网络设计方案中，（　）是核心层的功能。",
  options:["不同区域的高速数据转发","用户认证、计费管理","终端用户接入网络","实现网络的访问策略控制"], answer:"A",
  analysis:"核心层负责各区域间的高速、无阻塞数据转发。" },
{ id:"r2019下-68", source:"real", year:2019, sem:"下", paper:"上午", point:"网络规划与布线", diff:3,
  stem:"五阶段迭代周期模型把网络开发过程分为需求分析、通信规范分析、逻辑网络设计、物理网络设计、安装和维护五个阶段。以下叙述中正确的是（　）。",
  options:["需求分析阶段应尽量明确定义用户需求，输出需求规范、通信规范","逻辑网络设计阶段设计人员一般更加关注于网络层的连接图","物理网络设计阶段要输出网络物理结构图、布线方案、IP地址方案等","安装和维护阶段要确定设备和部件清单、安装测试计划，进行安装调试"], answer:"B",
  analysis:"逻辑网络设计关注网络层拓扑与连接图；通信规范分析在需求分析后输出。" },
{ id:"r2019下-69", source:"real", year:2019, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"以下关于网络冗余设计的叙述中，错误的是（　）。",
  options:["网络冗余设计避免网络组件单点失效造成应用失效","通常情况下主路径与备用路径承担相同的网络负载","负载分担是通过并行链路提供流量分担来提高性能","网络中存在备用链路时，可以考虑加入负载分担设计"], answer:"B",
  analysis:"通常备用路径在主路径正常时不承担负载(仅主路径工作)，主备并不承担相同负载。" },
{ id:"r2019下-70", source:"real", year:2019, sem:"下", paper:"上午", point:"网络规划与布线", diff:2,
  stem:"网络规划与设计应遵循一些设计原则，保证网络的先进性、可靠性、容错性、安全性和性能等。以下原则中有误的是（　）。",
  options:["应用最新的技术，保证网络设计技术的先进性","提供充足的带宽和先进的流量控制及拥塞管理功能","采用基于通用标准和技术的统一网络管理平台","网络设备的选择应考虑具有一定的可扩展空间"], answer:"A",
  analysis:"应采用成熟先进技术而非盲目追新；最新技术未必最稳定成熟。" },
{ id:"r2019下-71", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"A virtual (　) network, or VPN, is an encrypted connection over the Internet from a device to a network.（选最贴切的词）",
  options:["public","private","personal","proper"], answer:"B",
  analysis:"VPN即虚拟专用(private)网络。" },
{ id:"r2019下-72", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"The encrypted connection helps ensure that sensitive data is safely (　).（选最贴切的词）",
  options:["encoded","encrypted","stored","transmitted"], answer:"D",
  analysis:"加密连接确保敏感数据被安全地传输(transmitted)。" },
{ id:"r2019下-73", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"It prevents (　) people from eavesdropping on the traffic and allows the user to conduct work remotely.（选最贴切的词）",
  options:["employed","authorized","unauthorized","criminal"], answer:"C",
  analysis:"防止未授权(unauthorized)人员窃听流量。" },
{ id:"r2019下-74", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"Traffic on the virtual network is sent securely by establishing an encrypted connection across the Internet known as a (　).（选最贴切的词）",
  options:["channel","path","tunnel","route"], answer:"C",
  analysis:"跨互联网建立的加密连接称为隧道(tunnel)。" },
{ id:"r2019下-75", source:"real", year:2019, sem:"下", paper:"上午", point:"网络安全", diff:2,
  stem:"Site-to-site VPN connects the corporate office to branch offices over the Internet. Think of site-to-site access as (　) to network.（选最贴切的词）",
  options:["network","device","computer","data"], answer:"A",
  analysis:"站点到站VPN相当于网络(network)对网络的连接。" }
]);
